---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
```

```{r}
hplc <- read_csv(here("files", "hplc_2018_2020.csv"))

chl <- read_csv(here("files", "chl_2018_2020.csv"))
```
```{r}

chl_join <- chl %>% 
  filter(line_out_depth == 5 & filter_type == "Bulk GF/F") %>% 
  select(date, site_id, chla, chla_flag) %>% 
  filter(chla_flag == "AV" | chla_flag == "SVC" | is.na(chla_flag)) %>% 
  filter(!is.na(chla))

hplc_join <- hplc %>% 
  filter(line_out_depth == 5 & !is.na(all_chl_a)) %>% 
  select(date, site_id, tchla = all_chl_a)

hplc_join <- hplc_join %>% 
  left_join(chl_join)

hplc_join %>% 
  ggplot(aes(x = tchla, y = chla)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline(slope = 1, intercept = 0) +
  ggpubr::stat_cor(label.y = 18, vjust = 2, size = 8) +
  ggpubr::stat_regline_equation(label.y = 18, size = 8)

chl_lm = lm(chla ~ tchla, data = hplc_join) 
summary(chl_lm) 

```



```{r}
#Separating the 2018 chlorophyll data where there is no HPLC
chl_cali <- chl_join %>%
  filter(date < "2019-01-01")

#Applying the correction to the 2018 chl data based on the relationship between chl and HPLC TChla for 2019 and 2020. This relationship is plotted below.
chl_cali <- chl_cali %>% 
  mutate(tchla = (chla + 0.04)/1.2)

chl_merge <- chl_cali %>% 
  select(date, site_id, tchla)

hplc_merge <- hplc %>% 
  filter(line_out_depth == 5 & !is.na(all_chl_a)) %>% 
  select(date, site_id, tchla = all_chl_a)

tchla_merge <- rbind(hplc_merge, chl_merge)

tchla_export <- tchla_merge %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))
```

```{r}
#Write output to csv.
write_csv(tchla_export, here("outputs", "tchla_calibration_2022-11-15.csv"))
```