---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)

#Need to go through and test these

```

```{r}
#Upload data

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_all_2022-07-29.csv")) 

```



```{r}
#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria" &
           !group == "Metazoa" &
           !group == "Protozoa" &
           !group == "Choanoflagellata" &
           !group == "Ciliophora" &
           !group == "Kinetoplastidea")

```

```{r}
#Trying to look at only species present in 20% of samples
#How many samples
sample_num <- micro %>% 
  distinct(date, site_id)

species_10 <- micro %>% 
  group_by(scientificName) %>% 
  summarise(n_obs = n()) %>%
  ungroup() %>% 
  mutate(perc_obs = n_obs/50) %>% 
  filter(perc_obs >= 0.10)

species_10_list <- species_10$scientificName

micro <- micro %>% 
  filter(scientificName %in% species_10_list)

```

```{r}
micro <- micro %>% 
  mutate(month = lubridate::month(date))
```



```{r}
#Preparing data for cluster and nMDS analysis - need to be put into two separate matrices.

#Selecting columns
micro_piv <- micro %>% 
  select(date, month, site_id, scientificName, species_sum)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Adding year to wide format for plotting
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Arranging according to site ID and date
micro_piv <- micro_piv %>% 
  arrange(site_id, date)

#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 5:ncol(micro_piv)]

#Creating relative abundance matrix - not currently looking at relative abundance
transform <- decostand(species, method = "total")
  

transform <- sqrt(species)

#Not currently working with relative abundance
# transform_rel <- sqrt(transform_rel)
```

```{r}
#Creating rownames for dendrogram creating

#Changing site_id to location 
micro_piv <- micro_piv %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

metadata <- micro_piv %>%
  select(location, site_id, date) %>%  
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

#Creating a list of rownames
# labs_list <- labs$sample_name
labs_list <- metadata$sample_name

#creating a hierarchical clustering matrix
transform_hc <- transform

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(transform_hc) <- labs_list
```

```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- vegdist(transform_hc, method = "bray")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "average")

```

```{r}
#Turning off as tests show 1-2 clusters that do not make sense with data


# Looking at number of clusters
fviz_nbclust(transform, FUN = hcut, method = "wss")
fviz_nbclust(transform, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(transform, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```



```{r}
#This step sets clusters. Currently, I am not using.

# k <- 6
# clust <- cutree(cluster.average, k = k)
# 
# clust.df <- clust.df <- data.frame(label = rownames(transform_hc),
#                                    cluster = factor(clust))

# write_csv(clust.df, here("outputs", "clusters_micro_6.csv"))
```

```{r}
# extract dendrogram segment data for plotting

dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}

# get terminal dendrogram segments and join with names.
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

# dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
# rect <- aggregate(x~cluster, label(dendrogram_data), range)
# rect <- data.frame(rect$cluster, rect$x)
# ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.


p_dend <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 # geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0, ymax = ymax),
 #            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(0.8, -0.3)) +
 coord_flip() + 
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       # axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Dist.") # flipped x and y coordinates for aesthetic reasons

#Turning off saving for now because not needed
ggsave(here("figures_rev2", "hc_all_data.png"), p_dend,
       width = 6, height = 12, dpi = 300)
```

```{r}
#Running nmds on Calvert data
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Show results including stress - currently 0.21.
nmds

#Checking stressplot for fit
stressplot(nmds)

```

```{r}
# For clusters, need to merge on station/date code. This is using the old naming convention.
micro_piv <- micro_piv %>%
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

micro_piv <- micro_piv %>%
  left_join(clust_phy) %>%
  relocate(cluster, .after = month_surv) %>% 
  rename(clust_phy = cluster)

micro_piv_na <- micro_piv %>% 
  filter(!is.na(clust_phy)) %>% 
  relocate(location, .after = site_id)

#Pulling out species counts for transform and input into clustering and NMDS
species_na <- micro_piv_na[, 9:ncol(micro_piv_na)]

#Creating relative abundance matrix - not currently looking at relative abundance
# transform_rel <- decostand(species, method = "total")
  
#Log10 transformation + 1 (as per Mahara)
transform_na <- log10(species_na + 1)

```


```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

data.scores = as.data.frame(scores(nmds))
data.scores$month_surv = micro_piv$month_surv
data.scores$site = micro_piv$location
data.scores$year = micro_piv$year
data.scores$clust_phy = micro_piv$clust_phy

```

```{r}

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
data.scores <- arrange(mutate(data.scores,
                         site = factor(site, levels = order_loc)))
```

```{r}

#Trying to add species scores - Want to select the most important, but can't figure it out and wasting a lot of time on something that probably won't result in much gain.
vf <- envfit(nmds, transform, perm = 999)

r2 <- vf$vectors$r

test <- as.data.frame(r2)

spp.scrs <- as.data.frame(scores(vf, display = "vectors"))

spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

spp.scrs2 <- cbind(spp.scrs, test)

spp.scrs2 <- spp.scrs2 %>%
  filter(r2 >= 0.35)

rownames(spp.scrs2) <- c("C.deb.",
                         "C.lac.",
                         "P.n.s",
                         "Hill.",
                         "S.mar.",
                         "P.n.",
                         "C.cin",
                         "C.soc.")
```

```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits. This is for the absolute data

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 4) + 
  geom_segment(data = spp.scrs2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "grey30",
             fontface = "bold", label = row.names(spp.scrs2)) + 
  stat_ellipse(aes(color = site), level = 0.50) +
  scale_fill_brewer(palette = "RdYlBu") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  coord_fixed() + ## need aspect ratio of 1!
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"),
        # axis.ticks = element_blank(),
        # axis.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_text(size = 10, face = "bold", colour = "black"),
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_absolute_CALVERT.png"),
#        width = 6, height = 4.5, dpi = 300)
```


```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = spp.scrs2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
               size = 1.3) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 9) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        # legend.position = c(0.1, 0.65),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 7, stroke = 1.5) + 
  geom_segment(data = spp.scrs2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
               size = 1.3) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 9) +
  
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # xlim(-0.4, 0.7) +
  # annotate("text", x = -0.70, y = 0.40, label = "b)", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        # legend.position = c(0.90, 0.86),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Year", shape = "Station") +
    guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

fig_nmds_horiz <- (p1 / p2)

ggsave(here("figures_good", "nmds_relative_all.png"), fig_nmds_horiz,
       width = 8, height = 12, dpi = 300)

```

```{r}
#separating treatments for ANOSMIM and indicator
site_id <- micro_piv$site_id
month <- micro_piv$month_surv
year <- micro_piv$year

```

```{r}
#ANOSIM test to see if groupings statistically significant - abundance

#Turning off for now because takes time to analyze.
ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
ano_site
plot(ano_site)

transform.dist <- vegdist(transform, "bray")

ano_site2 <- anosim(transform.dist, site_id)
summary(ano_site2)

# 
ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
ano_month
# 
ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
ano_year


test1 <- adonis(transform ~ site_id,
               permutations = 999, method = "bray")

print(test1)
print(as.data.frame(test1$aov.tab)["site_id", "Pr(>F)"])

test2 <- adonis(transform ~ year,
               permutations = 999, method = "bray")
print(as.data.frame(test2$aov.tab)["year", "Pr(>F)"])

print(test2)

test3 <- adonis(transform ~ month,
               permutations = 999, method = "bray")

print(test3)
```


```{r}
# https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/multivariate-comparisons-of-microbial-community-composition.html#checking-the-homogeneity-condition-1

coef <- coefficients(test1)["site_id1",]
top.coef <- coef[rev(order(abs(coef)))[1:10]]
par(mar = c(5, 20, 2, 1))
barplot(sort(top.coef), horiz = T, las = 1, main = "Top taxa")
```
```{r}
# https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/multivariate-comparisons-of-microbial-community-composition.html#checking-the-homogeneity-condition-1

coef <- coefficients(test2)["year",]
top.coef <- coef[rev(order(abs(coef)))[1:10]]
par(mar = c(5, 14, 2, 1))
barplot(sort(top.coef), horiz = T, las = 1, main = "Top taxa")
```
```{r}
# https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/multivariate-comparisons-of-microbial-community-composition.html#checking-the-homogeneity-condition-1

coef <- coefficients(test3)["month",]
top.coef <- coef[rev(order(abs(coef)))[1:10]]
par(mar = c(5, 14, 2, 1))
barplot(sort(top.coef), horiz = T, las = 1, main = "Top taxa")
```






```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station
inv_site = multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_site)
```


```{r}
#ANOSIM test to see if groupings statistically significant - abundance

#Turning off for now because takes time to analyze.
ano_site_2018_fs = anosim(transform_2018_fs, site_id_2018_fs,
                       distance = "bray", permutations = 9999)
ano_site_2018_fs

ano_site_2019 = anosim(transform_2019, site_id_2019,
                       distance = "bray", permutations = 9999)
ano_site_2019

ano_site_2020 = anosim(transform_2020, site_id_2020,
                       distance = "bray", permutations = 9999)
ano_site_2020

```


```{r}
#Pulling out list of species from indicator analysis on station - Not currently used to make plot, but cool that I can do this - makes further analysis much easier and replicatable.
inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)
```

```{r}
# by month - Noth currently using.
inv_month = multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_month)
```





```{r}
#by year
inv_year = multipatt(transform, year, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_year)
```


```{r}
#Looking at p-value correction for indicator species analysis.
# https://stats.stackexchange.com/questions/370724/indiscpecies-multipatt-and-overcoming-multi-comparrisons

inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)

```




```{r}
#Ordering the data in the order of the dendrogram from hierarchical clustering.

#Creating a list with the order of the samples in the dendrogram.
hc_order <- dendrogram_ends$sample_name

hc_order_exp <- as_tibble(hc_order)

# write_csv(hc_order_exp, here("outputs", "hc_order.csv"))

#Creating a separate workbook, in tidy format, with the combined site and date name. 
micro_heat <- micro %>% 
    filter(!site_id == "QU39") %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

micro_heat <- micro_heat %>% 
  group_by(date, location) %>% 
  mutate(sum = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(perc = species_sum/sum)

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))

#Setting order of species for figure organized by group (i.e diatoms) and then species alphabetical within.
micro_heat$species_order <- factor(micro_heat$scientificName,
                                   (unique(micro_heat$scientificName
                                              [order(micro_heat$group,
                                                     micro_heat$scientificName)])))
```


```{r}
#Plotting indicator species where p < 0.01. 

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))


h1_1 <- micro_heat %>%   
   filter(
           scientificName == "Teleaulax acuta" |
           scientificName == "Dinophysis acuta " |
           scientificName == "Ceratium lineatum" |
           scientificName == "Chaetoceros cinctus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Chaetoceros decipiens" |
           scientificName == "Chaetoceros laciniosus" |
           scientificName == "Chaetoceros socialis" |
           scientificName == "Detonula pumila" |
           scientificName == "Hillea" |
           scientificName == "Pseudo-nitzschia" |
           scientificName == "Pseudo-nitzschia seriata" |
           scientificName == "Skeletonema marinoi"  |
           scientificName == "Prorocentrum micans" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Protoperidinium steinii" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Chaetoceros similis" |
           scientificName == "Protoperidinium" |
           scientificName == "Leptocylindrus danicus" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Pterosperma" |
           scientificName == "Dactyliosolen fragilissimus" 
           ) %>%
  ggplot(aes(x = sample_name, y = species_order, fill = perc)) +
  geom_tile(color = "black", size = 1) +
  # facet_grid(group ~ ., scales = "free_y", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_y_discrete(labels = c(
  #                             # "Ceratium lineatum" = "C.lin.",
  #                             # "Chaetoceros cinctus" = "C.cin.",
  #                             # "Chaetoceros debilis" = "C.deb.",
  #                             # "Chaetoceros decipiens" = "C.dec.",
  #                             # "Chaetoceros laciniosus" = "C.lac.",
  #                             "Chaetoceros socialis" = "C.soc.",
  #                             # "Detonula pumila" = "D.pum.",
  #                             "Hillea" = "Hill.",
  #                             "Pseudo-nitzschia" = "P.n.",
  #                             # "Pseudo-nitzschia seriata" = "P.n.s",
  #                             "Skeletonema marinoi" = "S.mar."
  #                             )) +
  # geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, label = label), 
  #           hjust = -0.1, vjust = -1) +
  ylab(bquote(Log^10 ~ "(Abund. +1)")) +
  # annotate("text", x = 1.5, y = 9, label = "e)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank())

```





```{r}
#Plotting indicator species where p < 0.01. 

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))


h1_2 <- micro_heat %>%   
   filter(scientificName == "Ceratium lineatum" |
          scientificName == "Chaetoceros debilis" |
          scientificName == "Chaetoceros decipiens" |
          scientificName == "Chaetoceros laciniosus" |
          scientificName == "Chaetoceros socialis" |
          scientificName == "Dactyliosolen fragilissimus" |
          scientificName == "Dactyliosolen phuketensis" |
          scientificName == "Detonula pumila" |
          scientificName == "Guinardia delicatula" |
          scientificName == "Leptocylindrus danicus" |
          scientificName == "Pseudo-nitzschia seriata" |
          scientificName == "Rhizosolenia setigera" |
          scientificName == "Scrippsiella precaria" |
          scientificName == "Skeletonema marinoi") %>%
  ggplot(aes(x = sample_name, y = species_order, fill = log10(count + 1))) +
  geom_tile(color = "black", size = 1) +
  # facet_grid(group ~ ., scales = "free_y", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  scale_y_discrete(labels = c("Ceratium lineatum" = "C.l.",
                              "Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros laciniosus" = "C.lac.",
                              "Chaetoceros socialis" = "C.soc.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.pu.",
                              "Guinardia delicatula" = "G.d",
                              "Leptocylindrus danicus" = "L.d.",
                              "Pseudo-nitzschia seriata" = "P.s.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Scrippsiella precaria" = "S.p.",
                              "Skeletonema marinoi" = "S.m.")) +
  # geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, label = label), 
  #           hjust = -0.1, vjust = -1) +
  ylab(bquote(Log^10 ~ "(Abund. +1)")) +
  annotate("text", x = 1.5, y = 11, label = "e)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background=element_blank())

```



```{r}
#Second approach to try to lineup dendrogram with heatmap so that they can be combined in a panel.
p_dend2 <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 scale_color_manual(values = site_color) +

 scale_x_continuous(expand = c(0.01, 0.01)) + 
 annotate("text", x = 49.5, y = 0.43, label = "c)", size = 10) +
 ylab("Dist.") +
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       # axis.title.y = element_blank(),
       axis.text.x = element_blank(),
       text = element_text(size = 25),
       axis.line = element_line(colour = "black"),
       axis.text = element_text(colour = "black")) 

```

```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / h1_1 + plot_layout(heights = c(1, 3))

fig2 <- fig_nmds_horiz / fig

ggsave(here("figures_good", "nmds_year_heat_rel.png"), fig2,
       width = 16, height = 13, dpi = 300)
```

```{r}
#Want to look at species richness and diversity index along HC clustering
micro_diat <- micro_heat %>% 
  filter(class == "Bacillariophyceae") %>% 
  group_by(sample_name) %>% 
  summarise(n_spec = n()) %>%
  ungroup() %>% 
  mutate(type = "D")

micro_nodiat <- micro_heat %>% 
  filter(!class == "Bacillariophyceae") %>% 
  group_by(sample_name) %>% 
  summarise(n_spec = n()) %>%
  ungroup() %>% 
  mutate(type = "F")

micro_rich <- rbind(micro_diat, micro_nodiat)

#Setting the order to the same as the clustering using the specified list
micro_rich$sample_name <- factor(micro_rich$sample_name, levels = unique(hc_order))

# micro_heat$date_fact <- as.factor(micro_heat$date)
# 
# micro_heat$test <- reorder(micro_heat$date_fact, micro_heat$sample_name)


bar <- micro_rich %>%   
  ggplot(aes(x = sample_name, y = n_spec, fill = type)) +
  geom_bar(stat = "identity", position = position_stack(reverse = T),
           color = "black") +
  geom_hline(yintercept = 20) +
  scale_fill_manual(values = c("black", "grey"),
                    labels = c("Diat.", "Flag.")) +
  ylab("Rich.") +
  annotate("text", x = 49.5, y = 52, label = "d)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.direction = "horizontal",
        legend.position = c(0.075, 0.85),
        legend.background=element_blank())

#It looks like diatoms have the biggest difference - can I do a stacked bar?

```

```{r}
micro_rich %>% 
  filter(type == "D") %>% 
  ggplot(aes(x = as.factor(sample_name), y = n_spec)) + 
  geom_point()

micro_rich %>% 
  filter(type == "F") %>% 
  ggplot(aes(x = as.factor(sample_name), y = n_spec)) + 
  geom_point()
```



```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / bar / h1_1 + plot_layout(heights = c(1, 1, 3))

fig2 <- fig_nmds_horiz / fig

ggsave(here("figures_good", "nmds_year_richness_REL.png"), fig2,
       width = 16, height = 15, dpi = 300)

```

```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / bar / h1_2 + plot_layout(heights = c(1, 1, 3))

fig2 <- fig_nmds_horiz / fig

ggsave(here("figures_good", "nmds_year_richness_2.png"), fig2,
       width = 16, height = 17, dpi = 300)

```

```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / bar / h1_1 + plot_layout(heights = c(1, 1, 3))

fig2 <- fig_nmds_horiz_phy_clust / fig

ggsave(here("figures_good", "nmds_clust_richness.png"), fig2,
       width = 16, height = 15, dpi = 300)

```

```{r}
#Look at shannon diversity

shannon <- diversity(species)

shannon <- as_tibble(shannon)

shannon$date <- micro_piv$date
shannon$year <- micro_piv$year
shannon$month <- micro_piv$month_surv
shannon$location <- micro_piv$location
```

```{r}
#looking at stats for shannon
shannon_stats_loc <- shannon %>% 
  group_by(location) %>% 
  summarise(med_div = median(value)) %>%
  ungroup()

shannon_stats_loc_year <- shannon %>% 
  group_by(year, location) %>% 
  summarise(med_div = median(value)) %>%
  ungroup()
  
shannon_stats_month <- shannon %>% 
  group_by(month, location) %>% 
  summarise(med_div = median(value)) %>%
  ungroup()
            
```




```{r}
#Setting the order to the same as the clustering using the specified list
shannon$sample_name <- factor(shannon$sample_name, levels = unique(hc_order))

sh <- shannon %>%   
  ggplot(aes(x = sample_name, y = value)) +
  geom_bar(stat = "identity", color = "black") +
  # geom_hline(yintercept = 40) +
  # scale_fill_manual(values = c("black", "grey"),
  #                   labels = c("Diat.", "Flag.")) +
  ylab("H") +
  # annotate("text", x = 49.5, y = 52, label = "d)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.direction = "horizontal",
        legend.position = c(0.075, 0.85),
        legend.background = element_blank())

# ggsave(here("figures_rev2", "shannon.png"),
#        width = 16, height = 6, dpi = 300)
```

```{r}
#Lets plot shannon diversity with richness.

fig <- p_dend2 / bar / sh + plot_layout(heights = c(1, 3, 3))

ggsave(here("figures_good", "dend_rich_div.png"), fig,
       width = 16, height = 10, dpi = 300)

#Richness is somewhat lower at DFO2, but not diversity
```
```{r}

```







```{r}
#When are some of these indicator species present at DFO2
cdec <- micro %>% 
  filter(scientificName == "Chaetoceros decipiens" & site_id == "DFO2")

csei <- micro %>% 
  filter(scientificName == "Chaetoceros seiracanthus" & site_id == "DFO2")

dpum <- micro %>% 
  filter(scientificName == "Detonula pumila" & site_id == "DFO2")
```



```{r}
#Creating a list of species determined via indicator species analysis on stations.
ind_list <- c("Chaetoceros decipiens", "Dactyliosolen phuketensis", 
              "Detonula pumila", "Thalassiosira rotula" , "Ceratium lineatum", 
              "Dactyliosolen fragilissimus", "Chaetoceros debilis", 
              "Guinardia delicatula", "Rhizosolenia setigera", 
              "Chaetoceros seiracanthus", "Skeletonema marinoi")  
```

```{r}
#Sub-setting the species determined via indicator species analysis on station
micro_ind_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% ind_list)

#Determining number of times each indicator species observed at each station
micro_ind_stat <- micro_ind_stat %>% 
  group_by(site_id, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum),
            median_count = median(species_sum)) %>% 
  ungroup() 

test <- micro %>% 
  filter(!site_id == "QU39" & class  == "Bacillariophyceae") %>% 
  group_by(site_id, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum),
            median_count = median(species_sum)) %>%
  ungroup()

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_station <- micro %>% 
  filter(!site_id == "QU39") %>% 
  group_by(date, site_id) %>% 
  distinct(date, site_id) %>% 
  ungroup() %>% 
  group_by(site_id) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_ind_stat <- micro_ind_stat %>% 
  left_join(n_station) %>% 
  mutate(perc_obs = n_obs/n_samp,
         label = scales::percent(perc_obs %>% round(2)))
```
```{r}
#Creating a placeholder for Ceratium lineatum for DFO2 - makes plot save a space so the groupings stay consistent.
dfo_cl <- data.frame(site_id = "DFO2",
                     scientificName = "Ceratium lineatum",
                     n_obs = 0,
                     max_count = 0,
                     mean_count = 0,
                     median_count = 0,
                     n_samp = 0,
                     perc_obs = 0,
                     label = "0%")
                 
micro_ind_stat <- rbind(dfo_cl, micro_ind_stat)
```


```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi" |
         !scientificName == "Thalassiosira rotula" |
         !scientificName == "Chaetoceros seiracanthus") %>% 
  ggplot(aes(x = perc_obs, y = scientificName, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 1.03)) +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
  labs(x = "% Observed") +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi" |
         !scientificName == "Thalassiosira rotula" |
         !scientificName == "Chaetoceros seiracanthus") %>% 
  ggplot(aes(x = mean_count, y = scientificName, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(x = "Mean Abundance (cells l)") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 26000)) +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              # "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.85, 0.1),
          legend.title = element_blank())

fig <- p1 + p2

ggsave(here("figures_good", "indicator_species_station_bar.png"), fig,
       width = 12, height = 7, dpi = 300)
```
```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_ind_stat %>% 
    filter(!scientificName == "Skeletonema marinoi" &
         !scientificName == "Thalassiosira rotula" &
         !scientificName == "Chaetoceros seiracanthus") %>%  
  ggplot(aes(x = scientificName, y = n_obs, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  geom_text(aes(label = label), position = position_dodge(width = 1), 
            hjust = -0.1, angle = 90, size = 5) +
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(expand = c(0.01, 0), limits = c(0, 20)) +
  scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              # "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              # "Skeletonema marinoi" = "S.m.",
                              # "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
  labs(y = "# Obs. + (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi" &
         !scientificName == "Thalassiosira rotula" &
         !scientificName == "Chaetoceros seiracanthus") %>% 
  ggplot(aes(x = scientificName, y = log10(median_count + 1),  fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1", labels = c("F", "C", "S")) +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(y = "Median log10(cells L + 1)") +
  scale_y_continuous(expand = c(0.01, 0), limits = c(0, 5)) +
  scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              # "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          # axis.title.y = element_blank(),
          # axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.95, 0.8),
          legend.title = element_blank())

fig <- p1 / p2

ggsave(here("figures_good", "indicator_species_station_bar4.png"), fig,
       width = 12, height = 9, dpi = 300)
```
```{r}
micro_ind_ts <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% ind_list)
```

```{r}
micro_ind_ts %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = species_sum, color = site_id)) +
  geom_line(size = 2) +
  geom_point(size = 3) +
  facet_grid(scientificName ~ year, scales = "free_y")

ggsave(here("figures_rev2", "indicator_species_ts.png"),
       width = 16, height = 20, dpi = 300)
```
```{r}
micro_diat_site2 <- micro_heat %>% 
  filter(class == "Bacillariophyceae") %>% 
  group_by(date, site_id) %>% 
  mutate(n_spec = n()) %>%
  ungroup() %>% 
  distinct(date, site_id, n_spec, .keep_all = TRUE) %>% 
  group_by(site_id, month_surv) %>% 
  summarise(mean = mean(n_spec),
            median = median(n_spec),
            sdev = sd(n_spec)) %>% 
  ungroup()

micro_diat_site2 %>% 
  ggplot(aes(x = as.factor(month_surv), y = mean, fill = site_id)) +
  geom_bar(stat = "identity", position = "dodge")

micro_diat_site2 %>% 
  ggplot(aes(x = as.factor(month_surv), y = median, fill = site_id)) +
  geom_bar(stat = "identity", position = "dodge")

```




```{r}
#Trying to do the same for annual indicator analysis. Creating a list of species determined via indicator species analysis on stations.

#subsetting species from annual indicator species analysis that had p values <= 0.01.
inv_year_sp <- inv_year_sp %>% 
  filter(p.value <= 0.01)

#Creating a list of the significant species from indicator species analysis.
inv_year_lis <- inv_year_sp$rn

```

```{r}
#Sub-setting the species determined via indicator species analysis on station
micro_year_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% inv_year_lis) %>% 
  mutate(year = lubridate::year(date))

#Determining number of times each indicator species observed at each station
micro_year_stat <- micro_year_stat %>% 
  group_by(year, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum)) %>% 
  ungroup() 

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_station_year <- micro %>% 
  filter(!site_id == "QU39") %>%
  mutate(year = lubridate::year(date)) %>% 
  group_by(date, year) %>% 
  distinct(date, year) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_year_stat <- micro_year_stat %>% 
  left_join(n_station_year) %>% 
  mutate(perc_obs = n_obs/n_samp)
```

```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_year_stat %>% 
  ggplot(aes(x = perc_obs, y = scientificName, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 1.03)) +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corythodinium" = "C.",
                              "Ceratium horridum" = "C.h.", #Y
                              "Corethron criophilum" = "C.c.", #Y
                              "Dinobryon" = "Db.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Phaeocystis pouchetii" = "P.p.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Teleaulax acuta" = "T.a.",
                              "Telonema subtilis" = "T.s.",
                              "Thalassiosira nordenskioeldii" = "T.n.")) +
  theme_bw() +
  labs(x = "% Observed") +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_year_stat %>% 
  ggplot(aes(x = mean_count, y = scientificName, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(x = "Mean Abundance (cells l)") +
  # scale_x_continuous(expand = c(0.01, 0), limits = c(0, 26000)) +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corythodinium" = "C.",
                              "Ceratium horridum" = "C.h.", #Y
                              "Corethron criophilum" = "C.c.", #Y
                              "Dinobryon" = "Db.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Phaeocystis pouchetii" = "P.p.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Teleaulax acuta" = "T.a.",
                              "Telonema subtilis" = "T.s.",
                              "Thalassiosira nordenskioeldii" = "T.n.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.85, 0.1),
          legend.title = element_blank())

fig <- p1 + p2

ggsave(here("figures_rev2", "indicator_species_year_bar.png"), fig,
       width = 12, height = 7, dpi = 300)
```



















