---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)

#Need to go through and test these

```

```{r}
#Upload data

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

clust_phy <- read_csv(here("outputs", "clusters_phys.csv"))

```

```{r}
test <- micro %>% 
  filter(class == "Raphidophyceae")

test2 <- micro %>% 
  filter(phylum == "Haptophyta")



test3 <- micro %>% 
  filter(class == "Dictyochophyceae" & site_id == "DFO2")

test4 <- micro %>% 
  filter(site_id == "DFO2" & phylum == "Chlorophyta")

test5 <- micro %>% 
  filter(site_id == "QCS01" & date == "2019-08-31")

dfo2_8_2019 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(year == 2019 & (month == 8 & site_id == "DFO2"))

dfo2_5_2019 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(year == 2019 & (month == 5 & site_id == "DFO2"))

kc10_2019 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(year == 2019 & (month == 9 & site_id == "KC10"))

qcs01_2019 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(site_id == "QCS01" & date == "2019-08-31")

q19_7_7 <- micro %>% 
  filter(site_id == "QCS01" & date == "2019-07-07")

q19_8_6 <- micro %>% 
  filter(site_id == "QCS01" & date == "2019-08-06")

q19_8_31 <- micro %>% 
  filter(site_id == "QCS01" & date == "2019-08-31")

q19_10_5 <- micro %>% 
  filter(site_id == "QCS01" & date == "2019-10-05")

c_horr <- micro %>% 
  filter(scientificName == "Ceratium horridum")

c_crio <- micro %>% 
  filter(scientificName == "Corethron criophilum")

p_pouc19 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" & year == 2019) %>% 
  filter(scientificName == "Phaeocystis pouchetii")

p_pouc <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName == "Phaeocystis pouchetii")

proro <- micro %>% 
  filter(scientificName == "Prorocentrum")

proro_g <- micro %>% 
  filter(scientificName == "Prorocentrum gracile")

cory <- micro %>% 
  filter(scientificName == "Corythodinium")

thal <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName == "Thalassiosira nordenskioeldii")

thal_p <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName == "Thalassiosira pacifica")

cha_soc <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName == "Chaetoceros socialis")

pn_s <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName == "Pseudo-nitzschia seriata")

dfo2_
```




```{r}
#Selecting the species groups I will work with and limiting species that rarely observed.

#For now, I am keeping all of the heterotrophic species (just in this workbook)

# micro <- micro %>% 
#   filter(trophicStatus == "auto")

#Counting how many times each species is observed
micro <- micro %>%
  group_by(scientificName) %>%
  mutate(num_occurrence = n())

#removing species that have not been observed at least twice -  this is to minimize the influence of zeros. When I used this, it removes some species that are important, but not observed often. So trying with it turned off.
# micro <- micro %>%
#   filter(num_occurrence > 5)

#Removing cyanobacteria as thier counts are not reliable
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")

```

```{r}
#Looking at the distinct groups and species being utilized
distinct_species <- micro %>% 
  distinct(group, scientificName_accepted)

#I am removing metozoa and protozoa because I'm not sure they are easily quantifiable with these methods.
micro <- micro %>% 
  filter(!group == "Metazoa") %>% 
  filter(!group == "Protozoa")

distinct_species_2 <- micro %>% 
  distinct(group, scientificName_accepted)
```

```{r}
#Preparing data for cluster and nMDS analysis - need to be put into two separate matrices.

#Selecting columns
micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Adding year to wide format for plotting
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Arranging according to site ID and date
micro_piv <- micro_piv %>% 
  arrange(site_id, date)

#Removing QU39 to focus analysis on QU39
micro_piv <- micro_piv %>% 
  filter(!site_id == "QU39")

#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 6:ncol(micro_piv)]

#Creating relative abundance matrix - not currently looking at relative abundance
# transform_rel <- decostand(species, method = "total")
  
#Log10 transformation + 1 (as per Mahara)
transform <- log10(species + 1)

#Not currently working with relative abundance
# transform_rel <- sqrt(transform_rel)
```

```{r}
#Creating rownames for dendrogram creating

#Combining site and date
# labs <- micro_piv %>%
#   select(site_id, date) %>% 
#   unite(sample_name, c(site_id, date), sep = "_")

metadata <- micro_piv %>%
  select(site_id, date) %>% 
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE) %>% 
  relocate(sample_name, .before = date)

#Creating a list of rownames
# labs_list <- labs$sample_name
labs_list <- metadata$sample_name

#creating a hierarchical clustering matrix
transform_hc <- transform

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(transform_hc) <- labs_list
```


```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- vegdist(transform_hc, method = "bray")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "average")

```

```{r}
#Looking at number of clusters
fviz_nbclust(transform, FUN = hcut, method = "wss")
fviz_nbclust(transform, FUN = hcut, method = "silhouette")
```
```{r}
gap_stat <- clusGap(transform, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```


```{r}
#This step sets clusters. Currently, I am not using.

# k <- 6
# clust <- cutree(cluster.average, k = k)
# 
# clust.df <- clust.df <- data.frame(label = rownames(transform_hc),
#                                    cluster = factor(clust))

# write_csv(clust.df, here("outputs", "clusters_micro_6.csv"))
```

```{r}
# extract dendrogram segment data for plotting

dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
#Creating metadata sheet with 
# metadata <- micro_piv %>% 
#   select(site_id, date)

# metadata <- micro_piv %>% 
#    select(sample_name, site_id, date)

#Making unique labels by combining site and date into single string
# metadata <- metadata %>% 
#   unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

# get terminal dendrogram segments and join with names.
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

# dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
# rect <- aggregate(x~cluster, label(dendrogram_data), range)
# rect <- data.frame(rect$cluster, rect$x)
# ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
p_dend <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 # geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0, ymax = ymax),
 #            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(0.6, -0.3)) +
 coord_flip() + 
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_rev2", "hc_average.png"), p_dend,
       width = 6, height = 12, dpi = 300)
```

```{r}
#Running nmds on Calvert data
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 


nmds
#Not currently running on relative data.
# nmds_rel <-  metaMDS(transform_rel, distance = "bray", autotransform = FALSE,
#                          k = 2, trymax = 100) 


#Checking stressplot for fit
stressplot(nmds)

# stressplot(nmds_rel)

```

```{r}
# For clusters, need to merge on station/date code.
micro_piv <- micro_piv %>%
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

micro_piv <- micro_piv %>%
  left_join(clust_phy) %>%
  relocate(cluster, .after = month_surv) %>% 
  rename(clust_phy = cluster)

#Didn't use clusters from HC on microscopy data because no clear clusters showed up.
# clust_df <- clust.df %>%
#   rename(sample_name = label)

# micro_piv <- micro_piv %>%
#   left_join(clust_df) %>%
#   relocate(cluster, .after = month_surv)

```


```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

# https://stackoverflow.com/questions/14711470/plotting-envfit-vectors-vegan-package-in-ggplot2
#If I want to try to get species vectors on plot try above link, near bottom
# spp.scrs <- as.data.frame(scores(nmds_sp, display = "vectors"))
# test <- as.data.frame(nmds_sp, display = "pvals")
# spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

data.scores = as.data.frame(scores(nmds))
data.scores$month_surv = micro_piv$month_surv
data.scores$site = micro_piv$site_id
data.scores$year = micro_piv$year
data.scores$clust_phy = micro_piv$clust_phy

# data.scores.rel = as.data.frame(scores(nmds_rel))
# data.scores.rel$month_surv = micro_piv$month_surv
# data.scores.rel$site = micro_piv$site_id
# data.scores.rel$year = micro_piv$year

```

```{r}
#Trying to add species scores - Want to select the most important, but can't figure it out and wasting a lot of time on something that probably won't result in much gain.
vf <- envfit(nmds, transform, perm = 999)

r2 <- vf$vectors$r

test <- as.data.frame(r2)

spp.scrs <- as.data.frame(scores(vf, display = "vectors"))

spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

spp.scrs2 <- cbind(spp.scrs, test)

spp.scrs2 <- spp.scrs2 %>% 
  filter(r2 >= 0.40)
```



```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits. This is for the absolute data

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.5, 1.8) +
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = spp.scrs2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = "c(0.92, 0.6)",
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_absolute_CALVERT.png"),
#        width = 6, height = 4.5, dpi = 300)
```

```{r}
#nmds plot for the relative data

# ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores.rel, aes(fill = as.factor(month_surv), shape = site),
#              size = 4) + 
#   scale_fill_brewer(palette = "RdYlBu") +
#   # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
#   #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
#   # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
#   #           fontface = "bold", label = row.names(en_coord_cont)) + 
#   # xlim(-0.5, 1.0) +
#   theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         legend.key = element_blank(), 
#         legend.title = element_text(size = 10, face = "bold", colour = "black"), 
#         legend.text = element_text(size = 9, colour = "black"),
#         legend.position = c(0.94, 0.6),
#         legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
#         text = element_text(size = 30)) +
#   labs(fill = "Month", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_relative_CALVERT.png"),
#        width = 6, height = 4.5, dpi = 300)
```

```{r}
#Plotting nMDS - by cluster

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(data = data.scores, aes(fill = as.factor(clust_phy), shape = site),
             size = 4) +
  scale_fill_brewer(palette = "Set1") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) +
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) +
  # xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_text(size = 10, face = "bold", colour = "black"),
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Cluster", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

ggsave(here("figures_rev2", "nmds_micro_physical_clusters.png"),
       width = 6, height = 4.5, dpi = 300)
```

```{r}
#Combining absolute and relative nmds separated by station and month - It could be good to do this by year as well.

# p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
#              size = 6) + 
#   scale_fill_brewer(palette = "RdYlBu") +
#   # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
#   #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
#   # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
#   #           fontface = "bold", label = row.names(en_coord_cont)) + 
#   # xlim(-0.5, 1.8) +
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         axis.title.x = element_blank(),
#         legend.key = element_blank(), 
#         legend.title = element_text(size = 20, face = "bold", colour = "black"), 
#         legend.text = element_text(size = 18, colour = "black"),
#         legend.position = c(0.92, 0.68),
#         legend.margin = margin(-0.3,0,0,0, unit = "cm"),
#         text = element_text(size = 30)) +
#   labs(fill = "Month", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# p2 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores.rel, aes(fill = as.factor(month_surv), shape = site),
#              size = 6) + 
#   scale_fill_brewer(palette = "RdYlBu") +
#   # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
#   #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
#   # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
#   #           fontface = "bold", label = row.names(en_coord_cont)) + 
#   # xlim(-0.5, 1.0) +
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         # legend.key = element_blank(), 
#         # legend.title = element_text(size = 10, face = "bold", colour = "black"), 
#         # legend.text = element_text(size = 9, colour = "black"),
#         legend.position = "none",
#         legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
#         text = element_text(size = 25)) +
#   labs(fill = "Month", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# fig <- p1/p2

# ggsave(here("figures_rev2", "nmds_CALVERT.png"), fig,
#        width = 10, height = 12, dpi = 300)

```

```{r}
#Combining absolute and relative nmds - plots for both month and year

# p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
#              size = 6) + 
#   scale_fill_brewer(palette = "RdYlBu") +
#   # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
#   #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
#   # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
#   #           fontface = "bold", label = row.names(en_coord_cont)) + 
#   xlim(-0.4, 0.7) +
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         axis.title.x = element_blank(),
#         legend.key = element_blank(), 
#         legend.title = element_text(size = 20, face = "bold", colour = "black"), 
#         legend.text = element_text(size = 18, colour = "black"),
#         legend.position = c(0.90, 0.68),
#         legend.margin = margin(-0.3,0,0,0, unit = "cm"),
#         text = element_text(size = 30)) +
#   labs(fill = "Month", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
#              size = 6) + 
#   scale_fill_brewer(palette = "Dark2") +
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   xlim(-0.4, 0.7) +
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         legend.key = element_blank(), 
#         legend.title = element_text(size = 20, face = "bold", colour = "black"), 
#         legend.text = element_text(size = 18, colour = "black"),
#         legend.position = c(0.90, 0.75),
#         legend.margin = margin(-0.3,0,0,0, unit = "cm"),
#         text = element_text(size = 30)) +
#   labs(shape = "Station", fill = "Year") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# p3 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores.rel, aes(fill = as.factor(month_surv), shape = site),
#              size = 6) + 
#   scale_fill_brewer(palette = "RdYlBu") +
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         legend.position = "none",
#         legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
#         text = element_text(size = 25)) +
#   labs(fill = "Month", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# p4 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores.rel, aes(fill = as.factor(year), shape = site),
#              size = 6) + 
#   scale_fill_brewer(palette = "Dark2") +
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         axis.title.y = element_blank(),
#         # axis.title.x = element_blank(),
#         legend.position = "none",
#         text = element_text(size = 25)) +
#   labs(fill = "Year", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# fig <- (p1 + p2) / (p3 + p4)
# 
# ggsave(here("figures_rev2", "nmds_CALVERT_year_all_spec.png"), fig,
#        width = 16, height = 12, dpi = 300)

```


```{r}
#Combining station month and year plots with dendrogram - sort of cool, but now have to figure out why DFO2 different. This is where a heatmpa plot comes in?

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.75),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(shape = "Station", fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

fig <- (p1/p2) | p_dend

ggsave(here("figures_rev2", "nmds_dendro_all_spec_2.png"), fig,
       width = 16, height = 12, dpi = 300)

```

```{r}
#Making another version for incorportion with different panel

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  annotate("text", x = -0.39, y = 0.35, label = "a)", size = 10) +
  annotate("text", x = 0.53, y = -0.30, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  annotate("text", x = -0.39, y = 0.35, label = "b)", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.86),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Year", shape = "Station") +
    guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

fig_nmds_horiz <- (p1 + p2)
```


```{r}
#Making another version for incorportion with different panel

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 7) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 7) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.75),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Year", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

fig_nmds_vert <- (p1 / p2)
```

```{r}
#separating treatments for following tests
site_id <- micro_piv$site_id
month <- micro_piv$month_surv
year <- micro_piv$year
cluster <- micro_piv$clust_phy
```



```{r}
#ANOSIM test to see if groupings statistically significant - abundance
ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
ano_site

ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
ano_month

ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
ano_year

# ano_cluster = anosim(transform, cluster, distance = "bray", permutations = 9999)
# ano_cluster

#Site and region are significant (p = 0.0001), with region having the highest R (0.62 vs 0.27) 

```


```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station
inv_site = multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_site)
```



```{r}
#Pulling out list of species from indicator analysis on station - Not currently used to make plot, but cool that I can do this - makes further analysis much easier and replicatable.
inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)
```

```{r}
# by month - Noth currently using.
inv_month = multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_month)
```

```{r}
#by year
inv_year = multipatt(transform, year, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_year)
```


```{r}
#Looking at p-value correction for indicator species analysis.
# https://stats.stackexchange.com/questions/370724/indiscpecies-multipatt-and-overcoming-multi-comparrisons

inv_year_sp <- data.table::as.data.table(inv_year$sign, keep.rownames = TRUE)

```

```{r}
#by cluster - Not currently using.
inv_cluster = multipatt(transform, cluster, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_cluster)
```

```{r}
#This section is all different attempts at heat maps using different ordering and species.

#Take a look at this - https://stackoverflow.com/questions/42047896/joining-a-dendrogram-and-a-heatmap
```


```{r}
#Ordering the data in the order of the dendrogram from hierarchical clustering.

#Creating a list with the order of the samples in the dendrogram.
hc_order <- dendrogram_ends$sample_name

#Creating a separate workbook, in tidy format, with the combined site and date name. 
micro_heat <- micro %>%
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE) %>%
  filter(!site_id == "QU39")

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))

#Setting order of species for figure organized by group (i.e diatoms) and then species alphabetical within.
micro_heat$species_order <- factor(micro_heat$scientificName,
                                   (unique(micro_heat$scientificName
                                              [order(micro_heat$group,
                                                     micro_heat$scientificName)])))
```


```{r}
#Making a plot with all species in the order of the dendrogram. 
micro_heat %>%
  ggplot(aes(x = sample_name, y = species_order, fill = log10(count+1))) +
  geom_tile(color = "black") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        axis.line = element_line(colour = "black"))

# ggsave(here("figures_rev2", "heat_all_species_dendro_order.png"),
#        width = 16, height = 25, dpi = 300)
```

```{r}
#Plotting the same as above (dendrogram order), but trying with only the indicator species (p < 0.01) Combining this later with the nMDS and dendrogram plots.

# h1 <- micro_heat %>%   
#    filter(scientificName == "Chaetoceros decipiens" |
#            scientificName == "Dactyliosolen phuketensis" |
#            scientificName == "Detonula pumila" |
#            scientificName == "Thalassiosira rotula" |
#            scientificName == "Ceratium lineatum" |
#            scientificName == "Dactyliosolen fragilissimus" |
#            scientificName == "Chaetoceros debilis" |
#            scientificName == "Guinardia delicatula" |
#            scientificName == "Rhizosolenia setigera" |
#            scientificName == "Chaetoceros seiracanthus" |
#            scientificName == "Skeletonema marinoi") %>%
#   ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
#   geom_tile(color = "black", size = 1) +
#   facet_grid(. ~ group, scales = "free_x", space = "free") +
#   scale_fill_gradient(name = "",
#                       low = "#FFFFFF",
#                       high = "#012345") +
#   # scale_fill_gradient2(name = "",
#   #                      midpoint = 3,
#   #                      low = "white",
#   #                      mid = "blue",
#   #                      high = "#FF0000") +
#   scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
#                               "Chaetoceros decipiens" = "C.dec.",
#                               "Chaetoceros seiracanthus" = "C.s.",
#                               "Dactyliosolen fragilissimus" = "D.f.",
#                               "Dactyliosolen phuketensis" = "D.ph.",
#                               "Detonula pumila" = "D.p.",
#                               "Guinardia delicatula" = "G.d.",
#                               "Rhizosolenia setigera" = "R.s.",
#                               "Skeletonema marinoi" = "S.m.",
#                               "Thalassiosira rotula" = "T.r.",
#                               "Ceratium lineatum" = "C.l.")) +
#   # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank(),
#         # legend.position = "bottomright",
#         axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         text = element_text(size = 35),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         legend.position = c(0.1, 0.03),
#         legend.direction = "horizontal",
#         axis.line = element_line(colour = "black"))

# ggsave(here("figures_rev2", "heat_dendro_order_station_indicator.png"),
#        width = 13, height = 18, dpi = 300)
```

```{r}
#Plotting the same as above (dendrogram order), but trying with only the indicator species (p <0.01). Trying again with no labels. Not sure what is difference from above here, but this is what I am using to construct the panel.

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))

# micro_heat$date_fact <- as.factor(micro_heat$date)
# 
# micro_heat$test <- reorder(micro_heat$date_fact, micro_heat$sample_name)


h1_1 <- micro_heat %>%   
   filter(scientificName == "Chaetoceros decipiens" |
           scientificName == "Dactyliosolen phuketensis" |
           scientificName == "Detonula pumila" |
           scientificName == "Thalassiosira rotula" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Dactyliosolen fragilissimus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Skeletonema marinoi") %>%
  ggplot(aes(x = sample_name, y = species_order, fill = log10(count + 1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(group ~ ., scales = "free_y", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "none",
        legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

```

```{r}
#Second approach to try to lineup dendrogram with heatmap so that they can be combined in a panel.
p_dend2 <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 # geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
 #                                       color = site_id),
 #           hjust = 0, angle = 0, size = 8) +
 # geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0, ymax = ymax),
 #            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 # scale_x_reverse(limits = c(0.51, 0)) +
 scale_x_continuous(expand = c(0.01, 0.01)) + 
 # coord_flip() + 
 annotate("text", x = 49.5, y = 0.43, label = "c)", size = 10) +
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.x = element_blank(),
       text = element_text(size = 25),
       axis.line = element_line(colour = "black"),
       axis.text = element_text(colour = "black")) 

```


```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / h1_1 + plot_layout(heights = c(1, 3))

fig2 <- fig_nmds_horiz / fig

ggsave(here("figures_rev2", "nmds_dendro_heat.png"), fig2,
       width = 16, height = 14, dpi = 300)
```




```{r}

#Indicator species from clustering - 6 clusters - organized by cluster.

#Indicator species from clustering - 6 clusters. 
# micro_heat3 <- micro_heat
# 
# clust_df <- clust.df %>% 
#   rename(sample_name = label)
# 
# micro_heat3 <- micro_heat3 %>% 
#   left_join(clust_df) %>% 
#   relocate(cluster, .after = site_id)
# 
# micro_heat3 <- micro_heat3 %>% 
#   mutate(group = case_when(scientificName == "Ciliophrys infusionum" ~ "Dictyochophyta",
#          TRUE ~ as.character(as.character(group))))
# 
# 
# micro_heat3$sample_name <- factor(micro_heat3$sample_name,
#                                    (unique(micro_heat3$sample_name
#                                               [order(micro_heat3$cluster)])))
# 
# micro_heat3 %>%   
#   filter(scientificName == "Protoperidinium steinii" |
#            scientificName == "Thalassiosira nordenskioeldii" |
#            scientificName == "Chaetoceros laciniosus" |
#            scientificName == "Ciliophrys infusionum" |
#            scientificName == "Chaetoceros debilis" |
#            scientificName == "Attheya" |
#            scientificName == "Leptocylindrus danicus" |
#            scientificName == "Dactyliosolen fragilissimus" |
#            scientificName == "Thalassiosira" |
#            scientificName == "Scrippsiella trochoidea" | #good.
#            scientificName == "Pseudo-nitzschia seriata" | #good
#            scientificName == "Pyramimonas orientalis" | #good
#            scientificName == "Apedinella spinifera" | #good
#            scientificName == "Hillea" |
#            scientificName == "Skeletonema marinoi") %>%
#   ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
#   geom_tile(color = "black", size = 1) +
#   facet_grid(cluster ~ group, scales = "free", space = "free") +
#   scale_fill_gradient(name = "",
#                       low = "#FFFFFF",
#                       high = "#012345") +
#   # scale_fill_gradient2(name = "",
#   #                      midpoint = 3,
#   #                      low = "white",
#   #                      mid = "blue",
#   #                      high = "#FF0000") +
#   scale_x_discrete(labels = c("Attheya" = "A.",
#                               "Chaetoceros debilis" = "C.deb.",
#                               "Chaetoceros laciniosus" = "C.lac.",
#                               "Dactyliosolen fragilissimus" = "D.f.",
#                               "Leptocylindrus danicus" = "L.d.",
#                               "Pseudo-nitzschia seriata" = "P.n.s",
#                               "Skeletonema marinoi" = "S.m.",
#                               "Thalassiosira" = "T.",
#                               "Thalassiosira nordenskioeldii" = "T.n.",
#                               "Pyramimonas orientalis" = "P.o.",
#                               "Apedinella spinifera" = "A.s.",
#                               "Hillea" = "Hill.",
#                               "Ciliophrys infusionum" = "C.i.",
#                               "Protoperidinium steinii" = "P.s.",
#                               "Scrippsiella trochoidea" = "S.t.")) +
#   # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank(),
#         # legend.position = "bottomright",
#         axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         text = element_text(size = 35),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         # legend.position = c(0.1, 0.03),
#         legend.position = "none",
#         # legend.direction = "horizontal",
#         axis.line = element_line(colour = "black"))
# 
# ggsave(here("figures_rev2", "heat_indicator_6_clusters_abbr_good_3.png"),
#        width = 13, height = 18, dpi = 300)
```




```{r}

#Year

micro_heat2 <- micro_heat

micro_heat2$sample_name <- factor(micro_heat2$sample_name,
                                   (unique(micro_heat2$sample_name
                                              [order(micro_heat$date)])))


micro_heat2 %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(scientificName == "Ceratium horridum" |
           scientificName == "Telonema subtilis" |
           scientificName == "Corethron criophilum" |
           scientificName == "Teleaulax acuta" |
           # scientificName == "Protoperidinium" |
           scientificName == "Prorocentrum" |
           scientificName == "Phaeocystis pouchetii" |
           scientificName == "Katodinium" |
           scientificName == "Corythodinium" |
           scientificName == "Gonyaulax" |
           scientificName == "Dinophyceae" |
           scientificName == "Skeletonema marinoi" |
           scientificName == "Thalassiosira nordenskioeldii" |
           scientificName == "Leptocylindrus danicus" |
           scientificName == "Dinobryon" |
           scientificName == "Pseudo-nitzschia seriata" |
           scientificName == "Gyrodinium" |
           scientificName == "Biddulphiales") %>% 
  ggplot(aes(x = species_order, y = reorder(sample_name, desc(date)), fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(year ~ group, scales = "free", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  scale_x_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corethron criophilum" = "C.c.", #Y
                              "Leptocylindrus danicus" = "L.d.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira nordenskioeldii" = "T.n.",
                              "Dinobryon" = "Db.",
                              "Teleaulax acuta" = "T.a.", #Y
                              "Ceratium horridum" = "C.h.", #Y
                              "Corythodinium" = "C.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Prorocentrum" = "Prc.",
                              "Telonema subtilis" = "T.s.",
                              "Phaeocystis pouchetii" = "P.p.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "none",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_year_all_spec_2.png"),
       width = 13, height = 18, dpi = 300)

```


```{r}

#Indicator species from clustering - 5 clusters. 
# micro_heat %>% arrange(factor(sample_name, levels = hc_order)) 
micro_heat_site <- micro_heat

micro_heat_site$sample_name <- factor(micro_heat_site$sample_name,
                                   (unique(micro_heat_site$sample_name
                                              [order(micro_heat_site$site_id)])))


micro_heat_site %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(scientificName == "Chaetoceros decipiens" |
           scientificName == "Dactyliosolen phuketensis" |
           scientificName == "Detonula pumila" |
           scientificName == "Thalassiosira rotula" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Dactyliosolen fragilissimus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = species_order, y = as.factor(date), fill = log10(count + 1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(site_id ~ group, scales = "free", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "none",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_site_good_all_spec.png"),
       width = 6, height = 14, dpi = 300)

```
```{r}

#Indicator species from clustering - 5 clusters. 
# micro_heat %>% arrange(factor(sample_name, levels = hc_order)) 
micro_heat_site <- micro_heat

micro_heat_site$sample_name <- factor(micro_heat_site$sample_name,
                                   (unique(micro_heat_site$sample_name
                                              [order(micro_heat_site$site_id)])))

p_heat <- micro_heat_site %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(scientificName == "Chaetoceros decipiens" |
           scientificName == "Dactyliosolen phuketensis" |
           scientificName == "Detonula pumila" |
           scientificName == "Thalassiosira rotula" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Dactyliosolen fragilissimus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = as.factor(date), y = species_order, fill = log10(count + 1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(group ~ site_id, scales = "free", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "right",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_test.png"),
       width = 14, height = 5, dpi = 300)

```

```{r}

#Combining station month and year plots with dendrogram - sort of cool, but now have to figure out why DFO2 different. This is where a heatmpa plot comes in?

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv),
                                     shape = site), size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.75),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(shape = "Station", fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))


fig <- (fig_nmds_vert | p_dend) / p_heat + plot_layout(heights = c(4, 1))

ggsave(here("figures_rev2", "nmds_dendro_heat_test.png"), fig,
       width = 16, height = 17, dpi = 300)

```

```{r}
#Creating a list of species determined via indicator species analysis on stations.
ind_list <- c("Chaetoceros decipiens", "Dactyliosolen phuketensis", 
              "Detonula pumila", "Thalassiosira rotula" , "Ceratium lineatum", 
              "Dactyliosolen fragilissimus", "Chaetoceros debilis", 
              "Guinardia delicatula", "Rhizosolenia setigera", 
              "Chaetoceros seiracanthus", "Skeletonema marinoi")  
```

```{r}
#Sub-setting the species determined via indicator species analysis on station
micro_ind_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% ind_list)

#Determining number of times each indicator species observed at each station
micro_ind_stat <- micro_ind_stat %>% 
  group_by(site_id, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum)) %>% 
  ungroup() 

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_station <- micro %>% 
  filter(!site_id == "QU39") %>% 
  group_by(date, site_id) %>% 
  distinct(date, site_id) %>% 
  ungroup() %>% 
  group_by(site_id) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_ind_stat <- micro_ind_stat %>% 
  left_join(n_station) %>% 
  mutate(perc_obs = n_obs/n_samp)
```
```{r}
#Creating a placeholder for Ceratium lineatum for DFO2 - makes plot save a space so the groupings stay consistent.
dfo_cl <- data.frame(site_id = "DFO2",
                     scientificName = "Ceratium lineatum",
                     n_obs = 0,
                     max_count = 0,
                     mean_count = 0,
                     n_samp = 0,
                     perc_obs = 0)
                 
micro_ind_stat <- rbind(dfo_cl, micro_ind_stat)
```


```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = perc_obs, y = scientificName, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 1.03)) +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
  labs(x = "% Observed") +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = mean_count, y = scientificName, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(x = "Mean Abundance (cells l)") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 26000)) +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.85, 0.1),
          legend.title = element_blank())

fig <- p1 + p2

ggsave(here("figures_rev2", "indicator_species_station_bar.png"), fig,
       width = 12, height = 7, dpi = 300)
```
```{r}
#Trying to do the same for annual indicator analysis. Creating a list of species determined via indicator species analysis on stations.

#subsetting species from annual indicator species analysis that had p values <= 0.01.
inv_year_sp <- inv_year_sp %>% 
  filter(p.value <= 0.01)

#Creating a list of the significant species from indicator species analysis.
inv_year_lis <- inv_year_sp$rn

```

```{r}
#Sub-setting the species determined via indicator species analysis on station
micro_year_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% inv_year_lis) %>% 
  mutate(year = lubridate::year(date))

#Determining number of times each indicator species observed at each station
micro_year_stat <- micro_year_stat %>% 
  group_by(year, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum)) %>% 
  ungroup() 

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_station_year <- micro %>% 
  filter(!site_id == "QU39") %>%
  mutate(year = lubridate::year(date)) %>% 
  group_by(date, year) %>% 
  distinct(date, year) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_year_stat <- micro_year_stat %>% 
  left_join(n_station_year) %>% 
  mutate(perc_obs = n_obs/n_samp)
```
```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_year_stat %>% 
  ggplot(aes(x = perc_obs, y = scientificName, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 1.03)) +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corythodinium" = "C.",
                              "Ceratium horridum" = "C.h.", #Y
                              "Corethron criophilum" = "C.c.", #Y
                              "Dinobryon" = "Db.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Phaeocystis pouchetii" = "P.p.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Teleaulax acuta" = "T.a.",
                              "Telonema subtilis" = "T.s.",
                              "Thalassiosira nordenskioeldii" = "T.n.")) +
  theme_bw() +
  labs(x = "% Observed") +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_year_stat %>% 
  ggplot(aes(x = mean_count, y = scientificName, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(x = "Mean Abundance (cells l)") +
  # scale_x_continuous(expand = c(0.01, 0), limits = c(0, 26000)) +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corythodinium" = "C.",
                              "Ceratium horridum" = "C.h.", #Y
                              "Corethron criophilum" = "C.c.", #Y
                              "Dinobryon" = "Db.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Phaeocystis pouchetii" = "P.p.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Teleaulax acuta" = "T.a.",
                              "Telonema subtilis" = "T.s.",
                              "Thalassiosira nordenskioeldii" = "T.n.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.85, 0.1),
          legend.title = element_blank())

fig <- p1 + p2

ggsave(here("figures_rev2", "indicator_species_year_bar.png"), fig,
       width = 12, height = 7, dpi = 300)
```






























