---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)
library(ggcorrplot) 
library(analogue)
# library(clustsig)
library(BiodiversityR)
library(ggsci)

```

```{r}
#Upload data

#Upload microscopy abundance data in OBIS and long/tide format
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Upload physical-chemical clusters derived via PCA
clust_pca <- read_csv(here("outputs", "pca_clusters_2023-08-2.csv"))

#Physical - chemical data
data <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

#Chlorophyll data
chl <- read_csv(here("outputs", "tchla_calibration_2022-08-04.csv"))

#General environmental data - discharge etc.
env <- read_csv(here("outputs", "enviro_2023-05-26_up.csv"))

sf <- read_csv(here("files", "chl_2018_2020.csv"))

chem <- read_csv(here("files", "chemtax_2023-04-14.csv"))

#Uploading size separated S.marinoi counts.
sm_size <- read_csv(here("outputs", "s_mar_size_2023-07-03.csv"))
```


```{r}
test <- micro %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  filter(site_id == "KC10" & year == 2019 & month == "7")
```

```{r}
#Filtering out bulk chlorophyll, removing bad data and cutting down on colums
sf_less <- sf %>% 
  filter(line_out_depth == 5 & !filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | is.na(chla_flag)) %>%
  mutate(year = lubridate::year(date)) %>% 
  select(date, year, site_id, filter_type, chla) %>% 
  filter(!is.na(chla)) %>% 
  group_by(date) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3) %>% 
  select(-n_filt) %>% 
  group_by(date, site_id) %>% 
  mutate(sum_sf = sum(chla)) %>% 
  ungroup() %>% 
  mutate(perc_sf = chla/sum_sf) 
```

```{r}
chem <- chem %>% 
  rename(cyan = Cyanobacteria, hapt = Hapto, GA = `Prasinophytes-3`,
         cryp = Cryptophytes, dino = `Dinoflagellates-1`, raph = Raphido,
         dict = Dictyo, diat = `Diatoms-1`)

chem_long <- chem %>% 
  pivot_longer(c(cyan:diat), values_to = "tchla", names_to = "group")
```



```{r}

data <- data %>% 
  select(date:secchi_depth)

#Joining all of the data
data_join <- data %>% 
  left_join(chl) %>% 
  left_join(env) 

#Relocating metadata
data_join <- data_join %>% 
  relocate(location, .after = site_id)

#Adding date information and relocating
data_join <- data_join %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(month, .after = date) %>% 
  relocate(year, .after = month)
```

```{r}
#Selecting the variables I want
data_pca <- data_join %>%
  select(date, month, year, site_id, location, temp = temp_dm, 
         sal = sal_dm, drho = delta_rho_dm, no2 = no2_dm, po4_dm, 
         sio2_dm, secchi = secchi_depth, sm_b1, gm_b1, ra_b1, wan_b1, wind_b1, 
         wind_dir_b1, up_b1, dep_26_dm, tchla, par_b1)


```

```{r}
data_pca_long <- data_pca %>% 
  select(date, site_id, temp:par_b1) %>% 
  pivot_longer(c(temp:par_b1), names_to = "par", values_to = "val")

```

```{r}

#Adding location instead of site ID for interpretation of results
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

#Creating a unique location-date ID for each sample - makes labels for plotting by dendrogram more informative 
micro <- micro %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

clust_pca <- clust_pca %>% 
  rename(sample_name = label)


#Joining the PCA clusters to the microscopy data
micro <- micro %>% 
  left_join(clust_pca) %>% 
  relocate(cluster, .after = location)

```

```{r}
#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

# Separating out diatoms
micro <- micro %>%
  filter(group == "Bacillariophyta")
```

```{r}
#Filtering out species that are not present in at least 10% of the samples - this is important for the clustering and nMDS methods I am using as these species can skew the results.

#Determining total number of samples in the dataset
sample_num <- micro %>% 
  distinct(date, site_id)

#Determining species that are present in > 10% of samples.
species_10 <- micro %>% 
  group_by(scientificName) %>% 
  summarise(n_obs = n()) %>%
  ungroup() %>% 
  mutate(perc_obs = n_obs/78) %>% 
  filter(perc_obs >= 0.10)

# species_2 <- micro %>% 
#   group_by(scientificName) %>% 
#   summarise(max_abund = max(species_sum)) %>% 
#   ungroup() %>% 
#   filter(max_abund < 5000)

#Creating a list of species in > 10% of samples.
species_10_list <- species_10$scientificName
# species_2_list <- species_2$scientificName

#Removing species that are not present in > 10% of samples.
micro <- micro %>% 
  filter(scientificName %in% species_10_list) 
# %>% 
#   filter(!scientificName %in% species_2_list)
```

```{r}
#Adding year and month to the microscopy dataset for analysis.

micro <- micro %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)
```

```{r}
#Preparing data for the different analysis.

#Selecting columns that I will use
micro_piv <- micro %>% 
  select(sample_name:cluster, scientificName, species_sum)

#pivoting wider so species are columns and samples are rows.
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, 
              values_from = species_sum, values_fill = 0) 

```


```{r}
#Pulling out species counts for transformation and use in analysis
species <- micro_piv[, 8:ncol(micro_piv)]

#Transforming the abundance data
# t_abund <- disttransform(species, method = "chord")

t_abund <- sqrt(species)

```

```{r}
#Making separate sheets to performed clustering on.
hc_abund <- t_abund

#Creating a list of rownames to attach to the clustering sheets - allows me to plot on the dendrogram.
labs_list <- micro_piv$sample_name

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(hc_abund) <- labs_list

```

```{r}
#method to assess
m <- c("average", "single","complete","ward")
names(m) <- c("average", "single","complete","ward")

#function to compute coefficient
ac <- function(x){agnes(hc_abund, method = x)$ac}
map_dbl(m,ac)
```

```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis_abund <- vegdist(hc_abund, method = "bray")


#Applying wards linkage method
# clust_ward_abund <- agnes(dis_abund, method = "ward")
clust_ward_abund <- hclust(dis_abund, method = "complete")


```

```{r}
coph <- cophenetic(clust_ward_abund)
cor(dis_abund, coph) 
```

```{r}
# Enhanced hierarchical clustering, cut in 3 groups
fviz_dend(clust_ward_abund, cex = 0.5, h = 0.67, color_labels_by_k = TRUE)

```

```{r}
#For the abundance data, looking at some methods to determine the number of clusters

#These are time intensive, so turning off until needed

fviz_nbclust(hc_abund, FUN = hcut, method = "wss")
fviz_nbclust(hc_abund, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(hc_abund, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)

#In general, these approaches do not show many clusters - only 2. This bothers me as there is clearly more structure in the data.
```


```{r}
#Trying cutting at line 

# Abundance data
k_abund <- 0.60
clust_abund <- cutree(clust_ward_abund, h = k_abund)
#
clust_df_abund <- data.frame(label = rownames(hc_abund),
                                   cluster = factor(clust_abund))
```


```{r}
# extract dendrogram segment data for plotting

#Abundance data
dend_abund <- as.dendrogram(clust_ward_abund)
dendrogram_data_abund <- dendro_data(dend_abund)
dendrogram_segments_abund <- dendrogram_data_abund$segments 

```

```{r}
#Setting up sheets so that I can color labels by station

#Creating metadata sheet with 
metadata <- micro_piv %>%
  select(sample_name, site_id)

# get terminal dendrogram segments and join with names. - abundance data.
dendrogram_ends_abund <- dendrogram_segments_abund %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data_abund$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. 


#Abundance
dendrogram_data_abund[["labels"]] <- merge(dendrogram_data_abund[["labels"]], clust_df_abund, by = "label")
rect_abund <- aggregate(x~cluster, label(dendrogram_data_abund), range)
rect_abund <- data.frame(rect_abund$cluster, rect_abund$x)
ymax_abund <- mean(clust_ward_abund$height[length(clust_ward_abund$height) - ((k_abund-2):(k_abund-1))])

```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

#Here doing abundance data

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars_abund <- levels(factor(dendrogram_ends_abund$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count_abund <- length(unique(unique_vars_abund$.))

# get RColorBrewer palette
get_palette_abund <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette_abund <- get_palette_abund(color_count_abund) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list_abund <- left_join(unique_vars_abund, palette_abund, by = "row_id") %>%
 select(-row_id)

site_color_abund <- as.character(color_list_abund$color)
names(site_color_abund) <- color_list_abund$.
```

```{r}
clust_df_abund2 <- clust_df_abund %>% 
  rename(sample_name = label)

dendrogram_ends_abund <- dendrogram_ends_abund %>% 
  left_join(clust_df_abund2)
```

```{r}
#Plotting dendrogram - saving for incorporation later.
dendro <- ggplot() +
 geom_segment(data = dendrogram_segments_abund, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends_abund, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = as.factor(cluster),
              size = 3)) +
 geom_text(data = dendrogram_ends_abund, aes(x = x, y = y.y, label = sample_name,
                                       color = as.factor(cluster),
           hjust = 1, angle = 90, size = 4)) +
 geom_hline(yintercept = 0.67, size = 1) +
 geom_rect(data = rect_abund, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0,
                                  ymax = ymax_abund),
            color = "black", fill = NA, size = 0.8) +
 # scale_color_manual(values = site_color_abund) +
 # scale_y_reverse(limits = c(1, -0.5)) +
 ylim(-0.7, 1) +
  # coord_flip() +
 theme_minimal() +
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.x = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") +
 annotate("text", x = 4, y = -0.3, label = "C2", size = 10) +
 annotate("text", x = 12, y = -0.3, label = "C1", size = 10) +
 annotate("text", x = 22, y = -0.3, label = "C5", size = 10) +
 annotate("text", x = 31.5, y = -0.3, label = "C6", size = 10) +
 annotate("text", x = 48, y = -0.3, label = "C4", size = 10) +
 annotate("text", x = 70, y = -0.3, label = "C3", size = 10)

ggsave(here("figures_nmds_new", "2023-09-11_complete_diat_65.png"),
       width = 16, height = 8, dpi = 300)
```

```{r}
#Setting up the derived abundance clusters for joining with the actual data
clust_abund_join <- clust_df_abund %>% 
  select(sample_name = label, clust_abund = cluster)

micro_piv <- micro_piv %>% 
  left_join(clust_abund_join) %>% 
  relocate(clust_abund, .after = cluster)

clust <- micro_piv %>% 
  select(date, site_id, clust_abund)
```


```{r}
# write_csv(clust, here("outputs", "bio_clust_full.csv"))

```
Should probably transfer indicator analysis for both PCA and taxonomy data to separate sheet

```{r}
#ANOSIM test to see if groupings statistically significant 
clust_pca <- micro_piv$clust_pca
clust_abund <- micro_piv$clust_abund

ano_clust_abund = anosim(t_abund, clust_abund, distance = "bray", permutations = 9999)
ano_clust_abund


```



```{r}
set.seed(123)

#Running nmds all species
nmds_abund <-  metaMDS(t_abund, distance = "bray", autotransform = F, 
                         k = 2, trymax = 100) 

#Show results including stress 
nmds_abund

#Checking stressplot for fit
stressplot(nmds_abund)

```


```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

#All abundance
data.scores_abund = as.data.frame(scores(nmds_abund))
data.scores_abund$date = micro_piv$date
data.scores_abund$month = micro_piv$month
data.scores_abund$site = micro_piv$location
data.scores_abund$year = micro_piv$year
data.scores_abund$clust_pca = micro_piv$pca_clust
data.scores_abund$clust_abund = micro_piv$clust_abund

```

```{r}
#Order locations from fjord to shelf for plotting order
order_loc <- c("F", "C", "S")

#Setting location order for plots 
data.scores_abund <- arrange(mutate(data.scores_abund,
                         site = factor(site, levels = order_loc)))

```


```{r}
# #Looking at species scores to add to the nmds plot
# 
#All species
vf <- envfit(nmds_abund, t_abund, perm = 999)
# 
# #Diatoms
# vf_diat <- envfit(nmds_diat, transform_diat, perm = 999)
# 
# #Dinoflagellates
# vf_dino <- envfit(nmds_dino, transform_dino, perm = 999)
# 
#Pulling out r2 scores
#All species
r2 <- vf$vectors$r
# 
# #Diatoms
# r2_diat <- vf_diat$vectors$r
# 
# #Diatoms
# r2_dino <- vf_dino$vectors$r
# 
#MAking dataframe out of r2 values
#All species
r2_df <- as.data.frame(r2)
# 
# #Diatoms
# r2_df_diat <- as.data.frame(r2_diat)
# 
# #Dino
# r2_df_dino <- as.data.frame(r2_dino)
# 
# #Pulling and binding vectors and r2 scores
# #All species
spp.scrs <- as.data.frame(scores(vf, display = "vectors"))
spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))
spp.scrs2 <- cbind(spp.scrs, r2_df)
```


```{r}
#Pulling species with only r2 > 0.3 scores
#All species
spp.scrs2 <- spp.scrs2 %>%
  filter(r2 >= 0.30)
# 
# #Diatoms
# spp.scrs2_diat <- spp.scrs2_diat %>%
#   filter(r2_diat >= 0.30)
# 
# #Dinoflagellates
# spp.scrs2_dino <- spp.scrs2_dino %>%
#   filter(r2_dino >= 0.30)
```


```{r}
#Making shorter abbreviated species names for plotting

# rownames(spp.scrs2) <- c("Hill.",
#                          "Tel.",
#                          "S.mar.",
#                          "P.pou.",
#                          "C.soc.",
#                          "C.cin.") 
# 
# rownames(spp.scrs2_diat) <- c("C.clo.",
#                               "P.n.s.",
#                               "R.set.",
#                               "Pen.",
#                               "S.mar.",
#                               "Bid.",
#                               "L.dan.")
# 
# rownames(spp.scrs2_dino) <- c("Gymn.",
#                               "Gyro.",
#                               "Kato.",
#                               "S.pre.",
#                               "S.tro.")
#                               
```

```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

ggplot(data = data.scores_abund, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_abund, aes(fill = as.factor(clust_abund), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Spectral") +
  scale_shape_manual(values = c(21, 22, 23)) + 
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) +
  ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2,
                                           label = row.names(spp.scrs2)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_nmds_new", "2023-07-11.png"),
#        width = 8, height = 5, dpi = 300)
```

```{r}
export_cluster <- data.scores_abund %>% 
  select(date, site, clust_abund)

write_csv(export_cluster, here("outputs", "final_cluster_2023-09-11_diat.csv"))
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for diatoms
inv_clust_abund = multipatt(t_abund, clust_abund, func = "r.g", duleg = T,
                       control = how(nperm = 999))

#Looking at results of analysis
summary(inv_clust_abund)

iv <- labdsv::indval(t_abund, clust_abund)

summary(iv)
```


```{r}
micro_test <- micro %>%
  left_join(clust_abund_join) %>% 
  group_by(clust_abund, scientificName) %>%
  summarise(mean_count = mean(species_sum)) %>% 
  ungroup() 

# micro_test %>% 
#   ggplot(aes(x = mean_count, y = clust_abund, fill = scientificName)) +
#   geom_bar(stat = "stack")
# 
# ggsave(here("figures_nmds_new", "test.png"),
#        width = 8, height = 16, dpi = 300)

micro_piv %>% 
  ggplot(aes(x = as.factor(clust_abund), y = `Skeletonema marinoi`)) +
  geom_boxplot()

micro_piv %>% 
  ggplot(aes(x = date, y = `Thalassiosira nordenskioeldii`, color = site_id)) +
  geom_line()

sm_size_join <- sm_size %>% 
  left_join(clust)

sm_size_join %>% 
  ggplot(aes(x = as.factor(clust_abund), y = species_sum, fill = scientificName)) +
  geom_boxplot()
```

```{r}
micro_piv <- micro_piv %>%
  mutate(month = lubridate::month(date)) %>% 
  mutate(season = case_when(month == 12 | month == 1 | month == 2 ~ "W",
                            month >= 3 & month <= 5 ~ "Sp",
                            month >= 6 & month <= 8 ~ "S",
                            month >= 9 & month <= 12 ~ "A",)) %>%
  relocate(season, .after = month)    
  
#I want to push December from each year to winter of the next year
micro_piv <- micro_piv %>%
  mutate(year = case_when(season == "winter" & month == 12 ~ year + 1,
                           TRUE ~ as.numeric(year)))

order_loc_seas <- c("W", "Sp", "S", "A")

micro_piv <- arrange(mutate(micro_piv,
                         season = factor(season, levels = order_loc_seas)))
```

```{r}
data_pca_join <- data_pca %>% 
  left_join(clust)
```



```{r}
f1 <- micro_piv %>% 
  ggplot(aes(x = as.factor(clust_abund), fill = as.factor(season))) +
  geom_bar(position = "stack", color = "black", alpha = 0.8) +
  scale_fill_manual(values = c("dodgerblue3", "darkolivegreen", "red2", "goldenrod1")) + 
  labs(y = "# of samples",
       x = "Cluster",
       fill = "") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.15, 0.82),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank())

f2 <- micro_piv %>% 
  ggplot(aes(x = as.factor(clust_abund), fill = as.factor(year))) +
  geom_bar(position = "stack", color = "black", alpha = 0.8) +
  scale_fill_brewer(palette = "Dark2") + 
  labs(y = "# of samples",
       x = "Cluster",
       fill = "") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.15, 0.82),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank())

f3 <- micro_piv %>% 
  ggplot(aes(x = as.factor(clust_abund), fill = as.factor(site_id))) +
  geom_bar(position = "stack", color = "black", alpha = 0.8) +
  # scale_fill_manual(values = c("brown", "forestgreen", "royalblue4"),
  #                   labels = c("F", "C", "S")) + 
  scale_fill_jco(labels = c("F", "C", "S")) +
  labs(y = "# of samples",
       x = "Cluster",
       fill = "") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.16, 0.82),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank())

f4 <- data_pca_join %>% 
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = temp, fill = as.factor(clust_abund))) +
  geom_boxplot() + 
  # ggpubr::stat_compare_means(size = 6) +
  labs(y = "Temp. (°C)") +
  scale_fill_npg() +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none")

f5 <- data_pca_join %>% 
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = sal, fill = as.factor(clust_abund))) +
  geom_boxplot() +
  scale_fill_npg() +
  labs(y = "Salinity") +
  # ggpubr::stat_compare_means(size = 6) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none")

f6 <- data_pca_join %>% 
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = sio2_dm, fill = as.factor(clust_abund))) +
  geom_boxplot() + 
  scale_fill_npg() +
  labs(y = "DSi\u207B\u0020\u0028\u00B5mol\u0020L\u207B\u00B9\u0029") +
  # ggpubr::stat_compare_means(size = 6) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none")

f7 <- data_pca_join %>% 
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = drho, fill = as.factor(clust_abund))) +
  geom_boxplot() +
  scale_fill_npg() +
  labs(y = "Δρ") +
  # scale_x_discrete(labels = c("1" = "W1",
  #                             "2" = "W2",
  #                             "3" = "Flag.",
  #                             "4" = "SM.",
  #                             "5" = "SB",
  #                             "6" = "PN"))
  # ggpubr::stat_compare_means(size = 6) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank(),
        legend.position = "none")

f8 <- data_pca_join %>% 
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = gm_b1/10^2, fill = as.factor(clust_abund))) +
  geom_boxplot() + 
  scale_fill_npg() +
  labs(y = bquote(G.Mtn. ~ "("~m^-3*~s^-1*")")) +
  # ggpubr::stat_compare_means(size = 6) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank(),
        legend.position = "none")

f9 <- data_pca_join %>% 
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = tchla, fill = as.factor(clust_abund))) +
  geom_boxplot() + 
  scale_fill_npg() +
  labs(y = bquote("TChla (mg" ~ m^-3*")")) +
  lims(y = c(0, 15)) +
  # ggpubr::stat_compare_means(size = 6) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.title.x = element_blank(),
        legend.position = "none")
```

```{r}
fig <- dendro / (f1 + f2 + f3 + f4 + f5 + f6 + f7 + f8 + f9) +
  plot_layout(heights = c(1.5, 4))

ggsave(here("figures_nmds_new", "test_diat.png"), fig,
       width = 16, height = 16, dpi = 300)
```

```{r}
kruskal.test(drho ~ clust_abund, data = data_pca_join)

data_pca_join$clust_abund <- as.factor(data_pca_join$clust_abund)

#Dunn Test to look where differences are occuring.
FSA::dunnTest(data_pca_join$drho ~ data_pca_join$clust_abund,
              method = "bonferroni")

```

```{r}
micro_clust <- micro %>% 
  left_join(clust_abund_join)
```


```{r}
shan_d <- diversity(species)

shan_d <- as.data.frame(shan_d)

shan_d$clust <- micro_piv$clust_abund

shan_d_med <- shan_d %>% 
  group_by(clust) %>% 
  summarise(median_h = median(shan_d)) %>% 
  ungroup()

rich <- micro %>% 
  group_by(sample_name) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  left_join(clust_abund_join) %>% 
  group_by(clust_abund) %>% 
  summarise(med_rich = median(n)) %>% 
  ungroup()

rich_diat <- micro %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(sample_name) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  left_join(clust_abund_join) %>% 
  group_by(clust_abund) %>% 
  summarise(med_rich = median(n),
            mean_rich = mean(n)) %>% 
  ungroup()

```
```{r}
#Preparing data for the different analysis.

#Selecting columns that I will use
micro_piv_diat <- micro %>%
  filter(group == "Bacillariophyta") %>% 
  select(sample_name:cluster, scientificName, species_sum)

#pivoting wider so species are columns and samples are rows.
micro_piv_diat <- micro_piv_diat %>% 
  pivot_wider(names_from = scientificName, 
              values_from = species_sum, values_fill = 0) 

micro_piv_diat <- micro_piv_diat %>% 
  left_join(clust_abund_join)

micro_piv_diat <- micro_piv_diat %>%
  relocate(clust_abund, .after = cluster)

species_diat <- micro_piv_diat[, 9:ncol(micro_piv_diat)]

shan_d_diat <- diversity(species_diat)

shan_d_diat <- as.data.frame(shan_d_diat)

shan_d_diat$clust_diat <- micro_piv_diat$clust_abund

shan_d_med_diat <- shan_d_diat %>% 
  group_by(clust_diat) %>% 
  summarise(median_h = median(shan_d_diat)) %>% 
  ungroup()
```

```{r}
micro_clust %>% 
  filter(scientificName == "Protoperidinium" | scientificName == "Gymnodinium" |
           scientificName == "Gyrodinium") %>% 
  ggplot(aes(x = as.factor(clust_abund), y = species_sum, fill = scientificName)) +
  geom_boxplot()

micro_clust %>% 
  filter(scientificName == "Oligotrichea") %>% 
  ggplot(aes(x = as.factor(clust_abund), y = species_sum, fill = scientificName)) +
  geom_boxplot()
```
```{r}
sf_join <- sf_less %>% 
  left_join(clust)
  
sf_join %>%
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = chla, fill = filter_type)) +
  geom_boxplot()

sf_join %>%
  filter(!is.na(clust_abund)) %>% 
  group_by(clust_abund, filter_type) %>% 
  summarise(mean = mean(chla)) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.factor(clust_abund), y = mean, fill = filter_type)) +
  geom_bar(position = "stack", stat = "identity")
```
```{r}
chem_join <- chem_long %>% 
  left_join(clust)
  
chem_join %>%
  filter(!is.na(clust_abund)) %>% 
  ggplot(aes(x = as.factor(clust_abund), y = tchla, fill = group)) +
  geom_boxplot()

chem_join %>%
  filter(!is.na(clust_abund)) %>% 
  group_by(clust_abund, group) %>% 
  summarise(mean = mean(tchla)) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.factor(clust_abund), y = mean, fill = group)) +
  geom_bar(position = "stack", stat = "identity")
```


