---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)
library(ggcorrplot) #Correlation plots

#Need to go through and test these

```

```{r}
#Upload data

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Uploading size separated S.marinoi counts.
# sm_size <- read_csv(here("outputs", "s_mar_size.csv"))
```

```{r}
#Removing Station QU39
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
#Adding location instead of site ID.
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 
```


```{r}
#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria" &
           !group == "Metazoa" &
           !group == "Protozoa" &
           !group == "Choanoflagellata" &
           !group == "Ciliophora" &
           !group == "Kinetoplastidea")

```


```{r}
# #For the site wide comparison, I want only where data were collected at all stations.
# 
# 
# #Determining total number of samples - deriving when a sample was collected at each station
# sample_num <- micro %>% 
#   distinct(date, site_id)
# 
# #Adding year and month to the sample records
# sample_num <-  sample_num %>% 
#   mutate(year = lubridate::year(date),
#          month = lubridate::month(date))
# 
# #Pushing the sampling month to following month when data collected at one station was collected at the end of the month.
# sample_num <- sample_num %>% 
#   mutate(month_surv = case_when(date == "2019-08-29" ~ 9,
#                                 date == "2020-04-30" ~ 5,
#                                 TRUE ~ as.numeric (month)))
# 
# 
# #Pulling out the sampling dates for each station so I can join them and filter out data where data wasn't collected at each station
# sample_num_s <- sample_num %>% 
#   filter(site_id == "QCS01") %>% 
#   select(date_s = date, year, month_surv)
# 
# sample_num_c <- sample_num %>% 
#   filter(site_id == "KC10") %>% 
#   select(date_c = date, year, month_surv)
# 
# sample_num_f <- sample_num %>% 
#   filter(site_id == "DFO2") %>% 
#   select(date_f = date, year, month_surv)
# 
# #Joining data to see where data was collected at each station for each transect/survey
# sample_compare <- sample_num_s %>% 
#   full_join(sample_num_c) %>% 
#   full_join(sample_num_f) %>% 
#   filter(!is.na(date_s))
# 
# #Pulling out the dates of sample collection for each station where data was collected at all stations on the survey/transect.
# shelf_list <- sample_compare$date_s
# channel_list <- sample_compare$date_c
# fjord_list <- sample_compare$date_f

```

```{r}
#Determining species that are present in > 10% of samples.
species_10 <- micro %>% 
  group_by(scientificName) %>% 
  summarise(n_obs = n()) %>%
  ungroup() %>% 
  mutate(perc_obs = n_obs/78) %>% 
  filter(perc_obs >= 0.10)

#Creating a list of species in > 10% of samples.
species_10_list <- species_10$scientificName

#Removing species that are not present in > 10% of samples.
micro <- micro %>% 
  filter(scientificName %in% species_10_list)

```

```{r}
#Subsetting data to where only data was collected across the transect for each survey
# micro2 <- micro %>% 
#   filter(date %in% shelf_list |
#            date %in% channel_list |
#            date %in% fjord_list)
```

```{r}
micro <- micro %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)
```

```{r}
#Creating separate sheets for just diatoms and dinoflagellates
micro_diat <- micro %>% 
  filter(class == "Bacillariophyceae")

micro_dino <- micro %>% 
  filter(class == "Dinophyceae")
```

```{r}
#Preparing data for nMDS analysis - needs to be in wide matrix.

#Selecting columns - all species
micro_piv <- micro %>% 
  select(date, month, location, scientificName, species_sum)

micro_piv_diat <- micro_diat %>% 
  select(date, month, location, scientificName, species_sum)

micro_piv_dino <- micro_dino %>% 
  select(date, month, location, scientificName, species_sum)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Diatoms
micro_piv_diat <- micro_piv_diat %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Dinoflagellates
micro_piv_dino <- micro_piv_dino %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))


#Adding year to wide format for plotting
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Diatoms
micro_piv_diat <- micro_piv_diat %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Dinoflaggelates
micro_piv_dino <- micro_piv_dino %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)
```


```{r}
#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 5:ncol(micro_piv)]

#Diatoms
species_diat <- micro_piv_diat[, 5:ncol(micro_piv_diat)]

#Dinoflagellates
species_dino <- micro_piv_dino[, 5:ncol(micro_piv_dino)]

# transform <- species
# 
# transform_diat <- species_diat
# 
# transform_dino <- species_dino

#Creating relative abundance matrix 
transform <- decostand(species, method = "total")

transform_diat <- decostand(species_diat, method = "total")

transform_dino <- decostand(species_dino, method = "total")

#Performing square root transformation
transform <- sqrt(transform)

#Diatoms
transform_diat <- sqrt(transform_diat)

#Dinoflagellates
transform_dino <- sqrt(transform_dino)
```


```{r}
#Setting up for ANOSIM and Indicator tests

#!!!THESE PROBABLY ARE ONLY CORRECT FOR MICRO_PIV, WON'T LINE UP FOR OTHERS!!!!

#separating treatments for ANOSMIM and indicator
loc <- micro_piv$location
month <- micro_piv$month
year <- micro_piv$year
```

```{r}
#ANOSIM test to see if groupings statistically significant 

# By Station
ano_site = anosim(transform, loc, distance = "bray", permutations = 9999)
ano_site

ano_site_diat = anosim(transform_diat, loc, distance = "bray", permutations = 9999)
ano_site_diat

ano_site_dino = anosim(transform_dino, loc, distance = "bray", permutations = 9999)
ano_site_dino

```

```{r}
# ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
# ano_month
# 
# ano_month_diat = anosim(transform_diat, month, distance = "bray", permutations = 9999)
# ano_month_diat
# 
# ano_month_dino = anosim(transform_dino, month, distance = "bray", permutations = 9999)
# ano_month_dino
```


```{r}
# ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
# ano_year
# 
# ano_year_diat = anosim(transform_diat, year, distance = "bray", permutations = 9999)
# ano_year_diat
# 
# ano_year_dino = anosim(transform_dino, year, distance = "bray", permutations = 9999)
# ano_year_dino

```

```{r}
set.seed(123)

#Running nmds all species
nmds <-  metaMDS(transform, distance = "bray", autotransform = F,
                         k = 2, trymax = 100) 

#Show results including stress 
nmds

#Checking stressplot for fit
stressplot(nmds)

```

```{r}
set.seed(123)

#Running nmds diatoms
nmds_diat <-  metaMDS(transform_diat, distance = "bray", autotransform = F,
                         k = 2, trymax = 100) 

#Show results including stress 
nmds_diat

#Checking stressplot for fit
stressplot(nmds_diat)
```

```{r}
set.seed(123)

#Running nmds dinoflagellates
nmds_dino <-  metaMDS(transform_dino, distance = "bray", autotransform = F,
                         k = 2, trymax = 100) 

#Show results including stress 
nmds_dino

#Checking stressplot for fit
stressplot(nmds_dino)
```
```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

#All species
data.scores = as.data.frame(scores(nmds))
data.scores$month = micro_piv$month
data.scores$site = micro_piv$location
data.scores$year = micro_piv$year

#Diatoms
data.scores_diat = as.data.frame(scores(nmds_diat))
data.scores_diat$month = micro_piv$month
data.scores_diat$site = micro_piv$location
data.scores_diat$year = micro_piv$year


#Dinoflagellates
data.scores_dino = as.data.frame(scores(nmds_dino))
data.scores_dino$month = micro_piv$month
data.scores_dino$site = micro_piv$location
data.scores_dino$year = micro_piv$year

```

```{r}
#Order locations from fjord to shelf for plotting order
order_loc <- c("F", "C", "S")

#Setting location order for plots 
data.scores <- arrange(mutate(data.scores,
                         site = factor(site, levels = order_loc)))

data.scores_diat <- arrange(mutate(data.scores_diat,
                         site = factor(site, levels = order_loc)))

data.scores_dino <- arrange(mutate(data.scores_dino,
                         site = factor(site, levels = order_loc)))
```


```{r}
#Looking at species scores to add to the nmds plot

#All species
vf <- envfit(nmds, transform, perm = 999)

#Diatoms
vf_diat <- envfit(nmds_diat, transform_diat, perm = 999)

#Dinoflagellates
vf_dino <- envfit(nmds_dino, transform_dino, perm = 999)

#Pulling out r2 scores
#All species
r2 <- vf$vectors$r

#Diatoms
r2_diat <- vf_diat$vectors$r

#Diatoms
r2_dino <- vf_dino$vectors$r

#MAking dataframe out of r2 values
#All species
r2_df <- as.data.frame(r2)

#Diatoms
r2_df_diat <- as.data.frame(r2_diat)

#Dino
r2_df_dino <- as.data.frame(r2_dino)

#Pulling and binding vectors and r2 scores
#All species
spp.scrs <- as.data.frame(scores(vf, display = "vectors"))
spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))
spp.scrs2 <- cbind(spp.scrs, r2_df)

#diatoms
spp.scrs_diat <- as.data.frame(scores(vf_diat, display = "vectors"))
spp.scrs_diat <- cbind(spp.scrs_diat, Species = rownames(spp.scrs_diat))
spp.scrs2_diat <- cbind(spp.scrs_diat, r2_df_diat)

#dinoflagellates
spp.scrs_dino <- as.data.frame(scores(vf_dino, display = "vectors"))
spp.scrs_dino <- cbind(spp.scrs_dino, Species = rownames(spp.scrs_dino))
spp.scrs2_dino <- cbind(spp.scrs_dino, r2_df_dino)
```


```{r}
#Pulling species with only r2 > 0.3 scores
#All species
spp.scrs2 <- spp.scrs2 %>%
  filter(r2 >= 0.30)

#Diatoms
spp.scrs2_diat <- spp.scrs2_diat %>%
  filter(r2_diat >= 0.30)

#Dinoflagellates
spp.scrs2_dino <- spp.scrs2_dino %>%
  filter(r2_dino >= 0.30)
```


```{r}
#Making shorter abbreviated species names for plotting

rownames(spp.scrs2) <- c("Hill.",
                         "Tel.",
                         "S.mar.",
                         "P.pou.",
                         "C.soc.",
                         "C.cin.") 

rownames(spp.scrs2_diat) <- c("C.clo.",
                              "P.n.s.",
                              "R.set.",
                              "Pen.",
                              "S.mar.",
                              "Bid.",
                              "L.dan.")

rownames(spp.scrs2_dino) <- c("Gymn.",
                              "Gyro.",
                              "Kato.",
                              "S.pre.",
                              "S.tro.")
                              
```

```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

f1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f3 <- ggplot(data = data.scores_diat, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_diat, aes(fill = as.factor(month), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2_diat,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2_diat, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2_diat)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f4 <- ggplot(data = data.scores_diat, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_diat, aes(fill = as.factor(year), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2_diat,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2_diat, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2_diat)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f5 <- ggplot(data = data.scores_dino, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_dino, aes(fill = as.factor(month), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2_dino,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2_dino, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2_dino)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.87, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f6 <- ggplot(data = data.scores_dino, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_dino, aes(fill = as.factor(year), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2_dino,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  ggrepel::geom_text_repel(data = spp.scrs2_dino, aes(x = NMDS1, y = NMDS2, 
                                           label = row.names(spp.scrs2_dino)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.87, 0.7),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Year", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))


fig <- f1 + f3 + f5 + f2 + f4 + f6 

ggsave(here("figures_nmds", "wtf.png"), fig,
       width = 16, height = 10, dpi = 300)
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for all species
inv_site = multipatt(transform, loc, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_site)
```

```{r}
inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)

inv_site_sp <- inv_site_sp %>% 
  filter(s.C == 1 | s.F == 1 | s.S == 1) %>% 
  filter(p.value < 0.01) %>% 
  # filter(!rn == "Skeletonema marinoi") %>% 
  arrange(rn)

inv_site_list <- inv_site_sp$rn

inv_site_list
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for diatoms
inv_site_diat = multipatt(transform_diat, loc, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_site_diat)
```

```{r}
inv_site_sp_diat <- data.table::as.data.table(inv_site_diat$sign, keep.rownames = TRUE)

inv_site_sp_diat <- inv_site_sp_diat %>% 
  filter(s.C == 1 | s.F == 1 | s.S == 1) %>% 
  filter(p.value < 0.01) %>% 
  # filter(!rn == "Skeletonema marinoi") %>% 
  arrange(rn)

inv_site_list_diat <- inv_site_sp_diat$rn

inv_site_list_diat
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for all species
# inv_year = multipatt(transform, year, func = "r.g",
#                        control = how(nperm = 9999))

#Looking at results of analysis
# summary(inv_year)
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for all species
# inv_month = multipatt(transform_diat, month, func = "r.g",
#                        control = how(nperm = 9999))
# 
# #Looking at results of analysis
# summary(inv_month)
```

```{r}
# inv_month_sp <- data.table::as.data.table(inv_month$sign, keep.rownames = TRUE)
# 
# inv_month_sp <- inv_month_sp %>% 
#   filter(s.5 == 1 | s.6 == 1 | s.7 == 1 | s.8 == 1 | s.9 == 1 | s.10 == 1) %>% 
#   filter(p.value < 0.05) %>% 
#   # filter(!rn == "Skeletonema marinoi") %>% 
#   arrange(rn)
# 
# inv_month_list <- inv_month_sp$rn
# 
# inv_month_list
```

```{r}
# inv_year_sp <- data.table::as.data.table(inv_year$sign, keep.rownames = TRUE)
# 
# inv_year_sp <- inv_year_sp %>% 
#   filter(s.2018 == 1 | s.2019 == 1 | s.2020 == 1) %>% 
#   filter(p.value < 0.05) %>% 
#   # filter(!rn == "Skeletonema marinoi") %>% 
#   arrange(rn)
# 
# inv_year_list <- inv_year_sp$rn
# 
# inv_year_list
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by month - all species
# inv_month = multipatt(transform, month, func = "r.g",
#                        control = how(nperm = 9999))
# 
# #Indicators by month - diatoms
# inv_month_diat = multipatt(transform_diat, month, func = "r.g",
#                        control = how(nperm = 9999))
# 
# #Indicators by month - dinos
# inv_month_dino = multipatt(transform_dino, month, func = "r.g",
#                        control = how(nperm = 9999))
# 
# #Looking at results of analysis
# summary(inv_month)
# summary(inv_month_diat)
# summary(inv_month_dino)
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by year - all species
inv_year = multipatt(transform, year, func = "r.g",
                       control = how(nperm = 9999))
# 
# #Indicators by year - diatoms
inv_year_diat = multipatt(transform_diat, year, func = "r.g",
                       control = how(nperm = 9999))
# 
# #Indicators by year - dinos
inv_year_dino = multipatt(transform_dino, year, func = "r.g",
                       control = how(nperm = 9999))
# 
# #Looking at results of analysis
summary(inv_year)
summary(inv_year_diat)
summary(inv_year_dino)
```

```{r}
inv_year_sp <- data.table::as.data.table(inv_year$sign, keep.rownames = TRUE)

inv_year_sp <- inv_year_sp %>% 
  filter(s.2018 == 1 | s.2019 == 1 | s.2020 == 1) %>% 
  filter(p.value < 0.01) %>% 
  # filter(!rn == "Skeletonema marinoi") %>% 
  arrange(rn)

inv_year_list <- inv_year_sp$rn

inv_year_list
```

```{r}
inv_year_sp_dino <- data.table::as.data.table(inv_year_dino$sign, keep.rownames = TRUE)

inv_year_sp_dino <- inv_year_sp_dino %>%
  filter(s.2018 == 1 | s.2019 == 1 | s.2020 == 1) %>%
  filter(p.value < 0.01) %>%
  # filter(!rn == "Skeletonema marinoi") %>%
  arrange(rn)

inv_year_list_dino <- inv_year_sp_dino$rn

inv_year_list_dino
```


```{r}
#should look at relative abundance plot of this, since using.
micro <- micro %>% 
  group_by(date, location) %>% 
  mutate(sum_total = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(perc_total = species_sum/sum_total)

micro <- arrange(mutate(micro,
                         location = factor(location, levels = order_loc)))
```

```{r}
# a <- c("Biddulphiales" = "green", #
#        "Ceratium lineatum" = "purple",
#        "Chaetoceros debilis" = "purple", #
#        "Chaetoceros decipiens" = "blue", #Either S of S/C depending on analysis
#        "Chaetoceros didymus" = "blue",
#        "Chaetoceros laciniosus" = "blue", #
#        "Chaetoceros radicans" = "blue", #
#        "Chaetoceros seiracanthus" = "purple", #
#        "Chaetoceros socialis" = "blue",
#        "Dactyliosolen fragilissimus" = "blue", #
#        "Dactyliosolen phuketensis" = "blue", #
#        "Detonula pumila" = "blue", #
#        "Dictyocha" = "blue",
#        "Dinophysis acuta" = "red",
#        "Eucampia zodiacus" = "blue", #
#        "Guinardia delicatula" = "purple", #Either S of S/C depending on analysis
#        "Leptocylindrus danicus" = "purple", #
#        "Navicula" = "blue", #
#        "Protoperidinium" = "blue",
#        "Protoperidinium steinii" = "blue",
#        "Pseudo-nitzschia seriata" = "blue", #
#        "Pterosperma" = "purple",
#        "Rhizosolenia setigera" = "blue", #
#        "Skeletonema marinoi" = "red",
#        "Teleaulax acuta" = "red",
#        "Thalassiosira" = "blue",
#        "Thalassiosira rotula" = "blue")
       
# test <- micro %>%   
#   filter(scientificName %in% inv_site_list | 
#          scientificName %in% inv_site_list_diat) %>% 
#   distinct(scientificName)

#Making a heatmap of the indicator species
all_2 <- micro %>%   
  filter(scientificName %in% inv_site_list | 
         scientificName %in% inv_site_list_diat |
         scientificName %in% inv_year_list |
         scientificName %in% inv_year_list_dino) %>% 
  ggplot(aes(x = as.factor(date), y = scientificName, fill = sqrt(perc_total))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(group ~ location , scales = "free", space = "free") +
  scale_fill_distiller(palette = "Spectral", name = expression(sqrt("%"))) +
  scale_y_discrete(labels = c("Biddulphiales" = expression(Bid.^C), #
                              "Ceratium lineatum" = expression(C.lin.^CS), #
                              "Chaetoceros convolutus" = "C.con.",
                              "Chaetoceros debilis" = expression(C.deb.^CS), #
                              "Chaetoceros decipiens" = expression(C.dec.^S), #
                              "Chaetoceros laciniosus" = expression(C.lac.^S), #
                              "Chaetoceros radicans" = expression(C.rad.^S), #
                              "Chaetoceros seiracanthus" = "C.sei.", #
                              "Chaetoceros similis" = "C.sim.",
                              "Chaetoceros socialis" = "C.soc.", #
                              "Chaetoceros didymus" = "C.did.", #
                              "Corethron criophilum" = expression(C.cri.^18),
                              "Corythodinium" = expression(Cory.^20),
                              "Dactyliosolen phuketensis" = expression(F.phu.^S), #
                              "Dactyliosolen fragilissimus" = expression(F.fra.^S), #
                              "Detonula pumila" = expression(D.pum.^S), #
                              "Dinobryon" = expression(Dino.^"18+19"),
                              "Eucampia zodiacus" = "E.zod.", #
                              "Leptocylindrus danicus" = expression(L.dan.^S), #
                              "Navicula" = "Nav.", #
                              "Guinardia delicatula" = expression(G.del.^S), #
                              "Gymnodinium" = "Gymn",
                              "Katodinium" = expression(Kato.^20),
                              "Navicula" = expression(Nav.^19),
                              "Scrippsiella precaria" = "S.prec",
                              "Protoperidinium" = expression(Prot.^"S+18"), #
                              "Prorocentrum" = expression(Pror.^19), #
                              "Protoperidinium steinii" = "Pro.s", #
                              "Prorocentrum micans" = "P.mic.",
                              "Pseudo-nitzschia seriata" = expression(P.n.s^"S+19"), #
                              "Pseudo-nitzschia" = "P.n.",
                              "Pterosperma" = "Pter.", #
                              "Dinophysis acuta" = "D.acu.", #
                              "Skeletonema marinoi" = expression(S.mar.^F), #
                              "Thalassiosira rotula" = expression(T.rot.^S), #
                              "Thalassiosira" = "T.", #
                              "Rhizosolenia setigera" = expression(R.s.^S), #
                              "Teleaulax acuta" = expression(T.acu.^"18+20"),
                              "Dictyocha" = "Dict.")) + #
  theme_bw() +
  theme(axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        # axis.text.y = element_text(color = c("darkgreen",
        #                                      "darkviolet",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "darkviolet",
        #                                      "darkviolet",
        #                                      "blue",
        #                                      "blue",
        #                                      "blue",
        #                                      "red",
        #                                      "blue",
        #                                      "blue",
        #                                      "purple",
        #                                      "purple"
        #                                      )),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        legend.key.height = unit(2.5, "cm"))

ggsave(here("figures_nmds", "indicator_all_rel.png"), all_2,
        width = 16, height = 8, dpi = 300)

```




```{r}
# micro_sm <- micro %>%   
#   filter(scientificName == "Skeletonema marinoi small" | 
#            scientificName == "Skeletonema marinoi large") %>%
#   group_by(date, month_surv, location) %>% 
#   mutate(perc_total = sum(perc_total)) %>% 
#   ungroup() %>% 
#   distinct(date, perc_total, .keep_all = TRUE) %>% 
#   mutate(scientificName = "S.m.T",
#          group = "A")
# 
# micro_comb <- rbind(micro, micro_sm)
# 
# 
# all_2 <- micro_comb %>%   
#   filter(scientificName %in% inv_site_list |
#            scientificName %in% inv_site_list_diat |
#            scientificName == "Skeletonema marinoi small" | 
#            scientificName == "S.m.T") %>% 
#   ggplot(aes(x = as.factor(date), y = scientificName, fill = sqrt(perc_total))) +
#   geom_tile(color = "black", size = 1) +
#   facet_grid(group ~ location , scales = "free", space = "free") +
#   scale_fill_distiller(palette = "Spectral", name = expression(sqrt("%"))) +
#   scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
#                               "Ceratium lineatum" = "C.lin.", 
#                               "Chaetoceros convolutus" = "C.con.",
#                               "Chaetoceros debilis" = "C.deb.",
#                               "Chaetoceros decipiens" = "C.dec.",
#                               "Chaetoceros laciniosus" = "C.lac.",
#                               "Chaetoceros radicans" = "C.rad.",
#                               "Chaetoceros seiracanthus" = "C.sei.",
#                               "Chaetoceros similis" = "C.sim.",
#                               "Chaetoceros socialis" = "C.soc.",
#                               "Dactyliosolen phuketensis" = "D.phu.",
#                               "Dactyliosolen fragilissimus" = "D.fra.",
#                               "Detonula pumila" = "D.pum.",
#                               "Eucampia zodiacus" = "E.zod.",
#                               "Leptocylindrus danicus" = "L.dan.",
#                               "Navicula" = "Nav.",
#                               "Guinardia delicatula" = "G.del.",
#                               "Gymnodinium" = "Gymn",
#                               "Scrippsiella precaria" = "S.prec",
#                               "Protoperidinium" = "Pro",
#                               "Protoperidinium steinii" = "Pro.s",
#                               "Prorocentrum micans" = "P.mic.",
#                               "Pseudo-nitzschia seriata" = "P.n.s.",
#                               "Pseudo-nitzschia" = "P.n.",
#                               "Pterosperma" = "Pter.",
#                               "Dinophysis acuta" = "D.acu.",
#                               "Skeletonema marinoi large" = "S.mar.L",
#                               "Skeletonema marinoi small" = "S.mar.S",
#                               "Thalassiosira rotula" = "T.rot.",
#                               "Teleaulax acuta" = "T.acu.")) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         strip.background = element_blank(),
#         strip.text.y = element_blank(),
#         # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         axis.text.x = element_blank(),
#         axis.title.y = element_blank(),
#         text = element_text(size = 28),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         # legend.position = c(0.03, 0.30),
#         legend.direction = "vertical",
#         axis.line = element_line(colour = "black"),
#         legend.background = element_blank(),
#         legend.key.height = unit(2.5, "cm"))
# 
# ggsave(here("figures_good", "indicator_all_rel_2022-10-27_sm_sep_2.png"), all_2,
#         width = 16, height = 10, dpi = 300)
```




```{r}
#should look at relative abundance plot of this, since using.
# micro_diat <- micro_diat %>% 
#   group_by(date, location) %>% 
#   mutate(sum_total = sum(species_sum)) %>% 
#   ungroup() %>% 
#   mutate(perc_total = species_sum/sum_total)
# 
# micro_diat <- arrange(mutate(micro_diat,
#                          location = factor(location, levels = order_loc)))
```

```{r}

#Making a heatmap of the indicator species
# diat <- micro_diat %>%   
#   filter(scientificName %in% inv_site_list_diat) %>%
#   ggplot(aes(x = as.factor(date), y = scientificName, fill = sqrt(perc_total))) +
#   geom_tile(color = "black", size = 1) +
#   facet_grid(. ~ location , scales = "free_x", space = "free") +
#   # scale_fill_gradient(name = expression(sqrt("%")),
#   #                     low = "#012345",
#   #                     high = "#FFFFFF") +
#   scale_fill_distiller(palette = "Spectral", name = expression(sqrt("%"))) +
#   scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
#                               "Chaetoceros convolutus" = "C.con.",
#                               "Chaetoceros debilis" = "C.deb.",
#                               "Chaetoceros decipiens" = "C.dec.",
#                               "Chaetoceros didymus" = "C.did.",
#                               "Chaetoceros laciniosus" = "C.lac.",
#                               "Chaetoceros radicans" = "C.rad.",
#                               "Chaetoceros seiracanthus" = "C.sei.",
#                               "Chaetoceros socialis" = "C.soc.",
#                               "Dactyliosolen fragilissimus" = "D.fra.",
#                               "Dactyliosolen phuketensis" = "D.phu.",
#                               "Detonula pumila" = "D.pum.",
#                               "Eucampia zodiacus" = "E.zod.",
#                               "Guinardia delicatula" = "G.del.",
#                               "Leptocylindrus danicus" = "L.dan.",
#                               "Navicula" = "Nav.",
#                               "Pseudo-nitzschia" = "P.n.",
#                               "Pseudo-nitzschia seriata" = "P.n.s.",
#                               "Skeletonema marinoi large" = "S.mar.L",
#                               "Thalassiosira rotula" = "T.rot.")) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         strip.background = element_blank(),
#         strip.text.y = element_blank(),
#         # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         axis.text.x = element_blank(),
#         axis.title.y = element_blank(),
#         text = element_text(size = 25),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         # legend.position = c(0.03, 0.30),
#         legend.direction = "vertical",
#         axis.line = element_line(colour = "black"),
#         legend.background = element_blank(),
#         legend.key.height = unit(2.5, "cm"))
# 
# #Could add color bars for year and month.
# # micro_diat %>%  
# #   mutate(year = lubridate::year(date)) %>% 
# #   ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(year))) +
# #   geom_tile(color = "black", size = 1) +
# #   facet_grid(. ~ location , scales = "free_x", space = "free")
# # 
# # micro_diat %>%  
# #   ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(month))) +
# #   geom_tile(color = "black", size = 1) +
# #   facet_grid(. ~ location , scales = "free_x", space = "free")
# 
# 
# ggsave(here("figures_good", "indicator_diatoms_rel_2022-10-27_sm_sep.png"),
#         width = 16, height = 8, dpi = 300)

```








```{r}
#should look at relative abundance plot of this, since using.
# micro_dino <- micro_dino %>% 
#   group_by(date, location) %>% 
#   mutate(sum_total = sum(species_sum)) %>% 
#   ungroup() %>% 
#   mutate(perc_total = species_sum/sum_total)
# 
# micro_dino <- arrange(mutate(micro_dino,
#                          location = factor(location, levels = order_loc)))
```

```{r}

#Making a heatmap of the indicator species
# dino <- micro_dino %>%   
#   mutate(year = lubridate::year(date)) %>% 
#   filter(scientificName %in% inv_site_list_dino) %>%
#   ggplot(aes(x = as.factor(date), y = scientificName, fill = sqrt(perc_total))) +
#   geom_tile(color = "black", size = 1) +
#   facet_grid(. ~ location , scales = "free_x", space = "free") +
#   # scale_fill_gradient(name = expression(sqrt("%")),
#   #                     low = "#012345",
#   #                     high = "#FFFFFF") +
#   scale_fill_distiller(palette = "Spectral") +
#   scale_y_discrete(labels = c("Scrippsiella trochoidea" = "S.t.",
#                               "Protoperidinium steinii" = "Prot.s.",
#                               "Protoperidinium" = "Prot.c",
#                               "Prorocentrum" = "Proro.",
#                               "Katodinium" = "Kat.",
#                               "Gyrodinium" = "Gyro.",
#                               "Corythodinium" = "Cor.",
#                               "Ceratium horridum" = "C.h.")) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         strip.background = element_blank(),
#         strip.text.y = element_blank(),
#         # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         axis.text.x = element_blank(),
#         axis.title.y = element_blank(),
#         text = element_text(size = 25),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         strip.text.x = element_blank(),
#         legend.position = "none",
#         # legend.direction = "none",
#         axis.line = element_line(colour = "black"),
#         legend.background = element_blank())
# 
# #Could add color bars for year and month.
# # micro_diat %>%  
# #   mutate(year = lubridate::year(date)) %>% 
# #   ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(year))) +
# #   geom_tile(color = "black", size = 1) +
# #   facet_grid(. ~ location , scales = "free_x", space = "free")
# # 
# # micro_diat %>%  
# #   ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(month))) +
# #   geom_tile(color = "black", size = 1) +
# #   facet_grid(. ~ location , scales = "free_x", space = "free")
# 
# 
# ggsave(here("figures_good", "indicator_dino_rel_2022-08-08.png"),
#         width = 16, height = 5, dpi = 300)

```

```{r}
#Could add color bars for year and month.
year <- micro %>%
  mutate(year = lubridate::year(date)) %>%
  ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(year))) +
  geom_tile() +
  facet_grid(. ~ location , scales = "free_x", space = "free") +
  scale_fill_brewer(palette = "Dark2") +
  theme(axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        # legend.direction = "none",
        # axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        axis.line = element_blank())
 
month <- micro %>%
  ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(month))) +
  geom_tile(color = "white", size = 0.3) +
  facet_grid(. ~ location , scales = "free_x", space = "free") +
  scale_fill_brewer(palette = "RdYlBu") +
  theme(axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        # legend.direction = "none",
        # axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        axis.line = element_blank())
```

```{r}
# panel <- diat / dino / plot_spacer() / year / plot_spacer() / month + 
#   plot_layout(heights = c(2, 0.8, -0.08, 0.1, -0.1, 0.1), guides = "collect")
# 
# ggsave(here("figures_good", "indicator_comb_test.png"), panel,
#         width = 16, height = 10, dpi = 300)
```

```{r}
# panel <- all / plot_spacer() / year / plot_spacer() / month + 
#   plot_layout(heights = c(2, -0.06, 0.1, -0.1, 0.07), guides = "collect")

panel <- all_2 / plot_spacer() / year / plot_spacer() / month + 
  plot_layout(heights = c(2, -0.07, 0.06, -0.09, 0.06), guides = "collect")

# ggsave(here("figures_good", "indicator_comb_all.png"), panel,
#         width = 16, height = 10, dpi = 300)

ggsave(here("figures_nmds", "indicator_comb_all_2_01.png"), panel,
        width = 16, height = 8, dpi = 300)
```






```{r}
labels <- c("Biddulphiales" = "bid",
            "Ceratium horridum" = "C.hor.",
            "Chaetoceros ceratosporus" = "C.cer.",
            "Corethron criophilum" = "C.cri.",
            "Corythodinium" = "Cory.",
            "Cylindrotheca closterium" = "C.clo.",
            "Dinobryon" = "Dino",
            "Gonyaulax" = "Gony.",
            "Katodinium" = "Kato",
            "Leptocylindrus danicus" = "L.dan.",
            "Navicula" = "Navi.",
            "Ochromonas" = "Ochr.",
            "Prorocentrum" = "Pror.",
            "Protoperidinium" = "Prot.",
            "Pseudo-nitzschia seriata" = "P.n.s.",
            "Scrippsiella trochoidea" = "S.tro.",
            "Skeletonema marinoi" = "S.mari.",
            "Teleaulax acuta" = "T.acu.",
            "Thalassiosira nordenskioeldii" = "T.nor.")

year <- micro %>% 
  filter(scientificName %in% inv_year_list |
           scientificName %in% inv_year_list_dino) %>% 
  ggplot(aes(x = as.factor(month), y = as.factor(location), fill = sqrt(perc_total))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(scientificName ~ year, scales = "free", space = "free",
             labeller = labeller(scientificName = labels)) +
  scale_fill_distiller(palette = "Spectral", name = expression(sqrt("%"))) +
  # scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
  #                             "Ceratium lineatum" = "C.lin.", 
  #                             "Chaetoceros convolutus" = "C.con.",
  #                             "Chaetoceros debilis" = "C.deb.",
  #                             "Chaetoceros decipiens" = "C.dec.",
  #                             "Chaetoceros laciniosus" = "C.lac.",
  #                             "Chaetoceros radicans" = "C.rad.",
  #                             "Chaetoceros seiracanthus" = "C.sei.",
  #                             "Chaetoceros similis" = "C.sim.",
  #                             "Chaetoceros socialis" = "C.soc.",
  #                             "Dactyliosolen phuketensis" = "D.phu.",
  #                             "Dactyliosolen fragilissimus" = "D.fra.",
  #                             "Detonula pumila" = "D.pum.",
  #                             "Eucampia zodiacus" = "E.zod.",
  #                             "Leptocylindrus danicus" = "L.dan.",
  #                             "Navicula" = "Nav.",
  #                             "Guinardia delicatula" = "G.del.",
  #                             "Gymnodinium" = "Gymn",
  #                             "Scrippsiella precaria" = "S.prec",
  #                             "Protoperidinium" = "Pro",
  #                             "Protoperidinium steinii" = "Pro.s",
  #                             "Prorocentrum micans" = "P.mic.",
  #                             "Pseudo-nitzschia seriata" = "P.n.s.",
  #                             "Pseudo-nitzschia" = "P.n.",
  #                             "Pterosperma" = "Pter.",
  #                             "Dinophysis acuta" = "D.acu.",
  #                             "Skeletonema marinoi large" = "S.mar.L",
  #                             "Skeletonema marinoi small" = "S.mar.S",
  #                             "Thalassiosira rotula" = "T.rot.",
  #                             "Teleaulax acuta" = "T.acu.")) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        strip.text.y.right = element_text(angle = 0),
        # strip.background = element_blank(),
        # strip.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 28),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        legend.key.height = unit(2.5, "cm"))

ggsave(here("figures_nmds", "test_01.png"),
        width = 12, height = 16, dpi = 300)
```

```{r}
labels <- c("Biddulphiales" = "bid",
            "Ceratium horridum" = "C.hor.",
            "Chaetoceros ceratosporus" = "C.cer.",
            "Corethron criophilum" = "C.cri.",
            "Corythodinium" = "Cory.",
            "Cylindrotheca closterium" = "C.clo.",
            "Dinobryon" = "Dino",
            "Gonyaulax" = "Gony.",
            "Katodinium" = "Kato",
            "Leptocylindrus danicus" = "L.dan.",
            "Navicula" = "Navi.",
            "Ochromonas" = "Ochr.",
            "Prorocentrum" = "Pror.",
            "Protoperidinium" = "Prot.",
            "Pseudo-nitzschia seriata" = "P.n.s.",
            "Scrippsiella trochoidea" = "S.tro.",
            "Skeletonema marinoi" = "S.mari.",
            "Teleaulax acuta" = "T.acu.",
            "Thalassiosira nordenskioeldii" = "T.nor.",
            "Biddulphiales" = "Bid.", #
            "Ceratium lineatum" = "C.lin.", #
                              "Chaetoceros convolutus" = "C.con.",
                              "Chaetoceros debilis" = "C.deb.", #
                              "Chaetoceros decipiens" = "C.dec.", #
                              "Chaetoceros laciniosus" = "C.lac.", #
                              "Chaetoceros radicans" = "C.rad.", #
                              "Chaetoceros seiracanthus" = "C.sei.", #
                              "Chaetoceros similis" = "C.sim.",
                              "Chaetoceros socialis" = "C.soc.", #
                              "Chaetoceros didymus" = "C.did.", #
                              "Dactyliosolen phuketensis" = "D.phu.", #
                              "Dactyliosolen fragilissimus" = "D.fra.", #
                              "Detonula pumila" = "D.pum.", #
                              "Eucampia zodiacus" = "E.zod.", #
                              "Leptocylindrus danicus" = "L.dan.", #
                              "Navicula" = "Nav.", #
                              "Guinardia delicatula" = "G.del.", #
                              "Gymnodinium" = "Gymn",
                              "Scrippsiella precaria" = "S.prec",
                              "Protoperidinium" = "Pro", #
                              "Protoperidinium steinii" = "Pro.s", #
                              "Prorocentrum micans" = "P.mic.",
                              "Pseudo-nitzschia seriata" = "P.n.s.", #
                              "Pseudo-nitzschia" = "P.n.",
                              "Pterosperma" = "Pter.", #
                              "Dinophysis acuta" = "D.acu.", #
                              "Skeletonema marinoi" = "S.mar.", #
                              "Thalassiosira rotula" = "T.rot.", #
                              "Thalassiosira" = "T.", #
                              "Rhizosolenia setigera" = "R.s.", #
                              "Teleaulax acuta" = "T.acu.",
                              "Dictyocha" = "Dict.")

micro %>% 
  filter(scientificName %in% inv_year_list |
           scientificName %in% inv_site_list) %>% 
  ggplot(aes(x = as.factor(month), y = as.factor(location), fill = sqrt(perc_total))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(scientificName ~ year, space = "free",
             labeller = labeller(scientificName = labels)) +
  scale_fill_distiller(palette = "Spectral", name = expression(sqrt("%"))) +
  # scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
  #                             "Ceratium lineatum" = "C.lin.", 
  #                             "Chaetoceros convolutus" = "C.con.",
  #                             "Chaetoceros debilis" = "C.deb.",
  #                             "Chaetoceros decipiens" = "C.dec.",
  #                             "Chaetoceros laciniosus" = "C.lac.",
  #                             "Chaetoceros radicans" = "C.rad.",
  #                             "Chaetoceros seiracanthus" = "C.sei.",
  #                             "Chaetoceros similis" = "C.sim.",
  #                             "Chaetoceros socialis" = "C.soc.",
  #                             "Dactyliosolen phuketensis" = "D.phu.",
  #                             "Dactyliosolen fragilissimus" = "D.fra.",
  #                             "Detonula pumila" = "D.pum.",
  #                             "Eucampia zodiacus" = "E.zod.",
  #                             "Leptocylindrus danicus" = "L.dan.",
  #                             "Navicula" = "Nav.",
  #                             "Guinardia delicatula" = "G.del.",
  #                             "Gymnodinium" = "Gymn",
  #                             "Scrippsiella precaria" = "S.prec",
  #                             "Protoperidinium" = "Pro",
  #                             "Protoperidinium steinii" = "Pro.s",
  #                             "Prorocentrum micans" = "P.mic.",
  #                             "Pseudo-nitzschia seriata" = "P.n.s.",
  #                             "Pseudo-nitzschia" = "P.n.",
  #                             "Pterosperma" = "Pter.",
  #                             "Dinophysis acuta" = "D.acu.",
  #                             "Skeletonema marinoi large" = "S.mar.L",
  #                             "Skeletonema marinoi small" = "S.mar.S",
  #                             "Thalassiosira rotula" = "T.rot.",
  #                             "Teleaulax acuta" = "T.acu.")) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        strip.text.y.right = element_text(angle = 0),
        # strip.background = element_blank(),
        # strip.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 28),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        legend.key.height = unit(2.5, "cm"))

ggsave(here("figures_nmds", "test_02.png"),
        width = 12, height = 16, dpi = 300)
```




```{r}
#Could add color bars for year and month.
site <- micro %>%
  mutate(year = lubridate::year(date)) %>%
  ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(location))) +
  geom_tile() +
  facet_grid(. ~ year , scales = "free_x", space = "free") +
  scale_fill_brewer(palette = "Set1") +
  theme(axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        # legend.direction = "none",
        # axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        axis.line = element_blank())
 
month_year <- micro %>%
  ggplot(aes(x = as.factor(date), y = 1, fill = as.factor(month))) +
  geom_tile(color = "white", size = 0.3) +
  facet_grid(. ~ year , scales = "free_x", space = "free") +
  scale_fill_brewer(palette = "RdYlBu") +
  theme(axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.y = element_blank(),
        # axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        # legend.direction = "none",
        # axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        axis.line = element_blank())
```

```{r}
# panel <- all / plot_spacer() / year / plot_spacer() / month + 
#   plot_layout(heights = c(2, -0.06, 0.1, -0.1, 0.07), guides = "collect")

panel2 <- year / plot_spacer() / site / plot_spacer() / month_year + 
  plot_layout(heights = c(2, -0.07, 0.06, -0.09, 0.06), guides = "collect")

# ggsave(here("figures_good", "indicator_comb_all.png"), panel,
#         width = 16, height = 10, dpi = 300)

ggsave(here("figures_nmds", "test_year_01.png"), panel2,
        width = 16, height = 8, dpi = 300)
```


























