---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(factoextra)
library(ggdendro)
library(ggforce)
library(concaveman)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(RColorBrewer)

#Need to go through and test these
```

```{r}
#Upload data
#Upload data from my master data standardization sheet
c <- read_csv(here("outputs", "chemtax_master_2022-03-16_het.csv")) 

clust_phy <- read_csv(here("outputs", "clusters_phys_chem.csv"))
```


```{r}

#Arranging according to site ID and date
c <- c %>% 
  arrange(site_id, date)

# c <- c %>% 
#   filter(!site_id == "QU39")

c <- c %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .after = date)

#Pulling out species counts for transform and input into clustering and NMDS
species <- c[, 6:ncol(c)]

transform_rel <- decostand(species, method = "total")
  
#Log10 transformation +1 (as per Mahara)
transform <- log10(species + 1)

# transform_rel <- sqrt(transform_rel)
```

```{r}
#Changing site_id to location 
c <- c %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))

#Create rownames for dendrogram
labs <- c %>%
  select(location, site_id, date) %>%  
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

labs_list <- labs$sample_name

transform_hc <- transform

rownames(transform_hc) <- labs_list

rownames(transform_rel) <- labs_list
```


```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- vegdist(transform_hc, method = "bray")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "average")

```

```{r}
#Looking at optimal number of clusters with the wss and silhouette methods
# fviz_nbclust(transform_hc, FUN = hcut, method = "wss")
# fviz_nbclust(transform_hc, FUN = hcut, method = "silhouette")

#Looking at optimal number of clusters with the gap statistic method
# gap_stat <- clusGap(transform_hc, FUN = hcut, nstart = 25, K.max = 10, B = 50)
# fviz_gap_stat(gap_stat)

#Turning off for now because takes time.
```

```{r}
#Setting number of clusters used - determined 5 based on silhouette plot and scrutiny of data with different clusters

k <- 5
clust <- cutree(cluster.average, k = k)

clust.df <- clust.df <- data.frame(label = rownames(transform_hc),
                                   cluster = factor(clust))

# write_csv(clust.df, here("outputs", "clusters_chem.csv"))
```

```{r}
# extract dendrogram segment data
dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
#Creating metadata sheet with 
metadata <- c %>% 
  select(location, site_id, date)

#Making unique labels by combining site and date into single string
metadata <- metadata %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

# get terminal dendrogram segments
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```

```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
# https://stackoverflow.com/questions/24140339/tree-cut-and-rectangles-around-clusters-for-a-horizontal-dendrogram-in-r
#I think I could actually add some cluster rectangles here.


#Plotting dendrogram - saving for incorporation later.
p_dend <- ggplot() +
 geom_segment(data = dendrogram_segments, 
 aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 geom_rect(data = rect, aes(xmin = X1-.3, xmax = X2+.3, ymin = 0, ymax = ymax), 
            color = "red", fill = NA) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(0.6, -0.3)) +
 coord_flip() + 
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_rev2", "hc_average_chemtax_pelago_test.png"), p_dend,
       width = 6, height = 12, dpi = 300)
```

```{r}
#Running nmds on entire dataset, without QU39 monthly averaged
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Decent stress score - 0.11

nmds_rel <-  metaMDS(transform_rel, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

# 0.11


#Checking stressplot for fit
stressplot(nmds)

stressplot(nmds_rel)

```

```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

# https://stackoverflow.com/questions/14711470/plotting-envfit-vectors-vegan-package-in-ggplot2
#If I want to try to get species vectors on plot try above link, near bottom
# spp.scrs <- as.data.frame(scores(nmds_sp, display = "vectors"))
# test <- as.data.frame(nmds_sp, display = "pvals")
# spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

data.scores = as.data.frame(scores(nmds))
data.scores$month_surv = c$month_surv
data.scores$site = c$site_id
data.scores$year = c$year

#Want to try to merge in clusters



# data.scores.rel = as.data.frame(scores(nmds_rel))
# data.scores.rel$month_surv = c$month_surv
# data.scores.rel$site = c$site_id

```

```{r}
# For clusters, need to merge on station/date code.
c <- c %>%
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

clust_df <- clust.df %>%
  rename(sample_name = label)

c <- c %>%
  left_join(clust_df) %>%
  relocate(cluster, .after = month_surv)

data.scores$clust = c$cluster
data.scores$loc = c$location
```

```{r}
#Would like to include the environmental clusters.

#Since the physical clusters are currently in the old naming convention, need to make a column with this so can do a join. I should be able to do this. 

clust_phy <- clust_phy %>% 
  select(sample_name, phys_clust)

c <- c %>% 
  left_join(clust_phy)

data.scores$phys_clust = c$phys_clust
```

```{r}
#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
data.scores <- arrange(mutate(data.scores,
                         loc = factor(loc, levels = order_loc)))
```

```{r}
#Combining station month and year plots with dendrogram - sort of cool, but now have to figure out why DFO2 different. This is where a heatmap plot comes in?

#Adding hulls came from here.
# https://www.r-bloggers.com/2021/07/ggforce-make-a-hull-plot-to-visualize-clusters-in-ggplot2/

nmds_month <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), 
                                     shape = loc),
             size = 7, stroke = 1.5) + 
  geom_mark_hull(data = data.scores, aes(color = clust, label = clust),
                 concavity = 2.8, label.fontsize = 30, expand = unit(4.1, "mm"),
                 radius = unit(4, "mm")) +
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.4, 0.7) +
  xlim(-1.1, 1.1) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.1, 0.31),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        legend.background = element_rect(fill = 'transparent', color = 'transparent'),
        legend.box.background = element_rect(fill='transparent', color = 'transparent'),  
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
   guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none")

nmds_year <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = loc),
             size = 7, stroke = 1.5) + 
  geom_mark_hull(data = data.scores, aes(color = clust, label = clust),
                 concavity = 2.8, label.fontsize = 30, expand = unit(4.1, "mm"),
                 radius = unit(4, "mm")) +
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-1.1, 1.1) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.08, 0.90),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(shape = "Station", fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

fig <- (nmds_month/nmds_year) | p_dend

# ggsave(here("figures_rev2", "nmds_dendro_chem_average_pelago_test.png"), fig,
#        width = 16, height = 12, dpi = 300)

```

```{r}
#Combining station month and physical clusters

#Adding hulls came from here.
# https://www.r-bloggers.com/2021/07/ggforce-make-a-hull-plot-to-visualize-clusters-in-ggplot2/

nmds_month <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), 
                                     shape = loc),
             size = 7, stroke = 1.5) + 
  geom_mark_hull(data = data.scores, aes(color = clust, label = clust),
                 concavity = 2.8, label.fontsize = 30, expand = unit(4.1, "mm"),
                 radius = unit(4, "mm")) +
  scale_fill_brewer(palette = "RdYlBu") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-1.1, 1.1) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.1, 0.31),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        legend.background = element_rect(fill = 'transparent', color = 'transparent'),
        legend.box.background = element_rect(fill='transparent', color = 'transparent'),  
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
   guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none")

nmds_pclust <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(phys_clust), shape = loc),
             size = 7, stroke = 1.5) + 
  geom_mark_hull(data = data.scores, aes(color = clust, label = clust),
                 concavity = 2.8, label.fontsize = 30, expand = unit(4.1, "mm"),
                 radius = unit(4, "mm")) +
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-1.1, 1.1) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.13, 0.85),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(shape = "Station", fill = "Env. Clust.") +
  guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

fig <- (nmds_month/nmds_year) | p_dend

# ggsave(here("figures_rev2", "nmds_dendro_chem_average_pelago_test.png"), fig,
#        width = 16, height = 12, dpi = 300)

```

```{r}
#Pivot chemtax sheet longer for plotting. 
c_long <- c %>% 
  pivot_longer(c(cyan, pela, hapt, pras2, pras3, cryp, dino, raph, diat),
                 names_to = "phyto_group", values_to = "TChla") %>% 
  group_by(sample_name, date, site_id, location, phyto_group) %>% 
  summarize(TChla_mean = mean(TChla)) %>% 
  ungroup() %>% 
  group_by(sample_name, date, site_id, location) %>% 
  mutate(TChla_sum = sum(TChla_mean)) %>% 
  ungroup()

clust_join <- clust.df %>% 
  select(sample_name = label, cluster)

#Plotting according to clusters.
c_long_clust <- c_long %>% 
  left_join(clust_join)

```

```{r}
#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "pela", "hapt", "pras2", "pras3", "cryp",
                "dino", "raph", "diat")

#Chemtax - Specify order of phyto groups for figures
c_long_clust <- arrange(mutate(c_long_clust,
                         phyto_group = factor(phyto_group,
                                              levels = order_chem)))

# hc_order <- dendrogram_ends$sample_name
# 
# c_long_clust$sample_name <- factor(c_long_clust$sample_name,
#                                  levels = unique(hc_order))


c_long_clust <- arrange(mutate(c_long_clust,
                         location = factor(location, levels = order_loc)))

# c_long_clust <- c_long_clust %>% 
#   arrange(date, site_id)

```

```{r}
#Set Color palette for plotting. Currently based on QU39 manuscript. Brewer has some good ones for R style.
palette_chem <- c("#ff8000", #1 - Diatoms (orange)
                  "#4d6600", #3 - Raphidophytes (dark green)
                  "#ff0000", #4 - Dinoflagellates (Red)
                  "#ffff00", #5 - Cryptophytes (yellow)
                  "#6EFF7C", #6 - prasinophytes-2 (lighter green)
                  "#00ff00", #6 - prasinophytes-3 (light green)
                  "#7d4dcc", #7 - Haptophytes (purple)
                  "#ff99c7", #2 - Pelagophytes (pink)
                  "#000000") #8 - Cyanobacteria (black)
```

```{r}
chem_clust_v <- c_long_clust %>%   
  ggplot(aes(x = TChla_mean, y = fct_reorder2(sample_name, desc(date), location),
             fill = fct_rev(phyto_group))) +
  geom_bar(stat = "identity", color = "black", size = 0.75) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 0.5, ymax = 10.5), fill = NA, 
  #           color = "black", size = 1) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 10.5, ymax = 29.5), fill = NA, 
  #           color = "black", size = 1) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 29.5, ymax = 31.5), fill = NA, 
  #           color = "black", size = 1) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 31.5, ymax = 35.5), fill = NA, 
  #           color = "black", size = 1) +
  scale_fill_manual(values = palette_chem) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 12.5)) +
  theme_bw() +
  facet_grid(cluster ~ ., scales = "free", space = "free") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.line = element_line(colour = "black")) +
  guides(fill = guide_legend(nrow = 1)) 

# ggsave(here("figures_rev2", "bar_chemtax_cluster_average_4_vert_pelag_test.png"), 
#        chem_clust_v, width = 16, height = 18, dpi = 300)
```




```{r}
dat_text <- data.frame(
  label = c("1", "2", "3", "4"),
  clust   = c(1, 2, 3, 4))
```

```{r}
chem_clust_h <- c_long_clust %>%   
  ggplot(aes(x = fct_reorder2(sample_name, desc(date), location), 
             y = TChla_mean, fill = fct_rev(phyto_group))) +
  geom_bar(stat = "identity", color = "black", size = 0.75) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 0.5, ymax = 10.5), fill = NA, 
  #           color = "black", size = 1) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 10.5, ymax = 29.5), fill = NA, 
  #           color = "black", size = 1) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 29.5, ymax = 31.5), fill = NA, 
  #           color = "black", size = 1) +
  # geom_rect(aes(xmin = 0, xmax = 12.3, ymin = 31.5, ymax = 35.5), fill = NA, 
  #           color = "black", size = 1) +
  scale_fill_manual(values = palette_chem) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 12.5)) +
  theme_bw() +
  facet_grid(. ~ cluster , scales = "free", space = "free") +
  geom_text(aes(x = -Inf, y = Inf, label = cluster, group = cluster),
            size = 10,
            hjust = -0.3,
            vjust = 1.4,
            inherit.aes = FALSE) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.line = element_line(colour = "black")) +
  guides(fill = guide_legend(nrow = 1)) 

ggsave(here("figures_rev2", "bar_chemtax_cluster_average_4_horiz_pelag_test.png"), 
       chem_clust_h, width = 16, height = 10, dpi = 300)

#Trying to figure out annotations
# https://stackoverflow.com/questions/56296428/adding-labels-to-each-individual-plot-with-facet-grid
# p + facet_grid(drv ~ cyl)+ annotate('text', label = LETTERS[1:12], x=min(mpg$displ), y=max(mpg$cty))

#this worked, but need to figure out how to add figure label.
# https://stackoverflow.com/questions/46499396/how-to-add-annotation-on-each-facet

```


```{r}
#Trying to bring together nmds and chemtax.

nmds_chem_panel <- (nmds_month + nmds_pclust) / chem_clust_h 

ggsave(here("figures_good", "nmds_chemtax_cluster.png"), nmds_chem_panel, 
       width = 16, height = 15, dpi = 300)

```

```{r}
#Looking at differences in chemtax clusters for each phytoplankton group - used in writing results of this section.

cluster_stats <- c_long_clust %>% 
  mutate(perc = TChla_mean/TChla_sum) %>% 
  group_by(cluster, phyto_group) %>% 
  summarize(min_conc = min(TChla_mean),
            max_conc = max(TChla_mean),
            min_perc = min(perc),
            max_perc = max(perc)) %>% 
  ungroup() 

station_stats <- c_long_clust %>% 
  mutate(perc = TChla_mean/TChla_sum) %>% 
  group_by(site_id, phyto_group) %>% 
  summarize(min_conc = min(TChla_mean),
            max_conc = max(TChla_mean),
            min_perc = min(perc),
            max_perc = max(perc)) %>% 
  ungroup() 

hapt <- c_long_clust %>% 
  filter(phyto_group == "hapt") %>% 
  mutate(perc = TChla_mean/TChla_sum)

pela <- c_long_clust %>% 
  filter(phyto_group == "pela") %>% 
  mutate(perc = TChla_mean/TChla_sum)
```




```{r}
#separating treatments for following tests
site_id <- c$site_id
month <- c$month
year <- c$year

#Need to do one for cluster.

```

```{r}
#For clusters, need to merge on station/date code. 
c <- c %>%
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

clust_df <- clust.df %>% 
  rename(sample_name = label)

c <- c %>% 
  left_join(clust_df) %>% 
  relocate(cluster, .after = month_surv)

cluster <- c$cluster


```


```{r}
#ANOSIM test to see if groupings statistically significant
ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
ano_site

ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
ano_month

ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
ano_year

ano_cluster = anosim(transform, cluster, distance = "bray", permutations = 9999)
ano_cluster


#Site and region are significant (p = 0.0001), with region having the highest R (0.62 vs 0.27) 

```

```{r}
#Indicator species analysis
```


```{r}
#by site
inv_site = multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_site)
```


```{r}
#by month
inv_month = multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_month)
```


```{r}
#by year
inv_year = multipatt(transform, year, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_year)
```


```{r}
#by year
inv_clust = multipatt(transform, cluster, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_clust)
```























