---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)

#Need to go through and test these

```

```{r}
#Upload data

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

clust_phy <- read_csv(here("outputs", "clusters_phys.csv"))

clust_chem <- read_csv(here("outputs", "chemtax_clusters.csv"))
```

```{r}
test <- micro %>%
  filter(class == "Raphidophyceae")
# 
# test2 <- micro %>% 
#   filter(phylum == "Haptophyta")
# 
# 
# 
# test3 <- micro %>% 
#   filter(class == "Dictyochophyceae" & site_id == "DFO2")
# 
# test4 <- micro %>% 
#   filter(site_id == "DFO2" & phylum == "Chlorophyta")
# 
# test5 <- micro %>% 
#   filter(site_id == "QCS01" & date == "2019-08-31")
# 
# dfo2_8_2019 <- micro %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   filter(year == 2019 & (month == 8 & site_id == "DFO2"))
# 
# dfo2_5_2019 <- micro %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   filter(year == 2019 & (month == 5 & site_id == "DFO2"))
# 
# kc10_2019 <- micro %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   filter(year == 2019 & (month == 9 & site_id == "KC10"))
# 
# qcs01_2019 <- micro %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   filter(site_id == "QCS01" & date == "2019-08-31")
# 
# q19_7_7 <- micro %>% 
#   filter(site_id == "QCS01" & date == "2019-07-07")
# 
# q19_8_6 <- micro %>% 
#   filter(site_id == "QCS01" & date == "2019-08-06")
# 
# q19_8_31 <- micro %>% 
#   filter(site_id == "QCS01" & date == "2019-08-31")
# 
# q19_10_5 <- micro %>% 
#   filter(site_id == "QCS01" & date == "2019-10-05")
# 
# c_horr <- micro %>% 
#   filter(scientificName == "Ceratium horridum")
# 
# c_crio <- micro %>% 
#   filter(scientificName == "Corethron criophilum")
# 
# p_pouc19 <- micro %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   filter(!site_id == "QU39" & year == 2019) %>% 
#   filter(scientificName == "Phaeocystis pouchetii")
# 
p_pouc <- micro %>%
  mutate(year = lubridate::year(date)) %>%
  filter(!site_id == "QU39") %>%
  filter(scientificName == "Phaeocystis pouchetii")
# 
# proro <- micro %>% 
#   filter(scientificName == "Prorocentrum")
# 
# proro_g <- micro %>% 
#   filter(scientificName == "Prorocentrum gracile")
# 
# cory <- micro %>% 
#   filter(scientificName == "Corythodinium")
# 
# thal <- micro %>% 
#   filter(!site_id == "QU39") %>% 
#   filter(scientificName == "Thalassiosira nordenskioeldii")
# 
# thal_p <- micro %>% 
#   filter(!site_id == "QU39") %>% 
#   filter(scientificName == "Thalassiosira pacifica")
# 
# cha_soc <- micro %>% 
#   filter(!site_id == "QU39") %>% 
#   filter(scientificName == "Chaetoceros socialis")
# 
# pn_s <- micro %>% 
#   filter(!site_id == "QU39") %>% 
#   filter(scientificName == "Pseudo-nitzschia seriata")

hapt_micro <- micro %>% 
  filter(phylum == "Haptophyta" & month > 6 & month < 11)

dict <- micro %>% 
  filter(site_id == "QCS01" & class == "Dictyochophyceae" & month > 6 & month < 11)
```




```{r}
#Selecting the species groups I will work with and limiting species that rarely observed.

#For now, I am keeping all of the heterotrophic species (just in this workbook)

# micro <- micro %>% 
#   filter(trophicStatus == "auto")

#Counting how many times each species is observed
micro <- micro %>%
  group_by(scientificName) %>%
  mutate(num_occurrence = n()) %>% 
  ungroup()

#removing species that have not been observed at least twice -  this is to minimize the influence of zeros. When I used this, it removes some species that are important, but not observed often. So trying with it turned off.
# micro <- micro %>%
#   filter(num_occurrence > 5)

#Removing cyanobacteria as thier counts are not reliable
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")

```

```{r}
#Looking at the distinct groups and species being utilized
distinct_species <- micro %>% 
  distinct(group, scientificName_accepted)

#I am removing metozoa and protozoa because I'm not sure they are easily quantifiable with these methods.
micro <- micro %>% 
  filter(!group == "Metazoa") %>% 
  filter(!group == "Protozoa")

distinct_species_2 <- micro %>% 
  distinct(group, scientificName_accepted)
```

```{r}
#Preparing data for cluster and nMDS analysis - need to be put into two separate matrices.

#Selecting columns
micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Adding year to wide format for plotting
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Arranging according to site ID and date
micro_piv <- micro_piv %>% 
  arrange(site_id, date)

#Removing QU39 to focus analysis on QU39
micro_piv <- micro_piv %>% 
  filter(!site_id == "QU39")

#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 6:ncol(micro_piv)]

#Creating relative abundance matrix - not currently looking at relative abundance
# transform_rel <- decostand(species, method = "total")
  
#Log10 transformation + 1 (as per Mahara)
transform <- log10(species + 1)

#Not currently working with relative abundance
# transform_rel <- sqrt(transform_rel)
```

```{r}
#Creating rownames for dendrogram creating

#Changing site_id to location 
micro_piv <- micro_piv %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

metadata <- micro_piv %>%
  select(location, site_id, date) %>%  
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

#Creating a list of rownames
# labs_list <- labs$sample_name
labs_list <- metadata$sample_name

#creating a hierarchical clustering matrix
transform_hc <- transform

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(transform_hc) <- labs_list
```

```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- vegdist(transform_hc, method = "bray")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "average")

```

```{r}
#Turning off as tests show 1-2 clusters that do not make sense with data


#Looking at number of clusters
# fviz_nbclust(transform, FUN = hcut, method = "wss")
# fviz_nbclust(transform, FUN = hcut, method = "silhouette")
# gap_stat <- clusGap(transform, FUN = hcut, nstart = 25, K.max = 10, B = 50)
# fviz_gap_stat(gap_stat)
```

```{r}
#This step sets clusters. Currently, I am not using.

# k <- 6
# clust <- cutree(cluster.average, k = k)
# 
# clust.df <- clust.df <- data.frame(label = rownames(transform_hc),
#                                    cluster = factor(clust))

# write_csv(clust.df, here("outputs", "clusters_micro_6.csv"))
```

```{r}
# extract dendrogram segment data for plotting

dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}

# get terminal dendrogram segments and join with names.
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

# dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
# rect <- aggregate(x~cluster, label(dendrogram_data), range)
# rect <- data.frame(rect$cluster, rect$x)
# ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
p_dend <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 # geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0, ymax = ymax),
 #            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(0.6, -0.3)) +
 coord_flip() + 
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       # axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Dist.") # flipped x and y coordinates for aesthetic reasons

#Turning off saving for now because not needed
# ggsave(here("figures_rev2", "hc_average_names.png"), p_dend,
#        width = 6, height = 12, dpi = 300)
```

```{r}
#Running nmds on Calvert data
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Show results including stress - currently 0.23.
nmds

#Checking stressplot for fit
stressplot(nmds)

```

```{r}
# For clusters, need to merge on station/date code. This is using the old naming convention.
micro_piv <- micro_piv %>%
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

micro_piv <- micro_piv %>%
  left_join(clust_phy) %>%
  relocate(cluster, .after = month_surv) %>% 
  rename(clust_phy = cluster)

```


```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

data.scores = as.data.frame(scores(nmds))
data.scores$month_surv = micro_piv$month_surv
data.scores$site = micro_piv$location
data.scores$year = micro_piv$year
data.scores$clust_phy = micro_piv$clust_phy

```

```{r}

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
data.scores <- arrange(mutate(data.scores,
                         site = factor(site, levels = order_loc)))
```






```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits. This is for the absolute data

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  coord_fixed() + ## need aspect ratio of 1!
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_text(size = 10, face = "bold", colour = "black"),
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_absolute_CALVERT.png"),
#        width = 6, height = 4.5, dpi = 300)
```

```{r}
#Plotting nMDS - by cluster

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(data = data.scores, aes(fill = as.factor(clust_phy), shape = site),
             size = 4) +
  scale_fill_brewer(palette = "Set1") +

  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  # xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_text(size = 10, face = "bold", colour = "black"),
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Cluster", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_physical_clusters.png"),
#        width = 6, height = 4.5, dpi = 300)
```

```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  annotate("text", x = -0.39, y = 0.35, label = "a)", size = 10) +
  annotate("text", x = 0.53, y = -0.30, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  annotate("text", x = -0.39, y = 0.35, label = "b)", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.86),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Year", shape = "Station") +
    guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

fig_nmds_horiz <- (p1 + p2)
```
```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  annotate("text", x = -0.39, y = 0.35, label = "a)", size = 10) +
  annotate("text", x = 0.53, y = -0.30, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(clust_phy), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  annotate("text", x = -0.39, y = 0.35, label = "b)", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.86),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Env. Clust", shape = "Station") +
    guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

fig_nmds_horiz_phy_clust <- (p1 + p2)
```

```{r}
#This is the vertical version of the month and year - not being used.

# p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
#              size = 7) + 
#   scale_fill_brewer(palette = "RdYlBu") +
#   # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
#   #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
#   # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
#   #           fontface = "bold", label = row.names(en_coord_cont)) + 
#   xlim(-0.4, 0.7) +
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         legend.key = element_blank(), 
#         legend.title = element_text(size = 20, face = "bold", colour = "black"), 
#         legend.text = element_text(size = 18, colour = "black"),
#         legend.position = c(0.90, 0.68),
#         legend.margin = margin(-0.3,0,0,0, unit = "cm"),
#         text = element_text(size = 32)) +
#   labs(fill = "Month", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
#   geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
#              size = 7) + 
#   scale_fill_brewer(palette = "Dark2") +
#   scale_shape_manual(values = c(21, 22, 23 ,24)) + 
#   xlim(-0.4, 0.7) +
#   theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
#         panel.background = element_blank(),
#         panel.border = element_rect(fill = NA, colour = "black"), 
#         axis.ticks = element_blank(),
#         axis.text = element_blank(),
#         axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         legend.key = element_blank(), 
#         legend.title = element_text(size = 20, face = "bold", colour = "black"), 
#         legend.text = element_text(size = 18, colour = "black"),
#         legend.position = c(0.90, 0.75),
#         legend.margin = margin(-0.3,0,0,0, unit = "cm"),
#         text = element_text(size = 32)) +
#   labs(fill = "Year", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# fig_nmds_vert <- (p1 / p2)
```

```{r}
#separating treatments for ANOSMIM and indicator
site_id <- micro_piv$site_id
month <- micro_piv$month_surv
year <- micro_piv$year
cluster <- micro_piv$clust_phy
```

```{r}
#Tried looking at indicator species of the chemtax clusters - didn't really show anything

# chem_test <- micro_piv %>% 
#     filter(!site_id == "QU39" & date > "2019-01-01") %>% 
#     mutate(location = case_when(site_id == "DFO2" ~ "F",
#                               site_id == "KC10" ~ "C",
#                               site_id == "QCS01" ~ "S",
#                               TRUE ~ as.character(site_id))) %>% 
#   unite(sample_name, c(location, date), sep = "", remove = FALSE) %>% 
#   relocate(location, .after = sample_name)
# 
# chem_test <- chem_test %>% 
#   left_join(clust_chem) %>% 
#   relocate(cluster, .after = clust_phy) %>% 
#   rename(chem_clust = cluster)
# 
# #Pulling out species counts for transform and input into clustering and NMDS
# chem_transform <- chem_test[, 10:ncol(chem_test)]
# 
# 
# #Log10 transformation + 1 (as per Mahara)
# chem_transform <- log10(chem_transform + 1)
# 
# 
# chem_clust <- chem_test$chem_clust
```

```{r}
# inv_chem = multipatt(chem_transform, chem_clust, func = "r.g",
#                        control = how(nperm = 9999))
# 
# #Looking at results of analysis
# summary(inv_chem)
```


```{r}
#ANOSIM test to see if groupings statistically significant - abundance

#Turning off for now because takes time to analyze.
# ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
# ano_site
# 
# ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
# ano_month
# 
# ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
# ano_year

#Not working because NA's in matrix
# ano_cluster = anosim(transform, cluster, distance = "bray", permutations = 9999)
# ano_cluster
```


```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station
inv_site = multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_site)
```



```{r}
#Pulling out list of species from indicator analysis on station - Not currently used to make plot, but cool that I can do this - makes further analysis much easier and replicatable.
inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)
```

```{r}
# by month - Noth currently using.
inv_month = multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_month)
```





```{r}
#by year
inv_year = multipatt(transform, year, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_year)
```


```{r}
#Looking at p-value correction for indicator species analysis.
# https://stats.stackexchange.com/questions/370724/indiscpecies-multipatt-and-overcoming-multi-comparrisons

inv_year_sp <- data.table::as.data.table(inv_year$sign, keep.rownames = TRUE)

```

```{r}
#by cluster - Not currently using - Again, not working because of NA's, but I performed this somewhere.
# inv_cluster = multipatt(transform, cluster, func = "r.g",
#                        control = how(nperm = 9999))
# 
# summary(inv_cluster)
```

```{r}
#This section is all different attempts at heat maps using different ordering and species.

#Take a look at this - https://stackoverflow.com/questions/42047896/joining-a-dendrogram-and-a-heatmap
```


```{r}
#Ordering the data in the order of the dendrogram from hierarchical clustering.

#Creating a list with the order of the samples in the dendrogram.
hc_order <- dendrogram_ends$sample_name

hc_order_exp <- as_tibble(hc_order)

# write_csv(hc_order_exp, here("outputs", "hc_order.csv"))

#Creating a separate workbook, in tidy format, with the combined site and date name. 
micro_heat <- micro %>% 
    filter(!site_id == "QU39") %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))

#Setting order of species for figure organized by group (i.e diatoms) and then species alphabetical within.
micro_heat$species_order <- factor(micro_heat$scientificName,
                                   (unique(micro_heat$scientificName
                                              [order(micro_heat$group,
                                                     micro_heat$scientificName)])))
```


```{r}
#Plotting indicator species where p < 0.01. 

#Setting the order to the same as the clustering using the specified list
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order))


h1_1 <- micro_heat %>%   
   filter(scientificName == "Chaetoceros decipiens" |
           scientificName == "Dactyliosolen phuketensis" |
           scientificName == "Detonula pumila" |
           scientificName == "Thalassiosira rotula" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Dactyliosolen fragilissimus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Skeletonema marinoi") %>%
  ggplot(aes(x = sample_name, y = species_order, fill = log10(count + 1))) +
  geom_tile(color = "black", size = 1) +
  # facet_grid(group ~ ., scales = "free_y", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  # geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, label = label), 
  #           hjust = -0.1, vjust = -1) +
  ylab(bquote(Log^10 ~ "(Abund. +1)")) +
  annotate("text", x = 1.5, y = 11, label = "e)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background=element_blank())

```

```{r}
#Second approach to try to lineup dendrogram with heatmap so that they can be combined in a panel.
p_dend2 <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 scale_color_manual(values = site_color) +

 scale_x_continuous(expand = c(0.01, 0.01)) + 
 annotate("text", x = 49.5, y = 0.43, label = "c)", size = 10) +
 ylab("Dist.") +
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       # axis.title.y = element_blank(),
       axis.text.x = element_blank(),
       text = element_text(size = 25),
       axis.line = element_line(colour = "black"),
       axis.text = element_text(colour = "black")) 

```

```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / h1_1 + plot_layout(heights = c(1, 3))

fig2 <- fig_nmds_horiz / fig

ggsave(here("figures_good", "nmds_year_heat.png"), fig2,
       width = 16, height = 13, dpi = 300)
```

```{r}
#Want to look at species richness and diversity index along HC clustering
micro_diat <- micro_heat %>% 
  filter(class == "Bacillariophyceae") %>% 
  group_by(sample_name) %>% 
  summarise(n_spec = n()) %>%
  ungroup() %>% 
  mutate(type = "D")

micro_nodiat <- micro_heat %>% 
  filter(!class == "Bacillariophyceae") %>% 
  group_by(sample_name) %>% 
  summarise(n_spec = n()) %>%
  ungroup() %>% 
  mutate(type = "F")

micro_rich <- rbind(micro_diat, micro_nodiat)

#Setting the order to the same as the clustering using the specified list
micro_rich$sample_name <- factor(micro_rich$sample_name, levels = unique(hc_order))

# micro_heat$date_fact <- as.factor(micro_heat$date)
# 
# micro_heat$test <- reorder(micro_heat$date_fact, micro_heat$sample_name)


bar <- micro_rich %>%   
  ggplot(aes(x = sample_name, y = n_spec, fill = type)) +
  geom_bar(stat = "identity", position = position_stack(reverse = T),
           color = "black") +
  # geom_hline(yintercept = 40) +
  scale_fill_manual(values = c("black", "grey"),
                    labels = c("Diat.", "Flag.")) +
  ylab("Rich.") +
  annotate("text", x = 49.5, y = 52, label = "d)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.direction = "horizontal",
        legend.position = c(0.075, 0.85),
        legend.background=element_blank())

#It looks like diatoms have the biggest difference - can I do a stacked bar?

```

```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / bar / h1_1 + plot_layout(heights = c(1, 1, 3))

fig2 <- fig_nmds_horiz / fig

ggsave(here("figures_good", "nmds_year_richness.png"), fig2,
       width = 16, height = 15, dpi = 300)

```

```{r}
#Merging the nMDS with the dendrogram and heatmap.
fig <- p_dend2 / bar / h1_1 + plot_layout(heights = c(1, 1, 3))

fig2 <- fig_nmds_horiz_phy_clust / fig

ggsave(here("figures_good", "nmds_clust_richness.png"), fig2,
       width = 16, height = 15, dpi = 300)

```

```{r}
#Look at shannon diversity

shannon <- diversity(species)

shannon <- as_tibble(shannon)

shannon$sample_name <- metadata$sample_name

#Setting the order to the same as the clustering using the specified list
shannon$sample_name <- factor(shannon$sample_name, levels = unique(hc_order))

sh <- shannon %>%   
  ggplot(aes(x = sample_name, y = value)) +
  geom_bar(stat = "identity", color = "black") +
  # geom_hline(yintercept = 40) +
  # scale_fill_manual(values = c("black", "grey"),
  #                   labels = c("Diat.", "Flag.")) +
  ylab("H") +
  # annotate("text", x = 49.5, y = 52, label = "d)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.direction = "horizontal",
        legend.position = c(0.075, 0.85),
        legend.background = element_blank())

# ggsave(here("figures_rev2", "shannon.png"),
#        width = 16, height = 6, dpi = 300)
```

```{r}
#Lets plot shannon diversity with richness.

fig <- p_dend2 / bar / sh + plot_layout(heights = c(1, 3, 3))

ggsave(here("figures_good", "dend_rich_div.png"), fig,
       width = 16, height = 10, dpi = 300)

#Richness is somewhat lower at DFO2, but not diversity
```
```{r}
#When are some of these indicator species present at DFO2
cdec <- micro %>% 
  filter(scientificName == "Chaetoceros decipiens" & site_id == "DFO2")

csei <- micro %>% 
  filter(scientificName == "Chaetoceros seiracanthus" & site_id == "DFO2")

dpum <- micro %>% 
  filter(scientificName == "Detonula pumila" & site_id == "DFO2")
```



```{r}
#Creating a list of species determined via indicator species analysis on stations.
ind_list <- c("Chaetoceros decipiens", "Dactyliosolen phuketensis", 
              "Detonula pumila", "Thalassiosira rotula" , "Ceratium lineatum", 
              "Dactyliosolen fragilissimus", "Chaetoceros debilis", 
              "Guinardia delicatula", "Rhizosolenia setigera", 
              "Chaetoceros seiracanthus", "Skeletonema marinoi")  
```

```{r}
#Sub-setting the species determined via indicator species analysis on station
micro_ind_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% ind_list)

#Determining number of times each indicator species observed at each station
micro_ind_stat <- micro_ind_stat %>% 
  group_by(site_id, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum),
            median_count = median(species_sum)) %>% 
  ungroup() 

test <- micro %>% 
  filter(!site_id == "QU39" & class  == "Bacillariophyceae") %>% 
  group_by(site_id, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum),
            median_count = median(species_sum)) %>%
  ungroup()

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_station <- micro %>% 
  filter(!site_id == "QU39") %>% 
  group_by(date, site_id) %>% 
  distinct(date, site_id) %>% 
  ungroup() %>% 
  group_by(site_id) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_ind_stat <- micro_ind_stat %>% 
  left_join(n_station) %>% 
  mutate(perc_obs = n_obs/n_samp,
         label = scales::percent(perc_obs %>% round(2)))
```
```{r}
#Creating a placeholder for Ceratium lineatum for DFO2 - makes plot save a space so the groupings stay consistent.
dfo_cl <- data.frame(site_id = "DFO2",
                     scientificName = "Ceratium lineatum",
                     n_obs = 0,
                     max_count = 0,
                     mean_count = 0,
                     median_count = 0,
                     n_samp = 0,
                     perc_obs = 0,
                     label = "0%")
                 
micro_ind_stat <- rbind(dfo_cl, micro_ind_stat)
```


```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = perc_obs, y = scientificName, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 1.03)) +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
  labs(x = "% Observed") +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = mean_count, y = scientificName, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(x = "Mean Abundance (cells l)") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 26000)) +
  scale_y_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.85, 0.1),
          legend.title = element_blank())

fig <- p1 + p2

ggsave(here("figures_rev2", "indicator_species_station_bar.png"), fig,
       width = 12, height = 7, dpi = 300)
```
```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = scientificName, y = n_obs, fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  geom_text(aes(label = label), position = position_dodge(width = 1), 
            hjust = -0.1, angle = 90, size = 5) +
  scale_fill_brewer(palette = "Set1") +
  scale_y_continuous(expand = c(0.01, 0), limits = c(0, 20)) +
  scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
  labs(y = "# Obs. + (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_ind_stat %>% 
  filter(!scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = scientificName, y = median_count,  fill = site_id)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1", labels = c("F", "C", "S")) +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(y = "Med. Abund (cells l)") +
  scale_y_continuous(expand = c(0.01, 0), limits = c(0, 18000)) +
  scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.p.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          # axis.title.y = element_blank(),
          # axis.text.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.95, 0.8),
          legend.title = element_blank())

fig <- p1 / p2

ggsave(here("figures_rev2", "indicator_species_station_bar3.png"), fig,
       width = 12, height = 7, dpi = 300)
```
```{r}
micro_ind_ts <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% ind_list)
```

```{r}
micro_ind_ts %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = species_sum, color = site_id)) +
  geom_line(size = 2) +
  geom_point(size = 3) +
  facet_grid(scientificName ~ year, scales = "free_y")

ggsave(here("figures_rev2", "indicator_species_ts.png"),
       width = 16, height = 20, dpi = 300)
```
```{r}
micro_diat_site2 <- micro_heat %>% 
  filter(class == "Bacillariophyceae") %>% 
  group_by(date, site_id) %>% 
  mutate(n_spec = n()) %>%
  ungroup() %>% 
  distinct(date, site_id, n_spec, .keep_all = TRUE) %>% 
  group_by(site_id, month_surv) %>% 
  summarise(mean = mean(n_spec),
            median = median(n_spec),
            sdev = sd(n_spec)) %>% 
  ungroup()

micro_diat_site2 %>% 
  ggplot(aes(x = as.factor(month_surv), y = mean, fill = site_id)) +
  geom_bar(stat = "identity", position = "dodge")

micro_diat_site2 %>% 
  ggplot(aes(x = as.factor(month_surv), y = median, fill = site_id)) +
  geom_bar(stat = "identity", position = "dodge")

```




```{r}
#Trying to do the same for annual indicator analysis. Creating a list of species determined via indicator species analysis on stations.

#subsetting species from annual indicator species analysis that had p values <= 0.01.
inv_year_sp <- inv_year_sp %>% 
  filter(p.value <= 0.01)

#Creating a list of the significant species from indicator species analysis.
inv_year_lis <- inv_year_sp$rn

```

```{r}
#Sub-setting the species determined via indicator species analysis on station
micro_year_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% inv_year_lis) %>% 
  mutate(year = lubridate::year(date))

#Determining number of times each indicator species observed at each station
micro_year_stat <- micro_year_stat %>% 
  group_by(year, scientificName) %>% 
  summarise(n_obs = n(),
            max_count = max(species_sum),
            mean_count = mean(species_sum)) %>% 
  ungroup() 

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_station_year <- micro %>% 
  filter(!site_id == "QU39") %>%
  mutate(year = lubridate::year(date)) %>% 
  group_by(date, year) %>% 
  distinct(date, year) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_year_stat <- micro_year_stat %>% 
  left_join(n_station_year) %>% 
  mutate(perc_obs = n_obs/n_samp)
```

```{r}
#Creating a plot showing number and percent observed for each indicator species by station. Then a second plot with the average abundance of each species for each station.

p1 <- micro_year_stat %>% 
  ggplot(aes(x = perc_obs, y = scientificName, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(expand = c(0.01, 0), limits = c(0, 1.03)) +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corythodinium" = "C.",
                              "Ceratium horridum" = "C.h.", #Y
                              "Corethron criophilum" = "C.c.", #Y
                              "Dinobryon" = "Db.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Phaeocystis pouchetii" = "P.p.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Teleaulax acuta" = "T.a.",
                              "Telonema subtilis" = "T.s.",
                              "Thalassiosira nordenskioeldii" = "T.n.")) +
  theme_bw() +
  labs(x = "% Observed") +
  theme(text = element_text(size = 25),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none")
  

p2 <- micro_year_stat %>% 
  ggplot(aes(x = mean_count, y = scientificName, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single"), 
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  # scale_x_continuous(expand = c(0, 1000)) +
  # ggbreak::scale_x_break(c(55000, 240000)) +
  labs(x = "Mean Abundance (cells l)") +
  # scale_x_continuous(expand = c(0.01, 0), limits = c(0, 26000)) +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corythodinium" = "C.",
                              "Ceratium horridum" = "C.h.", #Y
                              "Corethron criophilum" = "C.c.", #Y
                              "Dinobryon" = "Db.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Gyrodinium" = "Gy.",
                              "Katodinium" = "K.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Phaeocystis pouchetii" = "P.p.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Teleaulax acuta" = "T.a.",
                              "Telonema subtilis" = "T.s.",
                              "Thalassiosira nordenskioeldii" = "T.n.")) +
  theme_bw() +
    theme(text = element_text(size = 25),
          axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text = element_text(colour = "black"),
          legend.position = c(0.85, 0.1),
          legend.title = element_blank())

fig <- p1 + p2

ggsave(here("figures_rev2", "indicator_species_year_bar.png"), fig,
       width = 12, height = 7, dpi = 300)
```

```{r}
#Trying to look at distribution of indicator species for month.


inv_month_sp <- data.table::as.data.table(inv_month$sign, keep.rownames = TRUE)



#subsetting species from annual indicator species analysis that had p values <= 0.01.
inv_month_sp <- inv_month_sp %>% 
  filter(p.value <= 0.01)

#Creating a list of the significant species from indicator species analysis.
inv_month_lis <- inv_month_sp$rn


#Sub-setting the species determined via indicator species analysis on station
micro_month_stat <- micro %>% 
  filter(!site_id == "QU39") %>% 
  filter(scientificName %in% inv_month_lis) %>% 
  mutate(year = lubridate::year(date))

#Determining number of times each indicator species observed at each station
micro_month_stat <- micro_month_stat %>% 
  group_by(month_surv, scientificName) %>% 
  summarise(n_obs = n(),
            min_count = min(species_sum),
            max_count = max(species_sum),
            mean_count = mean(species_sum)) %>% 
  ungroup() 

#Maybe Friday brain, but this is the best way I could find to count how many times each station was sampled - Want this so I can determine percentage of times each indicator species was observed by station
n_month_year <- micro %>% 
  group_by(date, month_surv) %>% 
  distinct(date, month_surv) %>% 
  ungroup() %>% 
  group_by(month_surv) %>% 
  summarise(n_samp = n()) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_month_stat <- micro_month_stat %>% 
  left_join(n_month_year) %>% 
  mutate(perc_obs = n_obs/n_samp)
```
```{r}
test <- micro %>% 
  filter(scientificName == "Chaetoceros radicans")
```

```{r}
#Looking at what species are most prevalent at each station
micro_dom_spec <- micro_heat %>% 
  group_by(site_id,scientificName) %>% 
  summarise(n_ob = n(),
            med = median(species_sum)) %>% 
  ungroup()

#Joining total number of times each station was sampled with stats on how many times each species was observed at each station.
micro_dom_spec <- micro_dom_spec %>% 
  left_join(n_station) %>% 
  mutate(perc_obs = n_ob/n_samp)

micro_dom_spec <- micro_dom_spec %>%
  group_by(site_id) %>%
    mutate(my_ranks = order(order(n_ob, decreasing=TRUE)))

micro_dom_spec <- micro_dom_spec %>%
  group_by(site_id) %>%
    mutate(rank_obs = order(order(n_ob, decreasing = TRUE)),
           rank_obs_abund = order(order(n_ob, med, decreasing = TRUE))) %>% 
  ungroup()
```


```{r}
micro_dom_diat <- micro_heat %>% 
  filter(class == "Bacillariophyceae") %>% 
  group_by(site_id,scientificName) %>% 
  summarise(n_ob = n(),
            med = median(species_sum)) %>% 
  ungroup()

micro_dom_diat <- micro_dom_diat %>% 
  left_join(n_station) %>% 
  mutate(perc_obs = n_ob/n_samp)

micro_dom_diat <- micro_dom_diat %>%
  group_by(site_id) %>%
    mutate(rank_obs = order(order(n_ob, decreasing = TRUE)),
           rank_obs_abund = order(order(n_ob, med, decreasing = TRUE))) %>% 
  ungroup()
```



```{r}
#What about selecting only species that ever exceed 50000k. Doing a median of these and then plotting. 
diat_gt100k <- micro %>% 
  filter(!site_id == "QU39" & class == "Bacillariophyceae" 
         & species_sum >= 100000) %>%
  distinct(scientificName)

test <- micro %>% 
  filter(scientificName == "Chaetoceros debilis")

diat_gt100k_list <- diat_gt100k$scientificName

diat_test2 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" 
         & class == "Bacillariophyceae" 
         & scientificName %in% diat_gt100k_list) %>%
  group_by(site_id, year, month_surv, scientificName) %>% 
  summarize(med_count = median(species_sum)) %>% 
  mutate(rank_med = order(order(med_count, decreasing = TRUE))) %>% 
  ungroup()

diat_test2 <- diat_test2 %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

diat_test2 <- arrange(mutate(diat_test2,
                         location = factor(location, levels = order_loc)))
```

```{r}
diat_test2 %>% 
  ggplot(aes(x = as.factor(location), y = med_count, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "fill", color = "black") + 
  facet_grid(year ~ month_surv) + 
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test.png"), 
       width = 12, height = 8, dpi = 300)
```

```{r}
diat_test2 %>% 
  ggplot(aes(x = as.factor(location), y = (med_count/100000),
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(year ~ month_surv, scales = "free_y") + 
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test_abund.png"), 
       width = 12, height = 8, dpi = 300)
```
```{r}
#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))

#Importing chemtax data separately. I just use this to calibrate a new chlorophyll dataset that fixes some data quality gaps.
chem <- read_csv(here("outputs", "chemtax_master_2021-11-04.csv")) 
```

```{r}
#This just ensures that there are no exact duplicates introduced through joining. There aren't here, but it must have occured in earlier versions and I am keeping it in-case I make changes in the future.
data <- data %>% 
  distinct(date, site_id, .keep_all = TRUE)

#Removing QU39 for this worksheet
data <- data %>% 
  filter(!site_id == "QU39")
```


```{r}
#For Chl, I want to use Chl for 2018 and HPLC for 2019 and 2020 as there is greater data availability. I need to merge the 2018 chl with the 2019-2020 HPLC, but first calibrate the 2018 chlorophyll so that is comparable to the HPLC in 2019 and 2020.

#Separate chlorophyll data from before 2018
chl_bulk <- data %>%
  select(date, site_id, bulk_chl) %>% 
  filter(date < "2019-01-01") %>% 
  rename(chl = bulk_chl)

#For the pre-2018 data, make comparable through using the relationship between HPLC and chlorophyll from 2019 and 2020 (determined these in a separate workbook)
chl_bulk_fix <- chl_bulk %>% 
  mutate(chl = (0.65*chl) + 0.59 )

#Make the chemtax data long format and then calculate TChla from HPLC via addition of chlorophyll from each chemtax group. Was just easier than uploading another sheet with just the HPLC Tchla concentrations
chem_tidy <- chem %>% 
  pivot_longer(c(cyan, hapto, green, cryp, dino, dict, raph, diat),
                 names_to = "phyto_group", values_to = "TChla") %>% 
  group_by(date, site_id, phyto_group) %>% 
  summarize(TChla_mean = mean(TChla)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(TChla_sum = sum(TChla_mean)) %>% 
  ungroup()

#Separating out the calculated TChla concentrations from above.
chl_hplc <- chem_tidy %>% 
  select(date, site_id, chl = TChla_sum) %>% 
  distinct(date, site_id, chl, .keep_all = TRUE)

#Merging the 2018 calibrated chlorophyll to the 2019 and 2020 TChla from HPLC.
chl_merge <- rbind(chl_bulk_fix, chl_hplc)

```
```{r}
micro_date <- micro %>% 
  select(date, site_id, month_surv) %>% 
  distinct(date, site_id, month_surv) %>% 
  mutate(year = lubridate::year(date))

diat_test2 <- diat_test2 %>% 
  left_join(micro_date)

diat_test2 <- diat_test2 %>% 
  left_join(chl_merge)
```
```{r}
coeff <- 12.5

diat_test2 %>% 
  ggplot() + 
  geom_bar(aes(x = as.factor(location), y = med_count, fill = scientificName),
           stat = "identity", position = "fill", color = "black") + 
  geom_point(aes(x = as.factor(location), y = chl/coeff), pch = 21,
             color = "Black", fill = "white", stroke = 1.5, size = 3) +
  scale_y_continuous(sec.axis = sec_axis(~ . *coeff, name = "TChla")) +
  facet_grid(year ~ month_surv) + 
  # geom_text(aes(label = year), x = Inf, y = Inf, hjust = 1.5, vjust = 1.5,
            # check_overlap = TRUE) +
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test_perc_tchla.png"), 
       width = 12, height = 8, dpi = 300)
```






```{r}
diat_test3 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" 
         & class == "Bacillariophyceae" 
         & scientificName %in% diat_gt100k_list) %>%
  group_by(site_id, month_surv, scientificName) %>% 
  summarize(med_count = median(species_sum)) %>% 
  mutate(rank_med = order(order(med_count, decreasing = TRUE))) %>% 
  ungroup()

diat_test3 <- diat_test3 %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

diat_test3 <- arrange(mutate(diat_test3,
                         location = factor(location, levels = order_loc)))
```

```{r}
diat_test3 %>% 
  ggplot(aes(x = as.factor(location), y = med_count, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "fill", color = "black") + 
  facet_grid(. ~ month_surv) + 
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
        guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test_month.png"), 
       width = 12, height = 4, dpi = 300)
```

```{r}
#Want to include chlorophyll.

```






```{r}
#fagellates 
flag_gt100k <- micro %>% 
  filter(!site_id == "QU39" & trophicStatus == "auto" & 
           !class == "Bacillariophyceae" & species_sum >= 100000) %>%
  distinct(scientificName)

flag_gt100k_list <- flag_gt100k$scientificName

flag_test <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" 
         & scientificName %in% flag_gt100k_list) %>%
  group_by(site_id, year, month_surv, scientificName) %>% 
  summarize(med_count = median(species_sum)) %>% 
  mutate(rank_med = order(order(med_count, decreasing = TRUE))) %>% 
  ungroup()

flag_test <- flag_test %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

flag_test <- arrange(mutate(flag_test,
                         location = factor(location, levels = order_loc)))

flag_order <- c("Olisthodiscus", "Hillea", "Teleaulax", "Pterosperma",
                "Pyramimonas orientalis", "Phaeocystis pouchetii")

flag_test <- arrange(mutate(flag_test,
                         scientificName = factor(scientificName,
                                                 levels = flag_order)))
```

```{r}
flag_test %>% 
  ggplot(aes(x = as.factor(location), y = med_count, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "fill", color = "black") + 
  facet_grid(year ~ month_surv) + 
  scale_fill_brewer(palette = "Set1",
                    labels = c("O.",
                               "Hill.",
                               "Tel.",
                               "Pt.",
                               "P.o.",
                               "P.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "flag_test.png"), 
       width = 12, height = 8, dpi = 300)
```
```{r}
#fagellates 
dino_1k <- micro %>% 
  filter(!site_id == "QU39" & trophicStatus == "auto" &
           class == "Dinophyceae" & species_sum >= 2000) %>%
  distinct(scientificName)

flag_gt100k_list <- flag_gt100k$scientificName

flag_test <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" 
         & scientificName %in% flag_gt100k_list) %>%
  group_by(site_id, year, month_surv, scientificName) %>% 
  summarize(med_count = median(species_sum)) %>% 
  mutate(rank_med = order(order(med_count, decreasing = TRUE))) %>% 
  ungroup()

flag_test <- flag_test %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

flag_test <- arrange(mutate(flag_test,
                         location = factor(location, levels = order_loc)))

flag_order <- c("Olisthodiscus", "Hillea", "Teleaulax", "Pterosperma",
                "Pyramimonas orientalis", "Phaeocystis pouchetii")

flag_test <- arrange(mutate(flag_test,
                         scientificName = factor(scientificName,
                                                 levels = flag_order)))
```

```{r}
graz <- micro %>% 
  filter(!site_id == "QU39" & trophicStatus == "hetero")
```

```{r}
micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" & genus == "Dinophysis") %>% 
  ggplot(aes(x = as.factor(site_id), y = species_sum, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(year ~ month_surv) + 
  # scale_fill_brewer(palette = "Set1",
  #                   labels = c("O.",
  #                              "Hill.",
  #                              "Tel.",
  #                              "Pt.",
  #                              "P.o.",
  #                              "P.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))
```

```{r}

cil_month <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" 
         & phylum == "Ciliophora") %>% 
  group_by(site_id, month_surv, scientificName) %>% 
  summarize(med_count = median(species_sum)) %>% 
  mutate(rank_med = order(order(med_count, decreasing = TRUE))) %>% 
  ungroup()

cil_month <- cil_month %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

cil_month <- arrange(mutate(cil_month,
                         location = factor(location, levels = order_loc)))

```
```{r}
cil_month %>% 
  ggplot(aes(x = as.factor(location), y = med_count, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(. ~ month_surv) + 
  scale_fill_brewer(palette = "Paired") +
                    # labels = c("Bi.",
                    #            "C.c.",
                    #            "C.t.",
                    #            "P.",
                    #            "P.n.",
                    #            "P.n.s.",
                    #            "R.s.",
                    #            "S.m.",
                    #            "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
        guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "cil_test_month.png"), 
       width = 12, height = 4, dpi = 300)
```
```{r}
micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" & scientificName == "Oligotrichea") %>% 
  ggplot(aes(x = as.factor(site_id), y = species_sum, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(year ~ month_surv) + 
  # scale_fill_brewer(palette = "Set1",
  #                   labels = c("O.",
  #                              "Hill.",
  #                              "Tel.",
  #                              "Pt.",
  #                              "P.o.",
  #                              "P.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))
```

```{r}
#It really seems like these guys are at their highest concentrations when diatoms are at thier lowest.

#correlation?

#Feel like I am spinning off now, but made huge progress. Wouldn't mind at looking at correlation of oligotrics and diatom abundance.

#should also do the same for the dinoflagellates - but selecting the right ones is key.

diat_total <- micro %>% 
  filter(!site_id == "QU39" & class == "Bacillariophyceae") %>% 
  group_by(date, site_id) %>% 
  summarize(diat_sum = sum(species_sum)) %>% 
  ungroup()

cil <- micro %>% 
  filter(!site_id == "QU39" & scientificName == "Oligotrichea") %>%
  select(date, site_id, cil_sum = species_sum)

diat_total <- diat_total %>% 
  left_join(cil)
```
```{r}
diat_total %>% 
  ggplot(aes(x = diat_sum, y = cil_sum)) + 
  geom_point()
```
```{r}
cor(diat_total$diat_sum, diat_total$cil_sum, method = "spearman", use = "complete.obs")
```
```{r}
#Trying to look at whether percent diatoms works better...


diat_perc <- micro %>% 
  filter(!site_id == "QU39" & trophicStatus == "auto") %>% 
  group_by(date, site_id, group) %>% 
  summarise(group_sum = sum(species_sum)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(total_sum = sum(group_sum)) %>% 
  ungroup() %>% 
  mutate(perc = (group_sum/total_sum)*100) %>% 
  filter(group == "Bacillariophyta") %>% 
  select(date, site_id, perc)

diat_total <- diat_total %>% 
  left_join(diat_perc)
    
```
```{r}
cor(diat_total$perc, diat_total$cil_sum, method = "spearman", use = "complete.obs")
```
```{r}
#Dino species
dinos <- micro %>% 
  filter(!site_id == "QU39" & class == "Dinophyceae") %>%
  group_by(scientificName) %>% 
  summarise(max = max(species_sum),
            med = median(species_sum)) %>% 
  ungroup()
```

```{r}
#Dino species
alex <- micro %>% 
  filter(!site_id == "QU39" & scientificName == "Alexandrium catenella")
```
















