---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)
library(ggcorrplot) 

```

```{r}
#Upload data

#Upload microscopy abundance data in OBIS and long/tide format
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Upload physical-chemical clusters derived via PCA
clust_pca <- read_csv(here("outputs", "pca_clusters_2023-02-01.csv"))

```

```{r}

#Adding location instead of site ID for interpretation of results
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

#Creating a unique location-date ID for each sample - makes labels for plotting by dendrogram more informative 
micro <- micro %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

#Renaming the sample_name unique ID in the cluster datasheet so that it can be joined to the microscoply data
clust_pca <- clust_pca %>% 
  rename(sample_name = label)

#Joining the PCA clusters to the microscopy data
micro <- micro %>% 
  left_join(clust_pca) %>% 
  rename(clust_pca = cluster) %>% 
  relocate(clust_pca, .after = location)

```

```{r}
#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at for the analysis.
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria" &
           !group == "Metazoa" &
           !group == "Protozoa" &
           !group == "Choanoflagellata" &
           !group == "Ciliophora" &
           !group == "Kinetoplastidea")
```

```{r}
#Filtering out species that are not present in at least 10% of the samples - this is important for the clustering and nMDS methods I am using as these species can skew the results.

#Determining total number of samples in the dataset
sample_num <- micro %>% 
  distinct(date, site_id)

#Determining species that are present in > 10% of samples.
species_10 <- micro %>% 
  group_by(scientificName) %>% 
  summarise(n_obs = n()) %>%
  ungroup() %>% 
  mutate(perc_obs = n_obs/78) %>% 
  filter(perc_obs >= 0.10)

#Creating a list of species in > 10% of samples.
species_10_list <- species_10$scientificName

#Removing species that are not present in > 10% of samples.
micro <- micro %>% 
  filter(scientificName %in% species_10_list)

```

```{r}
#Adding year and month to the microscopy dataset for analysis.

micro <- micro %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)
```



```{r}
#Preparing data for the differen analysis.

#Selecting columns that I will use
micro_piv <- micro %>% 
  select(sample_name:clust_pca, scientificName, species_sum)

#pivoting wider so species are columns and samples are rows.
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

```


```{r}
#Pulling out species counts for transformation and use in analysis
species <- micro_piv[, 8:ncol(micro_piv)]

#Transforming the abundance data
t_abund <- log10(species + 1)

#Calculating relative abundance
t_rel <- decostand(species, method = "total")

#transforming the relativel abundance data
t_rel <- sqrt(t_rel)
```



```{r}
#Making separate sheets to performed clustering on.
hc_abund <- t_abund

hc_rel <- t_rel

#Creating a list of rownames to attach to the clustering sheets - allows me to plot on the dendrogram.
labs_list <- micro_piv$sample_name

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(hc_abund) <- labs_list
rownames(hc_rel) <- labs_list
```


```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis_abund <- vegdist(hc_abund, method = "bray")
dis_rel <- vegdist(hc_rel, method = "bray")

#Applying wards linkage method
clust_ward_abund <- hclust(dis_abund)
clust_ward_rel <- hclust(dis_rel)

# , "ward.D2"
```

```{r}
#For the abundance data, looking at some methods to determine the number of clusters

#These are time intensive, so turning off until needed

# fviz_nbclust(hc_abund, FUN = hcut, method = "wss")
# fviz_nbclust(hc_abund, FUN = hcut, method = "silhouette")
# gap_stat <- clusGap(hc_abund, FUN = hcut, nstart = 25, K.max = 10, B = 50)
# fviz_gap_stat(gap_stat)

#In general, these approaches do not show many clusters - only 2. This bothers me as there is clearly more structure in the data.
```

```{r}
#For the relative, looking at some methods to determine the number of clusters

#These are time intensive, so turning off until needed

# fviz_nbclust(hc_rel, FUN = hcut, method = "wss")
# fviz_nbclust(hc_rel, FUN = hcut, method = "silhouette")
# gap_stat <- clusGap(hc_rel, FUN = hcut, nstart = 25, K.max = 10, B = 50)
# fviz_gap_stat(gap_stat)

#Depending on the method there could be 3 - 7 clusters. Seems to be more information from the relative abundance data.
```

```{r}
#This step sets clusters.

# Abundance data
k_abund <- 3
clust_abund <- cutree(clust_ward_abund, k = k_abund)

clust_df_abund <- data.frame(label = rownames(hc_abund),
                                   cluster = factor(clust_abund))
# #Relative data
k_rel <- 4
clust_rel <- cutree(clust_ward_rel, k = k_rel)

clust_df_rel <- data.frame(label = rownames(hc_rel),
                                   cluster = factor(clust_rel))
```

```{r}
#Trying cutting at line 

#Abundance data
# k_abund <- 0.5
# clust_abund <- cutree(clust_ward_abund, h = k_abund)
# # 
# clust_df_abund <- data.frame(label = rownames(hc_abund),
#                                    cluster = factor(clust_abund))
# #Relative data
# k_rel <- 0.6
# clust_rel <- cutree(clust_ward_rel, h = k_rel)
# 
# clust_df_rel <- data.frame(label = rownames(hc_rel),
#                                    cluster = factor(clust_rel))
```


```{r}
# extract dendrogram segment data for plotting

#Abundance data
dend_abund <- as.dendrogram(clust_ward_abund)
dendrogram_data_abund <- dendro_data(dend_abund)
dendrogram_segments_abund <- dendrogram_data_abund$segments 

#Relative data
dend_rel <- as.dendrogram(clust_ward_rel)
dendrogram_data_rel <- dendro_data(dend_rel)
dendrogram_segments_rel <- dendrogram_data_rel$segments 
```

```{r}
#Setting up sheets so that I can color labels by station

#Creating metadata sheet with 
metadata <- micro_piv %>%
  select(sample_name, site_id)

# get terminal dendrogram segments and join with names. - abundance data.
dendrogram_ends_abund <- dendrogram_segments_abund %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data_abund$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

# get terminal dendrogram segments and join with names. - relative data.
dendrogram_ends_rel <- dendrogram_segments_rel %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data_rel$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name")
```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. 


#Abundance
dendrogram_data_abund[["labels"]] <- merge(dendrogram_data_abund[["labels"]], clust_df_abund, by = "label")
rect_abund <- aggregate(x~cluster, label(dendrogram_data_abund), range)
rect_abund <- data.frame(rect_abund$cluster, rect_abund$x)
ymax_abund <- mean(clust_ward_abund$height[length(clust_ward_abund$height) - ((k_abund-2):(k_abund-1))])

#Relative
dendrogram_data_rel[["labels"]] <- merge(dendrogram_data_rel[["labels"]], clust_df_rel, by = "label")
rect_rel <- aggregate(x~cluster, label(dendrogram_data_rel), range)
rect_rel <- data.frame(rect_rel$cluster, rect_rel$x)
ymax_rel <- mean(clust_ward_rel$height[length(clust_ward_rel$height) - ((k_rel-2):(k_rel-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

#Here doing abundance data

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars_abund <- levels(factor(dendrogram_ends_abund$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count_abund <- length(unique(unique_vars_abund$.))

# get RColorBrewer palette
get_palette_abund <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette_abund <- get_palette_abund(color_count_abund) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list_abund <- left_join(unique_vars_abund, palette_abund, by = "row_id") %>%
 select(-row_id)

site_color_abund <- as.character(color_list_abund$color)
names(site_color_abund) <- color_list_abund$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
ggplot() +
 geom_segment(data = dendrogram_segments_abund, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends_abund, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id),
              size = 2) +
 geom_text(data = dendrogram_ends_abund, aes(x = x, y = y.y, label = sample_name,
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 geom_rect(data = rect_abund, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0,
                                  ymax = ymax_abund),
            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color_abund) +
 scale_y_reverse(limits = c(1, -1)) +
 coord_flip() +
 theme_bw() +
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_nmds", "bray_2023-01-31_abund.png"),
       width = 6, height = 12, dpi = 300)
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

#Here doing relative

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars_rel <- levels(factor(dendrogram_ends_rel$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count_rel <- length(unique(unique_vars_rel$.))

# get RColorBrewer palette
get_palette_rel <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette_rel <- get_palette_rel(color_count_rel) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list_rel <- left_join(unique_vars_rel, palette_rel, by = "row_id") %>%
 select(-row_id)

site_color_rel <- as.character(color_list_rel$color)
names(site_color_rel) <- color_list_rel$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
ggplot() +
 geom_segment(data = dendrogram_segments_rel, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends_rel, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id),
              size = 2) +
 geom_text(data = dendrogram_ends_rel, aes(x = x, y = y.y, label = sample_name,
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 geom_rect(data = rect_rel, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0,
                                  ymax = ymax_rel),
            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color_rel) +
 scale_y_reverse(limits = c(1, -1)) +
 coord_flip() +
 theme_bw() +
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_nmds", "bray_2023-01-31_rel.png"),
       width = 6, height = 12, dpi = 300)
```








```{r}
#Setting up the derived abundance clusters for joining with the actual data
clust_abund_join <- clust_df_abund %>% 
  select(sample_name = label, clust_abund = cluster)

clust_rel_join <- clust_df_rel %>% 
  select(sample_name = label, clust_rel = cluster)

micro_piv <- micro_piv %>% 
  left_join(clust_abund_join) %>% 
  left_join(clust_rel_join) %>% 
  relocate(clust_abund, .after = clust_pca) %>% 
  relocate(clust_rel, .after = clust_abund)  
```

```{r}
#ANOSIM test to see if groupings statistically significant 
clust_pca <- micro_piv$clust_pca
clust_abund <- micro_piv$clust_abund
clust_rel <- micro_piv$clust_rel


ano_clust_pca = anosim(t_abund, clust_pca, distance = "bray", permutations = 9999)
ano_clust_pca
#  
# ano_clust_abund = anosim(t_abund, clust_abund, distance = "bray", permutations = 9999)
# ano_clust_abund
#  
ano_clust_rel = anosim(t_rel, clust_rel, distance = "bray", permutations = 9999)
ano_clust_rel
#  
# ano_clust_pca_rel = anosim(t_rel, clust_pca, distance = "bray", permutations = 9999)
# ano_clust_pca_rel

```



```{r}
set.seed(123)

#Running nmds all species
nmds_abund <-  metaMDS(t_abund, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Show results including stress 
nmds_abund

#Checking stressplot for fit
stressplot(nmds_abund)

```

```{r}
set.seed(123)

#Running nmds all species
nmds_rel <-  metaMDS(t_rel, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Show results including stress 
nmds_rel

#Checking stressplot for fit
stressplot(nmds_rel)
```



```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

#All abundance
data.scores_abund = as.data.frame(scores(nmds_abund))
data.scores_abund$month = micro_piv$month
data.scores_abund$site = micro_piv$location
data.scores_abund$year = micro_piv$year
data.scores_abund$clust_pca = micro_piv$clust_pca
data.scores_abund$clust_abund = micro_piv$clust_abund


data.scores_rel = as.data.frame(scores(nmds_rel))
data.scores_rel$month = micro_piv$month
data.scores_rel$site = micro_piv$location
data.scores_rel$year = micro_piv$year
data.scores_rel$clust_pca = micro_piv$clust_pca
data.scores_rel$clust_rel = micro_piv$clust_rel
```

```{r}
#Order locations from fjord to shelf for plotting order
order_loc <- c("F", "C", "S")

#Setting location order for plots 
data.scores_abund <- arrange(mutate(data.scores_abund,
                         site = factor(site, levels = order_loc)))

data.scores_rel <- arrange(mutate(data.scores_rel,
                         site = factor(site, levels = order_loc)))
```


```{r}
# #Looking at species scores to add to the nmds plot
# 
# #All species
# vf <- envfit(nmds, transform, perm = 999)
# 
# #Diatoms
# vf_diat <- envfit(nmds_diat, transform_diat, perm = 999)
# 
# #Dinoflagellates
# vf_dino <- envfit(nmds_dino, transform_dino, perm = 999)
# 
# #Pulling out r2 scores
# #All species
# r2 <- vf$vectors$r
# 
# #Diatoms
# r2_diat <- vf_diat$vectors$r
# 
# #Diatoms
# r2_dino <- vf_dino$vectors$r
# 
# #MAking dataframe out of r2 values
# #All species
# r2_df <- as.data.frame(r2)
# 
# #Diatoms
# r2_df_diat <- as.data.frame(r2_diat)
# 
# #Dino
# r2_df_dino <- as.data.frame(r2_dino)
# 
# #Pulling and binding vectors and r2 scores
# #All species
# spp.scrs <- as.data.frame(scores(vf, display = "vectors"))
# spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))
# spp.scrs2 <- cbind(spp.scrs, r2_df)
```


```{r}
#Pulling species with only r2 > 0.3 scores
#All species
# spp.scrs2 <- spp.scrs2 %>%
#   filter(r2 >= 0.30)
# 
# #Diatoms
# spp.scrs2_diat <- spp.scrs2_diat %>%
#   filter(r2_diat >= 0.30)
# 
# #Dinoflagellates
# spp.scrs2_dino <- spp.scrs2_dino %>%
#   filter(r2_dino >= 0.30)
```


```{r}
#Making shorter abbreviated species names for plotting

# rownames(spp.scrs2) <- c("Hill.",
#                          "Tel.",
#                          "S.mar.",
#                          "P.pou.",
#                          "C.soc.",
#                          "C.cin.") 
# 
# rownames(spp.scrs2_diat) <- c("C.clo.",
#                               "P.n.s.",
#                               "R.set.",
#                               "Pen.",
#                               "S.mar.",
#                               "Bid.",
#                               "L.dan.")
# 
# rownames(spp.scrs2_dino) <- c("Gymn.",
#                               "Gyro.",
#                               "Kato.",
#                               "S.pre.",
#                               "S.tro.")
#                               
```

```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

f1 <- ggplot(data = data.scores_abund, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_abund, aes(fill = as.factor(clust_pca), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  # ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
  #                                          label = row.names(spp.scrs2)),
  #                 # box.padding = unit(0.5, 'lines'),
  #                 # point.padding = NA,
  #                 point.padding = unit(2, 'lines'),
  #                 segment.color = 'black',
  #                 segment.size = 0.5,
  #                 segment.alpha = 0.7,
  #                 arrow = arrow(length = unit(0.01, 'npc')),
  #                 # nudge_y = 0.2,
  #                 # nudge_x = -0.2,
  #                 force = 3,
  #                 max.iter = 3e3,
  #                 size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f2 <- ggplot(data = data.scores_abund, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_abund, aes(fill = as.factor(clust_abund), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) +
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  # ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
  #                                          label = row.names(spp.scrs2)),
  #                 # box.padding = unit(0.5, 'lines'),
  #                 # point.padding = NA,
  #                 point.padding = unit(2, 'lines'),
  #                 segment.color = 'black',
  #                 segment.size = 0.5,
  #                 segment.alpha = 0.7,
  #                 arrow = arrow(length = unit(0.01, 'npc')),
  #                 # nudge_y = 0.2,
  #                 # nudge_x = -0.2,
  #                 force = 3,
  #                 max.iter = 3e3,
  #                 size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))




fig <- f1 + f2

ggsave(here("figures_nmds", "test_bray.png"), fig,
       width = 16, height = 5, dpi = 300)
```
```{r}
#This is the horizontal version of the month and year nMDS panel shown incorporated into a large panel later 

f1 <- ggplot(data = data.scores_rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_rel, aes(fill = as.factor(clust_pca), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  # ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
  #                                          label = row.names(spp.scrs2)),
  #                 # box.padding = unit(0.5, 'lines'),
  #                 # point.padding = NA,
  #                 point.padding = unit(2, 'lines'),
  #                 segment.color = 'black',
  #                 segment.size = 0.5,
  #                 segment.alpha = 0.7,
  #                 arrow = arrow(length = unit(0.01, 'npc')),
  #                 # nudge_y = 0.2,
  #                 # nudge_x = -0.2,
  #                 force = 3,
  #                 max.iter = 3e3,
  #                 size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

f2 <- ggplot(data = data.scores_rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_rel, aes(fill = as.factor(clust_rel), shape = site),
             size = 7, stroke = 1.5) + 
  scale_fill_brewer(palette = "Dark2") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) +
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  # geom_segment(data = spp.scrs2,
  #              aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
  #              arrow = arrow(length = unit(0.25, "cm")), colour = "grey",
  #              size = 1.2, alpha = 0.7) +
  # geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "black",
  #            fontface = "bold", label = row.names(spp.scrs2), size = 7) + 
  # ggrepel::geom_text_repel(data = spp.scrs2, aes(x = NMDS1, y = NMDS2, 
  #                                          label = row.names(spp.scrs2)),
  #                 # box.padding = unit(0.5, 'lines'),
  #                 # point.padding = NA,
  #                 point.padding = unit(2, 'lines'),
  #                 segment.color = 'black',
  #                 segment.size = 0.5,
  #                 segment.alpha = 0.7,
  #                 arrow = arrow(length = unit(0.01, 'npc')),
  #                 # nudge_y = 0.2,
  #                 # nudge_x = -0.2,
  #                 force = 3,
  #                 max.iter = 3e3,
  #                 size = 7) +
  # xlim(-0.4, 0.7) +
  # annotate("text", x = 0.60, y = 0.40, label = "a)", size = 10) +
  # annotate("text", x = 0.40, y = -0.40, label = "Stress = 0.23", size = 10) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # legend.position = "none",
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))




fig <- f1 + f2

ggsave(here("figures_nmds", "test_rel_ward.png"), fig,
       width = 16, height = 5, dpi = 300)
```





```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for all species
inv_clust_pca = multipatt(t_abund, clust_pca, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_clust_pca)
```

```{r}
# inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)
# 
# inv_site_sp <- inv_site_sp %>% 
#   filter(s.C == 1 | s.F == 1 | s.S == 1) %>% 
#   filter(p.value < 0.01) %>% 
#   # filter(!rn == "Skeletonema marinoi") %>% 
#   arrange(rn)
# 
# inv_site_list <- inv_site_sp$rn
# 
# inv_site_list
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for diatoms
inv_clust_abund = multipatt(t_abund, clust_abund, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_clust_abund)
```
```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for diatoms
inv_clust_rel = multipatt(t_rel, clust_rel, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_clust_rel)
```

```{r}
#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station for diatoms
inv_clust_pca_rel = multipatt(t_rel, clust_pca, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_clust_pca_rel)
```




```{r}
micro_piv %>% 
  ggplot(aes(x = as.factor(location), fill = as.factor(clust_rel))) +
  geom_bar( position = "stack")
```

```{r}
drows = vegdist(hc_rel, method="bray", binary=FALSE, diag=FALSE, upper=FALSE, na.rm = FALSE)                 

dcols = vegdist(t(hc_rel), method="bray", binary=FALSE, diag=FALSE, upper=FALSE, na.rm = FALSE)                                               

pheatmap::pheatmap(hc_rel, clustering_distance_rows = drows, cluster_cols = F,
                   cutree_rows = 5,
                   color = colorRampPalette(c("white", "red"))(50))
```
```{r}
micro %>% 
  filter(scientificName == "Navicula") %>% 
  ggplot(aes(x = date, y = species_sum, color = site_id)) + 
  geom_line() +
  geom_point()
```



























