---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(factoextra)
library(ggdendro)
library(ggforce)
library(concaveman)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(RColorBrewer)

#Need to go through and test these

```

```{r}
#Upload data

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_kc10_2021-12-01.csv")) 

#Download physical data
# data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))
```
```{r}
micro <- micro %>% 
  filter(!site_id == "QU39")

micro <- micro %>% 
  mutate(month = lubridate::month(date)) %>% 
  relocate(month, .after = date)
```


```{r}
#Selecting the species groups I will work with and limiting species that rarely observed.

#For now, I am keeping all of the heterotrophic species (just in this workbook)

# micro <- micro %>% 
#   filter(trophicStatus == "auto")

#Counting how many times each species is observed
micro <- micro %>%
  group_by(scientificName) %>%
  mutate(num_occurrence = n()) %>% 
  ungroup()

#removing species that have not been observed at least twice -  this is to minimize the influence of zeros. When I used this, it removes some species that are important, but not observed often. So trying with it turned off.
# micro <- micro %>%
#   filter(num_occurrence > 5)

#Removing cyanobacteria as their counts are not reliable
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")

micro <- micro %>% 
  filter(!group == "Metazoa") %>% 
  filter(!group == "Protozoa")
```

```{r}
# Trying to look at only species present in 10% of samples
# How many samples

sample_num <- micro %>%
  distinct(date, site_id)

species_10 <- micro %>%
  group_by(scientificName) %>%
  summarise(n_obs = n()) %>%
  ungroup() %>%
  mutate(perc_obs = n_obs/50) %>%
  filter(perc_obs >= 0.10)

species_10_list <- species_10$scientificName

micro <- micro %>%
  filter(scientificName %in% species_10_list)

```

```{r}
# micro <- micro %>%
#   filter(class == "Bacillariophyceae")

# micro <- micro %>%
#   mutate(year = lubridate::year(date)) %>%
#   relocate(year, .before = month) %>%
#   filter(site_id == "QCS01")
```

```{r}
#Preparing data for cluster and nMDS analysis - need to be put into two separate matrices.

#Selecting columns
micro_piv <- micro %>% 
  select(date, month, site_id, scientificName, species_sum)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Adding year to wide format for plotting
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Arranging according to site ID and date
micro_piv <- micro_piv %>% 
  arrange(site_id, date)

#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 5:ncol(micro_piv)]

#Creating relative abundance matrix - not currently looking at relative abundance
# transform <- decostand(species, method = "total")

#Log10 transformation + 1 (as per Mahara)
# transform <- log1p(species)
# transform <- species


#Not currently working with relative abundance
# transform <- sqrt(transform)
```

```{r}
#separating treatments for ANOSMIM and indicator
site_id <- micro_piv$site_id
month <- micro_piv$month
year <- micro_piv$year
```

```{r}
#ANOSIM test to see if groupings statistically significant - abundance

#Turning off for now because takes time to analyze.
# ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
# ano_site
# 
ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
ano_month
# 
ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
ano_year

```


```{r}
#Running nmds on Calvert data
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Show results including stress - currently 0.23.
nmds

#Checking stressplot for fit
stressplot(nmds)

```

```{r}
#Changing site_id to location 
micro_piv <- micro_piv %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

metadata <- micro_piv %>%
  select(location, site_id, date) %>%  
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

data.scores = as.data.frame(scores(nmds))
data.scores$month_surv = micro_piv$month_surv
data.scores$site = micro_piv$location
data.scores$year = micro_piv$year

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
data.scores <- arrange(mutate(data.scores,
                         site = factor(site, levels = order_loc)))
```

```{r}

#Trying to add species scores - Want to select the most important, but can't figure it out and wasting a lot of time on something that probably won't result in much gain.
vf <- envfit(nmds, transform, perm = 999)

r2 <- vf$vectors$r

test <- as.data.frame(r2)

spp.scrs <- as.data.frame(scores(vf, display = "vectors"))

spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

spp.scrs2 <- cbind(spp.scrs, test)

spp.scrs2 <- spp.scrs2 %>%
  filter(r2 >= 0.40)

# rownames(spp.scrs2) <- c("P.n.s","R.set.","Bidd.","S.mar.", "C.clos")
```

```{r}
phy <- data %>% 
  select(date:site_id, temp = temp_dm, sal = sal_dm, drho = delta_rho_dm, 
         no2 = no2_dm, sio2 = sio2_dm, po4 = po4_dm, secchi = secchi_depth)

micro_piv_join <- micro_piv %>% 
  left_join(phy)

env <- micro_piv_join[, 50:56]
  
en = envfit(nmds, env, permutations = 999, na.rm = TRUE)

en
```
```{r}
en_coord_cont = as.data.frame(scores(en, "vectors")) * ordiArrowMul(en)
en_coord_cat = as.data.frame(scores(en, "factors")) * ordiArrowMul(en)
```

```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits. This is for the absolute data

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month), shape = site),
             size = 4, stroke = 1.5) + 
  geom_segment(data = spp.scrs2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "blue") +
  geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "blue",
             fontface = "bold", label = row.names(spp.scrs2)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size =1, alpha = 0.5, colour = "black") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "black", 
  #             fontface = "bold", label = row.names(en_coord_cont)) + 
  scale_fill_brewer(palette = "RdYlBu") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # coord_fixed() + ## need aspect ratio of 1!
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        # legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 32)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

ggsave(here("figures_good", "nmds_diatoms_rel.png"),
        width = 6.5, height = 4.5, dpi = 300)
```

```{r}

#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station
inv_site <- multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_site)

```

```{r}

#Indicator species analysis
# https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html

#Indicators by station
inv_month <- multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

#Looking at results of analysis
summary(inv_month)

```



```{r}
inv_site_sp <- data.table::as.data.table(inv_site$sign, keep.rownames = TRUE)

inv_site_sp <- inv_site_sp %>% 
  filter(s.DFO2 == 1 | s.KC10 == 1 | s.QCS01 == 1) %>% 
  filter(p.value < 0.05) %>% 
  # filter(!rn == "Skeletonema marinoi") %>% 
  arrange(rn)

inv_site_list <- inv_site_sp$rn
```

```{r}
#Making a heatmap of the indicator species
micro %>%   
  filter(scientificName %in% inv_site_list) %>%
  ggplot(aes(x = as.factor(date), y = scientificName, fill = log10(species_sum))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(. ~ site_id , scales = "free_x", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Chaetoceros convolutus" = "C.con.",
                              "Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros didymus" = "C.did.",
                              "Chaetoceros laciniosus" = "C.lac.",
                              "Chaetoceros radicans" = "C.rad.",
                              "Chaetoceros seiracanthus" = "C.sei.",
                              "Chaetoceros socialis" = "C.soc.",
                              "Dactyliosolen fragilissimus" = "D.fra.",
                              "Dactyliosolen phuketensis" = "D.phu.",
                              "Detonula pumila" = "D.pum.",
                              "Eucampia zodiacus" = "E.zod.",
                              "Guinardia delicatula" = "G.del.",
                              "Leptocylindrus danicus" = "L.dan.",
                              "Navicula" = "Nav.",
                              "Pseudo-nitzschia" = "P.n.",
                              "Pseudo-nitzschia seriata" = "P.n.s.",
                              "Skeletonema marinoi" = "S.mar.",
                              "Thalassiosira rotula" = "T.rot.")) +
  # geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, label = label), 
  #           hjust = -0.1, vjust = -1) +
  # annotate("text", x = 1.5, y = 11, label = "e)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank())

ggsave(here("figures_good", "heat_test.png"),
        width = 16, height = 8, dpi = 300)
```





```{r}
#should look at relative abundance plot of this, since using.
micro_rel <- micro %>% 
  group_by(date, site_id) %>% 
  mutate(sum_total = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(perc_total = species_sum/sum_total)

```

```{r}

#Making a heatmap of the indicator species
micro_rel %>%   
  filter(scientificName %in% inv_site_list) %>%
  ggplot(aes(x = as.factor(date), y = scientificName, fill = perc_total)) +
  geom_tile(color = "black", size = 1) +
  facet_grid(. ~ site_id , scales = "free_x", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  scale_y_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Chaetoceros convolutus" = "C.con.",
                              "Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros didymus" = "C.did.",
                              "Chaetoceros laciniosus" = "C.lac.",
                              "Chaetoceros radicans" = "C.rad.",
                              "Chaetoceros seiracanthus" = "C.sei.",
                              "Chaetoceros socialis" = "C.soc.",
                              "Dactyliosolen fragilissimus" = "D.fra.",
                              "Dactyliosolen phuketensis" = "D.phu.",
                              "Detonula pumila" = "D.pum.",
                              "Eucampia zodiacus" = "E.zod.",
                              "Guinardia delicatula" = "G.del.",
                              "Leptocylindrus danicus" = "L.dan.",
                              "Navicula" = "Nav.",
                              "Pseudo-nitzschia" = "P.n.",
                              "Pseudo-nitzschia seriata" = "P.n.s.",
                              "Skeletonema marinoi" = "S.mar.",
                              "Thalassiosira rotula" = "T.rot.")) +
  # geom_text(data = dat_text, mapping = aes(x = -Inf, y = -Inf, label = label), 
  #           hjust = -0.1, vjust = -1) +
  # annotate("text", x = 1.5, y = 11, label = "e)", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank())

ggsave(here("figures_good", "heat_test_rel.png"),
        width = 16, height = 10, dpi = 300)

```


```{r}
cor_test <- micro %>% 
  filter(scientificName %in% inv_site_list)

cor_test <- cor_test %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

cor_test_piv <- cor_test %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))



cor_matrix <- cor_test_piv %>% 
  left_join(phy)

cor_matrix <- cor_matrix %>% 
  drop_na() %>% 
  select(`Chaetoceros debilis`:secchi)

spear_rho <- Hmisc::rcorr(as.matrix(cor_matrix), type = c("pearson"))

res2<-rcorr(as.matrix(mtcars[,1:7]))
flattenCorrMatrix(res2$r, res2$P)

# Insignificant correlations are left blank
corrplot::corrplot(spear_rho$r, type = "upper", order = "hclust", 
         p.mat = spear_rho$P, sig.level = 0.001, insig = "blank")








# Insignificant correlations are left blank
fig_corr2 <- corrplot(spear_rho$r, type="upper", order="hclust", 
         p.mat = spear_rho$P, sig.level = 0.001, insig = "blank")

```





```{r}
#Creating rownames for dendrogram creating

#Changing site_id to location 
micro_piv <- micro_piv %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

metadata <- micro_piv %>%
  select(location, site_id, date) %>%  
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

#Creating a list of rownames
# labs_list <- labs$sample_name
labs_list <- metadata$sample_name

#creating a hierarchical clustering matrix
transform_hc <- transform

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(transform_hc) <- labs_list
```



```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- vegdist(transform_hc, method = "bray")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "average")

```



```{r}
#Turning off as tests show 1-2 clusters that do not make sense with data


# Looking at number of clusters
# fviz_nbclust(transform, FUN = hcut, method = "wss")
# fviz_nbclust(transform, FUN = hcut, method = "silhouette")
# gap_stat <- clusGap(transform, FUN = hcut, nstart = 25, K.max = 10, B = 50)
# fviz_gap_stat(gap_stat)
```

```{r}
#This step sets clusters. Currently, I am not using.

k <- 2
clust <- cutree(cluster.average, k = k)

clust.df <- clust.df <- data.frame(label = rownames(transform_hc),
                                   cluster = factor(clust))

# write_csv(clust.df, here("outputs", "clusters_micro_6.csv"))
```

```{r}
# extract dendrogram segment data for plotting

dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}

# get terminal dendrogram segments and join with names.
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
p_dend <- ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0, ymax = ymax),
            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(1, -0.3)) +
 coord_flip() + 
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       # axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Dist.") # flipped x and y coordinates for aesthetic reasons

#Turning off saving for now because not needed
ggsave(here("figures_good", "hc_average_diat_2.png"), p_dend,
       width = 6, height = 12, dpi = 300)
```

```{r}

# For clusters, need to merge on station/date code.
micro_piv <- micro_piv %>%
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

clust_df <- clust.df %>%
  rename(sample_name = label)

micro_piv <- micro_piv %>%
  left_join(clust_df) %>%
  relocate(cluster, .after = month_surv)

data.scores$clust = micro_piv$cluster

```
```{r}
ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 4, stroke = 1.5) + 
  geom_segment(data = spp.scrs2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "blue") +
  geom_text(data = spp.scrs2, aes(x = NMDS1, y = NMDS2), colour = "blue",
             fontface = "bold", label = row.names(spp.scrs2)) + 
  geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
               data = en_coord_cont, size =1, alpha = 0.5, colour = "black") +
  geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "black", 
              fontface = "bold", label = row.names(en_coord_cont)) + 
  geom_mark_hull(data = data.scores, aes(color = clust, label = clust),
                 concavity = 2.8, label.fontsize = 30, expand = unit(4.1, "mm"),
                 radius = unit(4, "mm")) +
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.4, 0.7) +
  # xlim(-1.1, 1.1) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        # legend.position = c(0.1, 0.31),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        legend.background = element_rect(fill = 'transparent', color = 'transparent'),
        legend.box.background = element_rect(fill='transparent', color = 'transparent'),  
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
   guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none")
```

























