---
title: "R Notebook"
output: html_notebook
---

Here I run RDA analysis on the 2018-2020 Microscopy data and then the 2019-2020 Chemtax data. I do this in the same noptebook so I can combined the plots.

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)

#From https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html#1_Packages_needed

#For plotting with ggplot2

library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
```

```{r}
#Upload data

#All data merged to the CTD - Did I remove heterotrophs here? I think I need to go back and include the same species I am using for the nMDS.
mm <- read_csv(here("outputs", "ctd_merge_2022-02-01_het.csv")) 

#Just using calvert data
mm <- mm %>% 
  filter(!site_id == "QU39")

#Uploading the chl-HPLC timeseries that I created to eliminate data QC gaps.
chl_full <- read_csv(here("outputs", "chl_hplc_merged.csv"))

#Isolating chemtax data
mm_chem <- mm %>% 
  select(date:secchi_depth, cyan:diat)

```

```{r}
#Could try to limit cryptic species that influence stats. Leaving off for now.

#This removes any columns with all zeros- species not observed. Created because they sporadic were observed, but I have filtered the dataset down quite a bit.
mm <- mm %>% 
  select(where(~ any(. != 0)))

```

```{r}
#Running without Chlorophyll first.

#Just running Calvert data for this file
# mm <- mm %>% 
#   filter(!site_id == "QU39")

#With the chlorophyll data included, quite a few data point removed - trying without chlorophyll - made a mistake and was cutting out data where there was no chemtax. Need to fix this. 
mm_no_chl <- mm %>% 
  select(!(micro_chl:bulk_chl)) %>% 
  select(!(cyan:diat))

#Re adding chlorophyll using the full chl data-set without many NAs.
mm_no_chl <- mm_no_chl %>% 
  left_join(chl_full) %>% 
  relocate(chl, .after = secchi_depth)

#Removing columns-environmental drivers I'm not using before removing NAs as it preserved 2 more sites.
mm_no_chl <- mm_no_chl %>% 
  select(!N2_dm) %>% #Currently not using stability
  select(!dep_26_dm) %>%  #Currently not using 1026 depth
  select(!zeu_dm) %>% #not using z1% (zeu) in this file
  select(!flu_dm) #not using CTD chl fluorescence

#removing NAs for analysis
mm_no_chl <- mm_no_chl %>% 
  drop_na()

#Separating into response variables (microscopy counts) and Explanatory variables (Environmental)
resp <- mm_no_chl[, 19:139]

#Explanatory variables
expl <- mm_no_chl[, 7:15]

#Adding nutrient ratios - I'm not sure this is a good things to do as they will covary with the nutrients
# expl <- expl %>% 
#   mutate(n_p = no2_dm/po4_dm,
#          si_n = sio2_dm/no2_dm) %>% 
#   mutate_if(is.numeric, ~ replace(., is.infinite(.), 0))

```

```{r}
#Hellinger transformation on species data - particularly suited to species abundance data with large range and lots of zeros. Gives low weights to variables with low counts and many zeroes.
resp.hell <- decostand(resp, 'hell')

expl <- scale(expl)

expl <- as.data.frame(expl)

expl <- expl %>% 
  rename(temp = temp_dm, sal = sal_dm, drho = delta_rho_dm, turb = turb_dm,
         no3_no2 = no2_dm, sio2 = sio2_dm, po4 = po4_dm, secchi = secchi_depth)
```

```{r}
#Microscopy

tbRDA.all <- rda(resp.hell ~ . , data = expl)

tbRDA.all

anova(tbRDA.all)

adjR2.tbrda <- RsquareAdj (tbRDA.all)$adj.r.squared

adjR2.tbrda


# RDA1 - 
# RDA2 - 
# PCA1 - 
# PCA2 - 

#r2 = 0.25

#Global model significant to 0.001 
```
```{r}
constrained_eig <- tbRDA.all$CCA$eig/tbRDA.all$tot.chi*100
unconstrained_eig <- tbRDA.all$CA$eig/tbRDA.all$tot.chi*100
expl_var <- c(constrained_eig, unconstrained_eig)
barplot (expl_var[1:20], col = c(rep ('red', length (constrained_eig)), rep ('black', length (unconstrained_eig))),
         las = 2, ylab = '% variation')
```

```{r}
#Using DCA on chemtax data to test whether linear or unimodal model is appropriate - Apparently don't need if doing tb-RDA (hellinger) - see David Zeleny website
DCA <- decorana(resp.hell)
DCA

#2.4693

#As the length of the first DCA is < 3 S.D. - the dataset is homogenous and a linear model is appropriate. The score went down after applying the Hellinger Transformation. Proceed with RDA.

```

```{r}
#Trying different approach for ordiR2step from https://www.davidzeleny.net/anadat-r/doku.php/en:forward_sel_examples - same result as my other test
tb_rda.vasc.0 <- rda (resp.hell ~ 1, data = expl)

tb_rda.vasc.all <- rda (resp.hell ~ ., data = expl)

sel.osR2 <- ordiR2step (tb_rda.vasc.0, scope = formula (tb_rda.vasc.all), 
                        R2scope = adjR2.tbrda, direction = 'forward', 
                        permutations = 999)

sel.osR2$anova

sel.osR2_adj <- sel.osR2

sel.osR2_adj$anova$`Pr(>F)` <- p.adjust (sel.osR2$anova$`Pr(>F)`, 
                                         method = 'holm', n = ncol (expl))

sel.osR2_adj$anova

#secchi = 0.008
#sio2 = 0.008
#temp = 0.024
```

```{r}
#Select the statistically significant variables - May want to remove SiO2, see VIFS below!
env.signif <- subset(expl, select = c(temp, sio2, secchi))

#RDA using significant variables
rda.signif <- rda(resp.hell ~ . ,data = env.signif)
rda.signif
rda.sign.sum <- summary(rda.signif)

rda.sign.sum
#Total = 36%
#Constrained = 26%
#RDA1 = 18%
#RDA2 = 7%

#Adjusted R2 for the 1 significant variables
#AdjR2 = 
(R2adj <- RsquareAdj(rda.signif)$adj.r.squared)

#ANOVA for testing significance of model and individual axes #Can do ANOVA by terms...
#Entire model = 0.001***
#RDA1 = 0.001***
#RDA2 = 0.001***

# ?anova.cca
anova.cca(rda.signif, step = 1000)
anova.cca(rda.signif, step = 1000, by = "axis")

#All significant - already shown in forward rda, but easier to see (Not corrected)
anova(rda.signif, by = "terms")

```

```{r}

#Trying the same thing, but bringing in arrows from previous plot - trying scaling 2
#pdf(file = "rda_s2.pdf", width = 6.5, height = 5, pointsize = 2)

p_s1 <- plot(rda.signif, scaling = 1, type = "none", xlab = c("RDA1 (28%)"),
               ylab = c("RDA2 (5%)"), xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1))

# points(rda.signif, display = 'sites', pch = 21, cex = 2.2,
#        col = rgb(red = 1, green = 1, blue = 1, alpha = 0.5), scaling = 2,
#        bg = bg[eco])

points(scores(rda.signif, display = 'sites', choices = c(1, 2), scaling = 1),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(mm_no_chl$site_id)])

#So since distance doesn't matter, I can make arrows longer with scaling 2? 
# arrows(0,0, scores(rda.signif, display = "species", choices = c(1),
#                    scaling = 1), scores(rda.signif, display = "species",
#                                             choices = c(2), scaling = 1),
#        col = "black", length = 0)

text(rda.signif, scaling = 1, display = "bp", col = "blue",cex = 0.8, font = 2)

# text(scores(rda.signif, display = "species", choices = c(1), scaling = 1),
#      scores(rda.signif, display = "species", choices = c(2), scaling = 1),
#      labels = rownames(scores(rda.signif, display = "species", scaling = 1)),
#      col = "black", cex = 0.8, font = 2)


# legend("topleft", legend = levels(eco), bty ="n", col="gray32", pch = 21,
#        cex = 1.5, pt.bg = bg)

legend("topright", legend = c(levels(as.factor(mm$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

#dev.off()

```
```{r}
# png(here("figures_new", "rda_micro.png"),
#      width = 800, height = 500)

plot_s2 <- plot(rda.signif, scaling = 2, type = "none", xlab = c("RDA1 (28%)"),
               ylab = c("RDA2 (5%)"))

# , xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1)

# points(rda.signif, display = 'sites', pch = 21, cex = 2.2,
#        col = rgb(red = 1, green = 1, blue = 1, alpha = 0.5), scaling = 2,
#        bg = bg[eco])

points(scores(rda.signif, display = 'sites', choices = c(1, 2), scaling = 2),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(mm_no_chl$site_id)])

#So since distance doesn't matter, I can make arrows longer with scaling 2? 
# arrows(0,0, scores(rda.signif, display = "species", choices = c(1),
#                    scaling = 1), scores(rda.signif, display = "species",
#                                             choices = c(2), scaling = 1),
#        col = "black", length = 0)

text(rda.signif, scaling = 2, display = "bp", col = "blue",cex = 0.8, font = 2)

# text(scores(rda.signif, display = "species", choices = c(1), scaling = 1),
#      scores(rda.signif, display = "species", choices = c(2), scaling = 1),
#      labels = rownames(scores(rda.signif, display = "species", scaling = 1)),
#      col = "black", cex = 0.8, font = 2)


# legend("topleft", legend = levels(eco), bty ="n", col="gray32", pch = 21,
#        cex = 1.5, pt.bg = bg)

legend("topright", legend = c(levels(as.factor(mm$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

# dev.off()
```

```{r}
#Testing species goodness of fit to try to eliminate species

# https://stackoverflow.com/questions/27823131/customising-vegan-ordination-plot
sel <- goeveg::ordiselect(resp, rda.signif, fitlim = 0.10)

sel2 <- goeveg::ordiselect(resp, rda.signif, ablim = 0.10, fitlim = 0.10)

sel

sel2

```

```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as arrows with 10% best fit

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
meta <- mm_no_chl[,1:4]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

spl_10a_10p <- subset(sp_loc, rownames(sp_loc) %in% sel2)

row.names(spl_10a_10p) <- c("P.n.s",
                            "Th.",
                            "P.o",
                            "Hill.",
                            "Tel.",
                            "S.m.",
                            "P.p.",
                            "Bid.",
                            "C.s.",
                            "C.c.",
                            "P.t.")
                            
```


```{r}
#Plotting RDS scaling 2

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = as.factor(month_surv),
                                   shape = site_id), 
             size = 4, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = spl_10a_10p, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.10,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.3, colour = "darkgrey") +
  geom_text_repel(data = spl_10a_10p, aes(RDA1, RDA2, 
                                           label = row.names(spl_10a_10p)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 2,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.93, 0.69),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

ggsave(here("figures_rev2", "rda_calvert_scaling2_2_het_2.png"),
        width = 6.2, height = 5, dpi = 300)
```





```{r}
#RDA scaling 1 - angles. selecting distinct species and plotting as arrows with 15% best fit

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(p_s1, env.data = env.signif)
meta <- mm_no_chl[,1:4]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(p_s1)
species_loc

axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

# sp_loc_short_10p <- subset(sp_loc, rownames(sp_loc) %in% sel)
# 
# spl_10a_10p <- subset(sp_loc, rownames(sp_loc) %in% sel2)
# 
# row.names(spl_10a_10p) <- c("P.n.s",
#                             "th.",
#                             "P.o",
#                             "Hill", 
#                             "Tel", 
#                             "C.t.", 
#                             "P.n",
#                             "S.m.",
#                             "P.p",
#                             "Bi.",
#                             "C.s",
#                             "C.c", 
#                             "Pt")


ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = as.factor(month_surv),
                                   shape = site_id), 
             size = 4, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = spl_10a_10p, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.10,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.3, colour = "darkgrey") +
  geom_text_repel(data = spl_10a_10p, aes(RDA1, RDA2, 
                                           label = row.names(spl_10a_10p)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 2,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  # segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.93, 0.69),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

ggsave(here("figures_rev2", "rda_calvert_scaling1_2_hetero_2.png.png"),
       width = 6.2, height = 5, dpi = 300)
```
```{r}
sites_loc_2 <- sites_loc %>% 
  mutate(year = lubridate::year(date))

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_2, aes(x = axis1, y = axis2, fill = as.factor(year),
                                   shape = site_id), 
             size = 4, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = spl_10a_10p, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.10,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.3, colour = "darkgrey") +
  geom_text_repel(data = spl_10a_10p, aes(RDA1, RDA2, 
                                           label = row.names(spl_10a_10p)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 2,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  # segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.93, 0.69),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Year", shape = "Station")

ggsave(here("figures_rev2", "rda_calvert_scaling1_2_year.png.png"),
       width = 6.2, height = 5, dpi = 300)
```

#Working with chemtax data

```{r}
#Prepping chemtax data for analysis

#Remove rows with NaNs
mm_chem <- mm_chem %>% 
  drop_na()

#Separating into response variables (CHEMTAX) and Explainatory variables (Environmental)
resp_chem <- mm_chem[, 17:24]

#Things to add TChla, WSDP, iso depth, FWC...
expl_chem <- mm_chem[, 7:16]

expl_chem <- expl_chem %>% 
  select(!N2_dm) %>% 
  select(!dep_26_dm)
```

```{r}
test <- mm_no_chl %>% 
  select(temp_dm:secchi_depth, dp = `Detonula pumila`)

test %>% 
  ggplot(aes(x = temp_dm, y = dp)) +
  geom_point()

t_cl <- cor.test(test$secchi_depth, test$dp,  method = "spearman")

t_cl

#Ceratium lineatum
#temp = 0.56***
#sal = 0.32*
#drho = -0.43**
#no2 = -0.36*
#secchi = 0.39**

#Chaetoceros decipiens
#temp = 0.29*
#sal = 0.28 ns
#drho = -0.44**
#no2 = -0.23 ns
#secchi = 0.21 ns


#Detonula pumila
#temp = 0.22 ns
#sal = 0.34*
#drho = -0.37**
#no2 = -0.23*
#secchi = 0.21 ns

```







