---
title: "R Notebook"
output: html_notebook
---

Here I run RDA analysis on the 2018-2020 Microscopy data and then the 2019-2020 Chemtax data. I do this in the same noptebook so I can combined the plots.

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)

#From https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html#1_Packages_needed

#For plotting with ggplot2

library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
```

```{r}
#Upload data

#All data merged to the CTD 
data <- read_csv(here("outputs", "ctd_merge_2022-03-16_het.csv")) 

#Just using calvert data
data <- data %>% 
  filter(!site_id == "QU39")

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Removing QU39
micro <- micro %>% 
  filter(!site_id == "QU39")

#Uploading the chl-HPLC timeseries that I created to eliminate data QC gaps.
tcha <- read_csv(here("outputs", "chl_hplc_merged.csv"))

riv <- read_csv(here("files", "river.csv")) 

riv_b <- read_csv(here("files", "riv_bella_4.csv"))

ethel_wind <- read_csv(here("files", "ethel_wind.csv"))

lk_wind <- read_csv(here("files", "wind_lookout.csv"))

lk_par <- read_csv(here("files", "lookout_par.csv"))

#Uploading size separated S.marinoi counts.
sm_size <- read_csv(here("outputs", "s_mar_size.csv"))
```


```{r}
# micro <- micro %>% 
#   filter(!scientificName == "Skeletonema marinoi")
# 
# micro <- rbind(micro, sm_size)
```

```{r}
#Removing species groups

#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria" &
           !group == "Metazoa" &
           !group == "Protozoa" &
           !group == "Choanoflagellata" &
           !group == "Ciliophora" &
           !group == "Kinetoplastidea")

#Isolating chemtax data from the explanatory variables sheet 
chem <- data %>% 
  select(date:secchi_depth, cyan:diat)
```


```{r}
#Determining total number of samples collected
sample_num <- micro %>%
  distinct(date, site_id)

#Filtering out species that were not present in at least 10% of the samples
species_10 <- micro %>%
  group_by(scientificName) %>%
  summarise(n_obs = n()) %>%
  ungroup() %>%
  mutate(perc_obs = n_obs/50) %>%
  filter(perc_obs >= 0.10)

#Creating a list of species that were not in 10% of the samples
species_10_list <- species_10$scientificName

#Removing species that were not in 10% of the samples.
micro <- micro %>%
  filter(scientificName %in% species_10_list)

```


```{r}
# micro <- micro %>%
#   filter(class == "Bacillariophyceae")
```


```{r}
#Pivoting data for RDA analysis

#Selecting columns for pivot
micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

#performing pivot and making NA's 0's. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))
```


```{r}
riv <- riv %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_w <- riv %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA),
         Wan_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Wan_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_w <- riv_w %>% 
  select(date, Wan_b1, Wan_b25, Wan_b40)
```

```{r}
ethel_wind2 <- ethel_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

ew_da <- ethel_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, eth_w = w_b1, eth_wd = wd_b1)

lk_wind2 <- lk_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

lk_da <- lk_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par <- lk_par %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par <- par %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA)) %>% 
  select(date, par_b1)
  
```

```{r}
data <- data %>% 
  left_join(riv_w) %>% 
  left_join(ew_da) %>% 
  left_join(lk_da) %>% 
  left_join(par)
```


```{r}
#Only taking the columns I want from the explanatory datasheet so I can join it with the microscopy data
data <- data %>% 
  select(date:site_id,
         temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth,
         Wan_b1, 
         eth_w, eth_wd, 
         lk_w, lk_wd,
         par_b1)

micro_join <- data %>% 
  left_join(micro_piv)

#removing NAs for analysis
micro_join <- micro_join %>% 
  drop_na()
```


```{r}
# micro_join <- micro_join %>% 
#   filter(no2 > 0 & po4 > 0 & sio2 > 0) 
```

```{r}
#Separating into response variables (microscopy counts) and Explanatory variables (Environmental)
resp <- micro_join[, 18:100]

# resp <- decostand(resp, method = "total")

#Explanatory variables
expl <- micro_join[, 5:17]

#I want to add nutrient ratios.
# expl <- expl %>% 
#   mutate(n_p = no2/po4,
#          si_n = sio2/po4)

#Removing NA's for analysis (currently only 1)
# expl[is.na(expl)] <- 0
# expl[expl == Inf] <- 0


#Trying to remove variables that have high VIFS. Removed no2 and po4 because they had the highest VIFS. I also think silicate is important because of fjords trends. Doesn't really matter as sio2 should be representative of the other nutrients anyways - when I cut sio2 out, no2 vector was comparable.
# expl <- expl %>% 
#   select(-po4, -no2)

```

```{r}
#Hellinger transformation on species data - particularly suited to species abundance data with large range and lots of zeros. Gives low weights to variables with low counts and many zeroes.
resp.hell <- decostand(resp, 'hell')

```

```{r}
#Microscopy

tbRDA.all <- rda(resp.hell ~ . , data = expl)

tbRDA.all

anova(tbRDA.all)

adjR2.tbrda <- RsquareAdj (tbRDA.all)$adj.r.squared

adjR2.tbrda
```

```{r}
#Assessing collinearity of variables - nutrients are highly related. Play with this.
vif.cca(tbRDA.all)
```

```{r}
constrained_eig <- tbRDA.all$CCA$eig/tbRDA.all$tot.chi*100
unconstrained_eig <- tbRDA.all$CA$eig/tbRDA.all$tot.chi*100
expl_var <- c(constrained_eig, unconstrained_eig)
barplot (expl_var[1:20], col = c(rep ('red', length (constrained_eig)), rep ('black', length (unconstrained_eig))),
         las = 2, ylab = '% variation')
```

```{r}
#Trying different approach for ordiR2step from https://www.davidzeleny.net/anadat-r/doku.php/en:forward_sel_examples - same result as my other test
tb_rda.vasc.0 <- rda (resp.hell ~ 1, data = expl)

tb_rda.vasc.all <- rda (resp.hell ~ ., data = expl)

sel.osR2 <- ordiR2step (tb_rda.vasc.0, scope = formula (tb_rda.vasc.all), 
                        R2scope = adjR2.tbrda, direction = 'forward', 
                        permutations = 9999)

sel.osR2$anova

sel.osR2_adj <- sel.osR2

sel.osR2_adj$anova$`Pr(>F)` <- p.adjust (sel.osR2$anova$`Pr(>F)`, 
                                         method = 'holm', n = ncol (expl))

sel.osR2_adj$anova

#secchi = 0.008
#sio2 = 0.008
#temp = 0.024
```

```{r}
#Select the statistically significant variables - May want to remove SiO2, see VIFS below!
env.signif <- subset(expl, select = c(temp, sio2, secchi, Wan_b1))

#RDA using significant variables
rda.signif <- rda(resp.hell ~ . ,data = env.signif)
rda.signif
rda.sign.sum <- summary(rda.signif)

rda.sign.sum

#Adjusted R2 for the 1 significant variables
#AdjR2 = 
(R2adj <- RsquareAdj(rda.signif)$adj.r.squared)

#ANOVA for testing significance of model and individual axes #Can do ANOVA by terms...
#Entire model = 0.001***
#RDA1 = 0.001***
#RDA2 = 0.001***

# ?anova.cca
anova.cca(rda.signif, step = 1000)
anova.cca(rda.signif, step = 1000, by = "axis")

#All significant - already shown in forward rda, but easier to see (Not corrected)
anova(rda.signif, by = "terms")

```

```{r}
#Rough plots using both scaling types - setting scaling-2 as a variable to allow for further plotting.

# Type 1 scaling
ordiplot(rda.signif, scaling = 1, type = "text")

# Type 2 scaling
plot_s2 <- ordiplot(rda.signif, scaling = 2, type = "text")

```

```{r}
#Testing species goodness of fit to try to eliminate species
# https://stackoverflow.com/questions/27823131/customising-vegan-ordination-plot


#This selects the species with the 10% best fitting
sel <- goeveg::ordiselect(resp, rda.signif, fitlim = 0.10)
sel

#Can also cut species out based on abundance
# sel2 <- goeveg::ordiselect(resp, rda.signif, ablim = 0.20, fitlim = 0.10)
# sel2

```
```{r}
#Changing site_id to location 
meta <- micro_join %>% 
  select(date:site_id) %>% 
  mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

meta <- meta %>% 
  mutate(year = lubridate::year(date))

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
meta <- arrange(mutate(meta,
                         location = factor(location, levels = order_loc)))
```



```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as arrows with 10% best fit

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

sp_bf <- subset(sp_loc, rownames(sp_loc) %in% sel)

row.names(sp_bf) <- c("C.deb.",
                      "C.rad",
                      "P.n.s.",
                      "Tha.",
                      "P.gro",
                      "Hil.",
                      "Tel.a.",
                      "Tel.",
                      "Bid.",
                      "S.mar.",
                      "C.cin.",
                      "C.soc.",
                      "Pte.",
                      "P.pou")



# row.names(spl_10a_10p) <- c("P.n.s",
#                             "Th.",
#                             "P.o",
#                             "Hill.",
#                             "Tel.",
#                             "S.m.",
#                             "P.p.",
#                             "Bid.",
#                             "C.s.",
#                             "C.c.",
#                             "P.t.")
                            
```


```{r}
#Plotting RDS scaling 2

micro_1 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2,
                                   fill = as.factor(month_surv),
                                   shape = location), 
             size = 8, color = "black", stroke = 1.5) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 1.4, colour = "Red", alpha = 0.7) +
  geom_segment(data = sp_bf, aes(x = 0, y = 0, xend = RDA1*2,
                                       yend = RDA2*2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 1.4, colour = "grey", alpha = 0.7) +
  geom_text_repel(data = sp_bf, aes(RDA1*2, RDA2*2, 
                                           label = row.names(sp_bf)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 8) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                 # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  # segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = - 0.05,
                  force = 4,
                  max.iter = 3e3,
                  size = 10,
                  color = "red") +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 1),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 1),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.14, 0.29),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour= "black", face = "bold"),
        axis.line = element_line(colour = "black"), 
        plot.title = element_text(hjust = 0.5, face = "bold"),
        text = element_text(size = 28)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

micro_2 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2,
                                   fill = as.factor(year),
                                   shape = location), 
             size = 8, color = "black", stroke = 1.5) +
  scale_fill_brewer(palette = "Dark2") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 1.4, colour = "Red", alpha = 0.7) +
  geom_segment(data = sp_bf, aes(x = 0, y = 0, xend = RDA1*2,
                                       yend = RDA2*2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 1.4, colour = "grey", alpha = 0.7) +
  geom_text_repel(data = sp_bf, aes(RDA1*2, RDA2*2, 
                                           label = row.names(sp_bf)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 8) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                 # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  # segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = - 0.05,
                  force = 4,
                  max.iter = 3e3,
                  size = 10,
                  color = "red") +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 1),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 1),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.14, 0.22),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour= "black", face = "bold"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(colour = "black"), 
        plot.title = element_text(hjust = 0.5, face = "bold"),
        text = element_text(size = 28)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Year") +
  guides(shape = F)

micro_comb <- micro_1 + micro_2

ggsave(here("figures_good", "rda_scale-micro_comb_riv_wind2.png"), micro_comb,
        width = 16, height = 8, dpi = 300)
```

#Working with chemtax data

```{r}
#Only taking the columns I want from the explanatory datasheet so I can join it with the microscopy data
data <- data %>% 
  select(date:site_id,
         temp,
         sal,
         drho,
         no2,
         sio2,
         po4,
         secchi,
         tchla)

micro_join <- data %>% 
  left_join(micro_piv)

#removing NAs for analysis
micro_join <- micro_join %>% 
  drop_na()
```


```{r}
#Separating into response variables (microscopy counts) and Explanatory variables (Environmental)
resp <- micro_join[, 13:95]

#Explanatory variables
expl <- micro_join[, 5:12]

#I want to add nutrient ratios.
expl <- expl %>% 
  mutate(n_p = no2/po4,
         si_n = sio2/po4)

#Removing NA's for analysis (currently only 1)
expl[is.na(expl)] <- 0
expl[expl == Inf] <- 0


#Trying to remove variables that have high VIFS. Removed no2 and po4 because they had the highest VIFS. I also think silicate is important because of fjords trends. Doesn't really matter as sio2 should be representative of the other nutrients anyways - when I cut sio2 out, no2 vector was comparable.
expl <- expl %>% 
  select(-po4, -no2)

```

```{r}
#Prepping chemtax data for analysis

#Remove rows with NaNs - mostly 2018 data
chem <- chem %>% 
  drop_na()

#Separating into response variables (CHEMTAX) and Explainatory variables (Environmental)
resp_chem <- chem[, 18:26]

#Things to add TChla, WSDP, iso depth, FWC...
expl_chem <- chem[, 7:17]

expl_chem <- expl_chem %>% 
  select(temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth)

#I want to add nutrient ratios.
expl_chem <- expl_chem %>% 
  mutate(n_p = no2/po4,
         si_n = sio2/po4)

#Trying to remove variables that have high VIFS. Removed no2 and po4 because they had the highest VIFS. I also think silicate is important because of fjords trends. Doesn't really matter as sio2 should be representative of the other nutrients anyways - when I cut sio2 out, no2 vector was comparable.
expl_chem <- expl_chem %>% 
  select(-po4, -no2)
```

```{r}
#Hellinger transformation on species data - particularly suited to species abundance data with large range and lots of zeros. Gives low weights to variables with low counts and many zeroes.
resp.hell_chem <- decostand(resp_chem, 'hell')

```

```{r}
tbRDA.all_chem <- rda(resp.hell_chem ~ . , data = expl_chem)

tbRDA.all_chem

anova(tbRDA.all_chem)

adjR2.tbrda_chem <- RsquareAdj (tbRDA.all_chem)$adj.r.squared

adjR2.tbrda_chem

```

```{r}
constrained_eig_chem <- tbRDA.all_chem$CCA$eig/tbRDA.all_chem$tot.chi*100
unconstrained_eig_chem <- tbRDA.all_chem$CA$eig/tbRDA.all_chem$tot.chi*100
expl_var_chem <- c(constrained_eig_chem, unconstrained_eig_chem)
barplot(expl_var_chem[1:20], col = c(rep ('red', length (constrained_eig_chem)),
                                     rep ('black', length (unconstrained_eig_chem))),
         las = 2, ylab = '% variation')
```


```{r}
#Trying different approach for ordiR2step from https://www.davidzeleny.net/anadat-r/doku.php/en:forward_sel_examples - same result as my other test
tb_rda.vasc.0_chem <- rda (resp.hell_chem ~ 1, data = expl_chem)

tb_rda.vasc.all_chem <- rda (resp.hell_chem ~ ., data = expl_chem)

sel.osR2_chem <- ordiR2step (tb_rda.vasc.0_chem, 
                             scope = formula (tb_rda.vasc.all_chem), 
                        R2scope = adjR2.tbrda_chem, direction = 'forward', 
                        permutations = 9999)

sel.osR2_chem$anova

sel.osR2_adj_chem <- sel.osR2_chem

sel.osR2_adj_chem$anova$`Pr(>F)` <- p.adjust (sel.osR2_chem$anova$`Pr(>F)`, 
                                         method = 'holm', n = ncol (expl_chem))

sel.osR2_adj_chem$anova


```

```{r}
#Select the statistically significant variables - May want to remove SiO2, see VIFS below!
env.signif_chem <- subset(expl_chem, select = c(secchi, sio2, temp))

#RDA using significant variables
rda.signif_chem <- rda(resp.hell_chem ~ . ,data = env.signif_chem)
rda.signif_chem
rda.sign.sum_chem <- summary(rda.signif_chem)

rda.sign.sum_chem
#Total = 41.46%
#Constrained = 37.5%
#RDA1 = 27.43%
#RDA2 = 6.1%

#Adjusted R2 for the 1 significant variables
#AdjR2 = 0.319
(R2adj_chem <- RsquareAdj(rda.signif_chem)$adj.r.squared)

#ANOVA for testing significance of model and individual axes #Can do ANOVA by terms...
#Entire model = 0.001***
#RDA1 = 0.001***
#RDA2 = 0.001***

# ?anova.cca
anova.cca(rda.signif_chem, step = 1000)
anova.cca(rda.signif_chem, step = 1000, by = "axis")

#All significant - already shown in forward rda, but easier to see (Not corrected)
anova(rda.signif_chem, by = "terms")

```
```{r}
#Rough plots using both scaling types - setting scaling-2 as a variable to allow for further plotting.

# Type 1 scaling
ordiplot(rda.signif_chem, scaling = 1, type = "text")

# Type 2 scaling
plot_s2_chem <- ordiplot(rda.signif_chem, scaling = 2, type = "text")

```

```{r}
#Changing site_id to location 
meta_chem <- chem %>% 
  select(date:site_id) %>% 
  mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

meta_chem <- meta_chem %>% 
  mutate(year = lubridate::year(date))

#Chemtax - Specify order of phyto groups for figures
meta_chem <- arrange(mutate(meta_chem,
                         location = factor(location, levels = order_loc)))
```



```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as arrows with 10% best fit

#Extracting site locations
sites_loc_chem <- sites.long(plot_s2_chem, env.data = env.signif_chem)
sites_loc_chem <- cbind(meta_chem, sites_loc_chem)
head(sites_loc_chem)

#Species location in ordination
species_loc_chem <- species.long(plot_s2_chem)
species_loc_chem

axis.long_chem <- axis.long(rda.signif_chem, choices = c(1, 2))
axis.long_chem

env_loc_chem <-  as.data.frame(rda.sign.sum_chem$biplot[,1:2])

sp_loc_chem <-  as.data.frame(rda.sign.sum_chem$species[,1:2])

                       
```


```{r}
#Plotting RDS scaling 2

chem_1 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_chem, aes(x = axis1, y = axis2,
                                   fill = as.factor(month_surv),
                                   shape = location), 
             size = 8, color = "black", stroke = 1.5) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  geom_segment(data = env_loc_chem, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 1.4, alpha = 0.7, colour = "Red") +
  geom_segment(data = sp_loc_chem, aes(x = 0, y = 0, xend = RDA1,
                                       yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 1.4, alpha = 0.7, colour = "grey") +
  geom_text_repel(data = sp_loc_chem, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_chem)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 8) +
  geom_text_repel(data = env_loc_chem , aes(RDA1, RDA2,
                                            label = row.names(env_loc_chem)),
                 # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  # segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = - 0.05,
                  force = 4,
                  max.iter = 3e3,
                  size = 10,
                  color = "red") +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum_chem$cont[[1]][2,1], digits = 1),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum_chem$cont[[1]][2,2], digits = 1),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = "none",
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour= "black", face = "bold"),
        axis.line = element_line(colour = "black"), 
        plot.title = element_text(hjust = 0.5, face = "bold"),
        text = element_text(size = 28)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

chem_2 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_chem, aes(x = axis1, y = axis2,
                                   fill = as.factor(year),
                                   shape = location), 
             size = 8, color = "black", stroke = 1.5) +
  scale_fill_manual(values = c("#D95F02", "#7570B3")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  geom_segment(data = env_loc_chem, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 1.4, colour = "Red", alpha = 0.7) +
  geom_segment(data = sp_loc_chem, aes(x = 0, y = 0, xend = RDA1,
                                       yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 1.4, colour = "grey", alpha = 0.7) +
  geom_text_repel(data = sp_loc_chem, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_chem)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 3,
                  max.iter = 3e3,
                  size = 8) +
  geom_text_repel(data = env_loc_chem , aes(RDA1, RDA2, label = row.names(env_loc_chem)),
                 # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  # segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = - 0.05,
                  force = 3,
                  max.iter = 3e3,
                  size = 10,
                  color = "red") +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum_chem$cont[[1]][2,1], digits = 1),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum_chem$cont[[1]][2,2], digits = 1),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = "none",
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour= "black", face = "bold"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line = element_line(colour = "black"), 
        plot.title = element_text(hjust = 0.5, face = "bold"),
        text = element_text(size = 28)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Year", shape = "Station")

chem_comb <- chem_1 + chem_2

ggsave(here("figures_good", "rda_scale-chem_comb.png"), chem_comb,
        width = 16, height = 8, dpi = 300)
```





```{r}
#Combining Microscopy and chemtax RDAs

# micro_chem_panel <-  p_s1_micro + p_s1_chem2
# 
# ggsave(here("figures_rev2", "rda_micro_chem_s1_test.png"), micro_chem_panel, 
#        width = 16, height = 8, dpi = 300)
```






