---
title: "R Notebook"
output: html_notebook
---

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(zoo)
```

```{r}
#Upload data

micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv"))

ctd <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

env <- read_csv(here("outputs", "enviro_2023-05-26_up.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

clust <- read_csv(here("outputs", "final_cluster_2023-07-31.csv"))

chem <- read_csv(here("files", "chemtax_2023-04-14.csv"))

sf <- read_csv(here("files", "chl_2018_2020.csv"))
```

```{r}
#Here, only including 2019-2020
chem <- chem %>% 
  filter(date < "2021-01-01")
```


```{r}
#Removing species groups

#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")
```

```{r}
#Determining total number of samples collected
sample_num <- micro %>%
  distinct(date, site_id)

#Filtering out species that were not present in at least 10% of the samples
species_10 <- micro %>%
  group_by(scientificName) %>%
  summarise(n_obs = n()) %>%
  ungroup() %>%
  mutate(perc_obs = n_obs/78) %>%
  filter(perc_obs >= 0.10)

#Creating a list of species that were not in 10% of the samples
species_10_list <- species_10$scientificName

#Removing species that were not in 10% of the samples.
micro <- micro %>%
  filter(scientificName %in% species_10_list)

```

```{r}
#Filtering to only include diatoms
micro_d <- micro %>%
  filter(group == "Bacillariophyta")
```

```{r}
#Pivoting data for RDA analysis

#Selecting columns for pivot
micro_piv <- micro %>%
  mutate(month = lubridate::month(date)) %>% 
  select(date, month, site_id, scientificName, species_sum)

micro_piv_d <- micro_d %>%
  mutate(month = lubridate::month(date)) %>% 
  select(date, month, site_id, scientificName, species_sum)

#performing pivot and making NA's 0's. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum,
              values_fill = 0) 

micro_piv_d <- micro_piv_d %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum,
              values_fill = 0)

micro_piv <- micro_piv %>% 
  select(!month)

micro_piv_d <- micro_piv_d %>% 
  select(!month)
```

```{r}
#Selecting columns from the CTD master sheet
ctd <- ctd %>% 
  select(date, site_id, temp_dm, sal_dm, delta_rho_dm, no2_dm:secchi_depth, dep_26_dm, turb_dm)
```

```{r}
data <- ctd %>% 
  left_join(env) %>% 
  left_join(chl)
```


```{r}
#Selecting and renaming the columns that I want
data <- data %>% 
  select(date:site_id,
         temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth,
         wan_b1, 
         sm_b1,
         gm_b1,
         ra_b1,
         wind_b1,
         wind_dir_b1,
         par_b1,
         UI = up_b1,
         p1026 = dep_26_dm,
         tchla)

micro_join <- data %>%
  left_join(micro_piv)

micro_join_d <- data %>%
  left_join(micro_piv_d)

#removing NAs for analysis
micro_join <- micro_join %>% 
  drop_na()

micro_join_d <- micro_join_d %>% 
  drop_na()
```
```{r}
#Separating into response variables (microscopy counts) and Explanatory variables (Environmental)
resp <- micro_join[, 20:ncol(micro_join)]

resp_d <- micro_join_d[, 20:ncol(micro_join_d)]

#Explanatory variables
expl <- micro_join[, 3:18]

#Trying to remove variables that have high VIFS. Removed no2 and po4 because they had the highest VIFS. I also think silicate is important because of fjords trends. Doesn't really matter as sio2 should be representative of the other nutrients anyways - when I cut sio2 out, no2 vector was comparable. 
expl <- expl %>%
  select(-po4, -no2, -wan_b1)
```

```{r}
#Hellinger transformation on species data - particularly suited to species abundance data with large range and lots of zeros. Gives low weights to variables with low counts and many zeroes.
resp.hell <- decostand(resp, 'hell')

resp.hell_d <- decostand(resp_d, 'hell')
```

















