---
title: "R Notebook"
output: html_notebook
---

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(zoo)
```

```{r}
#Upload data

sf <- read_csv(here("files", "chl_2018_2020.csv")) 

ctd <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

env <- read_csv(here("outputs", "enviro_2023-05-26_up.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

```

```{r}

sf_less <- sf %>% 
  filter(line_out_depth == 5 & !filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | is.na(chla_flag)) %>%
  mutate(year = lubridate::year(date)) %>% 
  select(date, site_id, filter_type, chla) %>% 
  filter(!is.na(chla)) %>% 
  group_by(date) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3) %>%
  select(-n_filt)

sf_wide <- sf_less %>% 
  pivot_wider(names_from = filter_type, values_from = chla)
```

```{r}
#Selecting columns from the CTD master sheet
ctd <- ctd %>% 
  select(date:secchi_depth)
```

```{r}
data <- ctd %>% 
  left_join(env) %>% 
  left_join(chl) %>%
  left_join(sf_wide)
```


```{r}
#Selecting and renaming the columns that I want
data <- data %>% 
  select(date:site_id,
         temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth,
         wan_b1, 
         sm_b1,
         gm_b1,
         ra_b1,
         wind_b1,
         wind_dir_b1,
         par_b1,
         up_b1,
         dep_26_dm,
         micro = `20um`,
         nano = `3um`,
         pico = `GF/F`)

#Adding location instead of site ID for interpretation of results
data <- data %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

#removing NAs for analysis
data_na <- data %>% 
  drop_na()
```


```{r}
# data_na <- data_na %>% 
#   mutate(np = no2/po4) %>% 
#   relocate(np, .after = sio2)
```



```{r}
#Separating into response variables (chemtax) and Explanatory variables (Environmental)
resp <- data_na[, 20:ncol(data_na)]
# resp <- scale(resp, center = F, scale = T)

#Explanatory variables
expl <- data_na[, 4:19]

#Trying to remove variables that have high VIFS. Removed no2 and po4 because they had the highest VIFS. I also think silicate is important because of fjords trends. Doesn't really matter as sio2 should be representative of the other nutrients anyways - when I cut sio2 out, no2 vector was comparable. 
expl <- expl %>%
  select(-no2, -po4)


```

```{r}
#Hellinger transformation on species data - particularly suited to species abundance data with large range and lots of zeros. Gives low weights to variables with low counts and many zeroes.
# resp.hell <- decostand(resp, 'hellinger')

resp.hell <- resp
# resp.hell <- sqrt(resp)

decorana (resp.hell)
```

```{r}
#Microscopy

tbRDA.all <- rda(resp.hell ~ . , data = expl, scale = T)

tbRDA.all

anova(tbRDA.all)

adjR2.tbrda <- RsquareAdj (tbRDA.all)$adj.r.squared

adjR2.tbrda
```

```{r}
#Assessing collinearity of variables - nutrients are highly related. Play with this.
vif.cca(tbRDA.all)
```

```{r}
constrained_eig <- tbRDA.all$CCA$eig/tbRDA.all$tot.chi*100
unconstrained_eig <- tbRDA.all$CA$eig/tbRDA.all$tot.chi*100
expl_var <- c(constrained_eig, unconstrained_eig)
barplot (expl_var[1:20], col = c(rep ('red', length (constrained_eig)), rep ('black', length (unconstrained_eig))),
         las = 2, ylab = '% variation')
```

```{r}
#Trying different approach for ordiR2step from https://www.davidzeleny.net/anadat-r/doku.php/en:forward_sel_examples - same result as my other test
tb_rda.vasc.0 <- rda (resp.hell ~ 1, data = expl)

tb_rda.vasc.all <- rda (resp.hell ~ ., data = expl)

sel.osR2 <- ordiR2step (tb_rda.vasc.0, scope = formula (tb_rda.vasc.all), 
                        R2scope = adjR2.tbrda, direction = 'forward', 
                        permutations = 49999)

sel.osR2$anova

sel.osR2_adj <- sel.osR2

sel.osR2_adj$anova$`Pr(>F)` <- p.adjust (sel.osR2$anova$`Pr(>F)`, 
                                         method = 'holm', n = ncol (expl))

sel.osR2_adj$anova

```


```{r}
#Select the statistically significant variables - May want to remove SiO2, see VIFS below!
env.signif <- subset(expl, select = c(sio2, temp, secchi))

#RDA using significant variables
rda.signif <- rda(resp.hell ~ . ,data = env.signif)
rda.signif
rda.sign.sum <- summary(rda.signif)

rda.sign.sum

#Adjusted R2 for the 1 significant variables
#AdjR2 = 
(R2adj <- RsquareAdj(rda.signif)$adj.r.squared)

#ANOVA for testing significance of model and individual axes #Can do ANOVA by terms...
#Entire model = 0.001***
#RDA1 = 0.001***
#RDA2 = 0.001***

# ?anova.cca
anova.cca(rda.signif, step = 1000)
anova.cca(rda.signif, step = 1000, by = "axis")

#All significant - already shown in forward rda, but easier to see (Not corrected)
anova(rda.signif, by = "terms")

```

```{r}
#Rough plots using both scaling types - setting scaling-2 as a variable to allow for further plotting.

# Type 1 scaling
plot_s1 <- ordiplot(rda.signif, scaling = 1, type = "text")

# Type 2 scaling
plot_s2 <- ordiplot(rda.signif, scaling = 2, type = "text")

```



```{r}
#Changing site_id to location 
meta <- data_na %>% 
  select(date:location) %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date))

meta <- meta %>%
  mutate(season = case_when(month == 12 | month == 1 | month == 2 ~ "winter",
                            month >= 3 & month <= 5 ~ "spring",
                            month >= 6 & month <= 8 ~ "summer",
                            month >= 9 & month <= 12 ~ "autumn",)) %>%
  relocate(season, .after = month)    
  
#I want to push December from each year to winter of the next year
meta <- meta %>%
  mutate(year = lubridate::year(date)) %>%  
  mutate(year = case_when(season == "winter" & month == 12 ~ year+1,
                           TRUE ~ as.numeric(year)))

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
meta <- arrange(mutate(meta,
                         location = factor(location, levels = order_loc)))

#Order locations from fjord to shelf
order_loc_seas <- c("winter", "spring", "summer", "autumn")

#Chemtax - Specify order of phyto groups for figures
meta <- arrange(mutate(meta,
                         season = factor(season, levels = order_loc_seas)))
```



```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as arrows with 10% best fit

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

```


```{r}
#Plotting RDS scaling 2

# row.names(env_loc) <- c("Δρ",
#                         "SiO\u2082\u207B",
#                         "T",
#                         "GM")

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2,
                                   fill = as.factor(year),
                                   shape = location), 
             size = 10, color = "darkgray", stroke = 2, alpha = 0.9) +
  scale_fill_npg() +
  scale_shape_manual(values = c(21, 22, 23 ,24)) +
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1,
                                   yend = RDA2),
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 1.4, colour = "Red", alpha = 1) +
  geom_segment(data = sp_loc, aes(x = 0, y = 0, xend = RDA1,
                                       yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 1.4, colour = "black", alpha = 1) +
  geom_text_repel(data = sp_loc, aes(RDA1, RDA2,
                                           label = row.names(sp_loc)),
                  point.padding = unit(2, 'lines'),
                  segment.color = 'black',
                  segment.size = 0.7,
                  segment.alpha = 1,
                  nudge_y = 0.05,
                  force = 5,
                  max.iter = 3e3,
                  size = 5) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, 
                                       label = row.names(env_loc)),
                  point.padding = unit(2, 'lines'),
                  nudge_y = - 0.05,
                  force = 4,
                  max.iter = 3e3,
                  size = 10,
                  color = "Red") +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 1),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 1),
               "%)", sep = "")) +
 
  theme_bw() +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour= "black", face = "bold"),
        axis.line = element_line(colour = "black"), 
        plot.title = element_text(hjust = 0.5, face = "bold"),
        text = element_text(size = 28)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Year", shape = "Station")

ggsave(here("figures_rda", "rda_2023-06-23_CHEMTAX_relative_sqrt.png"),
        width = 8, height = 6, dpi = 300)
```








