---
title: "R Notebook"
output: html_notebook
---

Here I run RDA analysis on the 2018-2020 Microscopy data and then the 2019-2020 Chemtax data. I do this in the same notebook so I can combined the plots.

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(zoo)
```

```{r}
#Upload data

micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv"))

ctd <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

nuts <- read_csv(here("files", "kc10_nuts.csv"))

riv <- read_csv(here("files", "river.csv")) 

riv_b <- read_csv(here("files", "riv_bella_4.csv"))

ethel_wind <- read_csv(here("files", "ethel_wind.csv"))

lk_wind <- read_csv(here("files", "wind_lookout.csv"))

lk_par <- read_csv(here("files", "lookout_par.csv"))

ws844 <- read_csv(here("files", "ws844.csv"))

up <- read_csv(here("files", "upwell.csv"))

div <- read_csv(here("outputs", "diversity.csv"))

clust_bio <- read_csv(here("outputs", "bio_clust_full.csv"))

clust_phys <- read_csv(here("outputs", "pca_clusters_2023-04-18.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-08-04.csv"))

chem <- read_csv(here("files", "chemtax_2023-04-14.csv")) 

bb <- read_csv(here("files", "Daily_flow_2018_2020_v2023_04_27.csv"))
```



```{r}
#Removing species groups

#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")

```

```{r}
#Determining total number of samples collected
sample_num <- micro %>%
  distinct(date, site_id)

#Filtering out species that were not present in at least 10% of the samples
species_10 <- micro %>%
  group_by(scientificName) %>%
  summarise(n_obs = n()) %>%
  ungroup() %>%
  mutate(perc_obs = n_obs/78) %>%
  filter(perc_obs >= 0.10)

#Creating a list of species that were not in 10% of the samples
species_10_list <- species_10$scientificName

#Removing species that were not in 10% of the samples.
micro <- micro %>%
  filter(scientificName %in% species_10_list)

```

```{r}
micro <- micro %>%
  filter(group == "Bacillariophyta")
```

```{r}
rich <- micro %>% 
  group_by(date, site_id) %>% 
  summarise(rich = n()) %>% 
  ungroup()
```



```{r}
riv <- riv %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_w <- riv %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA),
         Wan_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Wan_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_w <- riv_w %>% 
  select(date, Wan_b1, Wan_b25, Wan_b40)
```

```{r}
riv_b <- riv_b %>% 
  mutate(Date = lubridate::mdy(Date))

riv_b <- riv_b %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_b <- riv_b %>%
  mutate(Bel_b1 = rollmeanr(lag(dis, 1), k = 5, fill = NA),
         Bel_b5 = rollmeanr(lag(dis, 5), k = 4, fill = NA),
         Bel_b10 = rollmeanr(lag(dis, 10), k = 4, fill = NA),
         Bel_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Bel_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_b <- riv_b %>% 
  select(date, Bel_b1, Bel_b5, Bel_b10, Bel_b25, Bel_b40)
```

```{r}
ethel_wind2 <- ethel_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

ew_da <- ethel_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, eth_w = w_b1, eth_wd = wd_b1)

lk_wind2 <- lk_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

lk_da <- lk_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par <- lk_par %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par <- par %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA)) %>% 
  select(date, par_b1)
  
```

```{r}
ws844_2 <- ws844 %>%
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, lev = PLS_Lvl_Avg, rain = `24hourRain`) %>% 
  filter(year > 2017 & year < 2022)

ws844_2 <- ws844_2 %>%
  mutate(lev_b1 = rollmeanr(lag(lev, 1), k = 10, fill = NA),
         rain_b1 = rollmeanr(lag(rain, 1), k = 10, fill = NA))

#So this is offsetting the the rolling average to one day before
ws844_2 <- ws844_2 %>% 
  select(date, lev, rain, lev_b1, rain_b1)
```

```{r}
up_dm <- up %>% 
  select(date = time, upwelling_index) %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_up = mean(upwelling_index)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(up_b1 = rollmeanr(lag(dm_up, 1), k = 3, fill = NA)) %>% 
  select(date, up_b1)
```
```{r}
bb_avg <- bb %>%
  mutate(QT_b1 = rollmeanr(lag(Q_Total, 1), k = 10, fill = NA),
         QGM_b1 = rollmeanr(lag(Q_GM, 1), k = 10, fill = NA),
         QSM_b1 = rollmeanr(lag(Q_SM, 1), k = 10, fill = NA),
         QRA_b1 = rollmeanr(lag(Q_RA, 1), k = 10, fill = NA))

#So this is offsetting the the rolling average to one day before
bb_dg <- bb_avg %>% 
  select(date = Date, QT_b1:QRA_b1)
```

```{r}
data <- ctd %>% 
  left_join(riv_w) %>% 
  left_join(bb_dg) %>%
  left_join(ew_da) %>% 
  left_join(lk_da) %>% 
  left_join(par) %>%
  left_join(ws844_2) %>% 
  left_join(up_dm) %>% 
  left_join(div) %>% 
  left_join(chl)
```

```{r}
#Only taking the columns I want from the explanatory datasheet so I can join it with the microscopy data
data <- data %>% 
  select(date:site_id,
         # cluster,
         div,
         temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         # fwc = fwc_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth,
         Wan_b1,
         QT_b1,
         QGM_b1,
         QSM_b1,
         QRA_b1,
         # eth_w, eth_wd, 
         lk_w, lk_wd,
         par_b1,
         up_b1,
         tchla)

rich_join <- data %>%
  left_join(rich)
```

```{r}
rich_join %>%
  mutate(month = lubridate::month(date)) %>%  
  ggplot(aes(x = temp, y = rich, color =site_id)) +
  geom_point(size = 5) +
  geom_smooth(method = "lm")
```

```{r}
rich_join %>% 
  ggplot(aes(x = date, y = rich, color = site_id)) +
  geom_line(size = 2) +
  geom_point()
```







