---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggpubr)
library(broom)

```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Uploading chl data that has been converted to TChla
chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

```

```{r}
#Remove QU39
micro <- micro %>% 
  filter(!site_id == "QU39")

micro <- micro %>% 
  filter(!scientificName == "Cyanobacteria")


```

```{r}
#Add year column
micro <- micro %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)


test <- micro %>% 
  filter(site_id == "QCS01") %>% 
  distinct(date)


micro <- micro %>%  
  mutate(month_surv = lubridate::month(date),
         month_surv = case_when(date == "2019-08-29" ~ 9,
                                date == "2019-08-31" ~ 9,
                                date == "2019-11-27" ~ 12,
                             TRUE ~ as.numeric (month_surv)))
```

```{r}
# Changing site_id to location 
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

chl <- chl %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```

```{r}
micro_all <- micro 

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_all <- arrange(mutate(micro_all,
                         location = factor(location, levels = order_loc)))


micro_all <- micro_all %>% 
  filter(trophicStatus == "auto")
#I want to look at species that never contribute to more than a certain percentage to the total biomass
```


```{r}
test2 <- micro_all %>% 
  filter(is.na(genus)) %>% 
  distinct(scientificName, .keep_all = T)
```

```{r}
micro_all_1 <- micro_all %>%
  group_by(date, location, genus) %>%
  mutate(genus_sum = sum(count)) %>%
  ungroup() %>%
  distinct(date, site_id, genus, genus_sum, .keep_all = T)


micro_all_2 <- micro_all_1 %>% 
  group_by(date, site_id) %>% 
  mutate(genus_all_sum = sum(genus_sum)) %>% 
  ungroup() %>% 
  mutate(perc = genus_sum/genus_all_sum)

micro_all_3 <- micro_all_2 %>%
  group_by(genus) %>%
  mutate(max = max(perc)) %>%
  ungroup()

test3 <- micro_all_3 %>% 
  filter(max < 0.25) %>% 
  distinct(genus, class, .keep_all = TRUE)

test4 <- micro_all_3 %>% 
  filter(max > 0.25) %>% 
  distinct(genus, class, .keep_all = TRUE)
```

```{r}
#Make a total diatom sum column for each date and then divide each species count by the total to derive a relative contribution
# micro_all <- micro_all %>% 
#   group_by(date, location) %>% 
#   mutate(sum_count = sum(species_sum)) %>% 
#   ungroup() %>% 
#   mutate(perc = species_sum/sum_count)

#Make a column showing the max contribution for each species
# micro_all <- micro_all %>% 
#   group_by(scientificName) %>% 
#   mutate(max = max(perc),
#          max_abund = max(species_sum)) %>% 
#   ungroup()
```

```{r}

micro_all_4 <- micro_all_3 %>% 
  mutate(genus = case_when(order == "Biddulphiales" ~ "Biddulphiales",
                           class == "Dinophyceae" ~ "Dinophyceae",
                              TRUE ~ as.character(genus))) 
```




```{r}
micro_all_gt10_perc <- micro_all_4 %>% 
  mutate(genus2 = ifelse(max < 0.40 & group == "Bacillariophyta",
                                  "Other diatom", genus)) %>% 
  mutate(genus2 = ifelse(max < 0.40 & !group == "Bacillariophyta",
                                  "Other flagellate", genus2))
```

```{r}
test6 <- micro_all_gt10_perc %>% 
  filter(max > 0.25) %>% 
  distinct(genus, class, .keep_all = TRUE)
```


```{r}
micro_all_gt10_perc2 <- micro_all_gt10_perc %>% 
  group_by(date, month_surv, location, genus2) %>% 
  summarise(species_sum = sum(species_sum)) %>% 
  ungroup()
```
```{r}
micro_all_c <- micro_all_gt10_perc2  

colourCount_c = length(unique(micro_all_c$genus2))
getPalette_c = colorRampPalette(brewer.pal(12, "Paired"))
```


```{r}
spec_dist <- micro_all_c %>% 
  distinct(genus2)

#25%
spec_ord <- c("Chaetoceros",
              "Pseudo-nitzschia",
              "Rhizosolenia",
              "Skeletonema",
              "Thalassiosira",
              "Olisthodiscus",
              "Hillea",
              "Teleaulax",
              "Phaeocystis",
              "Other diatom",
              "Other flagellate",
              "NA")
              
              
  
  
  


#20%
# spec_ord <- c("Biddulphiales",
#               "Chaetoceros cinctus",
#               "Chaetoceros tenuissimus",
#               "Pseudo-nitzschia seriata",
#               "Rhizosolenia setigera",
#               "Skeletonema marinoi small",
#               "Skeletonema marinoi large",
#               "Olisthodiscus",
#               "Hillea",
#               "Teleaulax",
#               "Phaeocystis pouchetii",
#               "Pyramimonas orientalis",
#               "Other")

#10%
# spec_ord <- c("Biddulphiales",
#               "Chaetoceros cinctus",
#               "Chaetoceros tenuissimus",
#               "Pseudo-nitzschia",
#               
#               "Rhizosolenia setigera",
#               "Skeletonema marinoi large",
#               "Skeletonema marinoi small",
#               "Thalassiosira nordenskioeldii",
#               "Thalassiosira pacifica",
#               "Olisthodiscus",
#               "Hillea",
#               "Teleaulax",
#               "Pterosperma",
#               "Pyramimonas orientalis",
#               "Phaeocystis pouchetii")

micro_all_c <- arrange(mutate(micro_all_c,
                         genus2 = factor(genus2,
                                                 levels = spec_ord)))
```

```{r}
micro_all_chl <- micro_all_c %>% 
  left_join(chl)

micro_all_chl <- arrange(mutate(micro_all_chl,
                         location = factor(location, levels = order_loc)))
```


```{r}
coeff <- 2

micro_all_chl %>%   
  mutate(year = lubridate::year(date)) %>% 
  ggplot() + 
  geom_bar(aes(x = as.factor(month_surv), y = species_sum/100000, 
           fill = genus2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = getPalette_c(colourCount_c)) +
  geom_line(aes(x = month_surv, y = tchla*coeff), size = 1.5) +
  geom_point(aes(x = month_surv, y = tchla*coeff, 
                 color = ifelse(tchla < 5, "Fail", "Pass")), size = 2.5, pch = 21,
             stroke = 2, fill = "black") +
  scale_y_continuous(name = "Phyto. Abundance (10^5 cells L)",
                     sec.axis = sec_axis(~ . /coeff, name = "TChla")) +
  scale_color_manual(values = c("black", "green"))+
  facet_grid(location ~ year) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(ncol = 4),
         color = "none")

ggsave(here("figures_species_timeseries", "test.png"),
       width = 16, height = 10, dpi = 300)
```






