---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)

```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Uploading chl data that has been converted to TChla
chl <- read_csv(here("outputs", "chl_hplc_merged.csv"))

#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))

#Uploading size separated S.marinoi counts.
sm_size <- read_csv(here("outputs", "s_mar_size.csv"))

fec <- read_csv(here("outputs", "fecal_master_2022-03-16_het.csv"))

#Upload microscopy data merged with physical and biogeochemical measures
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv")) 


c <- read_csv(here("outputs", "chemtax_master_2022-03-16_het.csv"))

wind <- read_csv(here("files", "wind.csv"), skip = 3)
```

```{r}
#Remove QU39
micro <- micro %>% 
  filter(!site_id == "QU39")

#Remove QU39
data <- data %>% 
  filter(!site_id == "QU39")

data <- data %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))

env <- data %>% 
  mutate(year = lubridate::year(date)) %>% 
  select(location, date, month, month_surv, year, t = temp_dm, s = sal_dm,
         dr = delta_rho_dm, no2 = no2_dm, po4 = po4_dm, sio2 = sio2_dm,
         secchi = secchi_depth)
```

```{r}

#Careful here - removing original s.marinoi counts and replacing with size separated counts. Ensure that the outputs are comparable.
micro <- micro %>% 
  filter(!scientificName == "Skeletonema marinoi")

micro <- rbind(micro, sm_size)

```

```{r}
#Add year column
micro <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .after = date)
```

```{r}
# Changing site_id to location 
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```

```{r}
#looking at only species present in 10% or more of samples -  might be too conservative here.

# species_10 <- micro %>%
#   group_by(scientificName) %>%
#   summarise(n_obs = n()) %>%
#   ungroup() %>%
#   mutate(perc_obs = n_obs/50) %>%
#   filter(perc_obs >= 0.10)
# # 
# species_10_list <- species_10$scientificName
# # 
# micro <- micro %>% 
#   filter(scientificName %in% species_10_list)

```

```{r}
micro_diat <- micro %>% 
  filter(group == "Bacillariophyta")

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_diat <- arrange(mutate(micro_diat,
                         location = factor(location, levels = order_loc)))

#I want to look at species that never contribute to more than a certain percentage to the total biomass

#Make a total diatom sum column for each date and then divide each species count by the total to derive a relative contribution
micro_diat <- micro_diat %>% 
  group_by(date, location) %>% 
  mutate(sum_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(diat_perc = species_sum/sum_count)

#Make a column showing the max contribution for each species
micro_diat <- micro_diat %>% 
  group_by(scientificName) %>% 
  mutate(max = max(diat_perc),
         max_abund = max(species_sum)) %>% 
  ungroup() 


micro_diat_gt5_perc <- micro_diat %>% 
  filter(max >= 0.10)


colourCount = length(unique(micro_diat_gt5_perc$scientificName))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))


micro_diat_gt5_perc %>% 
  ggplot(aes(x = as.factor(month_surv), y = species_sum/100000, 
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^5 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries-diatoms_gt10_perc_sm_size.png"),
       width = 16, height = 12, dpi = 300)
```
```{r}
micro_auto <- micro %>% 
  filter(trophicStatus == "auto")

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_auto <- arrange(mutate(micro_auto,
                         location = factor(location, levels = order_loc)))

#I want to look at species that never contribute to more than a certain percentage to the total biomass

#Make a total diatom sum column for each date and then divide each species count by the total to derive a relative contribution
micro_auto <- micro_auto %>% 
  group_by(date, location) %>% 
  mutate(sum_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(diat_perc = species_sum/sum_count)

#Make a column showing the max contribution for each species
micro_auto <- micro_auto %>% 
  group_by(scientificName) %>% 
  mutate(max = max(diat_perc),
         max_abund = max(species_sum)) %>% 
  ungroup() 


micro_auto_gt5_perc <- micro_auto %>% 
  filter(max >= 0.10)


colourCount = length(unique(micro_auto_gt5_perc$scientificName))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))


micro_auto_gt5_perc %>% 
  ggplot(aes(x = as.factor(month_surv), y = species_sum/100000, 
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^5 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries_gt10_perc_sm_size.png"),
       width = 16, height = 12, dpi = 300)
```






```{r}
micro <- micro %>% 
  mutate(yday = lubridate::yday(date),
         year = lubridate::year(date))

env <- env %>% 
  mutate(yday = lubridate::yday(date))

micro <- arrange(mutate(micro,
                         location = factor(location, levels = order_loc)))

env <- arrange(mutate(env,
                         location = factor(location, levels = order_loc)))

c <- c %>% 
  mutate(yday = lubridate::yday(date),
         year = lubridate::year(date))

f1 <- micro %>% 
  filter(year == 2019) %>% 
  filter(genus == "Pseudo-nitzschia" | group == "Raphidiophyta") %>%
  group_by(date, genus) %>% 
  mutate(pn_sum = sum(species_sum/10^5)) %>% 
  ungroup() %>% 
  ggplot(aes(x = yday, y = pn_sum, fill = as.factor(genus), color = as.factor(genus))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("PN 10^5 cells L") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f2 <- c %>%
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = hapt)) +
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ site_id) +
  scale_fill_manual(values = getPalette(colourCount)) +
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("Hapto (ug/L)") +
  # ggtitle("Shelf") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))


f3 <- env %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = t, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f4 <- env %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = s, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("sal") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f5 <- env %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = dr, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("dr") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f6 <- env %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = no2, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("no2") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f7 <- env %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = no2/po4, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("no2:po4") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f8 <- env %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = yday, y = sio2, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("sio2") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

fig <- f1/f2/f3/f4/f5/f6/f7/f8

ggsave(here("figures_good", "test2.png"), fig,
       width = 16, height = 16, dpi = 300)
```

```{r}
f1 <- micro %>% 
  filter(year == 2020) %>% 
  filter(genus == "Skeletonema") %>%
  group_by(date, genus) %>% 
  mutate(sum = sum(species_sum/10^5)) %>% 
  ungroup() %>% 
  ggplot(aes(x = yday, y = sum, fill = as.factor(genus), color = as.factor(genus))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("PN 10^5 cells L") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f2 <- c %>%
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = hapt)) +
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ site_id) +
  scale_fill_manual(values = getPalette(colourCount)) +
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("Hapto (ug/L)") +
  # ggtitle("Shelf") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))


f3 <- env %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = t, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f4 <- env %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = s, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("sal") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f5 <- env %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = dr, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("dr") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f6 <- env %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = no2, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("no2") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f7 <- env %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = po4, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("po4") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f8 <- env %>% 
  filter(year == 2020) %>% 
  ggplot(aes(x = yday, y = sio2, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ location) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("sio2") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

fig2 <- f1/f2/f3/f4/f5/f6/f7/f8

ggsave(here("figures_good", "test_2020.png"), fig2,
       width = 16, height = 16, dpi = 300)
```

```{r}
#Test join
env_s <- env %>% 
  select(location, date, s, t)

micro_diat_gt5_perc <-micro_diat_gt5_perc %>% 
  left_join(env_s)
```

```{r}
ylim.prim <- c(0, 20)   # in this example, precipitation
ylim.sec <- c(26, 32.5)    # in this example, temperature

b <- diff(ylim.prim)/diff(ylim.sec)
a <- b*(ylim.prim[1] - ylim.sec[1])


micro_diat_gt5_perc %>% 
  ggplot() + 
  geom_bar(data = micro_diat_gt5_perc, aes(x = month_surv, y = species_sum/100000, 
             fill = scientificName), stat = "identity", position = "stack", color = "black") + 
  geom_line(data = env, aes(x = month_surv, y = a + s*b)) +
  geom_point(data = env, aes(x = month_surv, y = a + s*b)) +
  scale_y_continuous("abundance", sec.axis = sec_axis(~ (. - a)/b, name = "salinity"),) +
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^5 cells L)") +
theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "bar_sal.png"),
       width = 16, height = 12, dpi = 300)
```

```{r}
ylim.prim <- c(10, 16)   # in this example, precipitation
ylim.sec <- c(30, 32.5)    # in this example, temperature

b <- diff(ylim.prim)/diff(ylim.sec)
a <- b*(ylim.prim[1] - ylim.sec[1])


env %>%
  mutate(yday = lubridate::yday(date)) %>% 
  filter(location == "S" & year == 2019) %>% 
  ggplot() + 
  geom_line(aes(x = yday, y = t)) +
  geom_line(aes(x = yday, y = a + s*b)) +
  scale_y_continuous("abundance", sec.axis = sec_axis(~ (. - a)/b, name = "salinity"),) +
  theme_bw() +
theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(ncol = 4))
```




```{r}
ylim.prim <- c(0, 20)   # in this example, precipitation
ylim.sec <- c(8, 16)    # in this example, temperature

b <- diff(ylim.prim)/diff(ylim.sec)
a <- b*(ylim.prim[1] - ylim.sec[1])


micro_diat_gt5_perc %>% 
  ggplot() + 
  geom_bar(data = micro_diat_gt5_perc, aes(x = month_surv, y = species_sum/100000, 
             fill = scientificName), stat = "identity", position = "stack", color = "black") + 
  geom_line(data = env, aes(x = month_surv, y = a + t*b)) +
  geom_point(data = env, aes(x = month_surv, y = a + t*b)) +
  scale_y_continuous("abund", sec.axis = sec_axis(~ (. - a)/b, name = "temp"),) +
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^5 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "bar_temp.png"),
       width = 16, height = 12, dpi = 300)
```

```{r}
f1 <- micro %>% 
  filter(genus == "Pseudo-nitzschia") %>%
  group_by(date, genus) %>% 
  mutate(genus_sum = sum(species_sum/10^5)) %>% 
  ungroup() %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = genus_sum, fill = genus)) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("Abund.") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.17, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

pn <- micro %>% 
  filter(genus == "Pseudo-nitzschia")

f2 <- env %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = s)) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ year) +
  coord_cartesian(ylim = c(29.5, 32.5)) +
  theme_bw() +
  ylab("Salinity") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f3 <- env %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = t)) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ year) +
  # coord_cartesian(ylim = c(29.5, 32.5)) +
  theme_bw() +
  ylab("Temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ps_shelf <- f1 / f2 / f3 

ggsave(here("figures_good", "test_ps_shelf.png"), ps_shelf,
       width = 16, height = 8, dpi = 300)
```

```{r}
f1 <- micro %>% 
  filter(genus == "Skeletonema") %>%
  group_by(date, genus) %>% 
  mutate(genus_sum = sum(species_sum/10^5)) %>% 
  ungroup() %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = genus_sum, fill = genus)) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("Abund.") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.17, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))


f2 <- env %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = s)) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ year) +
  # coord_cartesian(ylim = c(29.5, 32.5)) +
  theme_bw() +
  ylab("Salinity") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f3 <- env %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = secchi)) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ year) +
  # coord_cartesian(ylim = c(29.5, 32.5)) +
  theme_bw() +
  ylab("Temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ps_shelf <- f1 / f2 / f3 

ggsave(here("figures_good", "test_skel_channel.png"), ps_shelf,
       width = 16, height = 8, dpi = 300)
```



```{r}
wind2 <- wind %>% 
  mutate(measurementTime = lubridate::mdy_hm(measurementTime,
                                             tz = Sys.timezone()),
         yday = lubridate::yday(measurementTime)) 

f1 <- wind2 %>%   
  filter(year >= 2018 & year <= 2020) %>% 
  filter(yday > 150 & yday < 200) %>% 
  group_by(year, yday) %>% 
  summarise(w_day = mean(WindSpd_Avg)) %>% 
  ungroup() %>% 
  ggplot(aes(x = yday, y = w_day, color = as.factor(year))) + 
  geom_line() +
  geom_vline(xintercept = 188) +
  # coord_cartesian(ylim = c(29.5, 32.5)) +
  theme_bw() +
  ylab("Temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f2 <- wind2 %>%   
  filter(year >= 2018 & year <= 2020) %>% 
  filter(yday > 150 & yday < 200) %>% 
  group_by(year, yday) %>% 
  summarise(w_day = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  ggplot(aes(x = yday, y = w_day, color = as.factor(year))) + 
  geom_line() +
  geom_vline(xintercept = 188) +
  # coord_cartesian(ylim = c(29.5, 32.5)) +
  theme_bw() +
  ylab("Temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

fig <- f1 / f2


ggsave(here("figures_good", "wind.png"), fig,
       width = 16, height = 6, dpi = 300)
```



```{r}
c <- c %>% 
  mutate(yday = lubridate::yday(date),
         year = lubridate::year(date))

c %>% 
  ggplot(aes(x = yday, y = dino, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  facet_grid(. ~ site_id) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  # coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("PN 10^5 cells L") +
  ggtitle("Shelf") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))



```






```{r}
env <- env %>% 
  mutate(yday = lubridate::yday(date))


f1 <- env %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = t, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("temp") +
  ggtitle("Shelf") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f2 <- env %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = t, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(8, 16)) +
  theme_bw() +
  ylab("temp") +
  ggtitle("Channel") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f3 <- env %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = s, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(26, 33)) +
  theme_bw() +
  ylab("Salinity") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f4 <- env %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = s, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(26, 33)) +
  theme_bw() +
  ylab("Salinity") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f5 <- env %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = dr, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(0, 8)) +
  theme_bw() +
  ylab("Delat rho") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f6 <- env %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = dr, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(0, 8)) +
  theme_bw() +
  ylab("Delta Rho") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f7 <- env %>% 
  filter(location == "S") %>% 
  ggplot(aes(x = yday, y = sio2, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(0, 35)) +
  theme_bw() +
  ylab("siO2") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

f8 <- env %>% 
  filter(location == "C") %>% 
  ggplot(aes(x = yday, y = sio2, fill = as.factor(year), color = as.factor(year))) + 
  geom_point(pch = 21, color = "black", size = 5, stroke = 1.5) +
  geom_line(size = 2) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  scale_color_manual(values = getPalette(colourCount)) +
  coord_cartesian(ylim = c(0, 35)) +
  theme_bw() +
  ylab("siO2") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.35, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))


fig <- (f1 + f2) / (f3 + f4) / (f5 + f6) / (f7 + f8)

ggsave(here("figures_good", "test.png"), fig,
       width = 16, height = 18, dpi = 300)


test <- micro %>% 
  filter(location == "S") %>% 
  distinct(date)

```


```{r}
env %>% 
  filter(location == "S" & year == 2019) %>% 
  ggplot(aes(x = date, y = dr)) + 
  geom_point() +
  geom_line() +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

env %>% 
  filter(location == "S" & year == 2019) %>% 
  ggplot(aes(x = date, y = po4)) + 
  geom_point() +
  geom_line() +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("temp") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))
```



```{r}
#This seems to work pretty well - Can decide between percentage or abundance threshold. 
```

```{r}
#One of the request was total abundance versus TChla. How does it match?

#Determining total abundance of autotrophic species. May need to reformat what I consider autotrophic species.
total_abund <- micro %>% 
  filter(trophicStatus == "auto") %>% 
  group_by(date, site_id) %>% 
  mutate(abund_sum = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(abund_perc = (species_sum/abund_sum)*100) 

#Pulling the record with the dominant group contributing to total biomass
total_abund_top <- total_abund %>% 
  group_by(date, site_id) %>%
  top_n(n = 1, wt = abund_perc)


total_abund_top <- total_abund_top %>% 
  left_join(chl)
```
```{r}
palette_group <- c("#ff8000", #1 - Diatoms (orange)
                   "#4d6600", #3 - Raphidophytes (dark green)
                   "#ffff00", #5 - Cryptophytes (yellow)
                   "#7d4dcc" #7 - Haptophytes (purple)
                   ) 
```


```{r}
total_abund_top %>% 
  ggplot(aes(x = abund_sum/100000, y = chl)) + 
  geom_point(aes(fill = as.factor(group)), pch = 21, size = 4.5, stroke = 1.5) +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  # ggpubr::stat_cor(aes(label = ..rr.label..), label.y = 14, size = 8) +
  # ggpubr::stat_cor(aes(label = ..p.label..), label.y = 10, size = 8) +
  ggpubr::stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, size = 8) +
  xlim(0, 35) +
  ylim(0, 15) +
  labs(x = "Abundance (10^5 cells L)",
       y = "TChla (ug/L)") +
  scale_fill_manual(values = palette_group,
                    name = "Dom. Group", 
                    breaks = c("Bacillariophyta", "Raphidiophyta", 
                               "Cryptophyta", "Prymnesiophyta-Haptophyta"),
                    labels = c("Diat.", "Raph.", "Cryp.", "Hapt.")) +
  theme_bw() +
  theme(text = element_text(size = 24),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.85, 0.84))

ggsave(here("figures_good", "abund_tchla.png"),
       width = 7.5, height = 6, dpi = 300)
```

```{r}
#I want to look at heterotrophic dinoflagellates that have high grazing rates

```

```{r}

micro_dino <- micro %>% 
  filter(group == "Dinoflagellata")

#Chemtax - Specify order of phyto groups for figures
micro_dino <- arrange(mutate(micro_dino,
                         location = factor(location, levels = order_loc)))

#I want to look at species that never contribute to more than a certain percentage to the total biomass

#Make a total diatom sum column for each date and then divide each species count by the total to derive a relative contribution
micro_dino <- micro_dino %>% 
  group_by(date, location) %>% 
  mutate(sum_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(dino_perc = species_sum/sum_count)

#Make a column showing the max contribution for each species
micro_dino <- micro_dino %>% 
  group_by(scientificName) %>% 
  mutate(max = max(dino_perc),
         max_abund = max(species_sum)) %>% 
  ungroup() 


micro_dino_gt5_perc <- micro_dino %>% 
  filter(max >= 0.10)


colourCount = length(unique(micro_dino_gt5_perc$scientificName))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))


micro_dino_gt5_perc %>% 
  ggplot(aes(x = as.factor(month_surv), y = species_sum/100000, 
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^5 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries-dino_gt10_perc.png"),
       width = 16, height = 12, dpi = 300)

```
```{r}
micro %>%
  filter(genus == "Gymnodinium") %>% 
  ggplot(aes(x = as.factor(month_surv), y = species_sum/1000, 
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^3 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries-gymnodinium.png"),
       width = 16, height = 12, dpi = 300)
```
```{r}
micro %>%
  filter(genus == "Dinophysis") %>% 
  ggplot(aes(x = as.factor(month_surv), y = species_sum/1000, 
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. Diatoms (10^3 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries-dino.png"),
       width = 16, height = 12, dpi = 300)
```
```{r}
cil <- micro %>% 
  filter(group == "Ciliophora")

cil <- arrange(mutate(cil,
                       location = factor(location, levels = order_loc)))

cil %>%
  filter(scientificName == "Tintinnina") %>% 
  ggplot(aes(x = as.factor(month_surv), y = species_sum/10000, 
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. (10^4 cells L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries-tinn.png"),
       width = 16, height = 12, dpi = 300)
```

```{r}
fec <- fec %>% 
  filter(!site_id == "QU39")

fec <- fec %>% 
  mutate(year = lubridate::year(date))

fec <- fec %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))

fec <- arrange(mutate(fec,
                       location = factor(location, levels = order_loc)))


fec %>%
  ggplot(aes(x = as.factor(month_surv), y = fecal*100)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(location ~ year) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Abund. (pellets L)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 4))

ggsave(here("figures_good", "timeseries-fecal.png"),
       width = 16, height = 12, dpi = 300)
```








```{r}
#Goal is to show the prominent diatom species for each sampling date

#Separating diatoms
micro_diat <- micro %>% 
  filter(class == "Bacillariophyceae") %>% 
  group_by(date, site_id) %>% 
  mutate(total_abund = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(diat_perc = species_sum/total_abund)

#separating dinoflagellates
micro_dino <- micro %>% 
  filter(group == "Dinoflagellata") %>% 
  group_by(date, site_id) %>% 
  mutate(total_abund = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(diat_perc = species_sum/total_abund)

#Summing diatoms to genus level
micro_genus <- micro_diat %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, location, month_surv, genus) %>% 
  summarize(sum_genus = sum(species_sum)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(sum_genus)) %>% 
  ungroup() %>% 
  mutate(perc_genus = sum_genus/sum_all,
         year = lubridate::year(date))

#Summing dinoflagellates to genus level
micro_genus_dino <- micro_dino %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, location, month_surv, genus) %>% 
  summarize(sum_genus = sum(species_sum)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(sum_genus)) %>% 
  ungroup() %>% 
  mutate(perc_genus = sum_genus/sum_all,
         year = lubridate::year(date))
```

```{r}
#Merging genus level data with chlorophyll
micro_genus <- micro_genus %>% 
  left_join(chl)
```
```{r}

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_genus <- arrange(mutate(micro_genus,
                         location = factor(location, levels = order_loc)))

```

















```{r}
#define the colours to use in the figure
colours = c( "#A54657",
             "#582630",
             "#F7EE7F",
             "#4DAA57",
             "#F1A66A",
             "#F26157",
             "#F9ECCC",
             "#679289",
             "#33658A",
             "#F6AE2D")
```



```{r}
coeff <- 12.5

micro_genus %>% 
  filter(perc_genus >= 0.05) %>% 
  ggplot(aes(x = as.factor(location), y = perc_genus, 
             fill = genus)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  geom_point(aes(x = as.factor(location), y = chl/coeff), pch = 21,
             color = "Black", fill = "white", stroke = 1.5, size = 3) +
  scale_y_continuous(sec.axis = sec_axis(~ . *coeff, name = "TChla")) +
  facet_grid(year ~ month_surv) +
  scale_fill_manual(values = colours) +  
                    # labels = c("Bi.",
                    #            "C.c.",
                    #            "C.t.",
                    #            "P.",
                    #            "P.n.",
                    #            "P.n.s.",
                    #            "R.s.",
                    #            "S.m.",
                    #            "T.p.")) +
  theme_bw() +
  ylab("Rel. Abund. Diatoms (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 2))

ggsave(here("figures_good", "diat_genus_chla.png"),
       width = 14, height = 8, dpi = 300)
```

```{r}
diat_global <- micro_genus %>%
  select(date, location, genus, sum_genus, perc_genus) %>% 
  group_by(location, genus) %>% 
  summarise(median_perc = median(perc_genus),
            mean_perc = mean(perc_genus)) %>% 
  ungroup()

dino_global <- micro_genus_dino %>%
  select(date, location, genus, sum_genus, perc_genus) %>% 
  group_by(location, genus) %>% 
  summarise(median_perc = median(perc_genus),
            mean_perc = mean(perc_genus)) %>% 
  ungroup()

colourCount = length(unique(diat_global$genus))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
```


```{r}
diat_global %>% 
  ggplot(aes(x = as.factor(location), y = median_perc, fill = genus)) +
  geom_bar(stat = "identity", position = "fill", color = "black") +
  scale_fill_manual(values = getPalette(colourCount)) +
  theme_bw() +
  ylab("Rel. Abund. Diatoms (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))


ggsave(here("figures_good", "test.png"),
       width = 9, height = 5.5, dpi = 300)
```
```{r}
dino_global %>% 
  ggplot(aes(x = as.factor(location), y = median_perc, fill = genus)) +
  geom_bar(stat = "identity", position = "fill", color = "black") +
  scale_fill_manual(values = getPalette(colourCount)) +
  theme_bw() +
  ylab("Rel. Abund. Diatoms (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))


ggsave(here("figures_good", "test_dino.png"),
       width = 9, height = 5.5, dpi = 300)
```



```{r}
coeff <- 12.5

micro_genus %>% 
  # filter(perc_genus >= 0.05) %>% 
  ggplot(aes(x = as.factor(location), y = perc_genus, 
             fill = genus)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  geom_point(aes(x = as.factor(location), y = chl/coeff), pch = 21,
             color = "Black", fill = "white", stroke = 1.5, size = 3) +
  scale_y_continuous(sec.axis = sec_axis(~ . *coeff, name = "TChla")) +
  facet_grid(year ~ month_surv) +
  scale_fill_manual(values = getPalette(colourCount)) + 
  theme_bw() +
  ylab("Rel. Abund. Diatoms (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))

ggsave(here("figures_good", "diat_genus_chla_2.png"),
       width = 16, height = 8, dpi = 300)
```




```{r}
#Goal is to show the prominent diatom species for each sampling date

#1 Look at what species were dominant for each sample
micro_flag <- micro %>% 
  filter(!class == "Bacillariophyceae") %>% 
  group_by(date, site_id) %>% 
  mutate(total_abund = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(flag_perc = species_sum/total_abund)

# micro_diat_order <- micro_diat %>% 
#   group_by(date, site_id) %>%
#   mutate(diat_rank = order(order(species_sum, decreasing = TRUE))) %>% 
#   ungroup()

flag_diat_stats <- micro_flag %>% 
  group_by(site_id, scientificName) %>% 
  summarise(med_abund = median(species_sum),
            med_perc = median(flag_perc)) %>% 
  mutate_at(vars(med_perc), funs(round(., 2)))


flag_genus <- micro_flag %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, location, month_surv, genus) %>% 
  summarize(sum_genus = sum(species_sum)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(sum_genus)) %>% 
  ungroup() %>% 
  mutate(perc_genus = sum_genus/sum_all,
         year = lubridate::year(date))
```
```{r}
# flag_order <- c("Phaeocystis", "Hillea", "Teleaulax", "Pterosperma",
#                 "Pyramimonas", "Katodinium", "Dinobryon", "Olisthodiscus",
#                 "Metromonas", "Monosiga", "Parvicorbicula")

# flag_order <- c("Parvicorbicula", "Monosiga", "Metromonas", "Olisthodiscus",
#                 "Dinobryon", "Katodinium", "Pyramimonas", "Pterosperma", 
#                 "Teleaulax", "Hillea", "Phaeocystis")

flag_order <- c("Parvicorbicula", "Monosiga", "Metromonas", 
                "Scrippsiella", "Katodinium", "Corythodinium", 
                "Telonema",
                "Teleaulax", "Hillea",
                "Tetraselmis", "Pyramimonas", "Pterosperma",
                "Phaeocystis", 
                "Dinobryon", "Ciliophrys", "Apedinella")

flag_genus <- arrange(mutate(flag_genus,
                         genus = factor(genus, levels = flag_order)))


#Chemtax - Specify order of phyto groups for figures
flag_genus <- arrange(mutate(flag_genus,
                         location = factor(location, levels = order_loc)))

```

```{r}
# colours_flag = c("#E56AB3",
#                  "#F9A3CB",
#                  "#FFCEE6",
#                  "#9300ff",
#                  "#95F985",
#                  "#26D701",
#                  "#00AB08",
#                  "#FFDF00",
#                  "#EDC211",
#                  "#DAA521",
#                  "#8B0000",
#                  "#a23333",
#                  "#c58080",
#                  "#0000FF",
#                  "#4949FF",
#                  "#BFBFFF")


colours_flag = c("#BFBFFF",
                 "#4949FF",
                 "#0000FF",
                 "#4a010d",
                 "#940119",
                 "#de0226",
                 "#DAA521",
                 "#EDC211",
                 "#FFDF00",
                 "#00AB08",
                 "#26D701",
                 "#95F985",
                 "#9300ff",
                 "#FFCEE6",
                 "#F9A3CB",
                 "#E56AB3")
```



```{r}
flag_genus %>% 
  filter(perc_genus >= 0.05) %>% 
  ggplot(aes(x = as.factor(location), y = perc_genus, 
             fill = genus)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(year ~ month_surv) +
  scale_fill_manual(values = colours_flag) +
  # scale_fill_brewer(palette = "Paired") +  
                    # labels = c("Bi.",
                    #            "C.c.",
                    #            "C.t.",
                    #            "P.",
                    #            "P.n.",
                    #            "P.n.s.",
                    #            "R.s.",
                    #            "S.m.",
                    #            "T.p.")) +
  theme_bw() +
  ylab("Rel. Abund. Flagellates (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 3))

ggsave(here("figures_rev2", "flag_test_family_no-cryp.png"),
       width = 14, height = 8, dpi = 300)
```






```{r}
micro %>% 
  filter(scientificName == "Pseudo-nitzschia seriata"  & year == "2019") %>% 
  ggplot(aes(x = date, y = species_sum, color = location)) +
  geom_line() +
  geom_point()
```


```{r}
micro %>% 
  filter(scientificName == "Rhizosolenia setigera"  & year == "2018") %>% 
  ggplot(aes(x = date, y = species_sum, color = location)) +
  geom_line() +
  geom_point()

```







```{r}
#What about selecting only species that ever exceed 50000k. Doing a median of these and then plotting. 
diat_gt100k <- micro %>% 
  filter(!site_id == "QU39" & class == "Bacillariophyceae" 
         & species_sum >= 100000) %>%
  distinct(scientificName)

test <- micro %>% 
  filter(scientificName == "Chaetoceros debilis")

diat_gt100k_list <- diat_gt100k$scientificName

diat_test2 <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(!site_id == "QU39" 
         & class == "Bacillariophyceae" 
         & scientificName %in% diat_gt100k_list) %>%
  group_by(site_id, year, month_surv, scientificName) %>% 
  summarize(med_count = median(species_sum)) %>% 
  mutate(rank_med = order(order(med_count, decreasing = TRUE))) %>% 
  ungroup()

diat_test2 <- diat_test2 %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 

diat_test2 <- arrange(mutate(diat_test2,
                         location = factor(location, levels = order_loc)))
```

```{r}
diat_test2 %>% 
  ggplot(aes(x = as.factor(location), y = med_count, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "fill", color = "black") + 
  facet_grid(year ~ month_surv) + 
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test.png"), 
       width = 12, height = 8, dpi = 300)
```

```{r}
diat_test2 %>% 
  ggplot(aes(x = as.factor(location), y = (med_count/100000),
             fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") + 
  facet_grid(year ~ month_surv, scales = "free_y") + 
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test_abund.png"), 
       width = 12, height = 8, dpi = 300)
```

```{r}
coeff <- 12.5

diat_test2 %>% 
  ggplot() + 
  geom_bar(aes(x = as.factor(location), y = med_count, fill = scientificName),
           stat = "identity", position = "fill", color = "black") + 
  geom_point(aes(x = as.factor(location), y = chl/coeff), pch = 21,
             color = "Black", fill = "white", stroke = 1.5, size = 3) +
  scale_y_continuous(sec.axis = sec_axis(~ . *coeff, name = "TChla")) +
  facet_grid(year ~ month_surv) + 
  # geom_text(aes(label = year), x = Inf, y = Inf, hjust = 1.5, vjust = 1.5,
            # check_overlap = TRUE) +
  scale_fill_brewer(palette = "Paired", 
                    labels = c("Bi.",
                               "C.c.",
                               "C.t.",
                               "P.",
                               "P.n.",
                               "P.n.s.",
                               "R.s.",
                               "S.m.",
                               "T.p.")) +
  theme_bw() +
  ylab("%") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "diat_test_perc_tchla.png"), 
       width = 12, height = 8, dpi = 300)
```