---
title: "R Notebook"
output: html_notebook
---

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(zoo)
library(RColorBrewer)
```

```{r}
#Upload data

micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv"))

ctd <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

env <- read_csv(here("outputs", "enviro_2023-05-26_up.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

clust <- read_csv(here("outputs", "final_cluster_2023-07-31.csv"))

chem <- read_csv(here("files", "chemtax_2023-04-14.csv"))

sf <- read_csv(here("files", "chl_2018_2020.csv"))
```

```{r}
#Pivoting data for RDA analysis

#Selecting columns for pivot
micro_piv <- micro %>%
  mutate(month = lubridate::month(date)) %>% 
  select(date, month, site_id, scientificName, species_sum)

#performing pivot and making NA's 0's. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum,
              values_fill = 0) 

micro_piv <- micro_piv %>% 
  select(!month)
```

```{r}
#Selecting columns from the CTD master sheet
ctd <- ctd %>% 
  select(date, site_id, temp_dm, sal_dm, delta_rho_dm, no2_dm:secchi_depth, dep_26_dm, turb_dm)
```

```{r}
data <- ctd %>% 
  left_join(env) %>% 
  left_join(chl)
```
```{r}
#Selecting and renaming the columns that I want
data <- data %>% 
  select(date:site_id,
         temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth,
         wan_b1, 
         sm_b1,
         gm_b1,
         ra_b1,
         wind_b1,
         wind_dir_b1,
         par_b1,
         UI = up_b1,
         p1026 = dep_26_dm,
         tchla)

micro_join <- data %>%
  left_join(micro_piv)

```
```{r}
riv <- env %>%
  mutate(Q_tot = gm_b1 + sm_b1 + ra_b1) %>% 
  select(date, Q_GM = gm_dis, Q_SM = sm_dis, Q_RA = ra_dis, Q_tot) %>% 
  pivot_longer(!date, names_to = "Watershed_group", values_to = "Q")

# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

riv <- arrange(mutate(riv, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
```



```{r}
fs1 <- micro_join %>%
  filter(site_id == "KC10" | site_id == "QCS01") %>% 
  ggplot(aes(x = date, y = `Skeletonema marinoi`/10^5, fill = site_id)) +
  geom_col(color = "black", width = 1, size = 1) +
  scale_fill_manual(values = c("#EFC000FF","#868686FF"),
                    labels = c("C", "F")) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  labs(fill = "") +
  scale_x_date(limits = as.Date(c("2020-06-20", "2020-07-10"))) +
  annotate("text", x = as.Date("2020-06-24"), y = 21, label = "2020 - S.marinoi"
           , size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none")

fs2 <- riv %>%
  ggplot() +
  geom_area(data = riv %>% filter(!Watershed_group == "Q_tot"),
            aes(x = date, y = Q/10^3, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.5) +
  geom_line(data = riv %>% filter(Watershed_group == "Q_tot"),
            aes(x = date, y = Q/10^3), color = "black", size = 1.5) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Blues",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote(Dis. ~ "("~m^-3*~s^-1*")")) +
  scale_x_date(limits = as.Date(c("2020-06-20", "2020-07-10"))) +
  ylim(0, 7) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none")

fs3 <- env %>%
  mutate(year = lubridate::year(date)) %>% 
  filter(year > 2019) %>% 
  ggplot(aes(x = date, y = wind_dm^3, fill = wind_dir_dm)) +
  geom_col(color = "black") +
  # geom_line(size = 2) +
  scale_fill_stepsn(colors = brewer.pal(n = 8, name = "RdBu"),
                     breaks = seq(0, 360, by = 45),
                    limits = c(0, 360),
                    name = "Dir.(°)") +
  labs(y = bquote("Wind ("*m^3~s^-3*")")) +
  ylim(0, 1200) +
  scale_x_date(limits = as.Date(c("2020-06-20", "2020-07-10"))) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(color = guide_colourbar(barwidth = 1, barheight = 12))

fs4 <- env %>%
  mutate(year = lubridate::year(date)) %>% 
  filter(year > 2019) %>% 
  ggplot() +
  geom_col(aes(x = date, y = ifelse(up_dm < 0/10^2, up_dm/10^2, 0)),
           fill= "blue", color = "black") +
  geom_col(aes(x = date, y = ifelse(up_dm > 0/10^2, up_dm/10^2, 0)),
           fill= "red", color = "black") +
  labs(y = "upwelling") +
  scale_x_date(limits = as.Date(c("2020-06-20", "2020-07-10"))) +
  ylim(-2, 2) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none")
```

```{r}
fp1 <- micro_join %>%
  filter(site_id == "KC10" | site_id == "QCS01") %>% 
  ggplot(aes(x = date, y = `Pseudo-nitzschia seriata`/10^5, fill = site_id)) +
  geom_col(color = "black", width = 1, size = 1) +
  scale_fill_manual(values = c("#EFC000FF","#868686FF"),
                    labels = c("C", "F")) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")"),
       fill = NULL) +
  annotate("text", x = as.Date("2019-07-05"), y = 5, label = "2019 - P.seriata"
           , size = 10) +
  scale_x_date(limits = as.Date(c("2019-07-01", "2019-07-20"))) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = c(0.9, 0.8))

fp2 <- riv %>%
  ggplot() +
  geom_area(data = riv %>% filter(!Watershed_group == "Q_tot"),
            aes(x = date, y = Q/10^3, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.5) +
  geom_line(data = riv %>% filter(Watershed_group == "Q_tot"),
            aes(x = date, y = Q/10^3), color = "black", size = 1.5) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Blues",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote(Dis. ~ "("~m^-3*~s^-1*")")) +
  scale_x_date(limits = as.Date(c("2019-07-01", "2019-07-20"))) +
  ylim(0, 7) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = c(0.87, 0.83))

# micro_join %>%
#   ggplot(aes(x = date, y = p1026)) +
#   geom_col(color = "black") +
#   # geom_line(size = 2) +
#   scale_fill_stepsn(colors = brewer.pal(n = 8, name = "RdBu"),
#                      breaks = seq(0, 360, by = 45),
#                     limits = c(0, 360),
#                     name = "Dir.(°)") +
#   labs(y = bquote("Wind ("*m^3~s^-3*")")) +
#   # ylim(0, 1200) +
#   scale_x_date(limits = as.Date(c("2020-07-01", "2020-07-20"))) +
#   theme_bw() +
#   theme(text = element_text(size = 25),
#         axis.text = element_text(color = 'black'),
#         axis.text.x = element_blank(),
#         axis.title.x = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank()) +
#   guides(color = guide_colourbar(barwidth = 1, barheight = 12))

fp4 <- env %>%
  ggplot() +
  geom_col(aes(x = date, y = ifelse(up_dm < 0/10^2, up_dm/10^2, 0)),
           fill= "blue", color = "black") +
  geom_col(aes(x = date, y = ifelse(up_dm > 0/10^2, up_dm/10^2, 0)),
           fill= "red", color = "black") +
  labs(y = bquote("UI. ("~10^2 ~ m^-3*~s^-1*")")) +
  scale_x_date(limits = as.Date(c("2019-07-01", "2019-07-20"))) +
  ylim(-2, 2) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none")
```

```{r}
fig_panel <- fp1 + fs1 + fp2 + fs2 + fp4 + fs4 + plot_layout(ncol = 2)

ggsave(here("figures_species_timeseries", "skel_pseud_panel.png"), fig_panel,
        width = 16, height = 12, dpi = 300)
```


```{r}
riv_18 <- riv %>%
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  filter(year == 2019 & month > 4 & month < 9) 

riv_18 %>% 
  ggplot() +
  geom_area(data = riv_18 %>% filter(!Watershed_group == "Q_tot"),
            aes(x = date, y = Q/10^3, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.5) +
  geom_line(data = riv_18 %>% filter(Watershed_group == "Q_tot"),
            aes(x = date, y = Q/10^3), color = "black", size = 1.5) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Blues",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote(Dis. ~ "("~m^-3*~s^-1*")")) +
  ylim(0, 7) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = c(0.87, 0.83))
```

```{r}
qcs <- micro_join %>% 
  filter(site_id == "QCS01")
```












