---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggpubr)
library(broom)
library(vegan)
library(ggcorrplot)
```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Uploading chl data that has been converted to TChla
chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

chem <- read_csv(here("files", "chemtax_2023-04-14.csv")) 

sf <- read_csv(here("files", "chl_2018_2020.csv")) 
```

```{r}
#Add year column
micro <- micro %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)

micro <- micro %>%  
  mutate(month_surv = lubridate::month(date),
         month_surv = case_when(date == "2019-08-29" ~ 9,
                                date == "2019-08-31" ~ 9,
                                date == "2019-11-27" ~ 12,
                             TRUE ~ as.numeric (month_surv)))
```

```{r}
sf_less <- sf %>% 
  filter(line_out_depth == 5 & !filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | is.na(chla_flag)) %>%
  mutate(year = lubridate::year(date)) %>% 
  select(date, year, site_id, filter_type, chla) %>% 
  filter(!is.na(chla)) %>% 
  group_by(date) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3)
```

```{r}
# Changing site_id to location 
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

chl <- chl %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```

```{r}
micro <- micro %>%
  mutate(group = case_when(scientificName == "Ciliophrys infusionum" |
                                      scientificName == "Apedinella spinifera" ~
                                      "Dictyochophyta",
                           TRUE ~ as.character(group)))

micro_group_stats <- micro %>%  
  group_by(date, site_id, group) %>% 
  summarise(group_sum = sum(species_sum)) %>% 
  ungroup() %>% 
  group_by(group) %>% 
  summarise(median_group = median(group_sum),
            min = min(group_sum),
            max = max(group_sum)) %>% 
  ungroup()


micro_piv <- micro %>% 
  select(date:location, scientificName, species_sum)

#pivoting wider so species are columns and samples are rows.
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, 
              values_from = species_sum, values_fill = 0) 

micro_long <- micro_piv %>% 
  pivot_longer(c(`Chaetoceros seiracanthus`: `Prorocentrum minimum`),
               names_to = "scientificName", values_to = "count")

micro_species_stats <- micro_long %>% 
  group_by(scientificName) %>% 
  summarise(median = median(count),
            min = min(count),
            max = max(count)) %>% 
  ungroup()
```

```{r}
sb_dates <- c("2018-03-31", "2018-04-28", "2018-07-14", "2019-03-15",
              "2019-05-11", "2019-05-13", "2020-04-30", "2020-05-01") 

sb <- micro %>% 
  filter(date %in% as.Date(sb_dates)) %>% 
  mutate(doy = lubridate::yday(date)) %>% 
  distinct(date, doy)

```

```{r}
micro_group <- micro %>%  
  group_by(date, site_id, group) %>% 
  summarise(group_sum = sum(species_sum)) %>% 
  ungroup()

micro_group %>% 
  filter(group == "Cryptophyta") %>% 
  ggplot(aes(x = site_id, y = group_sum)) +
  geom_boxplot()
```


