---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggpubr)
library(broom)
library(vegan)
library(ggcorrplot)
```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Uploading chl data that has been converted to TChla
chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

chem <- read_csv(here("files", "chemtax_2023-04-14.csv")) 

sf <- read_csv(here("files", "chl_2018_2020.csv")) 
```


```{r}
hapt <- micro %>% 
  filter(date == "2019-08-06" | date == "2019-08-31" | date == "2020-09-04") %>% 
  filter(group == "Dictyochophyta" | group == "Prymnesiophyta-Haptophyta" |
           group == "Chrysophyta")

#Plot to show trends at the shelf when there was high haptophyte contributions.

hapt %>% 
  ggplot(aes(x = as.factor(date), y = species_sum/10^4, fill = scientificName)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") +
  ggsci::scale_fill_jco() +
  labs(y = bquote("Abund. ("~10^4 ~ cells ~ L^-1*")")) +
  annotate("text", x = 0.8, y = 6, label = "SHELF", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

ggsave(here("figures_species_timeseries", "summer_2019_shelf.png"),
       width = 10, height = 6, dpi = 300)
```

```{r}
#Removing cyanobacteria from the counts.
micro <- micro %>%
  filter(!scientificName_accepted == "Cyanobacteria")

#Only including autotrophic species
micro_phyto <- micro %>%
  filter(trophicStatus == "auto")
```

```{r}
#Adding date and Season Columns.
micro_phyto <- micro_phyto %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)

micro_phyto <- micro_phyto %>%  
  mutate(month_surv = case_when(date == "2019-08-29" ~ 9,
                                date == "2019-08-31" ~ 9,
                                date == "2020-04-30" ~ 5,
                                TRUE ~ as.numeric (month))) %>% 
  mutate(month_mid = 15) %>% 
  unite(month_date, c("year", "month_surv", "month_mid"), sep = "-") %>% 
  mutate(month_date = lubridate::ymd(month_date))
```

```{r}
#Formatting the size-fractionated data.
sf_less <- sf %>% 
  filter(line_out_depth == 5 & !filter_type == "Bulk GF/F") %>% 
  filter(chla_flag == "AV" | is.na(chla_flag)) %>%
  mutate(year = lubridate::year(date)) %>% 
  select(date, year, site_id, filter_type, chla) %>% 
  filter(!is.na(chla)) %>% 
  group_by(date) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3)
```

```{r}
# Changing site_id to location 
micro_phyto <- micro_phyto %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

chl <- chl %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```

```{r}
micro_phyto <- micro_phyto %>%
  group_by(date, location) %>%
  mutate(sum_count = sum(species_sum)) %>%
  ungroup() %>%
  mutate(perc = species_sum/sum_count)

micro_phyto <- micro_phyto %>%
  group_by(scientificName) %>%
  mutate(max = max(perc),
         max_abund = max(species_sum),
         median_abund = median(species_sum)) %>% 
  ungroup()

top_8 <- micro_phyto %>% 
  distinct(scientificName, max_abund) %>% 
  slice_max(max_abund, n = 8)
```

```{r}
micro_8 <- micro_phyto %>% 
  mutate(scientificName2 = ifelse(max_abund < 350000 & group == "Bacillariophyta",
                                  "Other diatom", scientificName)) %>% 
  mutate(scientificName2 = ifelse(max_abund < 350000 & !group == "Bacillariophyta",
                                  "Other flagellate", scientificName2))
```


```{r}
micro_8 <- micro_8 %>% 
  group_by(date, month_date, location, scientificName2) %>% 
  summarise(species_sum = sum(species_sum)) %>% 
  ungroup()
```
```{r}
micro_8_c <- micro_8  

colourCount_c = length(unique(micro_8_c$scientificName2))
getPalette_c = colorRampPalette(brewer.pal(15, "Paired"))
```
```{r}
#25%
spec_ord <- c("Biddulphiales", #
              "Chaetoceros tenuissimus", #
              # "Pennales", #
              "Pseudo-nitzschia seriata", #
              # "Rhizosolenia setigera", #
              "Skeletonema marinoi", #
              # "Olisthodiscus", #
              "Hillea", #
              "Teleaulax", #
              "Olisthodiscus",
              "Phaeocystis pouchetii", #
              # "Choanozoa",
              # "Parvicorbicula socialis",
              "Other diatom", #
              "Other flagellate") #

micro_8_c <- arrange(mutate(micro_8_c,
                         scientificName2 = factor(scientificName2,
                                                 levels = spec_ord)))
```

```{r}
micro_8_c <- micro_8_c %>% 
  left_join(chl)
```


```{r}
#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

micro_8_c <- arrange(mutate(micro_8_c,
                         location = factor(location, levels = order_loc)))
```


```{r}
micro_8_plot <- micro_8_c %>% 
  select(-site_id, -tchla) %>% 
  pivot_wider(names_from = scientificName2, values_from = species_sum,
              values_fill = 0) 

micro_8_plot <- micro_8_plot %>% 
  pivot_longer(cols = c(Hillea:Olisthodiscus), names_to = "scientificName2",
               values_to = "species_sum")
```

```{r}
micro_8_plot <- arrange(mutate(micro_8_plot,
                         scientificName2 = factor(scientificName2,
                                                 levels = spec_ord)))
```

```{r}

#Adding location instead of site ID for interpretation of results
chem <- chem %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

#Creating a unique location-date ID for each sample - makes labels for plotting by dendrogram more informative 
chem <- chem %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

chem <- chem %>% 
  rename(cyan = Cyanobacteria, hapt = Hapto, GA = `Prasinophytes-3`,
         cryp = Cryptophytes, dino = `Dinoflagellates-1`, dict = Dictyo, 
         raph = Raphido,
         diat = `Diatoms-1`)
```

```{r}
#Here, only including 2019-2020
chem <- chem %>% 
  filter(date < "2021-01-01")

# chem <- chem %>% 
#     add_row(sample_name = NA,
#             date = as.Date("2020-01-01"),
#             site_id = "QCS01",
#             location = "S",
#             cyan = NA,
#             hapt = NA,
#             GA = NA, 
#             cryp = NA,
#             dino = NA,
#             raph = NA,
#             dict = NA, 
#             diat = NA) 

chem_long <- chem %>% 
  pivot_longer(c(cyan:diat), names_to = "group", values_to = "tchla")


chem_long <- chem_long %>%  
  mutate(month_surv = case_when(date == "2019-08-29" ~ 9,
                                date == "2019-08-31" ~ 9,
                                date == "2020-04-30" ~ 5,
                                TRUE ~ as.numeric (month))) %>% 
  mutate(month_mid = 15) %>% 
  unite(month_date, c("year", "month_surv", "month_mid"), sep = "-") %>% 
  mutate(month_date = lubridate::ymd(month_date))
```


```{r}
#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
chem_long <- arrange(mutate(chem_long,
                         location = factor(location, levels = order_loc)))


#Chemtax - Specify order of phyto groups for figures
chl <- arrange(mutate(chl,
                         location = factor(location, levels = order_loc)))
```

```{r}
#Setting plotting order phytoplankton groups

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapt", "GA", "cryp",
                   "dino", "raph", "dict", "diat")

#Chemtax spring bloom - Specify order of phyto groups for figures
chem_long <- arrange(mutate(chem_long,
                                group = factor(group,
                                levels = order_chem)))

```

```{r}
#Set Color palette for plotting. Currently based on QU39 manuscript. Brewer has some good ones for R style.
palette <- c("#ff8000", #1 - Diatoms (orange)
             "#ff99c7", #2 - Dictyochophytes (pink)
             "#4d6600", #3 - Raphidophytes (dark green)
             "#ff0000", #4 - Dinoflagellates (Red)
             "#ffff00", #5 - Cryptophytes (yellow)
             "#00ff00", #6 - Chlorophyta (light green)
             "#7d4dcc", #7 - Haptophytes (purple)
             "#000000") #8 - Cyanobacteria (black)

palette_micro <- c("#FBCEB1", #Bidd
                   "#FF7F50", #C.ten.
                   "#FF4500", #P.n.s.
                   "#ff8000", #S.mar.
                   "#FFEA00", #Hill
                   "#FFFF8F", #Tel
                   "#4d6600", #Olis
                   "#7d4dcc", #P.p.
                   "#71797E", #OD
                   "#E5E4E2") #OF

```

```{r}
chem_long <- chem_long %>%
    mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>%
  mutate(month_surv = case_when(date == "2019-08-31" ~ 9,
                                TRUE ~ as.numeric (month)))
```

```{r}
f1 <- micro_8_plot %>%
  filter(location == "F") %>%
  ggplot() +
  geom_bar(data = filter(micro_8_plot, date < "2018-02-01" & location == "F"), 
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 20) +
  geom_area(data = filter(micro_8_plot, date > "2018-02-01" & date < "2018-11-01" &
                            location == "F"), 
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(micro_8_plot, date > "2018-11-01" & date < "2018-11-30" &
                           location == "F"), 
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 20) +
  geom_area(data = filter(micro_8_plot, date > "2019-01-01" & date < "2019-12-31"&
                            location == "F"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(micro_8_plot, date > "2020-01-01" & date < "2020-02-25" &
                            location == "F"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 20) +
  geom_area(data = filter(micro_8_plot, date > "2020-02-25" & date < "2020-12-21" &
                            location == "F"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-06-01"), y = 30, label = "FJORD", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) 


f2 <- chem_long %>%
  filter(site_id == "DFO2") %>% 
  ggplot() +
  geom_area(data = filter(chem_long, date > "2019-01-01" & date < "2019-12-31"&
                            location == "F"),
           aes(x = date, y = tchla, 
           fill = fct_rev(group)), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(chem_long, date > "2020-01-01" & date < "2020-02-25" &
                            location == "F"),
           aes(x = date, y = tchla, 
           fill = fct_rev(group)), stat = "identity", position = "stack",
           color = "black", width = 20) +
  geom_area(data = filter(chem_long, date > "2020-02-25" & date < "2020-12-21" &
                            location == "F"),
           aes(x = date, y = tchla, 
           fill = fct_rev(group)), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette,
                    labels = c("Diat", "Dict", "Raph", "Dino", "Cryt", "Chlo", 
                               "Hapt", "Cyan")) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  labs(y = bquote("Phy. (TChla, mg" ~ m^-3*")")) +
  ylim(0, 12.5) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.5, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        # strip.text.y = element_blank()
        ) +
  guides(fill = guide_legend(nrow = 2),
         color = "none")

f3 <- micro_8_plot %>%
  filter(location == "C") %>%
  ggplot() + 
  geom_area(data = filter(micro_8_plot, date > "2018-01-01" & date < "2018-12-31" &
                            location == "C"), 
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  geom_area(data = filter(micro_8_plot, date > "2019-01-01" & date < "2019-12-31" &
                            location == "C"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(micro_8_plot, date > "2020-01-01" & date < "2020-02-25" &
                            location == "C"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 25) +
  geom_area(data = filter(micro_8_plot, date > "2020-02-25" & date < "2020-12-21" &
                            location == "C"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  annotate("text", x = as.Date("2018-07-01"), y = 30, label = "CHANNEL", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) 


f4 <- chem_long %>%
  filter(site_id == "KC10") %>% 
  ggplot() +
  geom_area(data = filter(chem_long, date > "2019-01-01" & date < "2019-12-31"&
                            location == "C"),
           aes(x = date, y = tchla, 
           fill = fct_rev(group)), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(chem_long, date > "2020-01-01" & date < "2020-02-25" &
                            location == "C"),
           aes(x = date, y = tchla, 
           fill = fct_rev(group)), stat = "identity", position = "stack",
           color = "black", width = 20) +
  geom_area(data = filter(chem_long, date > "2020-02-25" & date < "2020-12-21" &
                            location == "C"),
           aes(x = date, y = tchla, 
           fill = fct_rev(group)), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette,
                    labels = c("Diat", "Dict", "Raph", "Dino", "Cryt", "Chlo", 
                               "Hapt", "Cyan")) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 12.5) +
  labs(y = "Phyto. ug/L") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        # strip.text.y = element_blank()
        ) +
  guides(fill = guide_legend(nrow = 1),
         color = "none")

micro_8_plot <- micro_8_plot %>% 
  mutate(year = lubridate::year(date))

f5 <- micro_8_plot %>%
  ggplot() +
  geom_bar(data = filter(micro_8_plot, date < "2018-02-01" & location == "S"), 
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 25) +
  geom_area(data = filter(micro_8_plot, date > "2018-02-01" & date < "2018-12-31" &
                            location == "S"), 
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  geom_area(data = filter(micro_8_plot, date > "2019-01-01" & date < "2019-12-31"&
                            location == "S"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(micro_8_plot, date > "2020-01-01" & date < "2020-02-25" &
                            location == "S"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 20) +
  geom_area(data = filter(micro_8_plot, date > "2020-02-25" & date < "2020-12-21" &
                            location == "S"),
           aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  annotate("text", x = as.Date("2018-05-01"), y = 30, label = "SHELF", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) 

GeomRibbon$handle_na <- function(data, params) { data }

test <- chem_long %>% 
  filter(site_id == "QCS01")

test$ymax <-test$tchla
test$ymin <- 0
zl <- levels(test$group)
for ( i in 2:length(zl) ) {
   zi <- test$group==zl[i]
   zi_1 <- test$group==zl[i-1]
   test$ymin[zi] <- test$ymax[zi_1]
   test$ymax[zi] <- test$ymin[zi] + test$ymax[zi]
}

f6 <- test %>%
  ggplot(aes(x = date, ymax = ymax, ymin = ymin, fill = fct_rev(group))) + 
  geom_ribbon(color = "black") +
  scale_fill_manual(values = palette,
                    labels = c("Diat", "Dict", "Raph", "Dino", "Cryt", "Chlo", 
                               "Hapt", "Cyan")) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 12.5) +
  labs(y = "Phyto. ug/L") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        # strip.text.y = element_blank()
        ) +
  guides(fill = guide_legend(nrow = 1),
         color = "none")

f7 <- sf_less %>%
  filter(site_id == "DFO2") %>%
  ggplot() + 
  geom_area(data = filter(sf_less, date > "2018-01-01" & date < "2018-11-01" &
                            site_id == "DFO2"), 
           aes(x = date, y = chla, 
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(sf_less, date > "2018-11-01" & date < "2018-11-30" &
                           site_id == "DFO2"), 
           aes(x = date, y = chla, 
           fill = filter_type), stat = "identity", position = "stack",
           color = "black", width = 25) +
  geom_area(data = filter(sf_less, date > "2019-01-01" & date < "2019-12-31"&
                            site_id == "DFO2"),
           aes(x = date, y = chla, 
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
  geom_bar(data = filter(sf_less, date > "2020-01-01" & date < "2020-02-25" &
                            site_id == "DFO2"),
           aes(x = date, y = chla, 
           fill = filter_type), stat = "identity", position = "stack",
           color = "black", width = 25) +
  geom_area(data = filter(sf_less, date > "2020-02-25" & date < "2020-12-21" &
                            site_id == "DFO2"),
           aes(x = date, y = chla, 
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Greens") +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 12.5) +
  labs(y = bquote("Chla (mg" ~ m^-3*")")) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.5, 0.9),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(nrow = 1),
         color = "none")

f8 <- sf_less %>%
  filter(site_id == "KC10") %>%
  ggplot() + 
  geom_area(aes(x = date, y = chla, 
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Greens") +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 12.5) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(nrow = 2),
         color = "none")

f9 <- sf_less %>%
  ggplot() + 
  geom_area(data = filter(sf_less, year == 2018 & site_id == "QCS01"), 
           aes(x = date, y = chla,
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
    geom_area(data = filter(sf_less, year == 2019 & site_id == "QCS01"), 
           aes(x = date, y = chla,
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
      geom_area(data = filter(sf_less, year == 2020 & site_id == "QCS01"), 
           aes(x = date, y = chla,
           fill = filter_type), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Greens") +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 12.5) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(nrow = 2),
         color = "none")


fig2 <- (f1 + plot_layout(guides = "collect") & theme(legend.position = "top")) +
  (f3 + theme(legend.position = "none")) + (f5 + theme(legend.position = "none"))

fig3 <- fig2 / (f2 + f4 + f6) 

fig4 <- fig3 / (f7 + f8 + f9)

ggsave(here("figures_species_timeseries", "panel_phyto_chem_sf.png"), fig4,
       width = 18, height = 12, dpi = 300)
```

```{r}
t1 <- micro_8_plot %>%
  filter(location == "F") %>%
  ggplot() +
  geom_bar(aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 15) +
  # geom_bar(data = filter(micro_8_plot, date < "2018-02-01" & location == "F"), 
  #          aes(x = date, y = species_sum/100000,
  #          fill = scientificName2), stat = "identity", position = "stack",
  #          color = "black", width = 20) +
  # geom_area(data = filter(micro_8_plot, date > "2018-02-01" & date < "2018-11-01" &
  #                           location == "F"), 
  #          aes(x = date, y = species_sum/100000,
  #          fill = scientificName2), stat = "identity", position = "stack",
  #          color = "black") +
  # geom_bar(data = filter(micro_8_plot, date > "2018-11-01" & date < "2018-11-30" &
  #                          location == "F"), 
  #          aes(x = date, y = species_sum/100000,
  #          fill = scientificName2), stat = "identity", position = "stack",
  #          color = "black", width = 20) +
  # geom_area(data = filter(micro_8_plot, date > "2019-01-01" & date < "2019-12-31"&
  #                           location == "F"),
  #          aes(x = date, y = species_sum/100000,
  #          fill = scientificName2), stat = "identity", position = "stack",
  #          color = "black") +
  # geom_bar(data = filter(micro_8_plot, date > "2020-01-01" & date < "2020-02-25" &
  #                           location == "F"),
  #          aes(x = date, y = species_sum/100000,
  #          fill = scientificName2), stat = "identity", position = "stack",
  #          color = "black", width = 20) +
  # geom_area(data = filter(micro_8_plot, date > "2020-02-25" & date < "2020-12-21" &
  #                           location == "F"),
  #          aes(x = date, y = species_sum/100000,
  #          fill = scientificName2), stat = "identity", position = "stack",
  #          color = "black") +
  scale_fill_manual(values = palette_micro) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "FJORD", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(nrow = 2),
         color = "none")

t2 <- micro_8_plot %>%
  filter(location == "C") %>%
  ggplot() +
  geom_bar(aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 15) +
  scale_fill_manual(values = palette_micro) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "CHANNEL", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

t3 <- micro_8_plot %>%
  filter(location == "S") %>%
  ggplot() +
  geom_bar(aes(x = date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black", width = 15) +
  scale_fill_manual(values = palette_micro) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "SHELF", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

fig_test <- t1/t2/t3

ggsave(here("figures_species_timeseries", "test_single_1.png"), fig_test,
       width = 18, height = 12, dpi = 300)
```
```{r}
palette_micro2 <- c("#001219", #Bidd
                   "#005f73", #C.ten.
                   "#0a9396", #P.n.s.
                   "#94d2bd", #S.mar.
                   "#e9d8a6", #Hill
                   "#ee9b00", #Tel
                   "#bb3e03", #Olis
                   "#751628", #P.p.
                   "#71797E", #OD
                   "#E5E4E2") #OF


```



```{r}
mf <- micro_8_plot %>%
  filter(location == "F") %>%
  ggplot() +
  annotate(geom = "rect",
           xmin = as.Date("2018-03-01"), xmax = as.Date("2018-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-06-01"), xmax = as.Date("2018-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-09-01"), xmax = as.Date("2018-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-03-01"), xmax = as.Date("2019-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-06-01"), xmax = as.Date("2019-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-09-01"), xmax = as.Date("2019-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-03-01"), xmax = as.Date("2020-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-06-01"), xmax = as.Date("2020-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-09-01"), xmax = as.Date("2020-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  geom_bar(aes(x = month_date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro2) +
  # ggsci::scale_fill_d3() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "Fjord", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(nrow = 2),
         color = "none")

mc <- micro_8_plot %>%
  filter(location == "C") %>%
  ggplot() +
  annotate(geom = "rect",
           xmin = as.Date("2018-03-01"), xmax = as.Date("2018-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-06-01"), xmax = as.Date("2018-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-09-01"), xmax = as.Date("2018-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-03-01"), xmax = as.Date("2019-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-06-01"), xmax = as.Date("2019-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-09-01"), xmax = as.Date("2019-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-03-01"), xmax = as.Date("2020-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-06-01"), xmax = as.Date("2020-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-09-01"), xmax = as.Date("2020-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  geom_bar(aes(x = month_date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro2) +
  # ggsci::scale_fill_d3() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abundance ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "Channel", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

ms <- micro_8_plot %>%
  filter(location == "S") %>%
  ggplot() +
  annotate(geom = "rect",
           xmin = as.Date("2018-03-01"), xmax = as.Date("2018-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-06-01"), xmax = as.Date("2018-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-09-01"), xmax = as.Date("2018-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-03-01"), xmax = as.Date("2019-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-06-01"), xmax = as.Date("2019-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-09-01"), xmax = as.Date("2019-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-03-01"), xmax = as.Date("2020-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-06-01"), xmax = as.Date("2020-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-09-01"), xmax = as.Date("2020-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  geom_bar(aes(x = month_date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro2) +
  # ggsci::scale_fill_d3() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "SHELF", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

fig_month <- mf / mc / ms

ggsave(here("figures_species_timeseries", "test_single_1.png"), fig_month,
       width = 16, height = 10, dpi = 300)
```

```{r}
mf <- micro_8_plot %>%
  filter(location == "F") %>%
  ggplot() +
  annotate(geom = "rect",
           xmin = as.Date("2018-03-01"), xmax = as.Date("2018-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-06-01"), xmax = as.Date("2018-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-09-01"), xmax = as.Date("2018-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-03-01"), xmax = as.Date("2019-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-06-01"), xmax = as.Date("2019-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-09-01"), xmax = as.Date("2019-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-03-01"), xmax = as.Date("2020-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-06-01"), xmax = as.Date("2020-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-09-01"), xmax = as.Date("2020-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  geom_bar(aes(x = month_date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro2) +
  # ggsci::scale_fill_d3() +
  scale_x_date(breaks = seq(as.Date("2018-01-01"), as.Date("2021-01-01"),
                            by = "4 months"), date_minor_breaks = "1 month",
               date_labels = "%b%y",
               limits = c(as.Date("2018-01-01"), as.Date("2021-01-01"))) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 32)) +
  # ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "Fjord", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        # axis.text.x = element_blank(),
        # axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) +
  guides(fill = guide_legend(nrow = 2),
         color = "none")

mc <- micro_8_plot %>%
  filter(location == "C") %>%
  ggplot() +
  annotate(geom = "rect",
           xmin = as.Date("2018-03-01"), xmax = as.Date("2018-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-06-01"), xmax = as.Date("2018-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-09-01"), xmax = as.Date("2018-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-03-01"), xmax = as.Date("2019-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-06-01"), xmax = as.Date("2019-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-09-01"), xmax = as.Date("2019-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-03-01"), xmax = as.Date("2020-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-06-01"), xmax = as.Date("2020-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-09-01"), xmax = as.Date("2020-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  geom_bar(aes(x = month_date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro2) +
  # ggsci::scale_fill_d3() +
 scale_x_date(breaks = seq(as.Date("2018-01-01"), as.Date("2021-01-01"),
                            by = "4 months"), date_minor_breaks = "1 month",
               date_labels = "%b%y",
               limits = c(as.Date("2018-01-01"), as.Date("2021-01-01"))) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 32)) +
  # ylim(0, 32) +
  labs(y = bquote("Abundance ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "Channel", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        # axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

ms <- micro_8_plot %>%
  filter(location == "S") %>%
  ggplot() +
  annotate(geom = "rect",
           xmin = as.Date("2018-03-01"), xmax = as.Date("2018-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-06-01"), xmax = as.Date("2018-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2018-09-01"), xmax = as.Date("2018-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-03-01"), xmax = as.Date("2019-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-06-01"), xmax = as.Date("2019-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2019-09-01"), xmax = as.Date("2019-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-03-01"), xmax = as.Date("2020-06-01"),
           ymin = 0, ymax = Inf,
           fill = "darkolivegreen", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-06-01"), xmax = as.Date("2020-09-01"),
           ymin = 0, ymax = Inf,
           fill = "red2", color = "transparent", alpha = 0.2) +
  annotate(geom = "rect",
           xmin = as.Date("2020-09-01"), xmax = as.Date("2020-12-01"),
           ymin = 0, ymax = Inf,
           fill = "goldenrod1", color = "transparent", alpha = 0.2) +
  geom_bar(aes(x = month_date, y = species_sum/100000,
           fill = scientificName2), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_manual(values = palette_micro2) +
  # ggsci::scale_fill_d3() +
  scale_x_date(breaks = seq(as.Date("2018-01-01"), as.Date("2021-01-01"),
                            by = "4 months"), date_minor_breaks = "1 month",
               date_labels = "%b%y",
               limits = c(as.Date("2018-01-01"), as.Date("2021-01-01"))) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 32)) +
  # ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^5 ~ cells ~ L^-1*")")) +
  annotate("text", x = as.Date("2018-03-01"), y = 30, label = "SHELF", size = 10) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        # axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

fig_month <- mf + mc + ms

ggsave(here("figures_species_timeseries", "test_single_2.png"), fig_month,
       width = 20, height = 5, dpi = 300)
```











```{r}
#Looking at dominant dinoflagellate species
dino <- micro %>% 
  filter(group == "Dinoflagellata") %>% 
  group_by(scientificName) %>% 
  summarise(median = median(species_sum)) %>% 
  ungroup()

hetero <- micro %>% 
  filter(group == "Ciliophora" | genus == "Gymnodinium" | genus == "Gyrodinium"
         | genus == "Protoperidinium" | 
           genus == "Ceratium")

hetero_genus <- hetero %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, genus) %>% 
  summarise(sum_genus = sum(species_sum)) %>% 
  ungroup()

hetero_genus_na <- hetero %>% 
  filter(is.na(genus)) %>%
  distinct(scientificName)

tin <- micro %>% 
  filter(scientificName == "Tintinnina") %>% 
  select(date, site_id, genus = scientificName, sum_genus = species_sum)

oli <- micro %>% 
  filter(scientificName == "Oligotrichea") %>% 
  select(date, site_id, Oligotrichea = species_sum)

hetero_genus2 <- rbind(hetero_genus, tin)

hetero_genus_wide <- hetero_genus2 %>% 
  pivot_wider(names_from = genus, values_from = sum_genus, values_fill = 0)

hetero_genus_long <- hetero_genus_wide %>% 
  pivot_longer(cols = c(Gymnodinium:Tintinnina), names_to = "genus",
               values_to = "sum_genus")

hetero_genus_long <- hetero_genus_long %>% 
  left_join(oli)
```


```{r}
scale = 4


hetero_genus_long %>%
  ggplot() + 
  geom_area(aes(x = date, y = sum_genus/10^3, 
           fill = genus), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  geom_line(aes(date, Oligotrichea/10^3/scale), size = 2) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale,
                                         name = bquote("Oligo. (x"~10^3~L^-1*")"))) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  facet_grid(site_id~.) +
  # ylim(0, 32) +
  labs(y = bquote("Abund. ("~10^3 ~ cells ~ L^-1*")")) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        strip.background.y = element_blank(),
        strip.text.y = element_blank())
```


```{r}
h1 <- hetero_genus_long %>%
  filter(site_id == "DFO2") %>%
  ggplot() + 
  geom_area(aes(x = date, y = sum_genus/10^3, 
           fill = genus), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  geom_point(aes(date, Oligotrichea/10^3/scale), size = 2.5, fill = "white",
             stroke = 1, pch = 21) +
  scale_y_continuous(limits = c(0, 20), sec.axis = sec_axis(~.*scale,
                                         name = bquote("Oligo. (x"~10^3~L^-1*")"))) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  labs(y = bquote("Abund. ("~10^3 ~ cells ~ L^-1*")")) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.title.y.right = element_blank(),
        axis.text.y.right = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank())

h2 <- hetero_genus_long %>%
  filter(site_id == "KC10") %>%
  ggplot() + 
  geom_area(aes(x = date, y = sum_genus/10^3, 
           fill = genus), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  geom_point(aes(date, Oligotrichea/10^3/scale), size = 2.5, fill = "white",
             stroke = 1, pch = 21) +
  scale_y_continuous(limits = c(0, 20), sec.axis = sec_axis(~.*scale,
                                         name = bquote("Oligo. (x"~10^3~L^-1*")"))) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +

  labs(y = bquote("Abund. ("~10^3 ~ cells ~ L^-1*")")) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.title.y.right = element_blank(),
        axis.text.y.right = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.position = c(0.35, 0.72),
        strip.background.y = element_blank(),
        strip.text.y = element_blank())  +
  guides(fill = guide_legend(ncol = 1)) 

hetero_genus_long <- hetero_genus_long %>% 
  mutate(year = lubridate::year(date)) 

h3 <- hetero_genus_long %>%
  filter(site_id == "QCS01") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot() + 
  geom_area(data = filter(hetero_genus_long, year == 2018 & site_id == "QCS01"), 
           aes(x = date, y = sum_genus/10^3,
           fill = genus), stat = "identity", position = "stack",
           color = "black") +
  geom_area(data = filter(hetero_genus_long, year == 2019 & site_id == "QCS01"), 
           aes(x = date, y = sum_genus/10^3,
           fill = genus), stat = "identity", position = "stack",
           color = "black") +
    geom_area(data = filter(hetero_genus_long, year == 2020 & site_id == "QCS01"), 
           aes(x = date, y = sum_genus/10^3,
           fill = genus), stat = "identity", position = "stack",
           color = "black") +
  scale_fill_brewer(palette = "Set1") +
  geom_point(aes(date, Oligotrichea/10^3/scale), size = 2.5, fill = "white",
             stroke = 1, pch = 21) +
  scale_y_continuous(limits = c(0, 20), 
                     sec.axis = sec_axis(~.*scale,
                                         name = bquote("Oligotrichea. (x"~10^3~L^-1*")"))) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  labs(y = bquote("Abund. ("~10^3 ~ cells ~ L^-1*")")) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.title.y.left = element_blank(),
        axis.text.y.left = element_blank(),
        axis.text = element_text(colour = "black"),
        legend.title = element_blank(),
        legend.position = "none",
        strip.background.y = element_blank(),
        strip.text.y = element_blank()) 

```

```{r}
# het2 <- (h1 + plot_layout(guides = "collect") & theme(legend.position = "top") &
#            guides(fill = guide_legend(nrow = 1))) +
#   (h2 + theme(legend.position = "none")) + (h3 + theme(legend.position = "none"))

het2 <- h1 + h2 + h3

ggsave(here("figures_species_timeseries", "het.png"), het2,
       width = 16, height = 5, dpi = 300)
```

```{r}
fig2 <- (f1 + plot_layout(guides = "collect") &
           theme(legend.position = "top",
                 legend.text = element_text(size = 23))) +
  (f3 + theme(legend.position = "none")) + (f5 + theme(legend.position = "none"))

fig3 <- fig2 / (f2 + f4 + f6) 

fig4 <- fig3 / (f7 + f8 + f9)

fig5 <- fig4 / (h1 + h2 + h3)

ggsave(here("figures_species_timeseries", "phyto_chem_het.png"), fig5,
       width = 18, height = 16, dpi = 300)
```

```{r}
my <- hetero_genus_wide %>% 
  left_join(chem)

m_cryp <- micro %>% 
  filter(group == "Cryptophyta") %>% 
  select(date, site_id, scientificName, species_sum) %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate(t_all = Teleaulax + `Teleaulax acuta` + `Teleaulax amphioxeia`,
         all = Teleaulax + `Teleaulax acuta` + `Teleaulax amphioxeia` + Hillea)

my <- my %>% 
  left_join(m_cryp)

my %>% 
  ggplot(aes(x = cryp, y = Myrionecta)) +
  geom_point() +
  ylim(0, 2500) +
  ggpubr::stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, size = 8)

my %>% 
  ggplot(aes(x = Hillea, y = Myrionecta)) +
  geom_point() +
  ylim(0, 5000) +
  ggpubr::stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, size = 8)
```




