---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggpubr)
library(broom)
library(zoo)
library(gsw)
library(gridtext)
```

```{r}
#Upload data from my master data standardization sheet
# micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Upload microscopy abundance data in OBIS and long/tide format
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

data <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-08-04.csv"))

data <- data %>% 
  left_join(chl)

riv <- read_csv(here("files", "river.csv")) 

lk_wind <- read_csv(here("files", "wind_lookout.csv"))

lk_par <- read_csv(here("files", "lookout_par.csv"))

up <- read_csv(here("files", "upwell.csv"))

div <- read_csv(here("outputs", "diversity.csv"))
```

```{r}
riv <- riv %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_w <- riv %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA),
         Wan_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Wan_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_w <- riv_w %>% 
  select(date, Wan_b1, Wan_b25, Wan_b40)
```


```{r}
lk_wind2 <- lk_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

lk_da <- lk_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par <- lk_par %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par <- par %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA)) %>% 
  select(date, par_b1)
  
```

```{r}
data <- data %>% 
  left_join(riv_w) %>% 
  left_join(lk_da) %>% 
  left_join(par) %>% 
  left_join(div)
```

```{r}
data_pca <- data %>% 
  select(date, temp = temp_dm, sal = sal_dm, 
         dr = delta_rho_dm, no2 = no2_dm, sio2 = sio2_dm, po4 = po4_dm, 
         Wan_b1, 
         lk_w, lk_wd,
         par_b1,
         div)
```


```{r}
data_pca <- data_pca %>%
  drop_na()
```



```{r}
#Dinoflagellate species known to feed on diatoms
#Gonyaulax (skeletonema)
#Gymnodinium (skel + chain diatoms)
#Gyrodinium (diatom chains)
#Prorocentrum(skel)
#Protoperidinium (medium to large diatoms and dinoflagellates - 30-80%)
#Scrippsiella trochoideas (Skel)
#Oligotrichea (ciliate)
#Myrionecta rubra (cryptophytes)
#Dinophysis (Cryptophytes)
#Tintinnina (Ciliate)
#Fecal

#Things to correlate against 
#TChla
#S.mar (small)
#S.mar (large)
#S.mar (total)
#diatom abundance 
#Cryptophyte abundance

#First do the summarizing and filtering for each grouping I want correlated against.
s_sum <- micro %>% 
  filter(scientificName == "Skeletonema marinoi") %>% 
  select(date, site_id, scientificName, exp_count = species_sum)

#No correlations found for any site. 
pns <- micro %>%
  filter(scientificName == "Pseudo-nitzschia seriata") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

pn <- micro %>%
  filter(scientificName == "Pseudo-nitzschia") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

hill <- micro %>%
  filter(scientificName == "Hillea") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

tel <- micro %>%
  filter(scientificName == "Teleaulax") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

d_sum <- micro %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "Diatom sum") %>% 
  relocate(scientificName, .before = exp_count)

c_sum <- micro %>% 
  filter(group == "Cryptophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "crypto sum") %>% 
  relocate(scientificName, .before = exp_count)

chl_corr <- chl %>% 
  select(date, site_id, exp_count = tchla) %>% 
  mutate(scientificName = "TChla") %>% 
  relocate(scientificName, .before = exp_count)
```


```{r}
cor_exp <- rbind(s_sum, d_sum, c_sum, chl_corr, pn, pns, hill,
                 tel)
```

```{r}
data_pca_long <- data_pca %>% 
  select(-sio2, -po4) %>% 
  pivot_longer(cols = c(temp:par_b1), names_to = "name", values_to = "vals")
```


```{r}
data <- data_pca_long %>% 
  left_join(cor_exp)

data <- data %>% 
  filter(site_id == "KC10")
```


```{r}
data_nest <- data %>% 
  group_by(name, scientificName) %>%
  nest()

head(data_nest)

str(head(slice(data_nest, 1)))

cor_fun <- function(df) cor.test(df$vals,
                                 df$exp_count,
                                 method = "pearson") %>% tidy()

data_nest <- mutate(data_nest, model = map(data, cor_fun))

corr_pr <- select(data_nest, -data) %>% unnest()

corr_pr

corr_pr <- mutate(corr_pr, sig = ifelse(p.value < 0.05, "Sig.", "Non Sig."))
```

```{r}
# Order locations from fjord to shelf
driver_loc <- c("temp",
                "sal",
                "dr",
                "no2",
                "par_b1",
                "lk_w",
                "lk_wd",
                "Wan_b1",
                "Div")
                
                
                # "lev",
                # "rain",
                # "lev_b1",
                # "rain_b1")

phy_loc <- c(
             # "Skeletonema marinoi large",
             # "Skeletonema marinoi small",
             "Skeletonema marinoi",
             "Pseudo-nitzschia",
             "Pseudo-nitzschia seriata",
             "Hillea",
             "Teleaulax",
             "Diatom sum",
             "crypto sum",
             "TChla")

#Chemtax - Specify order of phyto groups for figures
corr_pr <- arrange(mutate(corr_pr,
                         name = factor(name, levels = driver_loc)))

corr_pr <- arrange(mutate(corr_pr,
                         scientificName = factor(scientificName,
                                                 levels = phy_loc)))

```

```{r}
ggplot()+
  geom_tile(data = corr_pr,
            aes(scientificName, name, fill = estimate),
            size = 1,
            colour = "white")+
  geom_tile(data = filter(corr_pr, sig == "Sig."),
            aes(scientificName, name),
            size = 1.5,
            colour = "black",
            fill = "transparent") +
  geom_text(data = corr_pr,
            aes(scientificName, name, label = round(estimate, 2), 
                fontface = ifelse(sig == "Sig.", "bold", "plain")),
            size = 7) +
  scale_x_discrete(labels = c("crypto sum" = "Cryp.", 
                              "Diatom sum" = "Diat.",
                              "Skeletonema marinoi" = "S.mar.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Pseudo-nitzschia" = "P.n.",
                              "Hillea" = "Hill.",
                              "Teleaulax" = "Tel.")) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1 , 1), space = "Lab", 
                       name = "Pearson Correlation") +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        legend.key.height = unit(2.5, "cm"),
        legend.title = element_text(size = 30, angle = -90),
        legend.title.align = 0.5) +
        guides(fill = guide_colourbar(title.position = "right")) 

ggsave(here("figures_cor", "kc10_pearson_test.png"),
       width = 12, height = 12, dpi = 300)

# https://dominicroye.github.io/en/2019/tidy-correlation-tests-in-r/
```

```{r}
test <- data %>% 
  filter(name == "Wan_b1" & scientificName == "Skeletonema marinoi") 


test %>% 
  mutate(month = lubridate::month(date)) %>% 
  ggplot(aes(x = vals, y = exp_count, color = as.factor(month))) +
  geom_point()
```







