---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggpubr)
library(broom)
```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Uploading chl data that has been converted to TChla
chl <- read_csv(here("outputs", "chl_hplc_merged.csv"))

#Uploading size separated S.marinoi counts.
sm_size <- read_csv(here("outputs", "s_mar_size.csv"))

fec <- read_csv(here("outputs", "fecal_master_2022-03-16_het.csv"))
```

```{r}
#Remove QU39
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}

#Careful here - removing original s.marinoi counts and replacing with size separated counts. Ensure that the outputs are comparable.
micro <- micro %>% 
  filter(!scientificName == "Skeletonema marinoi")

micro <- rbind(micro, sm_size)

```

```{r}
#Dinoflagellate species known to feed on diatoms
#Gonyaulax (skeletonema)
#Gymnodinium (skel + chain diatoms)
#Gyrodinium (diatom chains)
#Prorocentrum(skel)
#Protoperidinium (medium to large diatoms and dinoflagellates - 30-80%)
#Scrippsiella trochoideas (Skel)
#Oligotrichea (ciliate)
#Myrionecta rubra (cryptophytes)
#Dinophysis (Cryptophytes)
#Tintinnina (Ciliate)
#Fecal

#Things to correlate against 
#TChla
#S.mar (small)
#S.mar (large)
#S.mar (total)
#diatom abundance 
#Cryptophyte abundance

#First do the summarizing and filtering for each grouping I want correlated against.
s_sum <- micro %>% 
  filter(scientificName == "Skeletonema marinoi small" | 
           scientificName == "Skeletonema marinoi small") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "Skeletonema marinoi sum") %>% 
  relocate(scientificName, .before = exp_count)

s_small <- micro %>% 
  filter(scientificName == "Skeletonema marinoi small") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

s_large <- micro %>% 
  filter(scientificName == "Skeletonema marinoi large") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

d_sum <- micro %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "Diatom sum") %>% 
  relocate(scientificName, .before = exp_count)

c_sum <- micro %>% 
  filter(group == "Cryptophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "crypto sum") %>% 
  relocate(scientificName, .before = exp_count)

chl_corr <- chl %>% 
  select(date, site_id, exp_count = chl) %>% 
  mutate(scientificName = "TChla") %>% 
  relocate(scientificName, .before = exp_count)

cor_exp <- rbind(s_sum, s_small, s_large, d_sum, c_sum, chl_corr)

cor_het <- micro %>% 
  filter(genus == "Gonyaulax" |
           genus == "Gymnodinium" |
           genus == "Gyrodinium" |
           genus == "Prorocentrum" |
           genus == "Protoperidinium" |
           genus == "Scrippsiella" |
           genus == "Dinophysis" |
           genus == "Katodinium") %>% 
  group_by(date, site_id, genus) %>% 
  summarise(het_count = sum(species_sum)) %>% 
  select(date, site_id, name = genus, het_count)



cor_het2 <- micro %>%
  filter(group == "Ciliophora") %>% 
  select(date, month_surv, site_id, name = scientificName, het_count = species_sum)

cor_het3 <- rbind(cor_het, cor_het2)
           
fec_merge <- fec %>%
  filter(!site_id == "QU39") %>% 
  mutate(name = "fecal") %>% 
  select(date, month_surv, site_id, name, het_count = fecal)

cor_het4 <- rbind(cor_het3, fec_merge)
```


```{r}
data <- cor_het4 %>% 
  left_join(cor_exp)

data_nest <- data %>% 
  group_by(name, scientificName) %>%
  nest()

head(data_nest)

str(head(slice(data_nest, 1)))

cor_fun <- function(df) cor.test(df$het_count,
                                 df$exp_count,
                                 method = "pearson") %>% tidy()

data_nest <- mutate(data_nest, model = map(data, cor_fun))

corr_pr <- select(data_nest, -data) %>% unnest()

corr_pr

corr_pr <- mutate(corr_pr, sig = ifelse(p.value < 0.05, "Sig.", "Non Sig."))
```

```{r}
#Order locations from fjord to shelf
het_loc <- c("fecal",
               "Myrionecta rubra",
               "Oligotrichea",
               "Tintinnina",
               "Dinophysis",
               "Gonyaulax",
               "Gymnodinium",
               "Gyrodinium",
               "Katodinium",
               "Prorocentrum",
               "Protoperidinium",
               "Scrippsiella")

#Chemtax - Specify order of phyto groups for figures
corr_pr <- arrange(mutate(corr_pr,
                         name = factor(name, levels = het_loc)))

```




```{r}
ggplot()+
  geom_tile(data = corr_pr,
            aes(scientificName, name, fill = estimate),
            size = 1,
            colour = "white")+
  geom_tile(data = filter(corr_pr, sig == "Sig."),
            aes(scientificName, name),
            size = 1.5,
            colour = "black",
            fill = "transparent") +
  geom_text(data = corr_pr,
            aes(scientificName, name, label = round(estimate, 2), 
                fontface = ifelse(sig == "Sig.", "bold", "plain")),
            size = 7) +
  scale_x_discrete(labels = c("crypto sum" = "Cryp", 
                              "Diatom sum" = "Diat",
                              "Skeletonema marinoi large" = "S.mar.L",
                              "Skeletonema marinoi small" = "S.mar.S",
                              "Skeletonema marinoi sum" = "S.mar.")) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1 , 1), space = "Lab", 
                       name = "Pearson Correlation") +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        legend.key.height = unit(2.5, "cm"),
        legend.title = element_text(size = 30, angle = -90),
        legend.title.align = 0.5) +
        guides(fill = guide_colourbar(title.position = "right")) 

ggsave(here("figures_good", "correlations_heterotrophs_pearson_katodinium.png"),
       width = 12, height = 12, dpi = 300)

# https://dominicroye.github.io/en/2019/tidy-correlation-tests-in-r/
```





