---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggpubr)
library(broom)
library(zoo)
```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Uploading size separated S.marinoi counts.
sm_size <- read_csv(here("outputs", "s_mar_size.csv"))

#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

data <- data %>% 
  left_join(chl)

riv <- read_csv(here("files", "river.csv")) 

riv_b <- read_csv(here("files", "riv_bella_4.csv"))

ethel_wind <- read_csv(here("files", "ethel_wind.csv"))

lk_wind <- read_csv(here("files", "wind_lookout.csv"))

lk_par <- read_csv(here("files", "lookout_par.csv"))
```

```{r}
#Remove QU39
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}

#Careful here - removing original s.marinoi counts and replacing with size separated counts. Ensure that the outputs are comparable.
micro <- micro %>% 
  filter(!scientificName == "Skeletonema marinoi")

micro <- rbind(micro, sm_size)

```

```{r}
riv <- riv %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_w <- riv %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA),
         Wan_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Wan_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_w <- riv_w %>% 
  select(date, Wan_b1, Wan_b25, Wan_b40)
```

```{r}
riv_b <- riv_b %>% 
  mutate(Date = lubridate::mdy(Date))

riv_b <- riv_b %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_b <- riv_b %>%
  mutate(Bel_b1 = rollmeanr(lag(dis, 1), k = 5, fill = NA),
         Bel_b5 = rollmeanr(lag(dis, 5), k = 4, fill = NA),
         Bel_b10 = rollmeanr(lag(dis, 10), k = 4, fill = NA),
         Bel_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Bel_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_b <- riv_b %>% 
  select(date, Bel_b1, Bel_b5, Bel_b10, Bel_b25, Bel_b40)
```

```{r}
ethel_wind2 <- ethel_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

ew_da <- ethel_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, eth_w = w_b1, eth_wd = wd_b1)

lk_wind2 <- lk_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

lk_da <- lk_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par <- lk_par %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par <- par %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA)) %>% 
  select(date, par_b1)
  
```

```{r}
data <- data %>% 
  left_join(riv_w) %>% 
  left_join(riv_b) %>% 
  left_join(ew_da) %>% 
  left_join(lk_da) %>% 
  left_join(par)
```

```{r}
data_pca <- data %>% 
  select(date, month, month_surv, site_id, temp = temp_dm, sal = sal_dm, 
         drho = delta_rho_dm, no2 = no2_dm, sio2 = sio2_dm, po4 = po4_dm, 
         secchi = secchi_depth, 
         Wan_b1, 
         # Bel_b1,
         eth_w, eth_wd, 
         lk_w, lk_wd,
         par_b1,
         )

#Changing site_id to location 
data_pca <- data_pca %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

data_pca <- data_pca %>%
  drop_na()
```



```{r}
#Dinoflagellate species known to feed on diatoms
#Gonyaulax (skeletonema)
#Gymnodinium (skel + chain diatoms)
#Gyrodinium (diatom chains)
#Prorocentrum(skel)
#Protoperidinium (medium to large diatoms and dinoflagellates - 30-80%)
#Scrippsiella trochoideas (Skel)
#Oligotrichea (ciliate)
#Myrionecta rubra (cryptophytes)
#Dinophysis (Cryptophytes)
#Tintinnina (Ciliate)
#Fecal

#Things to correlate against 
#TChla
#S.mar (small)
#S.mar (large)
#S.mar (total)
#diatom abundance 
#Cryptophyte abundance

#First do the summarizing and filtering for each grouping I want correlated against.
s_sum <- micro %>% 
  filter(scientificName == "Skeletonema marinoi small" | 
           scientificName == "Skeletonema marinoi small") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "Skeletonema marinoi sum") %>% 
  relocate(scientificName, .before = exp_count)

s_small <- micro %>% 
  filter(scientificName == "Skeletonema marinoi small") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

s_large <- micro %>% 
  filter(scientificName == "Skeletonema marinoi large") %>%
  select(date, site_id, scientificName, exp_count = species_sum)


#No corellations found for any site. 
pns <- micro %>%
  filter(scientificName == "Pseudo-nitzschia seriata") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

pn <- micro %>%
  filter(scientificName == "Pseudo-nitzschia") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

hill <- micro %>%
  filter(scientificName == "Hillea") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

tel <- micro %>%
  filter(scientificName == "Teleaulax") %>%
  select(date, site_id, scientificName, exp_count = species_sum)

d_sum <- micro %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "Diatom sum") %>% 
  relocate(scientificName, .before = exp_count)

c_sum <- micro %>% 
  filter(group == "Cryptophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(exp_count = sum(species_sum)) %>% 
  ungroup() %>% 
  mutate(scientificName = "crypto sum") %>% 
  relocate(scientificName, .before = exp_count)

chl_corr <- chl %>% 
  select(date, site_id, exp_count = tchla) %>% 
  mutate(scientificName = "TChla") %>% 
  relocate(scientificName, .before = exp_count)
```


```{r}
cor_exp <- rbind(s_sum, s_small, s_large, d_sum, c_sum, chl_corr, pn, pns, hill,
                 tel)
```

```{r}
data_pca_long <- data_pca %>% 
  pivot_longer(cols = c(temp:par_b1), names_to = "name", values_to = "vals")
```


```{r}
data <- data_pca_long %>% 
  left_join(cor_exp)

data <- data %>%
  filter(location == "C")

# | location == "S" | location == "F"
```


```{r}
data_nest <- data %>% 
  group_by(name, scientificName) %>%
  nest()

head(data_nest)

str(head(slice(data_nest, 1)))

cor_fun <- function(df) cor.test(df$vals,
                                 df$exp_count,
                                 method = "pearson") %>% tidy()

data_nest <- mutate(data_nest, model = map(data, cor_fun))

corr_pr <- select(data_nest, -data) %>% unnest()

corr_pr

corr_pr <- mutate(corr_pr, sig = ifelse(p.value < 0.05, "Sig.", "Non Sig."))
```

```{r}
test <- data %>% 
  distinct(date, location)

# Order locations from fjord to shelf
driver_loc <- c("temp",
                "sal",
                "drho",
                "no2",
                "sio2",
                "po4",
                "secchi",
                "par_b1",
                "eth_w",
                "eth_wd",
                "lk_w",
                "lk_wd",
                "Wan_b1",
                "Bel_b1")

phy_loc <- c("Diatom sum",
             "Skeletonema marinoi large",
             "Skeletonema marinoi small",
             "Skeletonema marinoi sum",
             "Pseudo-nitzschia",
             "Pseudo-nitzschia seriata",
             "crypto sum",
             "Hillea",
             "Teleaulax",
             "TChla")

#Chemtax - Specify order of phyto groups for figures
corr_pr <- arrange(mutate(corr_pr,
                         name = factor(name, levels = driver_loc)))

corr_pr <- arrange(mutate(corr_pr,
                         scientificName = factor(scientificName,
                                                 levels = phy_loc)))

```




```{r}
ggplot()+
  geom_tile(data = corr_pr,
            aes(scientificName, name, fill = estimate),
            size = 1,
            colour = "white")+
  geom_tile(data = filter(corr_pr, sig == "Sig."),
            aes(scientificName, name),
            size = 1.5,
            colour = "black",
            fill = "transparent") +
  geom_text(data = corr_pr,
            aes(scientificName, name, label = round(estimate, 2), 
                fontface = ifelse(sig == "Sig.", "bold", "plain")),
            size = 7) +
  scale_x_discrete(labels = c("crypto sum" = "Cryp.", 
                              "Diatom sum" = "Diat.",
                              "Skeletonema marinoi large" = "S.mar.L",
                              "Skeletonema marinoi small" = "S.mar.S",
                              "Skeletonema marinoi sum" = "S.mar.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Pseudo-nitzschia" = "P.n.",
                              "Hillea" = "Hill.",
                              "Teleaulax" = "Tel.",
                              "Phaeocystis pouchetii" = "P.p.")) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1 , 1), space = "Lab", 
                       name = "Pearson Correlation") +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.title.y = element_blank(),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.03, 0.30),
        legend.direction = "vertical",
        axis.line = element_line(colour = "black"),
        legend.background = element_blank(),
        legend.key.height = unit(2.5, "cm"),
        legend.title = element_text(size = 30, angle = -90),
        legend.title.align = 0.5) +
        guides(fill = guide_colourbar(title.position = "right")) 

ggsave(here("figures_good", "correlations_test_pearson_C4_10.png"),
       width = 12, height = 12, dpi = 300)

# https://dominicroye.github.io/en/2019/tidy-correlation-tests-in-r/
```
```{r}
data %>% 
  filter(name == "secchi" & scientificName == "Skeletonema marinoi large") %>% 
  ggplot(aes(y = vals, x = exp_count)) +
  geom_point() 

```
```{r}
sms <- data %>% 
  filter(scientificName == "Diatom sum" & name == "sal")

riv_w_j <- riv_w %>% 
    mutate(year = lubridate::year(date),
           yday = lubridate::yday(date)) %>% 
  select(date, year, yday, Wan_b1)

riv_b_j <- riv_b %>% 
    mutate(year = lubridate::year(date),
           yday = lubridate::yday(date)) %>% 
  select(date, year, yday, Bel_b1)

riv_w_j <- riv_w_j %>% 
  left_join(sms) %>% 
  left_join(riv_b_j)
```


```{r}
coeff <- 1000


riv_w_j %>% 
  ggplot(aes(x = yday)) +
  geom_line(aes(y = Wan_b1), size = 2, color = "blue") +
  geom_line(aes(y = Bel_b1), size = 2, color = "red") +
  geom_point(aes(y = exp_count/coeff), size = 4, pch = 21, fill = "darkgreen",
             color = "black", stroke = 2) +
  scale_y_continuous(name = "Wannock",
                     sec.axis = sec_axis(~.*coeff, name="Diatom Abundance")) +
  facet_grid(. ~ year) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(color = 'black'))

ggsave(here("figures_good", "Channel_Wannock_Diatom_Abund.png"), 
       width = 16, height = 8, dpi = 300)


```
```{r}
riv_w_j %>% 
  ggplot(aes(x = yday)) +
  geom_line(aes(y = Bel_b1), size = 2) +
  geom_point(aes(y = exp_count/coeff), size = 4) +
  scale_y_continuous(name = "Wannock",
                     sec.axis = sec_axis(~.*coeff, name = "Diatom Abundance")) +
  facet_grid(. ~ year) +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(color = 'black'))
```





```{r}
coeff2 <- 100

riv_w_j %>% 
  ggplot(aes(x = yday)) +
  geom_line(aes(y = Wan_b1)) +
  geom_point(aes(y = vals/coeff2)) +
  scale_y_continuous(name = "First Axis",
                     sec.axis = sec_axis(~.*coeff, name="Second Axis")) +
  facet_grid(. ~ year)
```




