---
title: "Pigment clustering"
output: html_notebook
---

```{r}
#Loading packages

library(tidyverse)
library(readxl) #Read excel files
library(here) #Save to working directory
library(ggcorrplot) #Correlation plots
library(GGally)
library(patchwork)

#Statistics and dendrogram plotting
library(vegan)
library(cluster)
library(factoextra)
library(ggdendro)
library(stats)
library(corrplot)
library(RColorBrewer)
```

```{r}
#Upload data

#pigment data using pigments selected for chemtax analysis
pigs_all <- read_csv(here("files", "2023-09-14_HakaiData_hplc.csv"))

#Upload microscopy abundance data in OBIS and long/tide format
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

```

```{r}
#Filtering for records with results and cutting down columns
pigs_red <- pigs_all %>% 
  filter(analyzing_lab == "USC") %>% 
  select(date, site_id, `_19_but`:all_chl_a) 

pigs_red_2 <- pigs_red %>% 
  select(date, site_id,chl_c3, chl_c1_c2, peri, BF = `_19_but`,
         fuco, pras = prasinoxanthin, viola = violaxanthin, HF = `_19_hex`,
         allo = alloxanthin, zea = zeaxanthin, lut = lutein,
         chl_b, tchla = all_chl_a)
```

```{r}
pigs_sum <- pigs_red_2 %>% 
  pivot_longer(c(chl_c3:tchla), names_to = "pig", values_to = "conc") %>% 
  group_by(pig) %>% 
  summarise(mean = mean(conc),
            median = median(conc),
            min = min(conc),
            max = max(conc))

zea <- pigs_red_2 %>% 
  select(zea, chl_b) %>%
  filter(chl_b > 0) %>% 
  mutate(zea_chlb = zea/chl_b) %>% 
  filter(zea_chlb > 0.28)

zea_2 <- zea %>% 
  summarise(mean = mean(zea_chlb),
            median = median(zea_chlb),
            min = min(zea_chlb),
            max = max(zea_chlb))

lut <- pigs_red_2 %>% 
  select(date, site_id, lut, chl_b) %>%
  mutate(lut_chlb = lut/chl_b)

pras <- pigs_red_2 %>% 
  select(date, site_id, pras, chl_b, tchla) %>%
  mutate(pras_tchla = pras/tchla)

pras_sum <- pras %>% 
  summarise(mean = mean(pras_tchla))

#I should looks into this! 4 samples have pigment for dino-1, which represents toxic species.
gyro <- pigs_all %>% 
  select(date, site_id, gyro = gyroxanthin_diester) %>% 
  filter(gyro > 0)

dino_stat <- micro %>% 
  filter(group == "Dinoflagellata") %>% 
  group_by(scientificName) %>% 
  summarise(mean = mean(species_sum),
            median = median(species_sum),
            min = min(species_sum),
            max = max(species_sum),
            n = n())

d_acu <- micro %>% 
  filter(scientificName == "Dinophysis acuminata")

raphido <- micro %>% 
  filter(group == "Raphidiophyta")

dictyo <- micro %>% 
  filter(group == "Dictyochophyta" | group == "Chrysophyta")

mering <- micro %>% 
  filter(genus == "Meringosphaera")

12/51
```

```{r}
group_distinct <- micro %>% 
  distinct(group)

green <- micro %>% 
  filter(group == "Chlorophyta-Prasinophyta" | group == "Euglenophyta") %>% 
  group_by(scientificName_accepted) %>% 
  summarise(mean = mean(species_sum),
            median = median(species_sum),
            min = min(species_sum),
            max = max(species_sum),
            n = n())

eugl <- micro %>% 
  filter(group == "Euglenophyta") 

micro_sum <- micro %>% 
  filter(group == "Bacillariophyta" |
         group == "Chrysophyta" | 
         group == "Cryptophyta" |
         group == "Dictyochophyta" |
         group == "Dinoflagellata" |
         group == "Euglenophyta" |
         group == "Chlorophyta-Prasinophyta" | 
         group == "Prymnesiophyta-Haptophyta" |
         group == "Raphidiophyta") %>%
  group_by(date, site_id, group) %>% 
  summarise(gr_sum = sum(species_sum)) %>% 
  group_by(date, site_id) %>% 
  mutate(sum = sum(gr_sum)) %>% 
  ungroup() %>% 
  mutate(perc = gr_sum/sum*100)

micro_sum_stat <- micro_sum %>% 
  group_by(group) %>% 
  summarise(mean = mean(perc),
            median = median(perc),
            min = min(perc),
            max = max(perc),
            n = n())

cryp_dom <- micro_sum %>% 
  filter(group == "Cryptophyta" & perc >  75 & date > "2019-01-01")

cryp_date <- cryp_dom$date

#So here I look at the pigment ratios for cryptophytes where they are dominant in terms of relative abundance.
cryp_rat <- pigs_red_2 %>% 
  filter(date %in% cryp_date) %>% 
  select(chl_c1_c2, allo, tchla) %>% 
  mutate(allo_tchla = allo/tchla,
         chlc12_tchla = chl_c1_c2/tchla) %>% 
  summarise(mean_allo = mean(allo_tchla),
            mean_chlc12 = mean(chlc12_tchla))

#Try looking where they have very high abundance???
```

```{r}
#Calculating pigment:TChla ratios and removing all chla
pigs_rat <- pigs_red_2 %>%
  select(-(date:site_id)) %>% 
  mutate(across(everything()), . / tchla) %>% 
  select(-tchla)



```

```{r}
hc <- pigs_rat[, 1:12]

metadata <- pigs_red_2 %>%
  select(date, site_id) %>%
  mutate(year = lubridate::year(date)) %>% 
  unite(sample_name, c(date, site_id), sep = "_stn_") 

labs_list <- metadata$sample_name

#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(hc) <- labs_list
```
```{r}

dist <- dist(hc, method = "euclidean")

euc_ward <- hclust(dist, "ward.D2")

# https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cophenetic.html
#Cophenetic score to assess quality of clustering.
coph <- cophenetic(euc_ward)
cor(dist, coph) 
```


```{r}
#Looking at tests to derive cluster number - turning off for now because adds time.
fviz_nbclust(hc, FUN = hcut, method = "wss")
fviz_nbclust(hc, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(hc, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```



```{r}
k <- 4
clust <- cutree(euc_ward, k = k)

clust.df <- data.frame(label = rownames(hc),
                                   cluster = factor(clust))
```

```{r}
# extract dendrogram segment data for plotting
dend <- as.dendrogram(euc_ward)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label)
```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(hc$height[length(hc$height) - ((k-2):(k-1))])
```

```{r}
#Testing joining dendrogram ends
clust.df_join <- clust.df %>% 
  rename(sample_name = label)


dendrogram_ends <- dendrogram_ends %>% 
  left_join(clust.df_join)
```

```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$cluster)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 4, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

clust_color <- as.character(color_list$color)
names(clust_color) <- color_list$.
```

```{r}

#Plotting dendrogram - saving for incorporation later.
ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend), size = 1) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = cluster),
              size = 3) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name,
                                       color = cluster),
           hjust = 1, angle = 0, size = 9, show_guide  = FALSE) +
 geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3,
                            ymin = 0, ymax = ymax),
            color = "black", fill = NA, size = 0.3) +
 scale_color_manual(values = clust_color) +
 scale_y_reverse(limits = c(1.2, -0.3)) +
 coord_flip() +
 ylim(-0.6, 1.25) +
 theme_bw() +
 theme(legend.position = c(0.70, 0.90),
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 36)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_chemtax", "HC_station_pigment_ratios_c4.png"),
       width = 12, height = 25, dpi = 300)

```

```{r}
pigs_rat$sample_name <- metadata$sample_name

pigs_rat <- pigs_rat %>%
  left_join(clust.df_join) %>%
  relocate(cluster, .after = sample_name)


pigs_rat_long <- pigs_rat %>% 
  pivot_longer(c(chl_c3:chl_b), names_to = "pigment", values_to = "ratio")

```
```{r}
pigs_rat_long_med <- pigs_rat_long %>%  
  group_by(cluster, pigment) %>% 
  summarise(med_rat = median(ratio)) %>% 
  ungroup() 

pigs_rat_long_med %>% 
  ggplot(aes(x = as.factor(cluster), y = med_rat, fill = pigment)) +
  geom_col(stat = "identity", position = "dodge", color = "black") +
  scale_fill_brewer(palette = "Paired") +
  labs(y = "Median Pigment Ratio",
       x = "Cluster") +
  theme_bw() +
  theme(text = element_text(size = 36, color = "black"))
  

ggsave(here("figures_chemtax", "cluster_median_ratios_c4.png"),
       width = 12, height = 6, dpi = 300)
```


```{r}
#Trying distance method

#Performing hierarchical clustering on the pigment ratio data

#Tranposing data so pigments are rows
t <- t(pigs_rat)

#Calculating distances for clustering based on pearson correlations
dist <- get_dist(t, stand = FALSE, method = "pearson")


#Applying hierarchical clustering using Wards linkage method
hc <- hclust(dist, "ward.D2")


# https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cophenetic.html
#Cophenetic score to assess quality of clustering.
coph <- cophenetic(hc)
cor(dist, coph) 

#For all data (NSoG and CSoG combined, value = 0.84, which is high)
```
```{r}
#This step sets clusters. Currently, I am not using.

k <- 4
clust <- cutree(hc, k = k)

clust.df <- clust.df <- data.frame(label = rownames(t),
                                   cluster = factor(clust))


```


```{r}
# extract dendrogram segment data for plotting
dend <- as.dendrogram(hc)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label)
```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(hc$height[length(hc$height) - ((k-2):(k-1))])
```

```{r}
#Testing joining dendrogram ends
clust.df_join <- clust.df %>% 
  rename(sample_name = label)


dendrogram_ends <- dendrogram_ends %>% 
  left_join(clust.df_join)
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$cluster)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 4, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

clust_color <- as.character(color_list$color)
names(clust_color) <- color_list$.
```

```{r}

#Plotting dendrogram - saving for incorporation later.
ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend), size = 1) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = cluster),
              size = 3) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name,
                                       color = cluster),
           hjust = 1, angle = 0, size = 9, show_guide  = FALSE) +
 # geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3,
 #                            ymin = 0, ymax = ymax),
 #            color = "black", fill = NA, size = 0.3) +
 scale_color_manual(values = clust_color) +
                    # name = "Cluster",
                    # labels = c("Hapt/Dict/Pela",
                    #            "Small Flag./Cyan",
                    #            "Diat",
                    #            "Dino")) +
 scale_y_reverse(limits = c(1.2, -0.3)) +
 # ggtitle("Ratios") +
 coord_flip() +
 geom_hline(yintercept = 0.9, size = 1.5) +
 ylim(-0.4, 2.5) +
 theme_bw() +
 theme(legend.position = c(0.85, 0.87),
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 36)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_chemtax", "kramer_dendro.png"), 
       width = 9, height = 12, dpi = 300)

```

#Making correlation plots 
 
```{r}
pigs_corr <- pigs_red_2 %>%
  select(-(date:site_id))  

pigs_corr <- pigs_corr %>% 
  select(TChla = tchla,
         Fuco = fuco,
         chlc3 = chl_c3,
         Chlc12 = chl_c1_c2,
         Peri = peri,
         BF, 
         HF,
         Allo = allo,
         Pras = pras,
         Viola = viola,
         Lut = lut,
         Zea = zea,
         Chlb = chl_b)

#Making correlation matrix
cor_A <- round(cor(pigs_corr), 2)

#Making significance' matrix
p.mat_A <- cor_pmat(pigs_corr)
```

```{r}
tchla <- pigs_red_2$tchla

tchla_comb <- cbind(pigs_rat, tchla)


pigs_rat2 <- tchla_comb %>% 
  select(TChla = tchla,
         Fuco = fuco,
         chlc3 = chl_c3,
         Chlc12 = chl_c1_c2,
         Peri = peri,
         BF, 
         HF,
         Allo = allo,
         Pras = pras,
         Viola = viola,
         Lut = lut,
         Zea = zea,
         Chlb = chl_b)

#Making correlation matrix
cor_B <- round(cor(pigs_rat2), 2)

#Making significance' matrix
p.mat_B <- cor_pmat(pigs_rat2)
```






```{r}
ggcorrplot(cor_A,
  p.mat = p.mat_A,
  method = "circle",
  type = "lower",
  sig.level = 0.01,
  lab = TRUE,
  insig = "blank") +
  # title = "pigments (ug/L)") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90, color = 'black', vjust = 0.4),
        axis.text.y = element_text(angle = 0, color = 'black'),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")

ggsave(here("figures_chemtax", "corr_conc.png"),
       width = 10, height = 8, dpi = 300)
```

```{r}
ggcorrplot(cor_B,
  p.mat = p.mat_B,
  method = "square",
  type = "lower",
  sig.level = 0.01,
  lab = TRUE,
  insig = "blank",
  title = "pigments (ug/L)") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90, color = 'black', vjust = 0.4),
        axis.text.y = element_text(angle = 0, color = 'black'),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")


```


```{r}
cor_B[lower.tri(cor_B)] <- cor_A[lower.tri(cor_A)]
p.mat_B[lower.tri(p.mat_B)] <- p.mat_A[lower.tri(p.mat_A)]
```


```{r}
ggcorrplot(cor_B,
  p.mat = p.mat_B,
  method = "square",
  sig.level = 0.01,
  lab = TRUE,
  insig = "blank",
  title = "pigments (ug/L)") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90, color = 'black', vjust = 0.4),
        axis.text.y = element_text(angle = 0, color = 'black'),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")
```

```{r}
ggcorrplot(cor_B[,13:1],
  p.mat = p.mat_B[,13:1],
  method = "square",
  sig.level = 0.01,
  lab = TRUE,
  insig = "blank") +
  ggtitle("Concentrations") +
  ylab("Ratios") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90, color = 'black', vjust = 0.4),
        axis.text.y = element_text(angle = 0, color = 'black'),
        plot.title = element_text(hjust = 1, size = 25), 
        # axis.title.y = element_blank(),
        axis.title.y = element_text(hjust = -0.02),
        axis.title.x = element_blank())

ggsave(here("figures_chemtax", "corr_conc_rats_combined_labels.png"),
       width = 10, height = 8, dpi = 300)

#To remove diagonal
# https://statisticsglobe.com/remove-diagonal-from-correlation-matrix-plot-r
```

```{r}
# pigs_all_2 <- pigs_all %>% 
#     mutate(viola_group = case_when(date == "2018-07-25" ~ "2018-07-25",
#                                    date == "2018-06-24" ~ "2018-06-24",
#                                    date == "2018-07-09" ~ "2018-07-09",
#                                    !(date == "2018-07-25" | 
#                                      date == "2018-06-04" |
#                                      date == "2018-07-09") ~ "Other"))
# 
# pigs_all_2 <- pigs_all_2 %>% 
#   mutate(viola_Tchla = Viola/`ALL Chl a`,
#          zea_Tchla = Zeax/`ALL Chl a`, 
#          fuco_Tchla = Fuco/`ALL Chl a`)
# 
#   
# f1 <- pigs_all_2 %>% 
#   filter(Region == "SofG2018" | Region == "SofG2019") %>% 
#   ggplot(aes(x = `ALL Chl a`, y = Viola, fill = viola_group, shape = Station)) +
#   geom_point(size = 7.5, stroke = 1.5) +
#   scale_fill_brewer(palette = "RdYlBu") +
#   scale_shape_manual(values = c(21, 22, 23 ,24, 25)) +
#   theme_bw() +
#   xlab(bquote('TChla ('*mg~m^-3~')')) +
#   ylab(bquote('Viola ('*mg~m^-3~')')) +
#   # xlim(0, 128) +
#   theme(text = element_text(size = 28),
#         axis.text = element_text(colour = "black"),
#         legend.position = c(0.39, 0.75)) +
#   labs(fill = "Date", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21), ncol = 2),
#          shape = guide_legend(ncol = 3))
# 
# 
# f2 <- pigs_all_2 %>% 
#   filter(Region == "SofG2018" | Region == "SofG2019") %>% 
#   ggplot(aes(x = Zeax, y = Viola, fill = viola_group, shape = Station)) +
#   geom_point(size = 7.5, stroke = 1.5) +
#   scale_fill_brewer(palette = "RdYlBu") +
#   scale_shape_manual(values = c(21, 22, 23 ,24, 25)) +
#   theme_bw() +
#   xlab(bquote('Zea ('*mg~m^-3~')')) +
#   ylab(bquote('Viola ('*mg~m^-3~')')) +
#   theme(text = element_text(size = 28),
#         axis.text = element_text(colour = "black"),
#         axis.text.y = element_blank(),
#         axis.title.y = element_blank(),
#         legend.position = "none") +
#   labs(fill = "Date", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# f3 <- pigs_all_2 %>% 
#   filter(Region == "SofG2018" | Region == "SofG2019") %>% 
#   ggplot(aes(x = Fuco, y = Viola, fill = viola_group, shape = Station)) +
#   geom_point(size = 7.5, stroke = 1.5) +
#   scale_fill_brewer(palette = "RdYlBu") +
#   scale_shape_manual(values = c(21, 22, 23 ,24, 25)) +
#   theme_bw() +
#   xlab(bquote('Fuco ('*mg~m^-3~')')) +
#   ylab(bquote('Viola ('*mg~m^-3~')')) +
#   theme(text = element_text(size = 28),
#         axis.text = element_text(colour = "black"),
#         legend.position = "none") +
#   labs(fill = "Date", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# f4 <- pigs_all_2 %>% 
#   filter(Region == "SofG2018" | Region == "SofG2019") %>% 
#   ggplot(aes(x = `Chl b`, y = Viola, fill = viola_group, shape = Station)) +
#   geom_point(size = 7.5, stroke = 1.5) +
#   scale_fill_brewer(palette = "RdYlBu") +
#   scale_shape_manual(values = c(21, 22, 23 ,24, 25)) +
#   theme_bw() +
#   xlab(bquote('Chlb ('*mg~m^-3~')')) +
#   ylab(bquote('Viola ('*mg~m^-3~')')) +
#   theme(text = element_text(size = 28),
#         axis.text = element_text(colour = "black"),
#         legend.position = "none",
#         axis.text.y = element_blank(),
#         axis.title.y = element_blank(),) +
#   labs(fill = "Date", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
# 
# fig <- f1 + f2 + f3 + f4
# 
# ggsave(here("figures", "raphio_scatters.png"), fig,
#        width = 14, height = 14, dpi = 300)

```
```{r}
# pigs_all_2 %>% 
#   filter(Region == "SofG2018" | Region == "SofG2019") %>% 
#   ggplot(aes(x = `ALL Chl a`, y = Fuco, fill = viola_group, shape = Station)) +
#   geom_point(size = 7.5, stroke = 1.5) +
#   scale_fill_brewer(palette = "RdYlBu") +
#   scale_shape_manual(values = c(21, 22, 23 ,24, 25)) +
#   theme_bw() +
#   xlab(bquote('Chlb ('*mg~m^-3~')')) +
#   ylab("Viola (ug/L)") +
#   theme(text = element_text(size = 28),
#         axis.text = element_text(colour = "black"),
#         legend.position = "none",
#         axis.text.y = element_blank(),
#         axis.title.y = element_blank(),) +
#   labs(fill = "Date", shape = "Station") +
#   guides(fill = guide_legend(override.aes = list(shape = 21)))
```


