---
title: "R Notebook"
output: html_notebook
---



```{r}
#Load packages
library(tidyverse) #Data wrangling
library(readxl) #Import excel files
library(here) #File structure management
```

```{r}
ctd <- read_csv(here("files", "ctd_qcs01_kc10_dfo2.csv"))
```

```{r}
ctd <- ctd %>% 
  rename(date = `Measurement time`,
         pres = `Pressure (dbar)`,
         sal = `Salinity (PSU)`,
         temp = `Temperature (deg C)`,
         date = `Measurement time`,
         station = Station,
         cast_pk = `Cast PK`,
         par = `PAR (umol m-2 s-1)`)

ctd <- ctd %>% 
  mutate(date = lubridate::date(date))

```

```{r}
ctd %>% 
  mutate(year = lubridate::year(date)) %>%
  filter(date == "2019-05-13" | date == "2019-06-09" | date == "2019-07-07" |
           date == "2019-08-06" | date == "2019-08-31" |
           date == "2020-05-01" | date == "2020-06-08" |
           date == "2020-07-05" | date == "2020-09-04") %>% 
  filter(station == "QCS01" | station == "HKP03" | station == "HKP01") %>% 
  ggplot(aes(y = pres, x = sal, fill = station)) + 
  geom_point(pch = 21, size = 3) +
  geom_vline(xintercept = 31) +
  scale_y_reverse(lim = c(25, 0)) +
  facet_grid(. ~ date)

ggsave(here("figures_good", "ctd_profs_sal.png"),
       width = 16, height = 6, dpi = 300)
```
```{r}
ctd %>% 
  mutate(year = lubridate::year(date)) %>%
  filter(date == "2019-05-13" | date == "2019-06-09" | date == "2019-07-07" |
           date == "2019-08-06" | date == "2019-08-31" |
           date == "2020-05-01" | date == "2020-06-08" |
           date == "2020-07-05" | date == "2020-09-04") %>% 
  filter(station == "QCS01" | station == "HKP03" | station == "HKP01") %>% 
  ggplot(aes(y = pres, x = `Fluorometry Chlorophyll (ug/L)`, fill = station)) + 
  geom_point(pch = 21, size = 3) +
  geom_vline(xintercept = 5) +
  scale_y_reverse(lim = c(25, 0)) +
  facet_grid(. ~ date)

ggsave(here("figures_good", "ctd_profs_flu.png"),
       width = 16, height = 6, dpi = 300)
```





```{r}
kc10_dates <- ctd %>% 
  filter(station == "KC10") %>% 
  distinct(date)

ctd %>% 
  mutate(year = lubridate::year(date)) %>%
  filter(date == "2019-05-11" | date == "2019-06-10" | date == "2019-07-10" |
           date == "2019-08-03" | date == "2019-09-01" |
           date == "2020-04-30" | date == "2020-07-02" |
           date == "2020-08-07" | date == "2020-09-03") %>% 
  filter(station == "KC10") %>% 
  ggplot(aes(y = pres, x = sal, fill = station)) + 
  geom_point(pch = 21, size = 3) +
  geom_vline(xintercept = 31) +
  scale_y_reverse(lim = c(25, 0)) +
  facet_grid(. ~ date)
```
```{r}
dfo2_dates <- ctd %>% 
  filter(station == "DFO2") %>% 
  distinct(date)

ctd %>% 
  mutate(year = lubridate::year(date)) %>%
  filter(date == "2019-05-14" | date == "2019-06-11" | date == "2019-07-06" |
           date == "2019-08-05" | date == "2019-09-02" |
           date == "2020-05-04" | date == "2020-06-06" |
           date == "2020-07-06" | date == "2020-08-08" | date == "2020-09-05") %>% 
  filter(station == "DFO2") %>% 
  ggplot(aes(y = pres, x = sal, fill = station)) + 
  geom_point(pch = 21, size = 3) +
  geom_vline(xintercept = 31) +
  scale_y_reverse(lim = c(25, 0)) +
  facet_grid(. ~ date)
```







```{r}
ctd %>% 
  mutate(year = lubridate::year(date)) %>%
  filter(date == "2019-05-13" | date == "2019-06-09" | date == "2019-07-07" |
           date == "2019-08-06" | date == "2019-08-31" |
           date == "2020-05-01" | date == "2020-06-08" |
           date == "2020-07-05" | date == "2020-09-04") %>% 
  filter(station == "QCS01" | station == "HKP03" | station == "HKP01") %>% 
  ggplot(aes(y = pres, x = temp, fill = station)) + 
  geom_point(pch = 21, size = 3) +
  # geom_vline(xintercept = 31) +
  scale_y_reverse(lim = c(25, 0)) +
  facet_grid(. ~ date)

ggsave(here("figures_good", "ctd_profs_temp.png"),
       width = 16, height = 6, dpi = 300)




```
```{r}
ctd %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  filter(station == "QCS01" & month == 7) %>% 
  ggplot(aes(y = pres, x = sal, fill = as.factor(year))) + 
  geom_point(pch = 21, size = 2) +
  # geom_vline(xintercept = 31) +
  scale_y_reverse(lim = c(20, 0)) 
```










