---
title: "pca_environemtal_data"
output: html_notebook
---
```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(cluster)
library(ggdendro)
library(RColorBrewer)
library(indicspecies)
library(factoextra)
```


```{r}
#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_merge_2022-03-16_het.csv"))

#Upload microscopy data in long format
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv"))
```

```{r}
#This just ensures that there are no exact duplicates introduced through joining. There aren't here, but it must have occured in earlier versions and I am keeping it in-case I make changes in the future.
data <- data %>% 
  distinct(date, site_id, .keep_all = TRUE)

#Removing QU39 for this worksheet
data <- data %>% 
  filter(!site_id == "QU39")

#Remove QU39 from the microscopy data
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
#selecting data I am going to use with the PCA - I think a case could be made to only include sio@ as this is what comes out as a driver in RDA and also, they all point in the same direction and have the same strength in PCA biplot.
pigments <- data %>% 
  select(date, month, month_surv, site_id, micro_chl, nano_chl, pico_chl,
         cyan:diat)

#Changing site_id to location 
pigments <- pigments %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)


#Changning site to location for microscopy data
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)

micro <- micro %>% 
    mutate(year = lubridate::year(date)) %>% 
  relocate(year, .after = date)
```

```{r}
sf <- pigments %>% 
  select(date:pico_chl)

sf <- sf %>% 
  drop_na()

sf_long <- sf %>% 
  pivot_longer(!date:location, names_to = "size", values_to = "chla")

sf_mean <- sf_long %>% 
  group_by(location, size) %>% 
  summarise(mean_chla = mean(chla)) %>% 
  ungroup() %>% 
  group_by(location) %>% 
  mutate(sum_chla = sum(mean_chla)) %>% 
  ungroup() %>% 
  mutate(mean_perc = mean_chla/sum_chla)
```
```{r}
chem <- pigments %>% 
  select(date:location, cyan:diat) 

chem <- chem %>% 
  drop_na()

chem_long <- chem %>% 
  pivot_longer(!date:location, names_to = "group", values_to = "tchla")

chem_mean <- chem_long %>% 
  group_by(location, group) %>% 
  summarise(mean_tchla = mean(tchla)) %>% 
  ungroup() %>% 
  group_by(location) %>% 
  mutate(sum_tchla = sum(mean_tchla)) %>% 
  ungroup() %>% 
  mutate(mean_perc = mean_tchla/sum_tchla)
```
```{r}
#Removing cyanobacteria as their counts are not reliable
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")

micro <- micro %>% 
  filter(!group == "Metazoa") %>% 
  filter(!group == "Protozoa")

micro_group <- micro %>%
  filter(!group == "Choanoflagellata", !group == "Ciliophora", 
         !group == "Ebriidea", !group == "Kinetoplastidea", !group == "Metazoa", 
         !group == "Cyanobacteria", !group == "Protozoa")
```

```{r}

micro_sum <- micro_group %>% 
  group_by(location, date, group) %>% 
  summarise(group_sum = sum(species_sum)) %>% 
  ungroup()

micro_mean <- micro_sum %>% 
  group_by(location, group) %>% 
  summarise(mean_abund = mean(group_sum)) %>% 
  ungroup() %>% 
  group_by(location) %>% 
  mutate(sum_abund = sum(mean_abund)) %>% 
  ungroup() %>% 
  mutate(mean_perc = mean_abund/sum_abund)

```


Plotting Size-fractionated results

```{r}
#Order phytoplankton groups roughly from smallest to largest - create order list
order_sf <- c("pico_chl", "nano_chl", "micro_chl")

#Chemtax - Specify order of phyto groups for figures
sf_mean <- arrange(mutate(sf_mean, size = factor(size,
                                              levels = order_sf)))

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
sf_mean <- arrange(mutate(sf_mean,
                         location = factor(location, levels = order_loc)))
```

```{r}
sf_fig <- sf_mean %>% 
  ggplot(aes(x = as.factor(location), y = mean_perc, fill = size)) + 
  geom_bar(stat = "identity", position = "stack", color = "black", size = 0.75) +
  scale_fill_brewer(palette = "Greens", labels = c(expression(Pico[CHL]),
                                                   expression(Nano[CHL]),
                                                   expression(Micro[CHL]))) +
  labs(y = "%") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.text = element_text(colour = "black"),
        axis.line = element_line(colour = "black")) 
```

Chemtax


```{r}
#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "pela", "hapt", "pras2", "pras3", "cryp",
                "dino", "raph", "diat")

#Chemtax - Specify order of phyto groups for figures
chem_mean <- arrange(mutate(chem_mean, group = factor(group,
                                              levels = order_chem)))

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
chem_mean <- arrange(mutate(chem_mean,
                         location = factor(location, levels = order_loc)))

#Set Color palette for plotting. Currently based on QU39 manuscript. Brewer has some good ones for R style.
palette_chem <- c("#ff8000", #1 - Diatoms (orange)
                  "#4d6600", #3 - Raphidophytes (dark green)
                  "#ff0000", #4 - Dinoflagellates (Red)
                  "#ffff00", #5 - Cryptophytes (yellow)
                  "#6EFF7C", #6 - prasinophytes-2 (lighter green)
                  "#00ff00", #6 - prasinophytes-3 (light green)
                  "#7d4dcc", #7 - Haptophytes (purple)
                  "#ff99c7", #2 - Pelagophytes (pink)
                  "#000000") #8 - Cyanobacteria (black)
```

```{r}
chem_fig <- chem_mean %>% 
  ggplot(aes(x = as.factor(location), y = mean_perc, fill = fct_rev(group))) + 
  geom_bar(stat = "identity", position = "stack", color = "black", size = 0.75) +
  scale_fill_manual(values = palette_chem) +
  # ggsci::scale_fill_npg() +
  labs(y = "%") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.text = element_text(colour = "black"),
        axis.line = element_line(colour = "black")) 
  # guides(fill = guide_legend(nrow = 3)) 
```

Microscopy

```{r}
#Order phytoplankton groups roughly from smallest to largest - create order list
micro_mean$group <- factor(micro_mean$group,
                         levels = c("Prymnesiophyta-Haptophyta",
                                    "Euglenophyta",
                                    "Chlorophyta-Prasinophyta",
                                    "Cryptophyta",
                                    "Dinoflagellata",
                                    "Raphidiophyta",
                                    "Dictyochophyta",
                                    "Chrysophyta",
                                    "Bacillariophyta"))

#Setting colour pallete for microscopy data - roughly comparable to chemtax data
palette_micro <- c("#ff8000", #Diatoms 
                   "#2642D5", #Chrysophytes
                   "#ff99c7", #Dicto (same color as chryso as same pig. group)
                   "#4d6600", #Raph
                   "#ff0000", #Dino
                   "#ffff00", #Crypto
                   "#00ff00", #Chloro (chloro and eugleno same colour, same pig. group)
                   "#93FFCA", #Eugleno
                   "#7d4dcc" #Hapto
                   )

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_mean <- arrange(mutate(micro_mean,
                         location = factor(location, levels = order_loc)))


```

```{r}
micro_fig <- micro_mean %>% 
  ggplot(aes(x = as.factor(location), y = mean_perc, fill = fct_rev(group))) + 
  geom_bar(stat = "identity", position = "stack", color = "black", size = 0.75) +
  scale_fill_manual(values = palette_micro, labels = c("diat", "chry", "dict",
                                                       "raph", "dino", "cryp",
                                                       "chlo", "eugl", "hapt")) +
  # ggsci::scale_fill_npg() +
  labs(y = "%") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.text = element_text(colour = "black"),
        axis.line = element_line(colour = "black")) 
  # guides(fill = guide_legend(nrow = 3))  
```


#Looking at Shannon index values.

```{r}
#Selecting columns
micro_piv1 <- micro %>% 
  select(date, month, month_surv, site_id, location, group, scientificName, species_sum)

micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

micro_diat <- micro_piv1 %>% 
  filter(group == "Bacillariophyta")

micro_dino <- micro_piv1 %>% 
  filter(group == "Dinoflagellata")

#pivoting wider so species are columns. 
micro_diat <- micro_diat %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_dino <- micro_dino %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_all <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Pulling out species counts for transform and input into clustering and NMDS
species_diat <- micro_diat[, 7:ncol(micro_diat)]

species_dino <- micro_dino[, 7:ncol(micro_dino)]

species_all <- micro_all[, 7:ncol(micro_all)]
```

```{r}

#Look at shannon diversity

shannon_diat <- diversity(species_diat)
shannon_dino <- diversity(species_dino)
shannon_all <- diversity(species_all)

shannon_diat <- as_tibble(shannon_diat)
shannon_diat <- shannon_diat %>% 
  rename(diat = value)

shannon_dino <- as_tibble(shannon_dino)
shannon_dino <- shannon_dino %>% 
  rename(dino = value)

shannon_all <- as_tibble(shannon_all)
shannon_all <- shannon_all %>% 
  rename(all = value)

shannon <- cbind(shannon_diat, shannon_dino, shannon_all)

shannon$location <- micro_diat$location

```

```{r}
shannon_long <- shannon %>% 
  pivot_longer(!location, names_to = "type", values_to = "value")
```

```{r}
shannon_mean <- shannon_long %>% 
  group_by(location, type) %>% 
  summarise(mean_shannon = median(value),
            sdev_shannon = sd(value)) %>% 
  ungroup()
```

```{r}
#Chemtax - Specify order of phyto groups for figures
shannon_mean <- arrange(mutate(shannon_mean,
                         location = factor(location, levels = order_loc)))
```

```{r}

shan_fig <- shannon_mean %>% 
  ggplot(aes(x = as.factor(location), y = mean_shannon,
             group = type, fill = type)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black", size = 0.75) +
  # scale_fill_brewer(palette = "Set1") +
  scale_fill_npg() +
  labs(y = "Shannon H'") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        text = element_text(size = 30),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.text = element_text(colour = "black"),
        axis.line = element_line(colour = "black")) 

```


```{r}
test <- sf_fig / chem_fig / micro_fig / shan_fig

ggsave(here("figures_good", "test_2.png"), test,
       width = 9, height = 16, dpi = 300)
```













```{r}
#Let's look at difference in diatom 
shannon$location <- micro_diat$location
shannon$date <- micro_diat$date
shannon$month_surv <- micro_diat$month_surv

shannon <- shannon %>% 
  mutate(year = lubridate::year(date))

shannon_f <- shannon %>% 
  filter(location == "F") %>% 
  select(year, month_surv, diat_f = diat, dino_f = dino)

shannon_s <- shannon %>% 
  filter(location == "S") %>% 
  select(year, month_surv, diat_s = diat, dino_s = dino)

shannon_join <- shannon_s %>% 
  left_join(shannon_f) %>% 
  mutate(diat_diff = diat_s - diat_f,
         dino_diff = dino_s - dino_f)

shannon_compare <- shannon_join %>% 
  select(year, month_surv, diat_diff, dino_diff) %>% 
  pivot_longer(!year:month_surv, names_to = "type", values_to = "value")

```

```{r}
shannon_compare %>% 
  ggplot(aes(x = as.factor(month_surv), y = value, fill = type)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  facet_grid(.~year) +
  theme_bw()  
```

```{r}
micro %>% 
  filter(class == "Bacillariophyceae"& !date %in% date_list) %>% 
  group_by(site_id, scientificName_accepted) %>% 
  mutate(n_obs = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.factor(site_id), y = scientificName,
             fill = n_obs)) +
  geom_tile(color = "black") +
  geom_text(aes(label= n_obs)) +
  scale_fill_gradient(low = "white",
                       high = "red")

ggsave(here("figures_good", "test2.png"),
       width = 8, height = 16, dpi = 300)
```
```{r}
micro_test <- micro %>% 
  distinct(year, month_surv, location, .keep_all = TRUE) %>% 
  group_by(year, month_surv) %>% 
  mutate(n_obs = n()) %>% 
  ungroup() %>% 
  filter(n_obs < 3)

date_list <- micro_test$date


```


```{r}
micro %>% 
  filter(class == "Dinophyceae" & !date %in% date_list) %>% 
  group_by(site_id, scientificName_accepted) %>% 
  mutate(n_obs = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.factor(site_id), y = scientificName,
             fill = n_obs)) +
  geom_tile(color = "black") +
  geom_text(aes(label= n_obs)) +
  scale_fill_gradient(low = "white",
                       high = "red")

ggsave(here("figures_good", "test2-dino.png"),
       width = 8, height = 16, dpi = 300)
```

```{r}
micro_ps <- micro %>% 
  filter(scientificName == "Pseudo-nitzschia seriata" & year == 2019)

micro_ps %>% 
  ggplot(aes(x = month_surv, y = species_sum, color = location)) + 
  geom_line()
```


```{r}
data %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x = month_surv, y = temp_dm, color = site_id)) + 
  geom_line()

```

```{r}
micro_df <- micro %>% 
  filter(scientificName == "Chaetoceros debilis")

micro_df %>% 
  ggplot(aes(x = month_surv, y = species_sum, color = location)) + 
  geom_line() +
  geom_point() +
  facet_grid(.~year)
```







```{r}
# https://towardsdatascience.com/common-mistakes-in-cluster-analysis-and-how-to-avoid-them-eb960116d773
```
