---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(patchwork)
library(RColorBrewer)

#Need to go through and test these

```

```{r}
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Uploading chl data that has been converted to TChla
chl <- read_csv(here("outputs", "chl_hplc_merged.csv"))

#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))

```

```{r}
#Remove QU39
micro <- micro %>% 
  filter(!site_id == "QU39")

micro <- micro %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .after = date)
```

```{r}
# Changing site_id to location 
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```

```{r}
#Trying to look at only species present in 10% of samples
#How many samples

species_10 <- micro %>%
  group_by(scientificName) %>%
  summarise(n_obs = n()) %>%
  ungroup() %>%
  mutate(perc_obs = n_obs/50) %>%
  filter(perc_obs >= 0.10)
# 
species_10_list <- species_10$scientificName
# 
micro <- micro %>% 
  filter(scientificName %in% species_10_list)

```

```{r}
micro_diat <- micro %>% 
  filter(class == "Bacillariophyceae")

micro_dino <- micro %>% 
  filter(class == "Dinophyceae")

distinct <- micro %>% 
  distinct(group)

micro_other <- micro %>% 
  filter(group == "Chlorophyta-Prasinophyta" | group == "Chrysophyta" | 
           group =="Cryptophyta" | group == "Dictyochophyta" |
           group == "Euglenophyta" | group == "Prymnesiophyta-Haptophyta")
```

```{r}
micro_genus <- micro_diat %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, location, month_surv, genus) %>% 
  summarize(sum_genus = sum(species_sum)) %>% 
  ungroup()

micro_piv <- micro_genus %>% 
  select(date, site_id, location, month_surv, genus, sum_genus)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = genus, values_from = sum_genus) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_long <- micro_piv %>% 
  pivot_longer(!date:month_surv, names_to = "genus", values_to = "count")

micro_long <- micro_long %>% 
  group_by(date, location) %>% 
  mutate(sum = sum(count)) %>% 
  ungroup() %>% 
  mutate(perc = count/sum)
```
```{r}
micro_genus_dino <- micro_dino %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, location, month_surv, genus) %>% 
  summarize(sum_genus = sum(species_sum)) %>% 
  ungroup()

micro_piv_dino <- micro_genus_dino %>% 
  select(date, site_id, location, month_surv, genus, sum_genus)

#pivoting wider so species are columns. 
micro_piv_dino <- micro_piv_dino %>% 
  pivot_wider(names_from = genus, values_from = sum_genus) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_long_dino <- micro_piv_dino %>% 
  pivot_longer(!date:month_surv, names_to = "genus", values_to = "count")

micro_long_dino <- micro_long_dino %>% 
  group_by(date, location) %>% 
  mutate(sum = sum(count)) %>% 
  ungroup() %>% 
  mutate(perc = count/sum)
```
```{r}
micro_genus_other <- micro_other %>% 
  filter(!is.na(genus)) %>% 
  group_by(date, site_id, location, month_surv, genus) %>% 
  summarize(sum_genus = sum(species_sum)) %>% 
  ungroup()

micro_piv_other <- micro_genus_other %>% 
  select(date, site_id, location, month_surv, genus, sum_genus)

#pivoting wider so species are columns. 
micro_piv_other <- micro_piv_other %>% 
  pivot_wider(names_from = genus, values_from = sum_genus) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_long_other <- micro_piv_other %>% 
  pivot_longer(!date:month_surv, names_to = "genus", values_to = "count")

micro_long_other <- micro_long_other %>% 
  group_by(date, location) %>% 
  mutate(sum = sum(count)) %>% 
  ungroup() %>% 
  mutate(perc = count/sum)
```


```{r}
micro_long <- micro_long %>% 
  left_join(chl)
```
```{r}

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_long <- arrange(mutate(micro_long,
                         location = factor(location, levels = order_loc)))

#Chemtax - Specify order of phyto groups for figures
micro_long_dino <- arrange(mutate(micro_long_dino,
                         location = factor(location, levels = order_loc)))

#Chemtax - Specify order of phyto groups for figures
micro_long_other <- arrange(mutate(micro_long_other,
                         location = factor(location, levels = order_loc)))
```

```{r}
diat_global <- micro_long %>%
  group_by(location, genus) %>% 
  summarize(perc = mean(perc)) %>% 
  mutate(across(where(is.numeric), ~ num(., digits = 2)))

dino_global <- micro_long_dino %>%
  group_by(location, genus) %>% 
  summarize(perc = mean(perc)) %>% 
  mutate(across(where(is.numeric), ~ num(., digits = 2)))

other_global <- micro_long_other %>%
  group_by(location, genus) %>% 
  summarize(perc = mean(perc)) %>% 
  mutate(across(where(is.numeric), ~ num(., digits = 2)))

colourCount = length(unique(micro_long$genus))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
```


```{r}
diat_global %>% 
  ggplot(aes(x = as.factor(location), y = perc, fill = genus)) +
  geom_bar(stat = "identity", position = "stack", color = "black") +
  scale_fill_manual(values = getPalette(colourCount)) +
  theme_bw() +
  ylab("Rel. Abund. Diatoms (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))


ggsave(here("figures_good", "test2.png"),
       width = 9, height = 5.5, dpi = 300)
```
```{r}
dino_global %>% 
  ggplot(aes(x = as.factor(location), y = perc, fill = genus)) +
  geom_bar(stat = "identity", position = "stack", color = "black") +
  scale_fill_manual(values = getPalette(colourCount)) +
  theme_bw() +
  ylab("Rel. Abund. Dinoflag. (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))


ggsave(here("figures_good", "test2_dino.png"),
       width = 9, height = 5.5, dpi = 300)
```

```{r}
other_global %>% 
  ggplot(aes(x = as.factor(location), y = perc, fill = genus)) +
  geom_bar(stat = "identity", position = "stack", color = "black") +
  scale_fill_manual(values = getPalette(colourCount)) +
  theme_bw() +
  ylab("Rel. Abund. Flag. (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))


ggsave(here("figures_good", "test2_other.png"),
       width = 9, height = 5.5, dpi = 300)
```

```{r}
micro_long_dino %>% 
  mutate(year = lubridate::year(date)) %>% 
  # filter(perc_genus >= 0.05) %>% 
  ggplot(aes(x = as.factor(location), y = perc, 
             fill = genus)) + 
  geom_bar(stat = "identity", position = "stack", color = "black") +  
  facet_grid(year ~ month_surv) +
  scale_fill_manual(values = getPalette(colourCount)) +
  theme_bw() +
  ylab("Rel. Abund. Dinoflag. (%)") +
  theme(text = element_text(size = 25),
        axis.title.x = element_blank(),
        # axis.text.y = element_blank(),
        axis.text = element_text(colour = "black"),
        # legend.position = "top",
        # legend.direction = "horizontal",
        legend.title = element_blank()) +
  guides(fill = guide_legend(ncol = 1))

ggsave(here("figures_good", "dino_genus.png"),
       width = 16, height = 8, dpi = 300)
```

```{r}
kato <- micro %>% 
  filter(scientificName == "Katodinium")

pro <- micro %>% 
  filter(genus == "Prorocentrum")
```



