---
title: "R Notebook"
output: html_notebook
---

```{r}
#Load packages
library(tidyverse)
library(patchwork)
library(here)
library(readr)
library(readxl)
library(ggpubr)
```

```{r}
#Upload microscopy data merged with physical and biogeochemical measures
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv")) 

#Uploading Chlorophyll data
tchla <- read_csv(here("outputs", "tchla_calibration_2022-08-04.csv"))

```

```{r}
#Remove QU39
data <- data %>% 
  filter(!site_id == "QU39")
```

```{r}
#Adding location to sheets rather than station names

#Making a location column.
data <- data %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))
```

```{r}
#Selecting important physical/chemical parameters and mankin names easier to work with.
env <- data %>% 
  mutate(year = lubridate::year(date)) %>% 
  select(location, month, month_surv, year, t = temp_dm, s = sal_dm,
         dr = delta_rho_dm, no2 = no2_dm, po4 = po4_dm, sio2 = sio2_dm,
         secchi = secchi_depth)

tchla <- tchla %>% 
  mutate(year = lubridate::year(date)) %>%
  relocate(year, .after = date)
```

```{r}
#Order locations from fjord to shelf for plotting
order_loc <- c("F", "C", "S")

#Apply ordering to data for plotting
env <- arrange(mutate(env,
                       location = factor(location, levels = order_loc)))

tchla <- arrange(mutate(tchla,
                       location = factor(location, levels = order_loc)))
```

```{r}
#Working with nutrient ratios

#For the N:P ratio - removing times when nutrients are zero and calculating ratios
n_p <- env %>% 
  select(location, no2, po4) %>% 
  filter(po4 > 0 & no2 > 0) %>% 
  mutate(n_p = no2/po4)
  
#Calculating stats for N:P by station
n_p_loc <- n_p %>% 
  group_by(location) %>% 
  summarise(across(n_p, .f = list(mean = mean,
                                  sd = sd,
                                  median = median,
                                  min = min,
                                  max = max),
                   na.rm = TRUE)) %>% 
  ungroup()

#Doing the same steps as above for the Si:N ratio.
s_n <- env %>% 
  select(location, sio2, no2) %>% 
  filter(no2 > 0 & sio2 > 0) %>% 
  mutate(s_n = sio2/no2) 


s_n_loc <- s_n %>% 
  group_by(location) %>% 
  summarise(across(s_n, .f = list(mean = mean, 
                                  sd = sd,
                                  median = median,
                                  min = min,
                                  max = max ),
                   na.rm = TRUE)) %>% 
  ungroup() 


```

```{r}
#Trying Kruskal Wallis Test followed by Dunn's test if differences found. Instead of creating separate code for each parameter - just changing code depending on what I am looking at. Need to switch datasheet to env when looking at physical parameters.

#Reason Kruskal Wallis test is used is because many (but not all) of the parameters do not meet assumptions for one way ANOVA, so figure better to be consistent and use same test across. When data plotted, clear that there are differences suggesting test is working. 

#Kruskal Wallace test
kruskal.test(n_p ~ location, data = n_p)

#Dunn Test to look where differences are occuring.
FSA::dunnTest(n_p$n_p ~ n_p$location,
              method = "bonferroni")

```

```{r}
#Plotting out box and whiskers showing differences in parameters between stations

#Only want to show statistical information where there are significant relationships. Setting up combinations here for use in plots

#Fjord-Channel, Fjord-Shelf
fc_fs <- list( c("F", "C"), c("F", "S")) #my_comparisons
fs_cs <- list(c("C", "S"), c("F", "S")) #my_comparisons2
fc_cs_fs <- list( c("F", "C"), c("C", "S"), c("F", "S")) #my_comparisons3

```


```{r}
#Boxplot - temp
f1 <- ggboxplot(env, x = "location", y = "t",
          fill = "location", palette = "jco", size = 0.5) + 
  stat_compare_means(comparisons = fc_fs,
                     label.y = c(14.5, 15.2), size = 7) + 
  stat_compare_means(label.y = 16.5, size = 6) +
  theme_bw() +
  labs(y = expression("Temperature ("*~degree*C*")")) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black")) 
  

#Boxplot - Salinity
f2 <- ggboxplot(env, x = "location", y = "s",
          fill = "location", palette = "jco", size = 0.5)+ 
  stat_compare_means(comparisons = fs_cs,
                     label.y = c(32.2, 32.7), size = 7) + 
  stat_compare_means(label.y = 33.5, size = 6) +
  theme_bw() +
  labs(y = "Salinity") +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black")) 


#boxplot - delta_rho
f3 <- ggboxplot(env, x = "location", y = "dr",
          fill = "location", palette = "jco", size = 0.5)+ 
  stat_compare_means(comparisons = fc_cs_fs,
                     label.y = c(16, 9, 18), size = 7) + 
  stat_compare_means(label.y = 21.5, size = 6) +
  theme_bw() +
  ylim(0, 22) +
  labs(y = expression(Delta*rho)) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black")) 

f4 <- ggboxplot(env, x = "location", y = "sio2",
          fill = "location", palette = "jco", size = 0.5)+ 
  stat_compare_means(comparisons = fc_fs, size = 7) + 
  stat_compare_means(label.y = 47, size = 6) +
  theme_bw() +
  labs(y = expression("Sio2 (um)")) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black")) 

f5 <- ggboxplot(env, x = "location", y = "secchi",
          fill = "location", palette = "jco", size = 0.5)+ 
  stat_compare_means(comparisons = fc_fs, size = 7) + 
  stat_compare_means(label.y = 18, size = 6) +
  theme_bw() +
  labs(y = expression("Secchi (m)")) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black"))

f6 <- ggboxplot(tchla, x = "location", y = "tchla",
          fill = "location", palette = "jco", size = 0.5)+ 
  # stat_compare_means(comparisons = fc_cs_fs) + 
  stat_compare_means(label.y = 13, size = 6) +
  theme_bw() +
  labs(y = expression("TChla (ug/L)")) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black"))

fig <- (f1 + f2 + f3) / (f4 + f5 + f6)

ggsave(here("figures_good", "kruskal_dunn_panel.png"), 
       width = 14, height = 10, dpi = 300)
```

```{r}
env_f <- env %>% 
  filter(location == "F")

year_all <- list(c("2018", "2019"), c("2019", "2020"), c("2018", "2020"))
year_18_20 <- list(c("2018", "2020"))

ggboxplot(env_f, x = "year", y 
          = "sio2",
          fill = "year", palette = "jco", size = 0.5)+ 
  stat_compare_means(comparisons = year_18_20, size = 7) + 
  stat_compare_means(label.y = 47, size = 6) +
  theme_bw() +
  labs(y = expression("Sio2 (um)")) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black")) 

ggsave(here("figures_good", "kruskal_dunn_dfo2_year.png"), 
       width = 8, height = 6, dpi = 300)
```

```{r}
tchla_f <- tchla %>% 
  filter(location == "S")

ggboxplot(tchla_f, x = "year", y = "tchla",
          fill = "year", palette = "jco", size = 0.5)+ 
  stat_compare_means(comparisons = year_all, size = 7) + 
  stat_compare_means(label.y = 20, size = 6) +
  theme_bw() +
  labs(y = expression("TChla (ug/L)")) +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(colour = "black")) 
```

```{r}
env %>% 
  filter(location == "F") %>% 
  ggplot(aes(x = month_surv, y = s, color = as.factor(year))) +
  geom_line() +
  geom_point()
```






