---
title: "R Notebook"
output: html_notebook
---

 

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(geosphere)
```

```{r}
#All data merged to the CTD 
data <- read_csv(here("outputs", "ctd_merge_2022-03-16_het.csv")) 

#Just using calvert data
data <- data %>% 
  filter(!site_id == "QU39")

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Removing QU39
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
#Removing species groups

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria" &
           !group == "Metazoa" &
           !group == "Protozoa" &
           !group == "Choanoflagellata" &
           !group == "Ciliophora" &
           !group == "Kinetoplastidea")


```

```{r}
#Determining total number of samples collected
sample_num <- micro %>%
  distinct(date, site_id)

#Filtering out species that were not present in at least 10% of the samples
species_10 <- micro %>%
  group_by(scientificName) %>%
  summarise(n_obs = n()) %>%
  ungroup() %>%
  mutate(perc_obs = n_obs/50) %>%
  filter(perc_obs >= 0.10)

#Creating a list of species that were not in 10% of the samples
species_10_list <- species_10$scientificName

#Removing species that were not in 10% of the samples.
micro <- micro %>%
  filter(scientificName %in% species_10_list)

micro <- micro %>% 
  filter(group == "Bacillariophyta")
```

```{r}
#Pivoting data for RDA analysis

#Selecting columns for pivot
micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

#performing pivot and making NA's 0's. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))
```

```{r}
#Removing chemtax and fluorometric chlorophyll from the environmental (explanatory) datasheet. 
data <- data %>% 
  select(!(micro_chl:bulk_chl)) %>% 
  select(!(cyan:diat))
```

```{r}
#Only taking the columns I want from the explanatory datasheet so I can join it with the microscopy data
data <- data %>% 
  select(date:long,
         temp = temp_dm,
         sal = sal_dm,
         drho = delta_rho_dm,
         no2 = no2_dm,
         sio2 = sio2_dm,
         po4 = po4_dm,
         secchi = secchi_depth)

micro_join <- data %>% 
  left_join(micro_piv)

#removing NAs for analysis
micro_join <- micro_join %>% 
  drop_na()
```




```{r}




#Separating into abundance data
abund <- micro_join[, 14:ncol(micro_join)]

#making a vector for temperature
temp <- micro_join[, 7]

#making a vector for salinity
sal <- micro_join[, 8]

#delta_rho
dr <- micro_join[, 9]

#no2
no2 <- micro_join[, 10]

#sio2
sio2 <- micro_join[, 11]

#po4
po4 <- micro_join[, 12]

#secchi
sec <- micro_join[, 13]

#Coordinates
geo <- data.frame(micro_join$long, micro_join$lat)

#All environmental variables
env <- micro_join[, 5:11]

```

```{r}
# Creating distance matrices for Mantel tests

#Abundance by bray curtis
dist.abund <- vegdist(abund, method = "bray")

#Temperature by euclidean 
dist.temp = dist(temp, method = "euclidean")

dist.sal = dist(sal, method = "euclidean")

dist.dr = dist(dr, method = "euclidean")

dist.no2 = dist(no2, method = "euclidean")

dist.sio2 = dist(sio2, method = "euclidean")

dist.po4 = dist(po4, method = "euclidean")

dist.po4 = dist(po4, method = "euclidean")

dist.sec = dist(sec, method = "euclidean")


d.geo = distm(geo, fun = distHaversine)
dist.geo = as.dist(d.geo)

#scale data 
scale.env = scale(env, center = TRUE, scale = TRUE)

#create distance matrix of scaled data
dist.env = dist(scale.env, method = "euclidean")
```

```{r}
abund_temp = mantel(dist.abund, dist.temp, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_temp
```


```{r}
abund_sal = mantel(dist.abund, dist.sal, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_sal
```


```{r}
abund_dr = mantel(dist.abund, dist.dr, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_dr
```

```{r}
abund_no2 = mantel(dist.abund, dist.no2, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_no2
```


```{r}
abund_sio2 = mantel(dist.abund, dist.sio2, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_sio2
```


```{r}
abund_po4 = mantel(dist.abund, dist.po4, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_po4
```


```{r}
abund_sec = mantel(dist.abund, dist.sec, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_sec
```
```{r}
abund_geo = mantel(dist.abund, dist.geo, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_geo
```


```{r}
#run mantel test 
abund_env = mantel(dist.abund, dist.env, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_env
```









