---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
```

```{r}
#Upload data
#Upload output from OBIS taxonomy matching/formatting for Calvert data.
#Need to look into how I'm actually classifying species here. It might be better to have Louis' original designations as I throw a lot of unknown species into protoza, which is one group rather than many.
micro_1 <- read_csv(here("files", "calvert.csv")) 

micro_1_distinct <- micro_1 %>% 
  distinct(date, site_id)

#Uploading QU39 data
micro_2 <- read_csv(here("files", "qu39.csv")) %>%
  mutate(site_id = "QU39") %>% 
  relocate(site_id, .after = "date")


#Separating dataset to do QU39 monthly averaging with.
# monthly_qu39 <- micro_2 %>%
#   filter(trophicStatus == "auto")

#Performing QU39 monthly averaging
monthly_qu39 <- micro_2 %>%
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>%
  group_by(year, month, group, scientificName, identificationRemark) %>%
  summarise(count = mean(count)) %>%
  ungroup() %>% 
  mutate(day = 15,
         site_id = "QU39") %>% 
  unite("date", c(year, month, day), sep = "-") %>% 
  relocate(site_id, .after = "date") %>% 
  select(-identificationRemark) %>% 
  mutate(date = lubridate::ymd(date))

#Selecting Calvert autotrophic groups.
# calvert <- micro_1 %>%
#   filter(trophicStatus == "auto")

#Selecting columns for binding with QU39
calvert <- micro_1 %>% 
  select(date, site_id, group, scientificName, count)

#Binding with QU39
micro <- rbind(monthly_qu39, calvert)

#Counting how many times each species is observed
micro <- micro %>% 
   group_by(scientificName) %>% 
   mutate(num_occurrence = n())

#removing species that have not been observed at least twice.
micro <- micro %>% 
  filter(num_occurrence > 2)

#
micro_full <- rbind(micro_1, micro_2)
```

```{r}
#trying to find the highest abundances for each station

#This gives me the top 10 abundances for each station, excluding unknown flagellates. The problem is that one or two species dominate the list for each station - i.e. Skeletonema was the highest abundance for most stations 
micro_max_abund <- micro_full %>% 
  filter(!group == "Unknown_flagellate") %>% 
  arrange(desc(count)) %>% 
  group_by(site_id) %>% 
  slice(1:10)

#What about number of occurrences. 
#Counting how many times each species is observed
micro_max_n <- micro_full %>% 
  group_by(scientificName) %>% 
  mutate(num_occurrence = n()) %>%
  ungroup() %>%
  arrange(desc(num_occurrence)) %>% 
  group_by(site_id) %>% 
  slice(1:10)

micro_full_short <- micro_full %>% 
  filter(date > "2018-01-01") %>% 
  select(date, site_id, group, scientificName, count, identificationRemark) %>% 
  group_by(date, site_id) %>% 
  mutate(sum = sum(count),
         n = n(),
         rel = ((count/sum)*100)) %>% 
  arrange(desc(count)) %>% 
  slice(1:10) %>% 
  ungroup() %>% 
  arrange(site_id, date) %>% 
  mutate_at(vars(rel), funs(round(., 1)))
```




```{r}
#Selecting columns
micro <- micro %>% 
  select(date, site_id, group, scientificName, count)

# Because I have some species separated out with identificationRemarks, identificationQualifiers and different resting stages, I sum these. If I don't, then the pivoting in later stages results in columns with combined numbers. I need to decide on best method for this once I have the analysis zeroed in. 

#Again, not sure if I want to do this...
micro <- micro %>%
  group_by(date, site_id, scientificName) %>%
  summarize(species_sum = sum(count)) %>%
  ungroup()

#Combining date and siteID - can't have both for the clustering I am trying now
# micro_clust <- micro_clust %>% 
#   unite(date_site, date, site_id, sep = "_")

#pivoting longer so species are columns. 
micro_piv <- micro %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Adding date columns
micro_piv <- micro_piv %>% 
  mutate(month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  relocate(month, .after = date) %>% 
  relocate(yday, .after = month)

#filtering for period under investigation
micro_piv <- micro_piv %>% 
  filter(date > "2018-01-01" & date < "2021-01-01")

# When turned on this removes QU39 data.
# micro_piv <- micro_piv %>% 
#   filter(!site_id == "QU39")

#Roughly adding seasons - would like to make cosmological seasons
micro_piv <- micro_piv %>% 
  mutate(season = case_when(month %in% c(12, 1, 2) ~ "winter",
                            month >= 3 & month <= 5 ~ "spring",
                            month >= 6 & month <= 8 ~ "summer",
                            month >= 9 & month <= 11 ~ "autumn",)) %>% 
  relocate(season, .after = month) 


#Pulling out species counts for tranform and input into clustering and NMDS
transform <- micro_piv[, 6:134]  
  
#Log10 transformation +1 (as per Mahara)
transform <- log10(transform + 1)

#Performing clustering
dend_micro <- transform %>% 
  vegdist("bray") %>% 
  hclust(method = "average") %>% 
  as.dendrogram()


```


```{r}
#Running nmds on entire dataset, without QU39 monthly averaged
nmds_all <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Checking stressplot for fit
stressplot(nmds_all)

```

```{r}
#Creating dendrogram cutoff for clustering in NMDS
grp <- cutree(dend_micro, 2)
```



```{r}
#For this plot I:
#1) Monthly averaged QU39 data
#2) Filtered to mostly autotrophic groups - removed ciliates etc. (Found out I wasn't removing these from the QU39 data, so now that this is fixed.... my results might not be nearly as good)
#3) removed species that only had 1 or 2 occurrences

#The removal of heterotrophs made a big difference. Before, the groups had huge overlap.


# https://fromthebottomoftheheap.net/2012/04/11/customising-vegans-ordination-plots/

with(micro_piv, levels(as.factor(site_id)))

col_site <- c("red", "green", "blue", "magenta")


plot(nmds_all, type = "n", ylim = c(-0.6, 0.6), xlim = c(-0.5, 0.5))



with(micro_piv, points(nmds_all, display = "sites", col = "black",
                      pch = 21, bg = col_site[as.factor(site_id)], cex = 2.2))

# text(example_NMDS, display = "species", scaling = scl, cex = 0.8, col = "darkcyan")

with(micro_piv, legend("topright", legend = levels(as.factor(site_id)), bty = "n",
                      col = "black", pch = 21, pt.bg = col_site, cex = 1.5))


orditorp(nmds_all, display = "sites", cex = 0.70, air = 0.01, col = "white")

# https://stackoverflow.com/questions/12436902/overlaying-clustering-results-on-an-ordination
ordihull(nmds_all, groups = grp, display = "sites", draw = "polygon")
#Stress is 0.15
# Cut dendrogram at 5 branches, but I only see three groupsings here.


```

```{r}
# png(here("figures", "Calvert_qu39_monthly_nmds.png"), width = 800, height = 500)

#displays empty ordination space
plot(nmds_all, type = "n", ylim = c(-0.5, 0.5), xlim = c(-0.5, 0.5)) 

# displays site points where symbols (pch) are different management options and colour (col) are different land uses
points(nmds_all, display = "sites", col = "black",
       pch = c(21, 22, 23, 24) [as.factor(micro_piv$season)], 
       bg = c("blue", "orange", "black", "magenta") [as.factor(micro_piv$site_id)],
       cex = 2) 

# displays symbol and colour legend
legend("topright", legend = c(levels(as.factor(micro_piv$season)), 
                              levels(as.factor(micro_piv$site_id))),
       pch = c(21, 22, 23, 24, 16, 16, 16, 16),
       col = c("black", "black", "black", "black", "blue", "orange", "black", "magenta"),
       bg = c(NA, NA, NA, NA, "blue", "orange", "black", "magenta"),
       bty = "n", cex = 1.5)

# # displays legend text of stress value
legend("topleft", "stress = 0.191", bty = "n", cex = 1.5)

# orditorp(nmds_all, display = "sites", cex = 0.70, air = 0.01, col = "white")

# grp <- cutree(dend_micro, 4)
# ordihull(nmds_all, groups = grp, display = "sites", draw = "polygon")

# ordihull(nmds_all, groups = micro_piv$site_id, draw = "polygon", col = NULL,
#   border = c("gray0", "gray0", "gray48", "gray48"),
#   lty = c(1, 2, 1, 2),
#   lwd = 2.5)

# plot(nmds.spp.fit, p.max = 0.01, col = "black", cex = 0.7)

# dev.off()
```

```{r}
#Might be valuable if I downgrade to genus.

# https://www.rpubs.com/RGrieger/545184

nmds.spp.fit <- envfit(nmds_all, transform, permutations = 999)
head(nmds.spp.fit)


```


```{r}

#For this plot I:
#1) Monthly averaged QU39 data
#2) Filtered to mostly autotrophic groups - removed ciliates etc.
#3) removed species that only had 1 or 2 occurrences

#The removal of heterotrophs made a big difference. Before, the groups had huge overlap.


# https://fromthebottomoftheheap.net/2012/04/11/customising-vegans-ordination-plots/

with(micro_piv, levels(as.factor(site_id)))

col_site <- c("red", "green", "blue", "magenta")

plot(nmds_all, type = "n", ylim = c(-0.6, 0.6), xlim = c(-0.5, 0.5))

with(micro_piv, points(nmds_all, display = "sites", col = "black",
                      pch = 21, bg = col_site[as.factor(site_id)], cex = 2.2))

# text(example_NMDS, display = "species", scaling = scl, cex = 0.8, col = "darkcyan")

with(micro_piv, legend("topright", legend = levels(as.factor(site_id)), bty = "n",
                      col = "black", pch = 21, pt.bg = col_site, cex = 1.5))


orditorp(nmds_all, display = "sites", cex = 0.70, air = 0.01, col = "white")

# https://stackoverflow.com/questions/12436902/overlaying-clustering-results-on-an-ordination
ordihull(nmds_all, groups = grp, display = "sites")
#Stress is 0.15

```



















```{r}
ordiplot(example_NMDS,type="n")
orditorp(example_NMDS,display="sites",cex=1.25,air=0.01)
```
```{r}
# https://fromthebottomoftheheap.net/2012/04/11/customising-vegans-ordination-plots/

with(micro_piv, levels(as.factor(site_id)))
```
```{r}
colvec <- c("red", "green", "blue")
```

```{r}
plot(example_NMDS, type = "n", xlim = c(-1, 1), ylim = c(-0.5, 0.5))

with(micro_piv, points(example_NMDS, display = "sites", col = "black",
                      pch = 21, bg = colvec[as.factor(site_id)], cex = 2.2))

# text(example_NMDS, display = "species", scaling = scl, cex = 0.8, col = "darkcyan")

with(micro_piv, legend("topright", legend = levels(as.factor(site_id)), bty = "n",
                      col = "black", pch = 21, pt.bg = colvec, cex = 2))


orditorp(example_NMDS, display="sites", cex = 0.70, air = 0.01, col = "white")

# https://stackoverflow.com/questions/12436902/overlaying-clustering-results-on-an-ordination
ordihull(example_NMDS, groups = grp, display = "sites")
#Stress is 0.15
#


```

```{r}

# https://fromthebottomoftheheap.net/2012/04/11/customising-vegans-ordination-plots/

with(micro_piv, levels(as.factor(season)))
```

```{r}
colvec_seas <- c("red", "green", "blue", "yellow")
```

```{r}
plot(example_NMDS, type = "n", xlim = c(-1, 1), ylim = c(-0.5, 0.5))

with(micro_piv, points(example_NMDS, display = "sites", col = "black",
                      pch = 21, bg = colvec_seas[as.factor(season)], cex = 1.5))

# text(example_NMDS, display = "species", scaling = scl, cex = 0.8, col = "darkcyan")

with(micro_piv, legend("topright", legend = levels(as.factor(season)), bty = "n",
                      col = "black", pch = 21, pt.bg = colvec_seas, cex = 1.5))



# https://stackoverflow.com/questions/12436902/overlaying-clustering-results-on-an-ordination
ordihull(example_NMDS, groups = grp, display = "sites")
#Stress is 0.15
#


```

```{r}
#Would really like to have this combined so it shows season and station

#Could try relative abundance

#Try with pigments

#Try with chemtax


```





```{r}
plot(example_NMDS)
```


```{r}
#Creation of dendrogram using Calvert data

png(here("figures", "Calvert_qu39_monthly.png"), width = 2200, height = 1000) 

season <- pull(micro_piv, season)
station <- pull(micro_piv, site_id)
yday <- pull(micro_piv, yday)


barcolor_season <- colormap(colormap = colormaps$earth, nshades = 4, format = "hex", alpha = 1, reverse = FALSE)

barcolor_station <- colormap(colormap = colormaps$jet, nshades = 4, format = "hex", alpha = 1, reverse = FALSE)

barcolor_yday <- colormap(colormap = colormaps$rainbow, nshades = 356, format = "hex", alpha = 1, reverse = FALSE)


# colormaps$viridis
# colormaps$jet
# c("#0342ff", "#00bd0d", "#fbff00", "#ff0000")

barcolor_season <- barcolor_season[as.numeric(as.factor(season))]
barcolor_station <- barcolor_station[as.numeric(as.factor(station))]
barcolor_yday <- barcolor_yday[as.numeric(yday)]

barcolor_full <- cbind(barcolor_season, barcolor_station)
colnames(barcolor_full) <- c("season", "station")

#Margins bottom, left, top, right.
par(mar=c(5,2,1,2))
dend_micro %>%
  plot() 

colored_bars(colors = barcolor_full, dend = dend_micro)


legend("topright", 
     legend = c("DFO2" , "KC10" , "QCS01" , "QU39"), 
     col = colormap(colormap = colormaps$jet, nshades = 4), 
     pch = c(20,20,20,20), bty = "n",  pt.cex = 3, cex = 2 , 
     text.col = "black", horiz = FALSE, inset = c(0, 0.1))

legend("right", 
     legend = c("Winter" , "Spring" , "Summer" , "Autumn"), 
     col = colormap(colormap = colormaps$earth, nshades = 4), 
     pch = c(20,20,20,20), bty = "n",  pt.cex = 3, cex = 2 , 
     text.col = "black", horiz = FALSE, inset = c(0, 0.1))

# legend("bottomright", 
#      legend = c(1:356), 
#      col = colormap(colormap = colormaps$rainbow, nshades = 4), 
#      pch = c(20,20,4,4,4), bty = "n",  pt.cex = 1.5, cex = 0.8 , 
#      text.col = "black", horiz = FALSE, inset = c(0, 0.1))

dev.off()
```
```{r}
plot(cut(dend_micro, h=0.79)$lower[[2]], 
     main="Second branch of lower tree with cut at h=75")
```

```{r}
fviz_cluster(dend_micro) # scatter plot
```


```{r}
matrix(rnorm(1000), ncol = 10) %>%
  scale %>% 
  dist  %>% 
  hclust %>% 
  as.dendrogram() -> dend_expr

tree_labels <- dendro_data(dend_micro, type = "rectangle")
tree_labels$labels <- cbind(tree_labels$labels, Diagnosis = as.factor(sample(1:2, 100, replace = T)))

ggplot() +
  geom_segment(data = segment(tree_labels), aes(x=x, y=y, xend=xend, yend=yend))+
  geom_segment(data = tree_labels$segments %>%
                 filter(yend == 0) %>%
                 left_join(tree_labels$labels, by = "x"), aes(x=x, y=y.x, xend=xend, yend=yend, color = Diagnosis)) +
  geom_text(data = label(tree_labels), aes(x=x, y=y, label=label, colour = Diagnosis, hjust=0), size=3) +
  coord_flip() +
  scale_y_reverse(expand=c(0.2, 0)) +
  scale_colour_brewer(palette = "Dark2") + 
  theme_dendro() +
  ggtitle("Mayo Cohort: Hierarchical Clustering of Patients Colored by Diagnosis")
```

```{r}
# https://www.rdocumentation.org/packages/dendextend/versions/1.8.0/topics/colored_bars

## mtcars example

# Create the dend:
dend <- as.dendrogram(hclust(dist(mtcars)))

# Create a vector giving a color for each car to which company it belongs to
car_type <- rep("Other", length(rownames(mtcars)))
is_x <- grepl("Merc", rownames(mtcars))
car_type[is_x] <- "Mercedes"
is_x <- grepl("Mazda", rownames(mtcars))
car_type[is_x] <- "Mazda"
is_x <- grepl("Toyota", rownames(mtcars))
car_type[is_x] <- "Toyota"
car_type <- factor(car_type)
n_car_types <- length(unique(car_type))
col_car_type <- colorspace::rainbow_hcl(n_car_types, c = 70, l  = 50)[car_type]

# extra: showing the various clusters cuts 
k234 <- cutree(dend, k = 2:4)

# color labels by car company:
labels_colors(dend) <- col_car_type[order.dendrogram(dend)]
# color branches based on cutting the tree into 4 clusters:
dend <- color_branches(dend, k = 4)

### plots
par(mar = c(12,4,1,1))
plot(dend)
colored_bars(cbind(k234[,3:1], col_car_type), dend, 
      rowLabels = c(paste0("k = ", 4:2), "Car Type"))

# horiz version:
par(mar = c(4,1,1,12))
plot(dend, horiz = TRUE)
colored_bars(cbind(k234[,3:1], col_car_type), dend, 
      rowLabels = c(paste0("k = ", 4:2), "Car Type"), horiz = TRUE)
```

```{r}
#Resources
#https://stackoverflow.com/questions/49088627/how-to-label-colored-bars-in-a-dendrogram
#https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/
#https://cran.r-project.org/web/packages/dendextend/vignettes/dendextend.html

#Goal - similarity/dissimilarity cluster analysis 

#How differnt or similar are the three calvert island sites

#Distance metric - Bray-curtis is used for abundance data

#Linkage method - criterion that will determine how observations will be grouped together.

#Figtree (software) allows you to view and edit dendograms - look into this

#https://ourcodingclub.github.io/tutorials/data-clustering/

#Mahara - average linkage Bray-curtis dissimilarity, log10(x+1) transformed

# https://www.davidzeleny.net/anadat-r/doku.php/en:similarity

# similarity calculated using similarity indices ranging from 0 to 1. Ordination uses distances (Euclidean). Legendre & Legendre (2012) offers key on how to select appropriate measure for given data. bray-Curtis and Hellinger distances may be better than Euclidean.

# Symmetrical indices (thos which consider double 0s as relevant not useful for ecological data). Asymmetrical similarity indices (ignore double zeros). Two types, qualitative (presence/absence) and quantitative (raw or transformed species abundance). 

#Qualitative (binary) asymmetrical similarity indices. Information about number of species shared by both samples AND number of species occuring in first or second sampe only.

#Quantitative similarity indices. Percentage Similarity and includes Bray-Curtis

#Distance Indices. Similarity indices return highest value when both samples the same. Distance indices opposite. Two types: 1) Those calculated from similarity indices (includes Bray-Curtis) and; 2) Those which have no analogue in similarity indices. Important criterium is whether distance index is metric or not. Metric = minimum distance is 0, distance is always positive, distance between sample 1 and 2 same as 2 and has triangle inequality.

#Bray-Curits/percentage difference. Suitable for community composition data since it is asymmetrical (ignores double 0s) and meaningful upper vlaue equal to 1. Considers absolute species abundances

```







