---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)

#Need to go through and test these

```

```{r}
#Upload data
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

```

```{r}
#Could try to limit cryptic species that influence stats. Leaving off for now.

#Only species occurring in 25% of the samples - could try this.

#Could also try removing samples that represent <1% of abundance (currently switched on)

micro <- micro %>% 
  filter(trophicStatus == "auto")

#Counting how many times each species is observed
micro <- micro %>%
  group_by(scientificName) %>%
  mutate(num_occurrence = n())

#removing species that have not been observed at least twice.
micro <- micro %>%
  filter(num_occurrence > 2)

#Method where I removed species not observed more than once resulted in 2420 records. Here I am trying a more convservative method where I remove any species that do not exceed 1% of abundance in any of the samples. The result is 1829 records - far fewer. Need to do a literature review here to see what is most appropriate, but I think this method is probably more focused.
# micro_1perc <- micro %>% 
#   group_by(date, site_id) %>% 
#   mutate(abund_sum = sum(species_sum)) %>% 
#   ungroup
# 
# micro_1perc <- micro_1perc %>% 
#   mutate(abund_rel = species_sum/abund_sum*100)
# 
# less_1perc <- micro_1perc %>% 
#   group_by(scientificName) %>% 
#   summarize(max = max(abund_rel)) %>% 
#   ungroup() %>% 
#   filter(max < 1)
# 
# sp_rem <- less_1perc$scientificName
# 
# micro_1perc <- micro %>%
#   filter(!(scientificName %in% sp_rem))
# 
# micro <- micro_1perc

#Result of analysis is pretty comparable. Lit review to determine best method.

```

```{r}

#Selecting columns
micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)


#pivoting longer so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Roughly adding seasons - would like to make cosmological seasons
micro_piv <- micro_piv %>%
  mutate(season = case_when(month >= 4 & month <= 6 ~ "spring",
                            month >= 7 & month <= 9 ~ "summer",
                            month >= 10 & month <= 11 ~ "autumn",)) %>%
  relocate(season, .after = month)

#Arranging according to site ID and date
micro_piv <- micro_piv %>% 
  arrange(site_id, date)

#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 6:ncol(micro_piv)]  

transform_rel <- decostand(transform, method = "total")
  
#Log10 transformation +1 (as per Mahara)
transform <- log10(species + 1)

transform_rel <- sqrt(transform_rel)
```


```{r}
#Performing hierarchical clustering for count data

#Setting rownames for hierarchical clustering
clust <- transform

rownames <- micro_piv %>% 
  select(site_id, date) %>% 
  unite(row_name, site_id:date, sep = "_")

rownames_list <-rownames$row_name

rownames(clust) <- rownames_list

#Performing hierarchical clustering
dend_micro <- clust %>%
  vegdist("bray") %>%
  hclust(method = "average") %>%
  as.dendrogram()


fviz_nbclust(clust, FUN = hcut, method = "wss")
fviz_nbclust(clust, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(clust, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```

```{r}
#Performing hierarchical clustering for relative data

#Setting rownames for hierarchical clustering
clust_rel <- transform_rel

rownames(clust_rel) <- rownames_list

#Performing hierarchical clustering
dend_micro_rel <- clust_rel %>%
  vegdist("bray") %>%
  hclust(method = "average") %>%
  as.dendrogram()


fviz_nbclust(clust, FUN = hcut, method = "wss")
fviz_nbclust(clust, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(clust, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```



```{r}
# http://www.sthda.com/english/wiki/beautiful-dendrogram-visualizations-in-r-5-must-known-methods-unsupervised-machine-learning

#https://stackoverflow.com/questions/21474388/colorize-clusters-in-dendogram-with-ggplot2

dend_data <- dendro_data(dend_micro, type = "rectangle")

cut <- 4

#Find clusters
clust_find <- cutree(dend_micro, k = cut)

clust_df <- data.frame(label = names(clust_find), cluster = clust_find)

# dendr[["labels"]] has the labels, merge with clust.df based on label column
dend_data[["labels"]] <- merge(dend_data[["labels"]], clust_df, by = "label")

ggplot() + 
  geom_segment(data = segment(dend_data),
               aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = label(dend_data), aes(x, y, label = label, hjust = 0, 
                                         color = as.factor(cluster)), size = 7) +
  coord_flip() + 
  scale_y_reverse(expand = c(0.2, 0)) + 
  scale_color_discrete(name = "Cluster", labels = c("1", "2", "3", "4")) +
  theme(legend.position = "none",
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 20),
        panel.background = element_rect(fill = "white"),
        panel.grid = element_blank())

ggsave(here("figures_new", "cluster_photo.png"),
       width = 18, height = 18, dpi = 300)

#Really keen to get this going.
#Silhoutette plots and other ways to determine clusters 
#Make labels station and date. Color arms. Print. Add clusters to nMDS. Do results make any sense?

```
```{r}
#Trying different visualizaton approach

# https://stackoverflow.com/questions/44646488/stacked-bar-plot-with-hierarchical-clustering-dendrogram

#First issue is that some metazoa and some 

#Summing to group level
# t <- micro %>% 
#   group_by(date, site_id, group) %>% 
#   mutate(group_sum = sum(species_sum)) %>% 
#   ungroup() %>% 
#   distinct(date, site_id, group, group_sum)
# 
# #pivoting longer so species are columns. 
# t <- t %>% 
#   pivot_wider(names_from = group, values_from = group_sum) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0))
# 
# #Arranging according to site ID and date
# # t <- t %>% 
# #   arrange(site_id, date)
# 
# #Pulling out species counts for transform and input into clustering and NMDS
# t <- t[, 3:ncol(t)]  
# 
# #Making rownames station and date.
# rownames(t) <- rownames_list
# 
# #Performing clustering
# hc <- clust %>%
#   vegdist("bray") %>%
#   hclust(method = "average")
# 
# #Not totally sure what this is doing - I think ordering.
# hc <- reorder(hc, wts = -as.matrix(t) %*% seq(ncol(t))^2) # vegan::reorder.hclust
# tree = ggdendro::dendro_data(as.dendrogram(hc), type = "rectangle")
# 
# #Plotting dendrogram
# p1 <-  ggplot(ggdendro::segment(tree)) +
#   geom_segment(aes(x = y, y = x, xend = yend,yend = xend),lineend = "round",
#                size = .4) + 
#   geom_text(data = label(tree), aes(x, y, label = label, hjust = 0, size = 7)) +
#   scale_x_continuous(expand = expansion(add = c(0,.01))) + # don't crop half of line between top-level nodes
#   scale_y_continuous(limits = .5 + c(0, nrow(t)), expand = c(0,0))+
#   theme(axis.text = element_blank(),
#         axis.ticks = element_blank(),
#         axis.ticks.length = unit(0,"pt"), # remove extra space occupied by ticks
#         axis.title = element_blank(),
#         panel.background = element_rect(fill = "white"),
#         panel.grid = element_blank(),
#         plot.margin = margin(5, 5, 5, 0))
# 
# #I suspect this is reording the counts according to the clustering - but it's removing my labels
# t <- t[hc$labels[hc$order], ]
# 
# #Not sure.
# t2 <- data.frame(V1 = rownames(t)[row(t)], V2 = colnames(t)[col(t)], 
#                   V3 = unname(do.call(c,t)))
# 
# # dendr[["labels"]] has the labels, merge with clust.df based on label column
# test <- clust_df_rel <- data.frame(label = names(tree))
# 
# #Must be the labels, which I am not using.
# lab <- round(100*t2$V3)
# lab[lab == 0] = ""
# 
# #Plotting the stacked bar plot.
# p2 <- ggplot(t2, aes(x = factor(V1, level = rownames(t)), y = V3, fill = V2)) +
#   geom_bar(stat = "identity", width = 1, position = position_stack(reverse = T)) +
# # geom_text(aes(label=lab),position=position_stack(vjust=.5,reverse=T),size=3.5)+
#   coord_flip()+
#   scale_x_discrete(expand = c(0, 0)) +
#   scale_y_discrete(expand = c(0, 0)) +
# # scale_fill_manual(values = colorspace::hex(HSV(head(seq(0,360,length.out=ncol(t) + 1),-1), .5, 1)))+
#   theme(
#   axis.text = element_text(color = "black", size = 11),
#   axis.text.x = element_blank(),
#   axis.ticks = element_blank(),
#   axis.title = element_blank(),
#   legend.position = "none",
#   plot.margin = margin(5, 0, 5, 5))
# 
# cowplot::plot_grid(p2, p1, rel_widths = c(1,.4))

# ggsave(here("figures_new", "test2.png"), height = .25*nrow(t),width = 7)

# ggsave(here("figures_new", "test.png"),
#        width = 16, height = 20, dpi = 300)

```

```{r}
# library(ggh4x)
# 
# #Summing to group level
# t <- micro %>% 
#   group_by(date, site_id, group) %>% 
#   mutate(group_sum = sum(species_sum)) %>% 
#   ungroup() %>% 
#   distinct(date, site_id, group, group_sum)
# 
# #pivoting longer so species are columns. 
# t <- t %>% 
#   pivot_wider(names_from = group, values_from = group_sum) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0))
# 
# #Arranging according to site ID and date
# # t <- t %>% 
# #   arrange(site_id, date)
# 
# #Pulling out species counts for transform and input into clustering and NMDS
# t <- t[, 3:ncol(t)]  
# 
# #Making rownames station and date.
# rownames(t) <- rownames_list
# 
# t2 = data.frame(V1=rownames(t)[row(t)],V2=colnames(t)[col(t)],V3=unname(do.call(c,t)))
# hc=hclust(dist(t))
# 
# ggplot(t2,aes(x=factor(V1,level=rownames(t)),y=V3,fill=V2))+
# geom_bar(stat="identity",width=1,position=position_stack(reverse=F))+
# # geom_text(aes(label=round(V3)),position=position_stack(vjust=.5,reverse=F),size=3)+
# scale_x_dendrogram(hclust=hc)+
# scale_y_discrete(expand=c(0,0))+
# # scale_fill_manual(values=colorspace::hex(HSV(head(seq(0,360,length.out=ncol(t)+1),-1),.5,1)))+
# theme(
#   axis.text=element_text(color="black",size=11),
#   axis.text.x=element_text(angle=90,hjust=1,vjust=.5),
#   axis.text.y=element_blank(),
#   axis.ticks=element_blank(),
#   axis.ticks.length=unit(14,"pt"), # height of dendrogram
#   axis.title=element_blank(),
#   legend.justification=c(0,1),
#   legend.key=element_rect(fill=NA), # remove gray border around color squares
#   legend.margin=margin(-6,0,0,0),
#   legend.position= "none",
#   legend.title=element_blank(),
#   panel.background=element_rect(fill="white"),
#   plot.margin=margin(5,0,5,5)
# )
# 
# ggsave(here("figures_new", "test_3.png"),
#         width = 16, height = 20, dpi = 300)
```





```{r}
#Dendrogram for relative data

dend_data_rel <- dendro_data(dend_micro_rel, type = "rectangle")

cut_rel <- 4

#Find clusters
clust_find_rel <- cutree(dend_micro_rel, k = cut_rel)

clust_df_rel <- data.frame(label = names(clust_find), cluster = clust_find_rel)

# dendr[["labels"]] has the labels, merge with clust.df based on label column
dend_data_rel[["labels"]] <- merge(dend_data_rel[["labels"]],
                                   clust_df_rel, by = "label")

ggplot() + 
  geom_segment(data = segment(dend_data_rel),
               aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = label(dend_data_rel), aes(x, y, label = label, hjust = 0, 
                                         color = as.factor(cluster)), size = 7) +
  coord_flip() + 
  scale_y_reverse(expand = c(0.2, 0)) + 
  scale_color_discrete(name = "Cluster", labels = c("1", "2", "3", "4")) +
  theme(legend.position = "none",
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 20),
        panel.background = element_rect(fill = "white"),
        panel.grid = element_blank())

ggsave(here("figures_new", "cluster_rel_photo.png"),
       width = 17, height = 18, dpi = 300)

#Really keen to get this going.
#Silhoutette plots and other ways to determine clusters 
#Make labels station and date. Color arms. Print. Add clusters to nMDS. Do results make any sense?

```




```{r}
#Running nmds on entire dataset, without QU39 monthly averaged
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Decent stress score - 0.16

nmds_rel <-  metaMDS(transform_rel, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 


#Checking stressplot for fit
stressplot(nmds)

stressplot(nmds_rel)
```
```{r}

#Calculating species scores that are driving the nmds

# https://www.rpubs.com/RGrieger/545184

nmds_sp <- envfit(nmds, transform, permutations = 999)
head(nmds_sp)

```

```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

# https://stackoverflow.com/questions/14711470/plotting-envfit-vectors-vegan-package-in-ggplot2
#If I want to try to get species vectors on plot try above link, near bottom
# spp.scrs <- as.data.frame(scores(nmds_sp, display = "vectors"))
# test <- as.data.frame(nmds_sp, display = "pvals")
# spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

data.scores = as.data.frame(scores(nmds))
data.scores$month = micro_piv$month
data.scores$site = micro_piv$site_id

data.scores.rel = as.data.frame(scores(nmds_rel))
data.scores.rel$month = micro_piv$month
data.scores.rel$site = micro_piv$site_id

```

```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits.

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month), shape = site),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

ggsave(here("figures_new", "nmds_micro_absolute_photo.png"),
       width = 6, height = 4.5, dpi = 300)
```
```{r}
ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores.rel, aes(fill = as.factor(month), shape = site),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.5, 1.0) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.94, 0.6),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

ggsave(here("figures_new", "nmds_micro_ggplot_month_station_relative.png"),
       width = 6, height = 4.5, dpi = 300)
```
```{r}
#Combining absolute and relative nmds

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.92, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores.rel, aes(fill = as.factor(month), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.5, 1.0) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # legend.key = element_blank(), 
        # legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        # legend.text = element_text(size = 9, colour = "black"),
        legend.position = "none",
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 25)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

fig <- p1/p2

ggsave(here("figures_new", "nmds_absolute_rel_comb.png"), fig,
       width = 10, height = 12, dpi = 300)

```





```{r}
#separating treatments for following tests
season <-  micro_piv$season
site_id <- micro_piv$site_id
month <- micro_piv$month

#Adding region - should so this earlier - potentially in data standardization
micro_piv <- micro_piv %>% 
  mutate(region = case_when(site_id == "QU39" ~ "NSoG",
                            !site_id == "QU39" ~ "Calvert")) %>% 
  relocate(region, .after = "site_id")

region <- micro_piv$region

```



```{r}
#ANOSIM test to see if groupings statistically significant
ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
ano_site

ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
ano_month

ano_season = anosim(transform, season, distance = "bray", permutations = 9999)
ano_season

ano_region = anosim(transform, region, distance = "bray", permutations = 9999)
ano_region

#Site and region are significant (p = 0.0001), with region having the highest R (0.62 vs 0.27) 

```

```{r}
#Indicator species analysis

#Indicators by season
inv_season = multipatt(transform, season, func = "r.g",
                       control = how(nperm = 9999))
#by site
inv_site = multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))
#by month
inv_month = multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

#by region
inv_region = multipatt(transform, region, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_region)
```

```{r}
#Want to look at diversity and richness.
div <- diversity(species)

div <- as.tibble(div)

div$site_id <- micro_piv$site_id

div$date <- micro_piv$date

div <- div %>% 
  rename(shannon = value)


div %>% 
  mutate(month = lubridate::month(date)) %>% 
  ggplot(aes(x = site_id, y = ))

```


















