---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
library(indicspecies)
library(fuzzySim)
library(cluster)
library(patchwork)
library(vegan)
library(RColorBrewer)

#Need to go through and test these

```

```{r}
#Upload data
#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

#Master sheet is missing May 2020 data for QU39 and KC10...

```

```{r}
#Could try to limit cryptic species that influence stats. Leaving off for now.

#Only species occurring in 25% of the samples - could try this.

#Could also try removing samples that represent <1% of abundance (currently switched on)

micro <- micro %>% 
  filter(trophicStatus == "auto")

#Counting how many times each species is observed
micro <- micro %>%
  group_by(scientificName) %>%
  mutate(num_occurrence = n())

#removing species that have not been observed at least twice.
micro <- micro %>%
  filter(num_occurrence > 2)

#Removing cyanobacteria
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")


#Method where I removed species not observed more than once resulted in 2420 records. Here I am trying a more convservative method where I remove any species that do not exceed 1% of abundance in any of the samples. The result is 1829 records - far fewer. Need to do a literature review here to see what is most appropriate, but I think this method is probably more focused.
# micro_1perc <- micro %>% 
#   group_by(date, site_id) %>% 
#   mutate(abund_sum = sum(species_sum)) %>% 
#   ungroup
# 
# micro_1perc <- micro_1perc %>% 
#   mutate(abund_rel = species_sum/abund_sum*100)
# 
# less_1perc <- micro_1perc %>% 
#   group_by(scientificName) %>% 
#   summarize(max = max(abund_rel)) %>% 
#   ungroup() %>% 
#   filter(max < 1)
# 
# sp_rem <- less_1perc$scientificName
# 
# micro_1perc <- micro %>%
#   filter(!(scientificName %in% sp_rem))
# 
# micro <- micro_1perc

#Result of analysis is pretty comparable. Lit review to determine best method.

```

```{r}

#Selecting columns
micro_piv <- micro %>% 
  select(date, month, month_surv, site_id, scientificName, species_sum)

#pivoting longer so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Roughly adding seasons - would like to make cosmological seasons
micro_piv <- micro_piv %>%
  mutate(season = case_when(month >= 4 & month <= 6 ~ "spring",
                            month >= 7 & month <= 9 ~ "summer",
                            month >= 10 & month <= 11 ~ "autumn",)) %>%
  relocate(season, .after = month_surv)

#Adding year 
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Arranging according to site ID and date
micro_piv <- micro_piv %>% 
  arrange(site_id, date)

micro_piv <- micro_piv %>% 
  filter(!site_id == "QU39")

#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv[, 7:ncol(micro_piv)]

#Creating relative abundance matrix
transform_rel <- decostand(species, method = "total")
  
#Log10 transformation +1 (as per Mahara)
transform <- log10(species + 1)

transform_rel <- sqrt(transform_rel)
```

```{r}
#Create rownames for dendrogram
labs <- micro_piv %>%
  select(site_id, date) %>% 
  unite(sample_name, c(site_id, date), sep = "_")

labs_list <- labs$sample_name

transform_hc <- transform

rownames(transform_hc) <- labs_list
```


```{r}
#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- vegdist(transform_hc, method = "bray")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "average")

```

```{r}
k <- 5
clust <- cutree(cluster.average, k = k)

clust.df <- clust.df <- data.frame(label = rownames(transform_hc),
                                   cluster = factor(clust))

# write_csv(clust.df, here("outputs", "clusters_micro.csv"))
```

```{r}
# extract dendrogram segment data
dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
#Creating metadata sheet with 
metadata <- micro_piv %>% 
  select(site_id, date)

#Making unique labels by combining site and date into single string
metadata <- metadata %>% 
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

# get terminal dendrogram segments
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
p_dend <- ggplot() +
 geom_segment(data = dendrogram_segments, 
 aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id), 
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name, 
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 geom_rect(data = rect, aes(xmin = X1-.3, xmax = X2+.3, ymin = 0, ymax = ymax),
            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(0.6, -0.3)) +
 coord_flip() + 
 theme_bw() + 
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_rev2", "hc_average_clusters_5.png"), p_dend,
       width = 6, height = 12, dpi = 300)
```

```{r}
#Running nmds on Calvert data
nmds <-  metaMDS(transform, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Stress - 0.24. Not great. With three dimensions 0.17.

nmds_rel <-  metaMDS(transform_rel, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

#Stress = 0.18 with 2 dimenstions

#Checking stressplot for fit
stressplot(nmds)
stressplot(nmds_rel)

```

```{r}
#Pulling NMDS scores, months and stations for plotting NMDS is ggplot

# https://stackoverflow.com/questions/14711470/plotting-envfit-vectors-vegan-package-in-ggplot2
#If I want to try to get species vectors on plot try above link, near bottom
# spp.scrs <- as.data.frame(scores(nmds_sp, display = "vectors"))
# test <- as.data.frame(nmds_sp, display = "pvals")
# spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))

data.scores = as.data.frame(scores(nmds))
data.scores$month_surv = micro_piv$month_surv
data.scores$site = micro_piv$site_id
data.scores$year = micro_piv$year

data.scores.rel = as.data.frame(scores(nmds_rel))
data.scores.rel$month_surv = micro_piv$month_surv
data.scores.rel$site = micro_piv$site_id
data.scores.rel$year = micro_piv$year

```

```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits. This is for the absolute data

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_absolute_CALVERT.png"),
#        width = 6, height = 4.5, dpi = 300)
```

```{r}
#nmds plot for the relative data

ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores.rel, aes(fill = as.factor(month_surv), shape = site),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.5, 1.0) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.94, 0.6),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_rev2", "nmds_micro_relative_CALVERT.png"),
#        width = 6, height = 4.5, dpi = 300)
```


```{r}
#Combining absolute and relative nmds separated by station and month - It could be good to do this by year as well.

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.92, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores.rel, aes(fill = as.factor(month_surv), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.5, 1.0) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # legend.key = element_blank(), 
        # legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        # legend.text = element_text(size = 9, colour = "black"),
        legend.position = "none",
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 25)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

fig <- p1/p2

# ggsave(here("figures_rev2", "nmds_CALVERT.png"), fig,
#        width = 10, height = 12, dpi = 300)

```
```{r}
#Combining absolute and relative nmds - plots for both month and year

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.75),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(shape = "Station", fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p3 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores.rel, aes(fill = as.factor(month_surv), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.position = "none",
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 25)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p4 <- ggplot(data = data.scores.rel, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores.rel, aes(fill = as.factor(year), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.y = element_blank(),
        # axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 25)) +
  labs(fill = "Year", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

fig <- (p1 + p2) / (p3 + p4)

ggsave(here("figures_rev2", "nmds_CALVERT_year.png"), fig,
       width = 16, height = 12, dpi = 300)

```
```{r}
#Combining station month and year plots with dendrogram - sort of cool, but now have to figure out why DFO2 different. This is where a heatmpa plot comes in?

p1 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(month_surv), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.68),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

p2 <- ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(fill = as.factor(year), shape = site),
             size = 6) + 
  scale_fill_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  xlim(-0.4, 0.7) +
  theme(axis.title = element_text(size = 25, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        # axis.title.x = element_blank(),
        # axis.title.y = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 20, face = "bold", colour = "black"), 
        legend.text = element_text(size = 18, colour = "black"),
        legend.position = c(0.90, 0.75),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(shape = "Station", fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

fig <- (p1/p2) | p_dend

ggsave(here("figures_rev2", "nmds_dendro_5_clust.png"), fig,
       width = 16, height = 12, dpi = 300)

```

```{r}
#Can I get the order the same as the 
hc_order <- dendrogram_ends$sample_name

#Want to try a heatmap in the order of the one in the dendrogram.
micro_heat <- micro %>%
  unite(sample_name, c(site_id, date), sep = "_", remove = FALSE) %>% 
  filter(!site_id == "QU39")

# micro_heat %>% arrange(factor(sample_name, levels = hc_order)) 
micro_heat$sample_name <- factor(micro_heat$sample_name, levels = unique(hc_order)) 

#Setting order of species for figure
micro_heat$species_order <- factor(micro_heat$scientificName,
                                   (unique(micro_heat$scientificName
                                              [order(micro_heat$group,
                                                     micro_heat$scientificName)])))

micro_heat_ds <- micro_heat %>% 
  group_by(scientificName) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n > 10)

micro_heat %>%   
  filter(group == "Bacillariophyta") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_diatom.png"),
       width = 16, height = 18, dpi = 300)
```

```{r}
#Trying with only the indicator species (p <0.01)

micro_heat %>%   
  filter(scientificName == "Chaetoceros decipiens" |
           scientificName == "Dactyliosolen phuketensis" |
           scientificName == "Detonula pumila" |
           scientificName == "Thalassiosira rotula" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Dactyliosolen fragilissimus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(.~group, scales = "free_x", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.pu.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.1, 0.03),
        legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_2.png"),
       width = 13, height = 18, dpi = 300)
```
```{r}
#Indicator species from clustering - 5 clusters. 

micro_heat %>%   
  filter(scientificName == "Attheya" |
           scientificName == "Chaetoceros laciniosus" |
           scientificName == "Thalassiosira" |
           scientificName == "Scrippsiella trochoidea" |
           scientificName == "Atheya" |
           scientificName == "Teleaulax acuta" |
           scientificName == "Pseudo-nitzschia seriata" |
           scientificName == "Hillea" |
           scientificName == "Dactyliosolen phuketensis" | #good.
           scientificName == "Thalassiosira rotula" | #good
           scientificName == "Dactyliosolen fragilissimus" | #good
           scientificName == "Chaetoceros debilis" | #good
           scientificName == "Guinardia delicatula" | #good
           scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(.~group, scales = "free_x", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  scale_x_discrete(labels = c("Attheya" = "A.",
                              "Chaetoceros debilis" = "C.d.",
                              "Chaetoceros laciniosus" = "C.l.",
                              # "Chaetoceros decipiens" = "C.dec.",
                              # "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              # "Detonula pumila" = "D.pu.",
                              "Guinardia delicatula" = "G.d.",
                              # "Rhizosolenia setigera" = "R.s.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira" = "T.",
                              "Thalassiosira rotula" = "T.r.",
                              "Hillea" = "Hill.",
                              "Teleaulax acuta" = "T.a.",
                              "Scrippsiella trochoidea" = "S.t.")) +
                              # "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "none",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_5_clusters_abbr.png"),
       width = 13, height = 18, dpi = 300)
```
```{r}
#Indicator species from clustering - 5 clusters - organized by cluster.

#Indicator species from clustering - 5 clusters. 
micro_heat3 <- micro_heat

clust_df <- clust.df %>% 
  rename(sample_name = label)

micro_heat3 <- micro_heat3 %>% 
  left_join(clust_df) %>% 
  relocate(cluster, .after = site_id)

micro_heat3$sample_name <- factor(micro_heat3$sample_name,
                                   (unique(micro_heat3$sample_name
                                              [order(micro_heat3$cluster)])))


micro_heat3 %>%   
  filter(scientificName == "Attheya" |
           scientificName == "Chaetoceros laciniosus" |
           scientificName == "Thalassiosira" |
           scientificName == "Scrippsiella trochoidea" |
           scientificName == "Atheya" |
           scientificName == "Teleaulax acuta" |
           scientificName == "Pseudo-nitzschia seriata" |
           scientificName == "Hillea" |
           scientificName == "Dactyliosolen phuketensis" | #good.
           scientificName == "Thalassiosira rotula" | #good
           scientificName == "Dactyliosolen fragilissimus" | #good
           scientificName == "Chaetoceros debilis" | #good
           scientificName == "Guinardia delicatula" | #good
           scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(cluster ~ group, scales = "free", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  scale_x_discrete(labels = c("Attheya" = "A.",
                              "Chaetoceros debilis" = "C.d.",
                              "Chaetoceros laciniosus" = "C.l.",
                              # "Chaetoceros decipiens" = "C.dec.",
                              # "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              # "Detonula pumila" = "D.pu.",
                              "Guinardia delicatula" = "G.d.",
                              # "Rhizosolenia setigera" = "R.s.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira" = "T.",
                              "Thalassiosira rotula" = "T.r.",
                              "Hillea" = "Hill.",
                              "Teleaulax acuta" = "T.a.",
                              "Scrippsiella trochoidea" = "S.t.")) +
                              # "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "none",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_5_clusters_abbr_2.png"),
       width = 13, height = 18, dpi = 300)
```




```{r}

#Indicator species from clustering - 5 clusters. 
# micro_heat %>% arrange(factor(sample_name, levels = hc_order)) 
micro_heat2 <- micro_heat

micro_heat2$sample_name <- factor(micro_heat2$sample_name,
                                   (unique(micro_heat2$sample_name
                                              [order(micro_heat$date)])))


micro_heat2 %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(scientificName == "Ceratium horridum" |
           scientificName == "Corethron criophilum" |
           scientificName == "Teleaulax acuta" |
           scientificName == "Protoperidinium" |
           scientificName == "Prorocentrum" |
           scientificName == "Phaeocystis pouchetii" |
           scientificName == "Corythodinium" |
           scientificName == "Gonyaulax" |
           scientificName == "Dinophyceae" |
           scientificName == "Skeletonema marinoi" |
           scientificName == "Thalassiosira nordenskioeldii" |
           scientificName == "Leptocylindrus danicus" |
           scientificName == "Dinobryon" |
           scientificName == "Pseudo-nitzschia seriata" |
           scientificName == "Biddulphiales") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(year ~ group, scales = "free", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  scale_x_discrete(labels = c("Biddulphiales" = "Bid.",
                              "Corethron criophilum" = "C.c.",
                              "Leptocylindrus danicus" = "L.d.",
                              "Pseudo-nitzschia seriata" = "P.n.s",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira nordenskioeldii" = "T.n.",
                              "Dinobryon" = "Db.",
                              "Teleaulax acuta" = "T.a.",
                              "Ceratium horridum" = "C.h.",
                              "Corythodinium" = "C.",
                              "Dinophyceae" = "D.",
                              "Gonyaulax" = "G.",
                              "Prorocentrum" = "Prc.",
                              "Protoperidinium" = "Ptp.",
                              "Phaeocystis pouchetii" = "P.p.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "none",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_date_abbr.png"),
       width = 13, height = 18, dpi = 300)

```
```{r}

#Indicator species from clustering - 5 clusters. 
# micro_heat %>% arrange(factor(sample_name, levels = hc_order)) 
micro_heat_site <- micro_heat

micro_heat_site$sample_name <- factor(micro_heat_site$sample_name,
                                   (unique(micro_heat_site$sample_name
                                              [order(micro_heat_site$site_id)])))


micro_heat_site %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(scientificName == "Chaetoceros decipiens" |
           scientificName == "Dactyliosolen phuketensis" |
           scientificName == "Detonula pumila" |
           scientificName == "Thalassiosira rotula" |
           scientificName == "Ceratium lineatum" |
           scientificName == "Dactyliosolen fragilissimus" |
           scientificName == "Chaetoceros debilis" |
           scientificName == "Guinardia delicatula" |
           scientificName == "Rhizosolenia setigera" |
           scientificName == "Chaetoceros seiracanthus" |
           scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(site_id ~ group, scales = "free", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
                              "Chaetoceros decipiens" = "C.dec.",
                              "Chaetoceros seiracanthus" = "C.s.",
                              "Dactyliosolen fragilissimus" = "D.f.",
                              "Dactyliosolen phuketensis" = "D.ph.",
                              "Detonula pumila" = "D.pu.",
                              "Guinardia delicatula" = "G.d.",
                              "Rhizosolenia setigera" = "R.s.",
                              "Skeletonema marinoi" = "S.m.",
                              "Thalassiosira rotula" = "T.r.",
                              "Ceratium lineatum" = "C.l.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        # legend.position = c(0.1, 0.03),
        legend.position = "none",
        # legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_site_abbr.png"),
       width = 13, height = 18, dpi = 300)

```


```{r}
#Trying with only the indicator species (p <0.05)

micro_heat %>%   
  filter(scientificName == "Dinophysis acuta" | 
          scientificName == "Biddulphiales" |
          scientificName == "Chaetoceros decipiens" |
          scientificName == "Dactyliosolen phuketensis" |
          scientificName == "Detonula pumila" |
          scientificName == "Thalassiosira rotula" |
          scientificName == "Ditylum brightwellii" |
          scientificName == "Scrippsiella precaria" |
          scientificName == "Ceratium lineatum" |
          scientificName == "Dactyliosolen fragilissimus" |
          scientificName == "Chaetoceros debilis" |
          scientificName == "Guinardia delicatula" |
          scientificName == "Rhizosolenia setigera" |
          scientificName == "Chaetoceros seiracanthus" |
          scientificName == "Pseudo-nitzschia seriata" |
          scientificName == "Protoperidinium steinii" |
          scientificName == "Chaetoceros similis" |
          scientificName == "Pseudo-nitzschia" |
          scientificName == "Pterosperma" |
          scientificName == "Leptocylindrus danicus" |
          scientificName == "Pseudo-nitzschia" | 
          scientificName == "Skeletonema marinoi") %>% 
  ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
  geom_tile(color = "black", size = 1) +
  facet_grid(.~group, scales = "free_x", space = "free") +
  scale_fill_gradient(name = "",
                      low = "#FFFFFF",
                      high = "#012345") +
  # scale_fill_gradient2(name = "",
  #                      midpoint = 3,
  #                      low = "white",
  #                      mid = "blue",
  #                      high = "#FF0000") +
  # scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
  #                             "Chaetoceros decipiens" = "C.dec.",
  #                             "Chaetoceros seiracanthus" = "C.s.",
  #                             "Dactyliosolen fragilissimus" = "D.f.",
  #                             "Dactyliosolen phuketensis" = "D.ph.",
  #                             "Detonula pumila" = "D.pu.",
  #                             "Ditylum brightwellii" = "D.b.",
  #                             "Guinardia delicatula" = "G.d.",
  #                             "Rhizosolenia setigera" = "R.s.",
  #                             "Skeletonema marinoi" = "S.m.",
  #                             "Thalassiosira rotula" = "T.r.",
  #                             "Ceratium lineatum" = "C.l.",
  #                             "Prorocentrum micans" = "P.m.")) +
  # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        # legend.position = "bottomright",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.91, 0.03),
        legend.direction = "horizontal",
        axis.line = element_line(colour = "black"))

ggsave(here("figures_rev2", "heat_indicator_3.png"),
       width = 15, height = 18, dpi = 300)



#All indicator species
# filter(scientificName == "Dinophysis acuta" | 
#            scientificName == "Biddulphiales" |
#            scientificName == "Chaetoceros decipiens" |
#            scientificName == "Dactyliosolen phuketensis" |
#            scientificName == "Detonula pumila" |
#            scientificName == "Thalassiosira rotula" |
#            scientificName == "Ditylum brightwellii" |
#            scientificName == "Scrippsiella precaria" |
#            scientificName == "Ceratium lineatum" |
#            scientificName == "Dactyliosolen fragilissimus" |
#            scientificName == "Chaetoceros debilis" |
#            scientificName == "Guinardia delicatula" |
#            scientificName == "Rhizosolenia setigera" |
#            scientificName == "Chaetoceros seiracanthus" |
#            scientificName == "Pseudo-nitzschia seriata" |
#            scientificName == "Protoperidinium steinii" |
#            scientificName == "Chaetoceros similis" |
#            scientificName == "Pseudo-nitzschia" |
#            scientificName == "Pterosperma" |
#            scientificName == "Leptocylindrus danicus" |
#            scientificName == "Pseudo-nitzschia") %>% 



```





```{r}
#Looking at differences by year

#Still not sure the best way to look at this, but try to figure out at another time.


# micro_heat_date %>%   
#   filter(scientificName == "Ceratium horridum" | 
#            scientificName == "Corethron criophilum" |
#            scientificName == "Teleaulax acuta" |
#            scientificName == "Protoperidinium" |
#            scientificName == "Prorocentrum" |
#            scientificName == "Phaeocystis pouchetii" |
#            scientificName == "Corythodinium" |
#            scientificName == "Gonyaulax" |
#            scientificName == "Dinophyceae" |
#            scientificName == "Skeletonema marinoi" |
#            scientificName == "Thalassiosira nordenskioeldii" |
#            scientificName == "Leptocylindrus danicus" |
#            scientificName == "Dinobryon" |
#            scientificName == "Pseudo-nitzschia seriata" |
#            scientificName == "Biddulphiales") %>% 
#   ggplot(aes(x = species_order, y = sample_name, fill = log10(count+1))) +
#   geom_tile(color = "black", size = 1) +
#   facet_grid(.~group, scales = "free_x", space = "free") +
#   scale_fill_gradient(name = "",
#                       low = "#FFFFFF",
#                       high = "#012345") +
#   # scale_fill_gradient2(name = "",
#   #                      midpoint = 3,
#   #                      low = "white",
#   #                      mid = "blue",
#   #                      high = "#FF0000") +
#   # scale_x_discrete(labels = c("Chaetoceros debilis" = "C.deb.",
#   #                             "Chaetoceros decipiens" = "C.dec.",
#   #                             "Chaetoceros seiracanthus" = "C.s.",
#   #                             "Dactyliosolen fragilissimus" = "D.f.",
#   #                             "Dactyliosolen phuketensis" = "D.ph.",
#   #                             "Detonula pumila" = "D.pu.",
#   #                             "Ditylum brightwellii" = "D.b.",
#   #                             "Guinardia delicatula" = "G.d.",
#   #                             "Rhizosolenia setigera" = "R.s.",
#   #                             "Skeletonema marinoi" = "S.m.",
#   #                             "Thalassiosira rotula" = "T.r.",
#   #                             "Ceratium lineatum" = "C.l.",
#   #                             "Prorocentrum micans" = "P.m.")) +
#   # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank(),
#         # legend.position = "bottomright",
#         axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
#         text = element_text(size = 35),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(),
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(),
#         legend.position = c(0.91, 0.03),
#         legend.direction = "horizontal",
#         axis.line = element_line(colour = "black"))
# 
# ggsave(here("figures_rev2", "heat_indicator_date.png"),
#        width = 15, height = 18, dpi = 300)
```







```{r}
#separating treatments for following tests
season <-  micro_piv$season
site_id <- micro_piv$site_id
month <- micro_piv$month
year <- micro_piv$year

```

```{r}
#For clusters, need to merge on station/date code. 
clust_analysis <- micro_piv %>%
  unite(sample_name, c(site_id, date), sep = "_")

clust_df <- clust.df %>% 
  rename(sample_name = label)

clust_analysis <- clust_analysis %>% 
  left_join(clust_df) %>% 
  relocate(cluster, .after = season)

cluster <- clust_analysis$cluster


```




```{r}
#ANOSIM test to see if groupings statistically significant - abundance
ano_site = anosim(transform, site_id, distance = "bray", permutations = 9999)
ano_site

ano_month = anosim(transform, month, distance = "bray", permutations = 9999)
ano_month

ano_season = anosim(transform, season, distance = "bray", permutations = 9999)
ano_season

ano_year = anosim(transform, year, distance = "bray", permutations = 9999)
ano_year

ano_cluster = anosim(transform, cluster, distance = "bray", permutations = 9999)
ano_cluster

#Site and region are significant (p = 0.0001), with region having the highest R (0.62 vs 0.27) 

```
```{r}
#ANOSIM test to see if groupings statistically significant - relative
ano_site_rel = anosim(transform_rel, site_id, distance = "bray", permutations = 9999)
ano_site_rel

ano_month_rel = anosim(transform_rel, month, distance = "bray", permutations = 9999)
ano_month_rel

ano_season_rel = anosim(transform_rel, season, distance = "bray", permutations = 9999)
ano_season_rel

ano_year_rel = anosim(transform_rel, year, distance = "bray", permutations = 9999)
ano_year_rel

#Site and region are significant (p = 0.0001), with region having the highest R (0.62 vs 0.27) 

```

```{r}
#Indicator species analysis

#Indicators by station
inv_site = multipatt(transform, site_id, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_site)
```

```{r}
#Trying SIMPER
# inv_site = simper(transform, site_id, permutations = 9999)
# 
# summary(inv_site, ordered = TRUE)

```


```{r}
#by month
inv_month = multipatt(transform, month, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_month)
```

```{r}
#by year
inv_year = multipatt(transform, year, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_year)
```

```{r}
#by year
inv_cluster = multipatt(transform, cluster, func = "r.g",
                       control = how(nperm = 9999))

summary(inv_cluster)
```


```{r}
#Calculating Shannon diversity and putting in dataframe
div <- diversity(species)

div <- as.tibble(div)

div$site_id <- micro_piv$site_id

div$date <- micro_piv$date

div$month_surv <- micro_piv$month_surv

div <- div %>% 
  rename(shannon = value)
```


```{r}
#Plotting diversity metrics
f1 <- micro %>% 
  filter(!site_id == "QU39") %>% 
  group_by(date, site_id) %>% 
  mutate(n_spec = n()) %>% 
  ungroup() %>% 
  distinct(date, site_id, n_spec, .keep_all = TRUE) %>% 
  ggplot(aes(x = site_id, y = n_spec, fill = site_id)) + 
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = site_id), color = "black", trim = FALSE, binaxis = 'y', 
               stackdir = 'center', dotsize = 1,
               position = position_dodge(0.8)) +
  facet_wrap(~ month_surv, nrow = 1) +
  ggsci::scale_fill_npg() +
  labs(y = "Richness (# of species)") +
  theme_bw() +
  theme(legend.position = c(0.05, 0.90),
        legend.title = element_blank(),
        legend.background=element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 24),
        axis.text = element_text(colour = "black"))
  
f2 <- div %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>%  
  ggplot(aes(x = site_id, y = shannon, fill = site_id)) +
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = site_id), color = "black", trim = FALSE, binaxis = 'y', 
               stackdir = 'center', dotsize = 1,
               position = position_dodge(0.8)) +
  facet_wrap(~ month_surv, nrow = 1) +
  scale_x_discrete(labels = c("DFO2" = "F", "KC10" = "C", "QCS01" = "S",
                              "QU39" = "E")) +
  ggsci::scale_fill_npg() +
  labs(y = "Shannon H") +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size = 24),
        axis.text = element_text(colour = "black"))

fig <- f1/f2

ggsave(here("figures_rev2", "richness_shannon.png"), fig,
       width = 16, height = 8, dpi = 300)
```

```{r}
#Looking at some of the indicator species
micro %>% 
  filter(scientificName == "Chaetoceros decipiens") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)

micro %>% 
  filter(scientificName == "Dactyliosolen phuketensis") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)

micro %>% 
  filter(scientificName == "Detonula pumila") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)

micro %>% 
  filter(scientificName == "Ceratium lineatum") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)

micro %>% 
  filter(scientificName == "Dactyliosolen fragilissimus") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)

micro %>% 
  filter(scientificName == "Dinophysis acuta") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)

micro %>% 
  filter(scientificName == "Biddulphiales") %>% 
  ggplot(aes(x = date, y = species_sum, fill = site_id)) + 
  geom_point(pch = 21, size = 3)
```


















