---
title: "pca_environemtal_data"
output: html_notebook
---

Running PCA and cluster analysis on environmental variables.

```{r}
#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))

#Importing chemtax data separately. I just use this to calibrate a new chlorophyll dataset that fixes some data quality gaps.
chem <- read_csv(here("outputs", "chemtax_master_2021-11-04.csv")) 
```

```{r}
#This just ensures that there are no exact duplicates introducted through joining. There aren't here, but it must have occured in earlier versions and I am keeping it in-case I make changes in the future.
data <- data %>% 
  distinct(date, site_id, .keep_all = TRUE)

#Removing QU39 for this worksheet
data <- data %>% 
  filter(!site_id == "QU39")
```

```{r}
#For Chl, I want to use Chl for 2018 and HPLC for 2019 and 2020 as there is greater data availability. I need to merge the 2018 chl with the 2019-2020 HPLC, but first calibrate the 2018 chlorophyll so that is comparable to the HPLC in 2019 and 2020.

#Separate chlorophyll data from before 2018
chl_bulk <- data %>%
  select(date, site_id, bulk_chl) %>% 
  filter(date < "2019-01-01") %>% 
  rename(chl = bulk_chl)

#For the pre-2018 data, make comparable through using the relationship between HPLC and chlorophyll from 2019 and 2020 (determined these in a separate workbook)
chl_bulk_fix <- chl_bulk %>% 
  mutate(chl = (0.65*chl) + 0.59 )

#Make the chemtax data long format and then calculate TChla from HPLC via addition of chlorophyll from each chemtax group. Was just easier than uploading another sheet with just the HPLC Tchla concentrations
chem_tidy <- chem %>% 
  pivot_longer(c(cyan, hapto, green, cryp, dino, dict, raph, diat),
                 names_to = "phyto_group", values_to = "TChla") %>% 
  group_by(date, site_id, phyto_group) %>% 
  summarize(TChla_mean = mean(TChla)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(TChla_sum = sum(TChla_mean)) %>% 
  ungroup()

#Separating out the calculated TChla concentrations from above.
chl_hplc <- chem_tidy %>% 
  select(date, site_id, chl = TChla_sum) %>% 
  distinct(date, site_id, chl, .keep_all = TRUE)

#Merging the 2018 calibrated chlorophyll to the 2019 and 2020 TChla from HPLC.
chl_merge <- rbind(chl_bulk_fix, chl_hplc)
```

```{r}
#Trying a PCA -  already scaled
pca <- rda(expl)

head(summary(pca))

loadings <- scores (pca, display = 'species', scaling = 0)
loadings

sort (abs (loadings[,1]), decreasing = TRUE)
```
```{r}
biplot (pca, display = 'species', scaling = 'species')
```
```{r}
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR2/cleanplot.pca.R')
par (mfrow = c(1,2))
cleanplot.pca (pca, scaling = 1)
cleanplot.pca (pca, scaling = 2)
```

```{r}
#Looking into importance of each axis

# define "evplot" function first:
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR1/evplot.R')

# Finally, in the PCA object select the component $eig with the vector of eigenvalues:
ev <- pca$CA$eig

evplot (ev)
```
```{r}
library (BiodiversityR)
sig <- PCAsignificance (pca, axes = 14)
sig

barplot(sig[c('percentage of variance', 'broken-stick percentage'), ], beside = T, 
  xlab = 'PCA axis', ylab = 'explained variation [%]', col = c('grey', 'black'), 
  legend = TRUE)
```
```{r}


#Trying the same thing, but bringing in arrows from previous plot - trying scaling 2
#pdf(file = "rda_s2.pdf", width = 6.5, height = 5, pointsize = 2)

p_pca <- biplot(pca, scaling = 1, type = "none", xlab = c("PCA1"),
               ylab = c("PCA2"), xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1))

# points(rda.signif, display = 'sites', pch = 21, cex = 2.2,
#        col = rgb(red = 1, green = 1, blue = 1, alpha = 0.5), scaling = 2,
#        bg = bg[eco])

points(scores(pca, display = 'sites', choices = c(1, 2), scaling = 1),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(mm_no_chl$site_id)])

#So since distance doesn't matter, I can make arrows longer with scaling 2? 
# arrows(0,0, scores(rda.signif, display = "species", choices = c(1),
#                    scaling = 1), scores(rda.signif, display = "species",
#                                             choices = c(2), scaling = 1),
#        col = "black", length = 0)

# text(pca, scaling = 1, display = "bp", col = "blue",cex = 0.8, font = 2)

# text(scores(rda.signif, display = "species", choices = c(1), scaling = 1),
#      scores(rda.signif, display = "species", choices = c(2), scaling = 1),
#      labels = rownames(scores(rda.signif, display = "species", scaling = 1)),
#      col = "black", cex = 0.8, font = 2)


# legend("topleft", legend = levels(eco), bty ="n", col="gray32", pch = 21,
#        cex = 1.5, pt.bg = bg)

legend("topright", legend = c(levels(as.factor(mm$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

#dev.off()


```
```{r}
#Setting up parameters for plotting PCA

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc_pca <- sites.long(p_pca, env.data = expl)
meta_pca <- mm_no_chl[,1:4]
sites_loc_pca <- cbind(meta_pca, sites_loc_pca)
head(sites_loc_pca)

#Species location in ordination
species_loc_pca <- species.long(p_pca)
species_loc_pca

axis.long_pca <- axis.long(pca, choices = c(1, 2))
axis.long_pca

#these are both throwing zeros - One I won't need because I'm not plotting species vectors.
#trying something from here. https://tem11010.github.io/Plotting-PCAs/
# env_loc_pca <- as.data.frame(pca$biplot[,1:2])
vscores <- as.data.frame(pca$CA$v)
```


```{r}
#Plotting PCA.

# sp_loc_pca <-  as.data.frame(pca$species[,1:2])

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, fill = as.factor(month_surv),
                                   shape = site_id, stroke = 1.5), 
             size = 6, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'darkgray', size = 1) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1",
       y = "PCA2") +
  xlim(-1.0, 1.4) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.9, 0.6),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Season", shape = "Station")

ggsave(here("figures_rev2", "PCA_test1.png"),
       width = 10, height = 7, dpi = 300)
```
