---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(patchwork)
library(RColorBrewer)
library(ggsci)
```

```{r}
#Upload data
ctd <- read_csv(here("files", "ctd.csv")) 

nuts <- read_csv(here("files", "nuts_2021-08-17.csv"))

secchi <- read_csv(here("files", "secchi.csv"))

```

```{r}
#Fixing datset so it is easier to work with

#making labels shorter
ctd <- ctd %>% 
  rename(pres = `Pressure (dbar)`,
         sal = `Salinity (PSU)`,
         temp = `Temperature (deg C)`,
         date = `Measurement time`,
         station = Station,
         cast_pk = `Cast PK`,
         par = `PAR (umol m-2 s-1)`)

#adding year, month and date
ctd <- ctd %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date))

ctd_coord <- ctd %>% 
  distinct(station, Latitude, Longitude)

#filling in lat where not present
ctd <- ctd %>% 
  mutate(Latitude = case_when(station == "QU39" & is.na(Latitude) ~ 50.03001,
                              station == "QCS01" & is.na(Latitude) ~ 51.70493,
                              station == "KC10" & is.na(Latitude) ~ 51.65064,
                              station == "DFO2" & is.na(Latitude) ~ 51.52111,
         TRUE ~ as.numeric(as.character(Latitude))))

#filling in lat where not present
ctd <- ctd %>% 
  mutate(Longitude = case_when(station == "QU39" & is.na(Longitude) ~ -125.0989,
                              station == "QCS01" & is.na(Longitude) ~ -128.2388,
                              station == "KC10" & is.na(Longitude) ~ -127.9513,
                              station == "DFO2" & is.na(Longitude) ~ -127.5590,
         TRUE ~ as.numeric(as.character(Longitude))))

nuts <- nuts %>%  
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date))

```

```{r}
#Performing gsw calculations

#Calculating absolute salinity
SA <- gsw_SA_from_SP(ctd$sal, ctd$pres, ctd$Longitude, ctd$Latitude)

SA <- as.data.frame(SA)

#conservative temperature
CT <- gsw_CT_from_t(SA$SA, ctd$temp, ctd$pres)

CT <- as.data.frame(CT)

#Density
rho = gsw_rho(SA$SA,CT$CT,ctd$pres)

rho <- as.data.frame(rho)

#Brunt-Vaisala frequency
bv <- gsw_Nsquared(SA$SA, CT$CT, ctd$pres)

bv <- bind_rows(bv)

#Had to add a row to bottom to make vector length equal. Ask Jessy if this is the best way to do this.
bv <- bv %>% 
  add_row(N2 = NA, p_mid = NA)

#Binding calculations to ctd data
ctd <- cbind(ctd, SA, CT, rho, bv)

# To Do

#Look into whether flagging is correct

```
```{r}
#Performing calculations

#Finding minimum cast start depth for each profile to determine range of depths to use for density difference. Only 5 casts start deeper than three metres and only 1 doesn't go to 30m.
range_pres <- ctd %>% 
  group_by(cast_pk) %>% 
  summarise(min_pres = min(pres),
            max_pres = max(pres)) %>% 
  ungroup() %>% 
  arrange(desc(min_pres))

#The next few steps are used to determine the density difference as a measure of stratification. Using 2 and 30m

#Filter 2m data
ctd_2 <- ctd %>% 
  filter(pres == 2) %>% 
  select(cast_pk, station, Latitude, Longitude, date, year:day, rho)

#filter 30m data
ctd_30 <- ctd %>% 
  filter(pres == 30) %>% 
  select(cast_pk, rho)

#joining 2m data to 3m data - didn't work.
ctd_dd <- ctd_2 %>% 
  left_join(ctd_30, by = "cast_pk") %>% 
  rename(rho_2 = rho.x, 
         rho_30 = rho.y)

#Calculating difference in density
ctd_dd <- ctd_dd %>% 
  mutate(delta_rho = rho_30 - rho_2)
  
```

```{r}
ctd <- ctd %>% 
  filter(date > "2018-01-01" & date < "2021-01-01")

nuts <- nuts %>% 
  filter(date > "2018-01-01" & date < "2021-01-01")

nuts_dm <- nuts %>% 
  filter(line_out_depth == 5) %>% 
  select(ymd = date, station = site_id, no2_no3_um, sio2, po4) %>% 
  group_by(ymd, station) %>% 
  summarise(no2_dm = mean(no2_no3_um),
            sio2_dm = mean(sio2),
            po4_dm = mean(po4)) %>% 
  ungroup()
```

```{r}
# Bringing in nutrient data that is not finalized and has some errors
nuts_bad <- read_xlsx(here("files", "nuts_bad_2020.xlsx"))

#Fixing names for joining
nuts_bad <- nuts_bad %>%  
  rename(hakai_id = `Sample ID`)

#pulling data that doesn't have a match
nuts_nd <- nuts %>% 
  filter(line_out_depth == 5 & date > "2020-06-24") %>% 
  select(date, hakai_id, station = site_id)

#Joining hakai IDS so concentrations have metadata (date and station). Checking for replicates. There are none.
nuts_nd_join <- nuts_nd %>% 
  left_join(nuts_bad, by = "hakai_id") %>% 
  drop_na() %>% 
  group_by(date, station) %>% 
  mutate(n = n()) %>% 
  ungroup()

#Binding the "bad data" with the nutrient daily mean dataset to complete timeseries.
nuts_nd_join <-  nuts_nd_join %>% 
  select(ymd = date, station, no2_dm = `NO3+NO2`, sio2_dm = SiO2, po4_dm = PO4)

nuts_dm <- nuts_dm %>% 
  drop_na() 

nuts_dm_bd <- rbind(nuts_nd_join, nuts_dm)

nuts_dm_bd <- nuts_dm_bd %>% 
  arrange(ymd, station)

```

```{r}
nuts_qu39 <- nuts_dm_bd %>% 
  rename(date = ymd) %>% 
  filter(station == "QU39" &
         (date == "2018-05-29" | #could also be 05-22
         date == "2018-06-26" |
         date == "2018-07-23" | # Could also be 07-16
         date == "2018-08-21" | # 08-14, 08-28
         date == "2018-09-13" |   
         date == "2018-10-24" |
         date == "2019-05-09" |
         date == "2019-06-04" |
         date == "2019-07-09" |
         date == "2019-08-07" |
         date == "2019-08-29" |
         date == "2019-10-09" |
         #date == "2019-11-26" | #removing this for multi-year analysis
         date == "2020-04-29" | #Different month, but very close temporally
         date == "2020-06-04" |
         date == "2020-07-09" | # Also 06-30 - Tricky
         date == "2020-08-04" | # Also 08-13 
         date == "2020-09-01" |
         date == "2020-10-08"))
            
#Merge with qu39 and calvert
nuts_no_qu39 <- nuts_dm_bd %>% 
  rename(date = ymd) %>% 
  filter(!station == "QU39")

nuts_scaled <- rbind(nuts_qu39, nuts_no_qu39)


#Dates that were collected on the cusp of a month change - rest of survey was done in following month. Just done for ease of plotting.
nuts_scaled <- nuts_scaled %>%  
  mutate(month = lubridate::month(date),
         month = case_when(date == "2019-08-29" ~ 9,
                           date == "2019-08-31" ~ 9,
                           date == "2020-04-29" ~ 5,
                           date == "2020-04-30" ~ 5,
                             TRUE ~ as.numeric (month)))

nuts_scaled <- nuts_scaled %>% 
  filter(date > "2018-01-01" & date < "2021-01-01" & month > 4 & month < 11)


nuts_scaled <- nuts_scaled %>%
  mutate(season = case_when(month == 5 | month == 6 ~ "Sp",
                            month == 7 | month == 8 ~ "Su",
                            month == 9 | month == 10 ~ "Au")) %>%
  relocate(season, .after = month)

```

```{r}
ctd_5 <- ctd %>% 
  filter(pres == 5) %>% 
  rename(date_long = date) %>% 
  mutate(date = lubridate::date(date_long))

ctd_5_qu39 <- ctd_5 %>% 
  filter(station == "QU39" &
         (date == "2018-05-29" | #could also be 05-22
         date == "2018-06-26" |
         date == "2018-07-23" | # Could also be 07-16
         date == "2018-08-21" | # 08-14, 08-28
         date == "2018-09-13" |   
         date == "2018-10-24" |
         date == "2019-05-09" |
         date == "2019-06-04" |
         date == "2019-07-09" |
         date == "2019-08-07" |
         date == "2019-08-29" |
         date == "2019-10-09" |
         #date == "2019-11-26" | #removing this for multi-year analysis
         date == "2020-04-29" | #Different month, but very close temporally
         date == "2020-06-04" |
         date == "2020-07-09" | # Also 06-30 - Tricky
         date == "2020-08-04" | # Also 08-13 
         date == "2020-09-01" |
         date == "2020-10-08"))
            
#Merge with qu39 and calvert
ctd_5_no_qu39 <- ctd_5 %>% 
  filter(!station == "QU39")

ctd_scaled <- rbind(ctd_5_qu39, ctd_5_no_qu39)


#Dates that were collected on the cusp of a month change - rest of survey was done in following month. Just done for ease of plotting.
ctd_scaled <- ctd_scaled %>%  
  mutate(month = lubridate::month(date),
         month = case_when(date == "2019-08-29" ~ 9,
                           date == "2019-08-31" ~ 9,
                           date == "2020-04-29" ~ 5,
                           date == "2020-04-30" ~ 5,
                             TRUE ~ as.numeric (month)))

ctd_scaled <- ctd_scaled %>% 
  filter(date > "2018-01-01" & date < "2021-01-01" & month > 4 & month < 11)


ctd_scaled <- ctd_scaled %>%
  mutate(season = case_when(month == 5 | month == 6 ~ "Sp",
                            month == 7 | month == 8 ~ "Su",
                            month == 9 | month == 10 ~ "Au")) %>%
  relocate(season, .after = month)

ctd_dd_merge <- ctd_dd %>% 
  select(cast_pk, delta_rho)

ctd_scaled <- ctd_scaled %>% 
  left_join(ctd_dd_merge)

ctd_scaled_check <- ctd_scaled %>% 
  group_by(date, station) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n > 1) %>% 
  select(cast_pk, date, date_long,station, pres, sal, temp, delta_rho, n) %>% 
  arrange(station)

ctd_scaled <- ctd_scaled %>%
  select(date, month, season, station, pres, sal, temp, delta_rho)

ctd_scaled <- ctd_scaled %>% 
  group_by(date, station) %>% 
  mutate(temp = mean(temp),
         sal = mean(sal),
         delta_rho = mean(delta_rho)) %>% 
  ungroup

ctd_scaled <- ctd_scaled %>% 
  distinct(date, station, sal, temp, delta_rho, .keep_all = TRUE)

ctd_scaled_month_check <- ctd_scaled %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year, month, station) %>% 
  mutate(n_month = n()) %>% 
  ungroup %>% 
  filter(n_month > 1)

#QCS01 - 2018-05-22, 2018-05-29. 2018-05-29 is the match used in RDA
#DFO2 - 2020-09-03, 2020-09-07. 2020-09-05 is what I have in RDA merged dataset. WEIRD. I need to have a central data wrangling file and then write out to all the other analysis. Getting to messy and convoluted and mistakes are being made.
```

```{r}
#Sub-setting secchi data to only include May to October and select QU39 with the closest matching dates to the Calvert surbeys

secchi_qu39_ds <- secchi %>%
  filter(site_id == "QU39")

#Trying to plot Relative in a different way - CHEMTAX
secchi_qu39_ds <- secchi_qu39_ds %>%
  filter(date == "2018-05-29" | #could also be 05-22
         date == "2018-06-26" |
         date == "2018-07-23" | # Could also be 07-16
         date == "2018-08-21" | # 08-14, 08-28
         date == "2018-09-13" |   
         date == "2018-10-24" |
         date == "2019-05-09" |
         date == "2019-06-04" |
         date == "2019-07-09" |
         date == "2019-08-07" |
         date == "2019-08-29" |
         date == "2019-10-09" |
         #date == "2019-11-26" | #removing this for multi-year analysis
         date == "2020-04-29" | #Different month, but very close temporally
         date == "2020-06-04" |
         date == "2020-07-09" | # Also 06-30 - Tricky
         date == "2020-08-04" | # Also 08-13 
         date == "2020-09-01" |
         date == "2020-10-08")

secchi_ds <- secchi %>%
  filter(!site_id == "QU39")

secchi_ds <- rbind(secchi_ds, secchi_qu39_ds)


secchi_ds <- secchi_ds %>%  
  mutate(month = lubridate::month(date),
         month = case_when(date == "2019-08-29" ~ 9,
                           date == "2019-08-31" ~ 9,
                           date == "2020-04-29" ~ 5,
                           date == "2020-04-30" ~ 5,
                             TRUE ~ as.numeric (month)))

secchi_ds <- secchi_ds %>% 
  filter(date > "2018-01-01" & date < "2021-01-01" & month > 4 & month < 11)



```



```{r}
#Boxplot panel. 

p1 <- ctd_scaled %>% 
  ggplot(aes(x = as.factor(month), y = temp, fill = station)) +
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = station), color = "black", trim = FALSE, binaxis='y', 
               stackdir = 'center', dotsize = 1,
               position = position_dodge(0.8)) +
  scale_fill_npg() +
  labs(y = "Temp (\u00B0C)",
       x = "Month") +
  theme_bw() +
  theme(legend.position = c(0.07, 0.75),
        legend.title = element_blank(),
        legend.background=element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"))

p2 <- ctd_scaled %>% 
  ggplot(aes(x = as.factor(month), y = sal, fill = station)) +
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = station), color = "black", trim = FALSE, binaxis='y', 
               stackdir ='center', dotsize = 1,
               position = position_dodge(0.8)) +
  scale_fill_npg() +
  labs(y = "Salinity",
       x = "Month") +
  theme_bw() +
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"))

p3 <- ctd_scaled %>% 
  ggplot(aes(x = as.factor(month), y = delta_rho, fill = station)) +
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = station), color = "black", trim = FALSE, binaxis='y', 
               stackdir ='center', dotsize = 1,
               position = position_dodge(0.8)) +
  scale_fill_npg() +
  labs(y = expression(~ Delta * rho ~ "(30-2m)"),
       x = "Month") +
  theme_bw() +
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"))

p4 <- nuts_scaled %>% 
  ggplot(aes(x = as.factor(month), y = no2_dm, fill = station)) +
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = station), color = "black", trim = FALSE, binaxis='y', 
               stackdir = 'center', dotsize = 1,
               position = position_dodge(0.8)) +
   scale_fill_npg() +
  labs(y = expression(NO[3]^{"-"} ~ "+" ~ NO[2]^{"-"}),
       x = "Month") +
  theme_bw() +
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"))

p5 <- secchi_ds %>% 
  ggplot(aes(x = as.factor(month), y = line_out_depth, fill = site_id)) +
  geom_boxplot(position = position_dodge(preserve = "single"), alpha = 0.6,
               color = "black", lwd = 0.7) +
  geom_dotplot(aes(fill = site_id), color = "black", trim = FALSE, binaxis='y', 
               stackdir='center', dotsize = 1,
               position = position_dodge(0.8)) +
  ylim(0, 15) +
  scale_fill_npg() +
  labs(y = "Secchi (m)",
       x = "Month") +
  theme_bw() +
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        text = element_text(size = 30),
        axis.text = element_text(colour = "black"))

fig <- p1/p2/p3/p4/p5

ggsave(here("figures_new", "box_descriptor_stats.png"), 
       fig, width = 14, height = 15, dpi=300)
```








