---
title: "R Notebook"
output: html_notebook
---

 

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(gsw)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)

#From https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html#1_Packages_needed

#For plotting with ggplot2

library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
```

```{r}
#Upload data

#ctd data with gsw calculations
ctd_calcs <- read_csv(here("outputs", "ctd_calcs.csv")) 

#delta rho data
ctd_dd <- read_csv(here("outputs", "ctd_dd.csv"))

#nutrient data
nuts <- read_csv(here("outputs", "nuts.csv"))

#turbidity data with offset corrections
turb_corr <- read_csv(here("outputs", "corrected_turbidity_v1.csv"))

#chl
chl <- read_csv(here("files", "chl.csv"))

```

```{r}
#Further work to some of the ctd data for merging

#Pulling out data I need for merging with ctd - There are duplicate casts here, so for now performing daily mean.
ctd_dd_dm <- ctd_dd %>% 
  select(date, station, delta_rho) %>% 
  mutate(ymd = lubridate::date(date)) %>% 
  group_by(ymd, station) %>% 
  summarise(dd_dm = mean(delta_rho)) %>%
  ungroup()
  

#Pulling out data I need for merging with ctd
turb_corr_dm <- turb_corr %>% 
  filter(pressure == 5) %>% 
  select(ymd = date, station, turb_cor) %>% 
  group_by(ymd, station) %>% 
  summarise(turb_dm = mean(turb_cor)) %>%
  ungroup()

#Finding the N2 max
n2_max_dm <- ctd_calcs %>% 
  mutate(ymd = lubridate::date(date)) %>%
  select(cast_pk, ymd, station, N2) %>% 
  group_by(cast_pk) %>% 
  mutate(n2_max = max(N2)) %>% 
  ungroup() %>% 
  distinct(cast_pk, n2_max, .keep_all = TRUE) %>% 
  group_by(ymd, station) %>% 
  summarise(n2_max_dm = mean(n2_max)) %>% 
  ungroup()
  
#cutting out data I am using from 5m depth - for some reason throwing tons of duplicates in temp/sal
ctd_dm <- ctd_calcs %>% 
  filter(pres == 5) %>%
  mutate(ymd = lubridate::date(date)) %>%
  select(ymd, station, temp, sal) %>%
  group_by(ymd, station) %>% 
  mutate(sal_dm = mean(sal),
         temp_dm = mean(temp)) %>% 
  ungroup() %>% 
  distinct(ymd, station, temp_dm, sal_dm)

nuts_dm <- nuts %>% 
  filter(line_out_depth == 5) %>% 
  select(ymd = date, station = site_id, no2_no3_um, sio2, po4) %>% 
  group_by(ymd, station) %>% 
  summarise(no2_dm = mean(no2_no3_um),
            sio2_dm = mean(sio2),
            po4_dm = mean(po4)) %>% 
  ungroup()
  
  
# ctd_merge <- ctd_dm %>% 
#   left_join(ctd_dd_dm, by = c("station", "ymd")) %>% 
#   left_join(turb_corr_dm, by = c("station", "ymd")) %>% 
#   left_join(n2_max_dm, by = c("station", "ymd")) %>% 
#   left_join(nuts_dm, by = c("station", "ymd"))
# 
# #Cleaning/standardizing for merge with microscopy and chemtax
# ctd <- ctd_merge %>% 
#   rename(date = ymd, site_id = station, sal = sal_dm, temp = temp_dm,
#          dr = dd_dm, turb = turb_dm, n2_max = n2_max_dm, no2 = no2_dm,
#          sio2 = sio2_dm, po4 = po4_dm)
# 
# write_csv(ctd_merge, here("outputs", "ctd_merge.csv"))

#OK, so all of the physical and chemical data are merged. I could consider adding FWC, solar, wind, 1026 depth etc.
```


```{r}
# Bringing in nutrient data that is not finalized and has some errors
nuts_bad <- read_xlsx(here("files", "nuts_bad_2020.xlsx"))

#Fixing names for joining
nuts_bad <- nuts_bad %>%  
  rename(hakai_id = `Sample ID`)

#pulling data that doesn't have a match
nuts_nd <- nuts %>% 
  filter(line_out_depth == 5 & date > "2020-06-24") %>% 
  select(date, hakai_id, station = site_id)

#Joining hakai IDS so concentrations have metadata (date and station). Checking for replicates. There are none.
nuts_nd_join <- nuts_nd %>% 
  left_join(nuts_bad, by = "hakai_id") %>% 
  drop_na() %>% 
  group_by(date, station) %>% 
  mutate(n = n()) %>% 
  ungroup()

#Binding the "bad data" with the nutrient daily mean dataset to complete timeseries.
nuts_nd_join <-  nuts_nd_join %>% 
  select(ymd = date, station, no2_dm = `NO3+NO2`, sio2_dm = SiO2, po4_dm = PO4)

nuts_dm <- nuts_dm %>% 
  drop_na() 

nuts_dm_bd <- rbind(nuts_nd_join, nuts_dm)

nuts_dm_bd <- nuts_dm_bd %>% 
  arrange(ymd, station)

```

```{r}
#Merging all CTD calculations with turbidity and nutrients including bad 2020 data

ctd_merge <- ctd_dm %>% 
  left_join(ctd_dd_dm, by = c("station", "ymd")) %>% 
  left_join(turb_corr_dm, by = c("station", "ymd")) %>% 
  left_join(n2_max_dm, by = c("station", "ymd")) %>% 
  left_join(nuts_dm_bd, by = c("station", "ymd"))

#Cleaning/standardizing for merge with microscopy and chemtax
ctd <- ctd_merge %>% 
  rename(date = ymd, site_id = station, sal = sal_dm, temp = temp_dm,
         dr = dd_dm, turb = turb_dm, n2_max = n2_max_dm, no2 = no2_dm,
         sio2 = sio2_dm, po4 = po4_dm)

write_csv(ctd_merge, here("outputs", "ctd_merge_nuts-bd.csv"))
```



```{r}
#Wrangling Chl data

#Selecting only Size fractions, checking for duplicates, calculating relative contributions of each size fraction
chl <- chl %>% 
  filter(chla_flag == "AV" | chla_flag == "ADL" |
           is.na(chla_flag)) %>% 
  select(date, site_id, filter_type, chla, chla_flag) %>% 
  group_by(date, site_id) %>% 
  mutate(n = n(),
         chl_sum = sum(chla)) %>% 
  ungroup() %>% 
  mutate(chl_per = chla/chl_sum)

#Pivoting wider for joining with other data
chl_wide <- chl %>% 
  select(date, site_id, filter_type, chla) %>% 
  pivot_wider(names_from = filter_type, values_from = chla)

chl_qu39 <- chl_wide %>%
  filter(site_id == "QU39") %>% 
  filter(date == "2018-05-29" | #could also be 05-22
         date == "2018-06-26" |
         date == "2018-07-23" | # Could also be 07-16
         date == "2018-08-21" | # 08-14, 08-28
         date == "2018-09-13" |   
         date == "2018-10-24" |
         date == "2019-05-09" |
         date == "2019-06-04" |
         date == "2019-07-09" |
         date == "2019-08-07" |
         date == "2019-08-29" |
         date == "2019-10-09" |
         #date == "2019-11-26" | #removing this for multi-year analysis
         date == "2020-04-29" | #Different month, but very close temporally
         date == "2020-06-04" |
         date == "2020-07-09" | # Also 06-30 - Tricky
         date == "2020-08-04" | # Also 08-13 
         date == "2020-09-01" |
         date == "2020-10-08")

chl_cal <- chl_wide %>% 
  filter(!site_id == "QU39")

chl_wide <- rbind(chl_qu39, chl_cal)

```



```{r}
#Upload Microscopy data
#Upload output from OBIS taxonomy matching/formatting for Calvert data.
cal <- read_csv(here("files", "calvert.csv")) 

qu39 <- read_csv(here("files", "qu39.csv"))

#Removing data outside of the date of investigation
# cal <- cal %>% 
#   filter(date > "2019-05-10" & date < "2019-12-01")

cal <- cal %>% 
  filter(trophicStatus == "auto")

#Selecting closest temporal stations from QU39
qu39 <- qu39 %>% 
  filter(trophicStatus == "auto")

qu39 <- qu39 %>% 
  filter(date == "2018-05-29" | #could also be 05-22
         date == "2018-06-26" |
         date == "2018-07-23" | # Could also be 07-16
         date == "2018-08-21" | # 08-14, 08-28
         date == "2018-09-13" |   
         date == "2018-10-24" |
         date == "2019-05-09" |
         date == "2019-06-04" |
         date == "2019-07-09" |
         date == "2019-08-07" |
         date == "2019-08-29" |
         date == "2019-10-09" |
         #date == "2019-11-26" | #removing this for multi-year analysis
         date == "2020-04-29" | #Different month, but very close temporally
         date == "2020-06-04" |
         date == "2020-07-09" | # Also 06-30 - Tricky
         date == "2020-08-04" | # Also 08-13 
         date == "2020-09-01" |
         date == "2020-10-08")
            
#Merge with qu39 and calvert
micro <- rbind(cal, qu39)

#Dates that were collected on the cusp of a month change - rest of survey was done in following month. Just done for ease of plotting.
micro <- micro%>%  
  mutate(month = lubridate::month(date),
         month = case_when(date == "2019-08-29" ~ 9,
                           date == "2019-08-31" ~ 9,
                           date == "2020-04-29" ~ 5,
                           date == "2020-04-30" ~ 5,
                             TRUE ~ as.numeric (month)))

micro <- micro %>% 
  filter(date > "2018-01-01" & date < "2021-01-01" & month > 4 & month < 11)

micro_distinct <- micro %>% 
  distinct(date, site_id)

#Annoying
spCodes(micro$scientificName, nchar.gen = 8, nchar.sp = 4, nchar.ssp = 0, 
sep.species = " ", sep.spcode = ".")

# micro <- micro %>% 
#   filter(!site_id == "QU39")

```

```{r}
#Could try to limit cryptic species that influence stats. Leaving off for now.

#Only species occurring in 25% of the samples - could try this.

# Counting how many times each species is observed
micro <- micro %>%
   group_by(scientificName) %>%
   mutate(num_occurrence = n())

# removing species that have not been observed at least twice.
# micro <- micro %>%
#   filter(num_occurrence > 2)
```

```{r}
#Selecting columns
micro <- micro %>% 
  select(date, site_id, group, scientificName, count)


  

# Because I have some species separated out with identificationRemarks, identificationQualifiers and different resting stages, I sum these. If I don't, then the pivoting in later stages results in columns with combined numbers. I need to decide on best method for this once I have the analysis zeroed in. 

#I could re-merge the qualifiers with the name to separate out some of groups here, especially if they are important, such as the unidentified small dinoflagellates.

#Again, not sure if I want to do this...
# micro <- micro %>%
#   group_by(date, site_id, scientificName) %>%
#   summarize(species_sum = sum(count)) %>%
#   ungroup()

# micro_group <- micro %>% 
#   distinct(group)

micro <- micro %>%
  filter(!scientificName == "Protozoa") %>%
  group_by(date, site_id, scientificName) %>%
  summarize(species_sum = sum(count)) %>%
  ungroup()

# micro <- micro %>% 
#   filter(!scientificName == "Protozoa" & !site_id == "QU39") %>% 
#   group_by(date, site_id, group) %>% 
#   summarise(count  = sum(count)) %>% 
#   ungroup()

#pivoting longer so species are columns. 
micro_piv <- micro %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Adding date columns
micro_piv <- micro_piv %>% 
  mutate(month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  relocate(month, .after = date) %>% 
  relocate(yday, .after = month)

#Roughly adding seasons - would like to make cosmological seasons
micro_piv <- micro_piv %>%
  mutate(season = case_when(month %in% c(12, 1, 2) ~ "winter",
                            month >= 3 & month <= 6 ~ "spring",
                            month >= 7 & month <= 9 ~ "summer",
                            month >= 10 & month <= 11 ~ "autumn",)) %>%
  relocate(season, .after = month)

micro_piv <- micro_piv %>% 
  arrange(site_id, date)

#Pulling out species counts for transform and input into clustering and NMDS
# transform <- micro_piv[, 6:ncol(micro_piv)]  
  
#Log10 transformation +1 (as per Mahara)
# transform <- log10(transform + 1)

#Performing clustering
# dend_micro <- transform %>% 
#   vegdist("bray") %>% 
#   hclust(method = "average") %>% 
#   as.dendrogram()


```

```{r}
#merging using the truncated microscopy data as

#Merging the microscopy data with the physical/chemical data. Here, the microscopy data was already filtered to the 2019 May to November period.
micro_merge <- micro_piv %>% 
  left_join(ctd, by = c("date", "site_id"))

#Only keeping 2um SF as was overwhelming everything else
chl_wide <- chl_wide %>%
  select(date, site_id, GFF_chl = `GF/F`, Chl = `Bulk GF/F`)


#Merging with Chl data
micro_merge <- micro_merge %>% 
   left_join(chl_wide, by = c("date", "site_id"))

#Seems to be some wierd data mis-matches. Will need to cross check this for accuracy. Particularily days when chlorophyll exists, but no other measurements. Shouldn't happen.

```

```{r}
#Remove rows with NaNs
micro_merge <- micro_merge %>% 
  drop_na()

#Separating into response variables (CHEMTAX) and Explainatory variables (Environmental)
resp <- micro_merge[, 6:127]

#Things to add TChla, WSDP, iso depth, FWC...
expl <- micro_merge[, 128:ncol(micro_merge)]
```

```{r}
#Hellinger transformation on species data - particularly suited to species abundance data with large range and lots of zeros. Gives low weights to variables with low counts and many zeroes.
resp.hell <- decostand(resp,'hell')
```

```{r}
tbRDA.all <- rda(resp.hell ~ . , data = expl)

tbRDA.all

anova(tbRDA.all)

adjR2.tbrda <- RsquareAdj (tbRDA.all)$adj.r.squared

adjR2.tbrda

# Variables explain 41% of the variance
#Constrained Variance = 54.73.46%
# RDA1 - 
# RDA2 - 
# PCA1 - 
# PCA2 - 

#r2 = 0.41

#Global model significant to 0.001 
```
```{r}
constrained_eig <- tbRDA.all$CCA$eig/tbRDA.all$tot.chi*100
unconstrained_eig <- tbRDA.all$CA$eig/tbRDA.all$tot.chi*100
expl_var <- c(constrained_eig, unconstrained_eig)
barplot (expl_var[1:20], col = c(rep ('red', length (constrained_eig)), rep ('black', length (unconstrained_eig))),
         las = 2, ylab = '% variation')
```

```{r}
ordiplot (tbRDA.all)
```


```{r}
#Using DCA on chemtax data to test whether linear or unimodal model is appropriate
DCA <- decorana(resp.hell)
DCA

#2.4693

#As the length of the first DCA is < 3 S.D. - the dataset is homogenous and a linear model is appropriate. The score went down after applying the Hellinger Transformation. Proceed with RDA.

```

```{r}
#Trying different approach for ordiR2step from https://www.davidzeleny.net/anadat-r/doku.php/en:forward_sel_examples - same result as my other test
tb_rda.vasc.0 <- rda (resp.hell ~ 1, data = expl)

tb_rda.vasc.all <- rda (resp.hell ~ ., data = expl)

sel.osR2 <- ordiR2step (tb_rda.vasc.0, scope = formula (tb_rda.vasc.all), 
                        R2scope = adjR2.tbrda, direction = 'forward', 
                        permutations = 999)

sel.osR2$anova

sel.osR2_adj <- sel.osR2

sel.osR2_adj$anova$`Pr(>F)` <- p.adjust (sel.osR2$anova$`Pr(>F)`, 
                                         method = 'holm', n = ncol (expl))

sel.osR2_adj$anova

#temp = 0.008
#po4 = 0.008
#sal = 0.008
#no2 = 0.025
```

```{r}
#Select the statistically significant variables - May want to remove SiO2, see VIFS below!
env.signif <- subset(expl, select = c(temp, po4, GFF_chl, no2, sal, dr))

#RDA using significant variables
rda.signif <- rda(resp.hell ~ . ,data = env.signif)
rda.signif
rda.sign.sum <- summary(rda.signif)

rda.sign.sum
#Total = 41.46%
#Constrained = 37.5%
#RDA1 = 27.43%
#RDA2 = 6.1%

#Adjusted R2 for the 1 significant variables
#AdjR2 = 0.319
(R2adj <- RsquareAdj(rda.signif)$adj.r.squared)

#ANOVA for testing significance of model and individual axes #Can do ANOVA by terms...
#Entire model = 0.001***
#RDA1 = 0.001***
#RDA2 = 0.001***

# ?anova.cca
anova.cca(rda.signif, step = 1000)
anova.cca(rda.signif, step = 1000, by = "axis")

#All significant - already shown in forward rda, but easier to see (Not corrected)
anova(rda.signif, by = "terms")
```
```{r}

#Trying the same thing, but bringing in arrows from previous plot - trying scaling 2
#pdf(file = "rda_s2.pdf", width = 6.5, height = 5, pointsize = 2)

p_s1 <- plot(rda.signif, scaling = 1, type = "none", xlab = c("RDA1 (28%)"),
               ylab = c("RDA2 (5%)"), xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1))

# points(rda.signif, display = 'sites', pch = 21, cex = 2.2,
#        col = rgb(red = 1, green = 1, blue = 1, alpha = 0.5), scaling = 2,
#        bg = bg[eco])

points(scores(rda.signif, display = 'sites', choices = c(1, 2), scaling = 1),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(micro_merge$site_id)])

#So since distance doesn't matter, I can make arrows longer with scaling 2? 
# arrows(0,0, scores(rda.signif, display = "species", choices = c(1),
#                    scaling = 1), scores(rda.signif, display = "species",
#                                             choices = c(2), scaling = 1),
#        col = "black", length = 0)

text(rda.signif, scaling = 1, display = "bp", col = "blue",cex = 0.8, font = 2)

# text(scores(rda.signif, display = "species", choices = c(1), scaling = 1),
#      scores(rda.signif, display = "species", choices = c(2), scaling = 1),
#      labels = rownames(scores(rda.signif, display = "species", scaling = 1)),
#      col = "black", cex = 0.8, font = 2)


# legend("topleft", legend = levels(eco), bty ="n", col="gray32", pch = 21,
#        cex = 1.5, pt.bg = bg)

legend("topright", legend = c(levels(as.factor(micro_merge$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

#dev.off()

```
```{r}
# png(here("figures_new", "rda_micro.png"),
#      width = 800, height = 500)

plot_s2 <- plot(rda.signif, scaling = 2, type = "none", xlab = c("RDA1 (28%)"),
               ylab = c("RDA2 (5%)"))

# , xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1)

# points(rda.signif, display = 'sites', pch = 21, cex = 2.2,
#        col = rgb(red = 1, green = 1, blue = 1, alpha = 0.5), scaling = 2,
#        bg = bg[eco])

points(scores(rda.signif, display = 'sites', choices = c(1, 2), scaling = 2),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(micro_merge$site_id)])

#So since distance doesn't matter, I can make arrows longer with scaling 2? 
# arrows(0,0, scores(rda.signif, display = "species", choices = c(1),
#                    scaling = 1), scores(rda.signif, display = "species",
#                                             choices = c(2), scaling = 1),
#        col = "black", length = 0)

text(rda.signif, scaling = 2, display = "bp", col = "blue",cex = 0.8, font = 2)

# text(scores(rda.signif, display = "species", choices = c(1), scaling = 1),
#      scores(rda.signif, display = "species", choices = c(2), scaling = 1),
#      labels = rownames(scores(rda.signif, display = "species", scaling = 1)),
#      col = "black", cex = 0.8, font = 2)


# legend("topleft", legend = levels(eco), bty ="n", col="gray32", pch = 21,
#        cex = 1.5, pt.bg = bg)

legend("topright", legend = c(levels(as.factor(micro_merge$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

# dev.off()
```


```{r}
#Trying a ggplot version -  didn't really work

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

# spec.envfit <- envfit(plot2, env = env.signif)
# spec.data.envfit <- data.frame(r=spec.envfit$vectors$r, p=spec.envfit$vectors$pvals)
# species.long2 <- species.long(plot2, spec.data=spec.data.envfit)
# species.long2

#I think this is the axes scores, and I use another metod for this.
axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = sp_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.6, colour = "red") +
  geom_text_repel(data = sp_loc, aes(RDA1, RDA2, label = row.names(sp_loc)),
                  box.padding = unit(0.5, 'lines'),
                  point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'red',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = 0.45,
                  force = 1,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  box.padding = unit(1, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.1,
                  # nudge_x = 0.3,
                  force = 50,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.92, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts.png"),
       width = 6.2, height = 5, dpi = 300)
```

```{r}
#Trying a ggplot version for scaling 1

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(p_s1, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(p_s1)
species_loc

# spec.envfit <- envfit(plot2, env = env.signif)
# spec.data.envfit <- data.frame(r=spec.envfit$vectors$r, p=spec.envfit$vectors$pvals)
# species.long2 <- species.long(plot2, spec.data=spec.data.envfit)
# species.long2

#I think this is the axes scores, and I use another metod for this.
axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = sp_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.6, colour = "red") +
  geom_text_repel(data = sp_loc, aes(RDA1, RDA2, label = row.names(sp_loc)),
                  box.padding = unit(0.5, 'lines'),
                  point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'red',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = 0.45,
                  force = 1,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  box.padding = unit(1, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.1,
                  # nudge_x = 0.3,
                  force = 50,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.92, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts_s1.png"),
       width = 6.2, height = 5, dpi = 300)
```
```{r}
#Trying a ggplot version for scaling 1 - selecting distinct species and plotting as points. Not sure of this works, but looks better.

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(p_s1, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(p_s1)
species_loc

# spec.envfit <- envfit(plot2, env = env.signif)
# spec.data.envfit <- data.frame(r=spec.envfit$vectors$r, p=spec.envfit$vectors$pvals)
# species.long2 <- species.long(plot2, spec.data=spec.data.envfit)
# species.long2

#I think this is the axes scores, and I use another metod for this.
axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

sp_loc_short <- sp_loc %>% 
  filter(RDA1 <= -0.1 | RDA1 >= 0.1 | RDA2 <= -0.1 | RDA2 >= 0.1)

row.names(sp_loc_short) <- c("A.s", "C.d", "C.t", "Hill", "Pn.s", "S.m", "Tel",
                             "Th", "C.c", "C.s", "P.p")

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_point(data = sp_loc_short, aes(x = RDA1, y = RDA2)) +
  geom_text_repel(data = sp_loc_short, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_short)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = 0.05,
                  force = 0.5,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.1, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts_s1_test.png"),
       width = 6.2, height = 5, dpi = 300)
```

```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as points. Not sure of this works, but looks better. 

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

# spec.envfit <- envfit(plot2, env = env.signif)
# spec.data.envfit <- data.frame(r=spec.envfit$vectors$r, p=spec.envfit$vectors$pvals)
# species.long2 <- species.long(plot2, spec.data=spec.data.envfit)
# species.long2

#I think this is the axes scores, and I use another metod for this.
axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

sp_loc_short <- sp_loc %>% 
  filter(RDA1 <= -0.1 | RDA1 >= 0.1 | RDA2 <= -0.1 | RDA2 >= 0.1)

row.names(sp_loc_short) <- c("A.s", "C.d", "C.t", "Hill", "Pn.s", "S.m", "Tel",
                             "Th", "C.c", "C.s", "P.p")

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_point(data = sp_loc_short, aes(x = RDA1, y = RDA2)) +
  geom_text_repel(data = sp_loc_short, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_short)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = 0.05,
                  nudge_x = -0.02,
                  force = 1,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.92, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts_test.png"),
       width = 6.2, height = 5, dpi = 300)
```

```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as arrows

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

# spec.envfit <- envfit(plot2, env = env.signif)
# spec.data.envfit <- data.frame(r=spec.envfit$vectors$r, p=spec.envfit$vectors$pvals)
# species.long2 <- species.long(plot2, spec.data=spec.data.envfit)
# species.long2

#I think this is the axes scores, and I use another metod for this.
axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

sp_loc_short <- sp_loc %>% 
  filter(RDA1 <= -0.1 | RDA1 >= 0.1 | RDA2 <= -0.1 | RDA2 >= 0.1)

row.names(sp_loc_short) <- c("A.s", "C.d", "C.t", "Hill", "Pn.s", "S.m", "Tel",
                             "Th", "C.c", "C.s", "P.p")

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = sp_loc_short, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.10,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.3, colour = "red") +
  geom_text_repel(data = sp_loc_short, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_short)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = 0.05,
                  nudge_x = -0.02,
                  force = 1,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.92, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts_test_arrows.png"),
       width = 6.2, height = 5, dpi = 300)
```

```{r}
#Testing species goodness of fit to try to eliminate species
gfit <- goodness(rda.signif)

gfit <- as.data.frame(gfit) 

test <- gfit %>% 
  filter(RDA1 <= -0.15 | RDA1 >= 0.15 | RDA2 <= -0.15 | RDA2 >= 0.15)

test

# https://stackoverflow.com/questions/27823131/customising-vegan-ordination-plot
sel <- goeveg::ordiselect(resp, rda.signif, fitlim = 0.10)

# sel <- as.data.frame(sel)
```

```{r}
#RDA scaling 2 - angles. selecting distinct species and plotting as arrows with 15% best fit

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(plot_s2, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(plot_s2)
species_loc

axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

sp_loc_short_15p <- subset(sp_loc, rownames(sp_loc) %in% sel)


row.names(sp_loc_short_15p) <- c("A.s", #Apedinella spinifera 
                                 "bi", #Biddulphiales
                                 "C.d", 
                                 "C.r", 
                                 "C.t",
                                 "Eu",
                                 "Hill",
                                 "Pen",
                                 "Pn_m",
                                 "Pn_s",
                                 "Pg",
                                 "S.m", 
                                 "Tel",
                                 "Tel_a",
                                 "Th_n", 
                                 "th",
                                 "C.c", 
                                 "C.s", 
                                 "Pt",
                                 "Po",
                                 "te",
                                 "P.p",
                                 "dp",
                                 "Py",
                                 "Pro",
                                 "Ha",
                                 "Ol")

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = sp_loc_short_15p, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.10,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.3, colour = "red") +
  geom_text_repel(data = sp_loc_short_15p, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_short_15p)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = 0.5,
                  nudge_x = -0.2,
                  force = 2,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.92, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts_test_arrows_15perc.png"),
       width = 6.2, height = 5, dpi = 300)
```
```{r}
#RDA scaling 1 - angles. selecting distinct species and plotting as arrows with 15% best fit

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc <- sites.long(p_s1, env.data = env.signif)
meta <- micro_merge[,1:5]
sites_loc <- cbind(meta, sites_loc)
head(sites_loc)

#Species location in ordination
species_loc <- species.long(p_s1)
species_loc

axis.long <- axis.long(rda.signif, choices = c(1, 2))
axis.long

env_loc <-  as.data.frame(rda.sign.sum$biplot[,1:2])

sp_loc <-  as.data.frame(rda.sign.sum$species[,1:2])

sp_loc_short_15p <- subset(sp_loc, rownames(sp_loc) %in% sel)


row.names(sp_loc_short_15p) <- c("A.s", #Apedinella spinifera 
                                 "bi", #Biddulphiales
                                 "C.d", 
                                 "C.r", 
                                 "C.t",
                                 "Eu",
                                 "Hill",
                                 "Pen",
                                 "Pn_m",
                                 "Pn_s",
                                 "Pg",
                                 "S.m", 
                                 "Tel",
                                 "Tel_a",
                                 "Th_n", 
                                 "th",
                                 "C.c", 
                                 "C.s", 
                                 "Pt",
                                 "Po",
                                 "te",
                                 "P.p",
                                 "dp",
                                 "Py",
                                 "Pro",
                                 "Ha",
                                 "Ol")

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc, aes(x = axis1, y = axis2, fill = site_id,
                                   shape = season), 
             size = 4, alpha = 0.7) +
  scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  geom_segment(data = env_loc, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), 
                arrow = arrow(angle = 22.5,length = unit(0.35,"cm"),
                              type = "closed"),
                linetype = 1, size = 0.6, colour = "blue") +
  geom_segment(data = sp_loc_short_15p, aes(x = 0, y = 0, xend = RDA1, yend = RDA2),
                 arrow = arrow(angle = 22.5,length = unit(0.10,"cm"),
                               type = "closed"),
               linetype = 1, size = 0.3, colour = "red") +
  geom_text_repel(data = sp_loc_short_15p, aes(RDA1, RDA2, 
                                           label = row.names(sp_loc_short_15p)),
                  # box.padding = unit(0.5, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(2, 'lines')) +
                  segment.color = 'grey',
                  segment.size = 0.5,
                  segment.alpha = 0.7,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = 0.2,
                  # nudge_x = -0.2,
                  force = 2,
                  max.iter = 3e3) +
  geom_text_repel(data = env_loc , aes(RDA1, RDA2, label = row.names(env_loc)),
                  # box.padding = unit(0.8, 'lines'),
                  # point.padding = NA,
                  # point.padding = unit(1, 'lines'),
                  segment.color = 'blue',
                  segment.size = 0.5,
                  segment.alpha = 0.4,
                  arrow = arrow(length = unit(0.01, 'npc')),
                  nudge_y = -0.07,
                  # nudge_x = 0.3,
                  force = 0.5,
                  max.iter = 3e3) +
  labs(x = paste("RDA 1 (", format(100 *rda.sign.sum$cont[[1]][2,1], digits = 3),
               "%)", sep = ""),
       y = paste("RDA 2 (", format(100 *rda.sign.sum$cont[[1]][2,2], digits = 2),
               "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        legend.position = c(0.92, 0.73),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 10)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Station", shape = "Season")

ggsave(here("figures_new", "rda_micro_ggplot_Chl_bad-nuts_test_arrows_15perc_s1.png"),
       width = 6.2, height = 5, dpi = 300)
```

```{r}
#Need to go through and clean this up
#Questions for Louis
#What groups should I be combining?
```

```{r}
#lets look at what species are most abundant overall

# micro_max_abund <- micro %>% 
#   group_by(scientificName) %>% 
#   summarise(max = max(species_sum)) %>% 
#   ungroup() %>% 
#   arrange(desc(max))
# 
# max_st <- micro %>% 
#   group_by(site_id, scientificName) %>% 
#   mutate(mean = mean(species_sum),
#             sd = sd(species_sum)) %>% 
#   top_n(mean, n = 10) %>% 
#   ungroup() %>% 
#   arrange(desc(mean))
# 
# max_st$species_order <- factor(max_st$scientificName,
#                                    (unique(max_st$scientificName
#                                               [order(max_st$group, max_st$scientificName)])))
# 
# max_st %>% 
#   ggplot(aes(x = site_id, y = fct_rev(species_order), fill = mean)) +
#   geom_tile() +
#   scale_fill_gradient(name = "Mean Abundance",
#                       low = "#FFFFFF",
#                       high = "#012345") +
#   # scale_y_discrete(limits = rev(levels(as.factor(micro_ds$species_order)))) +
#   scale_x_discrete(labels = c("DFO2" = "F", "KC10" = "C", "QCS01" = "S",
#                               "QU39" = "E")) +
#   theme_bw() +
#   theme(axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         strip.background = element_blank(),
#         strip.text.x = element_blank(),
#         # legend.position = "bottomright",
#         text = element_text(size = 25),
#         axis.text = element_text(colour = "black"),
#         panel.grid.major = element_blank(), 
#         panel.grid.minor = element_blank(),
#         panel.background = element_blank(), 
#         axis.line = element_line(colour = "black")) 
# 
# 

```



