---
title: "R Notebook"
output: html_notebook
---



```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(factoextra)
library(ggdendro)
library(dendextend)
```

```{r}
#Upload data
#Upload output from OBIS taxonomy matching/formatting
micro <- read_csv(here("files", "calvert.csv"))
```

```{r}
#Selecting columns
micro <- micro %>% 
  select(date, site_id, scientificName, count)

#Complete species list for each station date and fill with zero for not observed. Because I have some species separated out with identificationRemarks, identificationQualifiers and different resting stages, I sum these. I need to decide on best method for this once I have the analysis zeroed in. Complete gives me empty rows... might not need to do this...
micro <- micro %>%  
  #complete(date, site_id, scientificName, fill = list(count = 0)) %>%  
  group_by(date, site_id, scientificName) %>% 
  summarize(species_sum = sum(count)) %>% 
  ungroup()

#Combining date and siteID - can't have both for the clustering I am trying now
# micro_clust <- micro_clust %>% 
#   unite(date_site, date, site_id, sep = "_")

#pivoting longer so species are columns. 
micro_piv <- micro %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_piv <- micro_piv %>% 
  mutate(month = lubridate::month(date)) %>% 
  relocate(month, .after = date)

micro_piv <- micro_piv %>% 
  filter(date > "2018-01-01")

micro_piv <- micro_piv %>% 
  mutate(season = case_when(month >= 1 & month <=3 ~ "winter",
                            month >= 4 & month <=6 ~ "spring",
                            month >= 7 & month <=9 ~ "summer",
                            month >= 9 & month <=12 ~ "autumn",)) %>% 
  relocate(season, .after = month)

transform <- micro_piv[, 5:138]  
  
transform <- log10(transform + 1)

dend_micro <- transform %>% 
  vegdist("bray") %>% 
  hclust(method = "average") %>% 
  as.dendrogram() 

dend_test <- micro_piv[,-c(1,2,3,4)] %>% 
  vegdist("bray") %>% 
  hclust(method = "average") %>% 
  as.dendrogram()

# par(mar = c(10,2,1,1)) %>% 
# plot(dend) 
# the_bars <- ifelse(micro_piv$season, "blue", "green") 
# colored_bars(colors = the_bars, dend = dend, rowLabels = "am")



# %>% 
#   column_to_rownames(var = "date_site") %>% 
#   mutate_all(~replace(., is.na(.), 0))
```




```{r}
#https://stackoverflow.com/questions/49088627/how-to-label-colored-bars-in-a-dendrogram

data("mtcars")

# Create the dendrogram, use default options
dend_mtcars <- mtcars %>% 
  dist %>% 
  hclust() %>% 
  as.dendrogram

# Set the plot margin: bottom, left, top & right
par(mar = c(10, 3, 3, 4) + 0.1,
    xpd = NA) # allow content to go into outer margin 

# Plot
plot(dend_mtcars)

# Setup the color bar based on $am & $vs
the_bars_am <- ifelse(mtcars$am, "firebrick3", "beige")
the_bars_vs <- ifelse(mtcars$vs, "firebrick3", "beige")
the_bars <- cbind(the_bars_vs, the_bars_am)
colored_bars(colors = the_bars, dend = dend_mtcars, rowLabels = c("vs", "am"))

# Add the legend manually
legend("topright", legend = c('0', '1'), pch = 15, pt.cex = 3, cex = 1.5, bty = 'n',
       inset = c(-0.1, 0), # place outside
       title = "Status", 
       col = c('beige', 'firebrick3'))
```
```{r}
small_iris <- iris[c(1, 51, 101, 2, 52, 102), ]
dend <- as.dendrogram(hclust(dist(small_iris[,-5])))


```



```{r}
#Working through steps from https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/

#Calculate dissimilarity matrix. 
bray.dist <- vegdist(log10(micro_clust+1), "bray")

#Compute hierarchical clustering - not sure if this is the right way to do this...
bray.hc <- hclust(bray.dist, method = "average")

plot(bray.hc, cex = 0.5, hang = -1)


```

```{r}
#Trying steps from below website and dendextend package
#https://cran.r-project.org/web/packages/dendextend/vignettes/dendextend.html

dend <- micro_clust %>% 
  vegdist("bray") %>% 
  hclust(method = "average") %>% 
  as.dendrogram()

dend %>% plot
dend %>% labels
dend %>% nleaves
dend %>% nnodes
dend %>% head

dend %>% 
  set("labels_cex", 0.5) %>%
  set("branches_k_color") %>% 
  
  plot(horiz = TRUE)

dend %>% set("branches_k_color") %>% plot(horiz = TRUE)
dend %>% rect.dendrogram(k=3, horiz = TRUE,
                           border = 8, lty = 5, lwd = 2)

dend %>% set("branches_k_color") %>% plot

dend %>% set("branches_k_color") %>% plot(horiz = TRUE)
dend %>% rect.dendrogram(k=3, horiz = TRUE,
                           border = 8, lty = 5, lwd = 2)
```


```{r}
ggdendrogram(bray.hc, size = 5)

ggsave(here("figures", "bray_average_test_2.png"), width=16, height=15, dpi=300)

#Well I have a dendrogram - But does it mean anything? I feel like I'm trying to look at two different questions. Spatial and Temporal...

```




```{r}
#Trying different plotting methods?
fviz_dend(bray.hc, rect = TRUE) # dendrogam
```

```{r}
#Method on https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/

#Not really sure what this is doing, but it looks nice!

res.hc <- eclust(micro_clust, "hclust") # compute hclust

fviz_dend(res.hc, rect = TRUE)

```





```{r}
#Goal - similarity/dissimilarity cluster analysis 

#How differnt or similar are the three calvert island sites

#Distance metric - Bray-curtis is used for abundance data

#Linkage method - criterion that will determine how observations will be grouped together.

#Figtree (software) allows you to view and edit dendograms - look into this

#https://ourcodingclub.github.io/tutorials/data-clustering/

#Mahara - average linkage Bray-curtis dissimilarity, log10(x+1) transformed

# https://www.davidzeleny.net/anadat-r/doku.php/en:similarity

# similarity calculated using similarity indices ranging from 0 to 1. Ordination uses distances (Euclidean). Legendre & Legendre (2012) offers key on how to select appropriate measure for given data. bray-Curtis and Hellinger distances may be better than Euclidean.

# Symmetrical indices (thos which consider double 0s as relevant not useful for ecological data). Asymmetrical similarity indices (ignore double zeros). Two types, qualitative (presence/absence) and quantitative (raw or transformed species abundance). 

#Qualitative (binary) asymmetrical similarity indices. Information about number of species shared by both samples AND number of species occuring in first or second sampe only.

#Quantitative similarity indices. Percentage Similarity and includes Bray-Curtis

#Distance Indices. Similarity indices return highest value when both samples the same. Distance indices opposite. Two types: 1) Those calculated from similarity indices (includes Bray-Curtis) and; 2) Those which have no analogue in similarity indices. Important criterium is whether distance index is metric or not. Metric = minimum distance is 0, distance is always positive, distance between sample 1 and 2 same as 2 and has triangle inequality.

#Bray-Curits/percentage difference. Suitable for community composition data since it is asymmetrical (ignores double 0s) and meaningful upper vlaue equal to 1. Considers absolute species abundances

```







