---
title: "R Notebook"
output: html_notebook
---

```{r}
#Upload packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(factoextra)
library(ggdendro)
library(dendextend)
library(colormap)
```

```{r}
#Upload data
#Upload output from OBIS taxonomy matching/formatting
micro_1 <- read_csv(here("files", "calvert.csv")) 

#Uploading QU39 data
micro_2 <- read_csv(here("files", "qu39.csv")) %>% 
  mutate(site_id = "QU39",
         month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  relocate(site_id, .after = "date") %>%
  relocate(month, .after = "date") %>% 
  relocate(year, .after = "date")  

#Performing monthly average to make comparable to Calvert data - Turn this off for alternative
micro_2 <- micro_2 %>% 
  group_by(year, month, scientificName) %>% 
  mutate(count_avg = mean(count, rm.na = FALSE)) %>% 
  ungroup() %>% 
  distinct(year, month, scientificName, count_avg, .keep_all = TRUE) %>% 
  select(-year, -month, -count, count = count_avg)
  
  

micro <- rbind(micro_1, micro_2)
```

```{r}
#Selecting columns
micro <- micro %>% 
  select(date, site_id, scientificName, count)

#Complete species list for each station date and fill with zero for not observed. Because I have some species separated out with identificationRemarks, identificationQualifiers and different resting stages, I sum these. I need to decide on best method for this once I have the analysis zeroed in. Complete gives me empty rows... might not need to do this...
micro <- micro %>%  
  #complete(date, site_id, scientificName, fill = list(count = 0)) %>%  
  group_by(date, site_id, scientificName) %>% 
  summarize(species_sum = sum(count)) %>% 
  ungroup()

#Combining date and siteID - can't have both for the clustering I am trying now
# micro_clust <- micro_clust %>% 
#   unite(date_site, date, site_id, sep = "_")

#pivoting longer so species are columns. 
micro_piv <- micro %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

micro_piv <- micro_piv %>% 
  mutate(month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  relocate(month, .after = date) %>% 
  relocate(yday, .after = month)

micro_piv <- micro_piv %>% 
  filter(date > "2018-01-01" & date < "2021-01-01")

micro_piv <- micro_piv %>% 
  mutate(season = case_when(month %in% c(12, 1, 2) ~ "winter",
                            month >= 3 & month <= 5 ~ "spring",
                            month >= 6 & month <= 8 ~ "summer",
                            month >= 9 & month <= 11 ~ "autumn",)) %>% 
  relocate(season, .after = month)

nmds <- micro_piv[, 6:162]

transform <- micro_piv[, 6:162]  
  
transform <- log10(transform + 1)

dend_micro <- transform %>% 
  vegdist("bray") %>% 
  hclust(method = "average") %>% 
  as.dendrogram()
```


```{r}
example_NMDS <-  metaMDS(nmds , k = 2, trymax = 100) 

stressplot(example_NMDS)

plot(example_NMDS)
```

```{r}
#Creation of dendrogram using Calvert data

png(here("figures", "Calvert_qu39_monthavg.png"), width = 2200, height = 1000) 

season <- pull(micro_piv, season)
station <- pull(micro_piv, site_id)
yday <- pull(micro_piv, yday)


barcolor_season <- colormap(colormap = colormaps$earth, nshades = 4, format = "hex", alpha = 1, reverse = FALSE)

barcolor_station <- colormap(colormap = colormaps$jet, nshades = 4, format = "hex", alpha = 1, reverse = FALSE)

barcolor_yday <- colormap(colormap = colormaps$rainbow, nshades = 356, format = "hex", alpha = 1, reverse = FALSE)


# colormaps$viridis
# colormaps$jet
# c("#0342ff", "#00bd0d", "#fbff00", "#ff0000")

barcolor_season <- barcolor_season[as.numeric(as.factor(season))]
barcolor_station <- barcolor_station[as.numeric(as.factor(station))]
barcolor_yday <- barcolor_yday[as.numeric(yday)]

barcolor_full <- cbind(barcolor_season, barcolor_station)
colnames(barcolor_full) <- c("season", "station")

#Margins bottom, left, top, right.
par(mar=c(5,2,1,2))
dend_micro %>%
  plot() 

colored_bars(colors = barcolor_full, dend = dend_micro)


legend("topright", 
     legend = c("DFO2" , "KC10" , "QCS01" , "QU39"), 
     col = colormap(colormap = colormaps$jet, nshades = 4), 
     pch = c(20,20,20,20), bty = "n",  pt.cex = 3, cex = 2 , 
     text.col = "black", horiz = FALSE, inset = c(0, 0.1))

legend("right", 
     legend = c("Winter" , "Spring" , "Summer" , "Autumn"), 
     col = colormap(colormap = colormaps$earth, nshades = 4), 
     pch = c(20,20,20,20), bty = "n",  pt.cex = 3, cex = 2 , 
     text.col = "black", horiz = FALSE, inset = c(0, 0.1))

# legend("bottomright", 
#      legend = c(1:356), 
#      col = colormap(colormap = colormaps$rainbow, nshades = 4), 
#      pch = c(20,20,4,4,4), bty = "n",  pt.cex = 1.5, cex = 0.8 , 
#      text.col = "black", horiz = FALSE, inset = c(0, 0.1))

dev.off()
```
```{r}
plot(cut(dend_micro, h=0.79)$lower[[2]], 
     main="Second branch of lower tree with cut at h=75")
```

```{r}
fviz_cluster(dend_micro) # scatter plot
```


```{r}
matrix(rnorm(1000), ncol = 10) %>%
  scale %>% 
  dist  %>% 
  hclust %>% 
  as.dendrogram() -> dend_expr

tree_labels <- dendro_data(dend_micro, type = "rectangle")
tree_labels$labels <- cbind(tree_labels$labels, Diagnosis = as.factor(sample(1:2, 100, replace = T)))

ggplot() +
  geom_segment(data = segment(tree_labels), aes(x=x, y=y, xend=xend, yend=yend))+
  geom_segment(data = tree_labels$segments %>%
                 filter(yend == 0) %>%
                 left_join(tree_labels$labels, by = "x"), aes(x=x, y=y.x, xend=xend, yend=yend, color = Diagnosis)) +
  geom_text(data = label(tree_labels), aes(x=x, y=y, label=label, colour = Diagnosis, hjust=0), size=3) +
  coord_flip() +
  scale_y_reverse(expand=c(0.2, 0)) +
  scale_colour_brewer(palette = "Dark2") + 
  theme_dendro() +
  ggtitle("Mayo Cohort: Hierarchical Clustering of Patients Colored by Diagnosis")
```

```{r}
# https://www.rdocumentation.org/packages/dendextend/versions/1.8.0/topics/colored_bars

## mtcars example

# Create the dend:
dend <- as.dendrogram(hclust(dist(mtcars)))

# Create a vector giving a color for each car to which company it belongs to
car_type <- rep("Other", length(rownames(mtcars)))
is_x <- grepl("Merc", rownames(mtcars))
car_type[is_x] <- "Mercedes"
is_x <- grepl("Mazda", rownames(mtcars))
car_type[is_x] <- "Mazda"
is_x <- grepl("Toyota", rownames(mtcars))
car_type[is_x] <- "Toyota"
car_type <- factor(car_type)
n_car_types <- length(unique(car_type))
col_car_type <- colorspace::rainbow_hcl(n_car_types, c = 70, l  = 50)[car_type]

# extra: showing the various clusters cuts 
k234 <- cutree(dend, k = 2:4)

# color labels by car company:
labels_colors(dend) <- col_car_type[order.dendrogram(dend)]
# color branches based on cutting the tree into 4 clusters:
dend <- color_branches(dend, k = 4)

### plots
par(mar = c(12,4,1,1))
plot(dend)
colored_bars(cbind(k234[,3:1], col_car_type), dend, 
      rowLabels = c(paste0("k = ", 4:2), "Car Type"))

# horiz version:
par(mar = c(4,1,1,12))
plot(dend, horiz = TRUE)
colored_bars(cbind(k234[,3:1], col_car_type), dend, 
      rowLabels = c(paste0("k = ", 4:2), "Car Type"), horiz = TRUE)
```

```{r}
#Resources
#https://stackoverflow.com/questions/49088627/how-to-label-colored-bars-in-a-dendrogram
#https://www.datanovia.com/en/blog/cluster-analysis-in-r-simplified-and-enhanced/
#https://cran.r-project.org/web/packages/dendextend/vignettes/dendextend.html

#Goal - similarity/dissimilarity cluster analysis 

#How differnt or similar are the three calvert island sites

#Distance metric - Bray-curtis is used for abundance data

#Linkage method - criterion that will determine how observations will be grouped together.

#Figtree (software) allows you to view and edit dendograms - look into this

#https://ourcodingclub.github.io/tutorials/data-clustering/

#Mahara - average linkage Bray-curtis dissimilarity, log10(x+1) transformed

# https://www.davidzeleny.net/anadat-r/doku.php/en:similarity

# similarity calculated using similarity indices ranging from 0 to 1. Ordination uses distances (Euclidean). Legendre & Legendre (2012) offers key on how to select appropriate measure for given data. bray-Curtis and Hellinger distances may be better than Euclidean.

# Symmetrical indices (thos which consider double 0s as relevant not useful for ecological data). Asymmetrical similarity indices (ignore double zeros). Two types, qualitative (presence/absence) and quantitative (raw or transformed species abundance). 

#Qualitative (binary) asymmetrical similarity indices. Information about number of species shared by both samples AND number of species occuring in first or second sampe only.

#Quantitative similarity indices. Percentage Similarity and includes Bray-Curtis

#Distance Indices. Similarity indices return highest value when both samples the same. Distance indices opposite. Two types: 1) Those calculated from similarity indices (includes Bray-Curtis) and; 2) Those which have no analogue in similarity indices. Important criterium is whether distance index is metric or not. Metric = minimum distance is 0, distance is always positive, distance between sample 1 and 2 same as 2 and has triangle inequality.

#Bray-Curits/percentage difference. Suitable for community composition data since it is asymmetrical (ignores double 0s) and meaningful upper vlaue equal to 1. Considers absolute species abundances

```







