---
title: "R Notebook"
output: html_notebook
---


```{r}
#Load packages
library(tidyverse)
library(patchwork)
library(here)
library(readr)
library(readxl)
```

```{r}
#Upload fully formatted microscopy data

micro <- read_csv(here("outputs", "micro_master_2021-10-18.csv"))

micro_kc10 <- read_csv(here("outputs", "micro_kc10_2021-12-01.csv"))

micro_kc10_ds <- read_csv(here("outputs", "micro_kc10_ds_2021-12-01.csv"))

#Upload data
data <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv")) 

#Uploading chemtax data
chem <- read_csv(here("outputs", "chemtax_master_2021-11-04.csv")) 

```

Working with microscopy data

```{r}
#Removing QU39 
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
#I want to see what species are the most abundance and have the highest contributions for each group
micro_stats <- micro %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(species_sum),
         perc = species_sum/sum_all) %>% 
  ungroup()

micro_stats_2 <- micro_stats %>% 
  group_by(group, scientificName) %>% 
  summarise(med_abund = median(species_sum),
            min_abund = min(species_sum),
            max_abund = max(species_sum),
            med_perc = median(perc),
            min_perc = min(perc),
            max_perc = max(perc)) %>% 
  ungroup()


#Trying to look at only species present in 20% of samples
#How many samples
sample_num <- micro %>% 
  distinct(date, site_id)

species_10 <- micro %>% 
  group_by(scientificName) %>% 
  summarise(n_obs = n()) %>%
  ungroup() %>% 
  mutate(perc_obs = n_obs/50) %>% 
  filter(perc_obs >= 0.10)

species_10_list <- species_10$scientificName


micro_stats_s10 <- micro %>% 
  filter(scientificName %in% species_10_list) %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(species_sum),
         perc = species_sum/sum_all) %>% 
  ungroup()

micro_stats_2_s10 <- micro_stats_s10 %>% 
  group_by(group, scientificName) %>% 
  summarise(med_abund = median(species_sum),
            min_abund = min(species_sum),
            max_abund = max(species_sum),
            med_perc = median(perc),
            min_perc = min(perc),
            max_perc = max(perc),
            n_obs = n()) %>% 
  ungroup()

micro_dino <- micro %>% 
  filter(class == "Dinophyceae") %>% 
  filter(genus == "Dinophysis")
```
```{r}
#Selecting autotrophic groups from class level specifications above. Too coarse for dinos.
micro <- micro %>% 
  filter(!group == "Cyanobacteria")

#Can't figure out how to make this work with multiple stations. Trying each separately and binding
micro_sum_dfo2 <- micro %>%
  filter(trophicStatus == "auto" &
          site_id == "DFO2") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "DFO2") #replace NAs, created by complete, with 0s

micro_sum_kc10 <- micro %>%
  filter(trophicStatus == "auto" &
          site_id == "KC10") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "KC10") #replace NAs, created by complete, with 0s

micro_sum_qcs01 <- micro %>%
  filter(trophicStatus == "auto" &
          site_id == "QCS01") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "QCS01") #replace NAs, created by complete, with 0s

micro_sum_qu39 <- micro %>%
  filter(trophicStatus == "auto" &
          site_id == "QU39") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "QU39") #replace NAs, created by complete, with 0s

micro_sum <- rbind(micro_sum_dfo2, micro_sum_kc10, micro_sum_qcs01, micro_sum_qu39)
```

```{r}
#Summing species for the KC10-QU39 Timeseries
micro_kc10_sum <- micro_kc10 %>%
  filter(trophicStatus == "auto" &
          site_id == "KC10") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "KC10") #replace NAs, created by complete, with 0s

micro_sum_qu39 <- micro_kc10 %>%
  filter(trophicStatus == "auto" &
          site_id == "QU39") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "QU39")

micro_sum_2 <- rbind(micro_kc10_sum, micro_sum_qu39)

#Doing the same for the QU39 downscaled timeseries

micro_kc10_ds_sum <- micro_kc10_ds %>%
  filter(trophicStatus == "auto" &
          site_id == "KC10") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "KC10") #replace NAs, created by complete, with 0s

micro_sum_ds_qu39 <- micro_kc10_ds %>%
  filter(trophicStatus == "auto" &
          site_id == "QU39") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "QU39")

micro_sum_3 <- rbind(micro_kc10_ds_sum, micro_sum_ds_qu39)
```


```{r}
#Making a location column.
data <- data %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
data <- arrange(mutate(data,
                       location = factor(location, levels = order_loc)))
```





```{r}
#Set order or groups for plotting

micro_sum$group <- factor(micro_sum$group,
                         levels = c("Bacillariophyta", #Y
                                    "Chrysophyta", #Y
                                    "Dictyochophyta", #Y
                                    "Raphidiophyta", #Y
                                    "Dinoflagellata", #Y
                                    "Cryptophyta",#Y
                                    "Chlorophyta-Prasinophyta", #Y 
                                    "Euglenophyta", #Y
                                    "Prymnesiophyta-Haptophyta", #Y 
                                    "Unknown_Chlorophyta?", #Y
                                    "Unknown_Dinophyceae?", #Y
                                    "Unknown_flagellate" #Y
                                    ))

micro_sum_2$group <- factor(micro_sum_2$group,
                         levels = c("Bacillariophyta", #Y
                                    "Chrysophyta", #Y
                                    "Dictyochophyta", #Y
                                    "Raphidiophyta", #Y
                                    "Dinoflagellata", #Y
                                    "Cryptophyta",#Y
                                    "Chlorophyta-Prasinophyta", #Y 
                                    "Euglenophyta", #Y
                                    "Prymnesiophyta-Haptophyta", #Y 
                                    "Unknown_Chlorophyta?", #Y
                                    "Unknown_Dinophyceae?", #Y
                                    "Unknown_flagellate" #Y
                                    ))

micro_sum_3$group <- factor(micro_sum_3$group,
                         levels = c("Bacillariophyta", #Y
                                    "Chrysophyta", #Y
                                    "Dictyochophyta", #Y
                                    "Raphidiophyta", #Y
                                    "Dinoflagellata", #Y
                                    "Cryptophyta",#Y
                                    "Chlorophyta-Prasinophyta", #Y 
                                    "Euglenophyta", #Y
                                    "Prymnesiophyta-Haptophyta", #Y 
                                    "Unknown_Chlorophyta?", #Y
                                    "Unknown_Dinophyceae?", #Y
                                    "Unknown_flagellate" #Y
                                    ))

```

```{r}
#Setting colour pallete for microscopy data - roughly comparable to chemtax data
color_palette_micro <- c("#ff8000", #Diatoms 
                   "#2642D5", #Chrysophytes
                   "#ff99c7", #Dicto (same color as chryso as same pig. group)
                   "#4d6600", #Raph
                   "#ff0000", #Dino
                   "#ffff00", #Crypto
                   "#00ff00", #Chloro (chloro and eugleno same colour, same pig. group)
                   "#93FFCA", #Eugleno
                   "#7d4dcc" #Hapto
                   )

#Set month labels for plot
month_labels_5 <- rep(c('J','F','M','A','M','J','J','A','S','O','N','D'), 5)

month_labels <- c('J','F','M','A','M','J','J','A','S','O','N','D')
```

```{r}
#Plotting when we have data available for microscopy at Calvert
# micro %>%  
#   filter(!site_id == "QU39" & date > "2018-01-01" & date < "2021-01-01") %>%  
#   distinct(date, site_id) %>% 
#   mutate(year = lubridate::year(date),
#          month = lubridate::month(date)) %>% 
#   group_by(year, month, site_id) %>% 
#   summarise(n = n()) %>% 
#   ggplot(aes(x = as.factor(month), y = n, fill = site_id)) + 
#   geom_bar(stat = "identity", color = "black") +
#   facet_wrap(~ year, ncol = 1) +
#   theme_bw() +
#   labs(y = "# of micro. samples",
#        x = "month",
#        fill = "station") +
#   theme(text = element_text(size = 25))
# 
# ggsave(here("figures_new", "sample_number.png"),
#        width = 17, height = 15, dpi = 300)
```

```{r}
#Plotting time-series of chl, temp, sal, nuts, secchi. For Chl, I want to use Chl for 2018 and HPLC for 2019 and 2020 as there is greater data availability. I need to merge the 2018 chl with the 2019-2020 HPLC.


#Separating the 2018 chlorophyll data where there is no HPLC
chl_bulk <- data %>%
  select(date, site_id, bulk_chl) %>% 
  filter(date < "2019-01-01") %>% 
  rename(chl = bulk_chl)

#Applying the correction to the 2018 chl data based on the relationship between chl and HPLC TChla for 2019 and 2020. This relationship is plotted below.
chl_bulk_fix <- chl_bulk %>% 
  mutate(chl = (0.65*chl) + 0.59 )

#Making the chemtax data tidy so that TChla concentrations can be easily derived by summing concentrations from each chemtax group
chem_tidy <- chem %>% 
  pivot_longer(c(cyan, hapto, green, cryp, dino, dict, raph, diat),
                 names_to = "phyto_group", values_to = "TChla") %>% 
  group_by(date, site_id, phyto_group) %>% 
  summarize(TChla_mean = mean(TChla)) %>% 
  ungroup() %>% 
  group_by(date, site_id) %>% 
  mutate(TChla_sum = sum(TChla_mean)) %>% 
  ungroup()


#Pulling out the TChla concentrations from the chemtax data
chl_hplc <- chem_tidy %>% 
  select(date, site_id, chl = TChla_sum) %>% 
  distinct(date, site_id, chl, .keep_all = TRUE)


#Bringing corrected 2018 chl concentrations into 2019-2020 HPLC Tchla so they are together in a column for plotting.
chl_merge <- rbind(chl_bulk_fix, chl_hplc)
```
```{r}
#Making a location column.
chl_merge <- chl_merge %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))


chl_merge <- arrange(mutate(chl_merge,
                       location = factor(location, levels = order_loc)))

```

```{r}
#Looking at relationship between Chl and TCHLA when both data are available in 2019 and 2020

#renaming chl from the HPLC sheet to TChla so I can join with the chl data
chem_compare <- chl_hplc %>% 
  rename(tchla = chl)  

#Selecting chl data from 2019 and 2020
chl_compare <- data %>%
  select(date, site_id, bulk_chl) %>% 
  filter(data > "2019-01-01")

#Joining 2019 and 2020 hplc Tchla and chl
chem_compare <- chem_compare %>% 
  left_join(chl_compare)

#Plotting a scatterplot of the two variabiles including linear regression line and statistics
chem_compare %>% 
  ggplot(aes(x = bulk_chl, y = tchla)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline(slope = 1, intercept = 0) +
  ggpubr::stat_cor(label.y.npc = 1.0, vjust = 2, size = 8) +
  ggpubr::stat_regline_equation(label.y = 18, size = 6) 
  

#Cross checking that the linear regression statistics on the plot are correct by running model independently
chl_lm = lm(bulk_chl~tchla, data = chem_compare) 
summary(chl_lm) 

```

```{r}
#Exporting corrected TChla magnitudes
write_csv(chl_merge, here("outputs", "bulk_chla_corrected.csv"))
```



```{r}
#Pulling out dates where there were bloom conditions (Tchla > 5 ug/L)

#Subsetting all dates where TChla > 5ug/L
blooms <- chl_merge %>% 
  filter(chl >= 5)

#Making a list of bloom dates
bloom_dates <- blooms$date

#Subsetting microscopy dates where there was bloom conditions.
micro_bloom <- micro %>% 
  filter(date %in% bloom_dates) %>% 
  select(date, site_id, scientificName, count)
```

```{r}
#Making a timeseries plot of all of the drivers (chl, temp, sal, nuts, secchi) - this is the official plot I am using for the current stage of analysis.

f1 <- chl_merge %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = chl, group = location, fill = location, 
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  geom_hline(yintercept = 5, linetype = "dashed", color = "black") +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 15)) +
  labs(y = "Chl") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        # strip.text.x = element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.92, 0.7),
        legend.background = element_blank(),
        text = element_text(size = 30))

f2 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = temp_dm, group = location, fill = location, 
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(8, 16)) +
  labs(y = "Temp") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f3 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sal_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(27, 33), 
                     breaks = seq(27, 33, by = 2)) +
  labs(y = "Salinity") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f4 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = delta_rho_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 16)) +
  labs(y = expression(~ Delta * rho)) +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))


f5 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = no2_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 20)) +
  facet_wrap(~ year) +
  labs(y = expression(NO[3]^{"-"} ~ "+" ~ NO[2]^{"-"})) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f6 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = po4_dm, group = location, fill = location, 
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1.6)) +
  ylab(bquote(PO[4])) +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f7 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sio2_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 30)) +
  ylab(bquote(SiO[4])) +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f8 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = secchi_depth, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 15)) +
  ylab("Secchi") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

fig <- f1/f2/f3/f4/f5/f6/f7/f8

ggsave(here("figures_rev2", "timeseries_drivers.png"), fig,
       width = 16, height = 20, dpi = 300)
```

```{r}
#Truncated version

f1 <- chl_merge %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = chl, group = location, fill = location, 
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  geom_hline(yintercept = 5, linetype = "dashed", color = "black") +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 15)) +
  labs(y = "Chl") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        # strip.text.x = element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.95, 0.7),
        legend.background = element_blank(),
        text = element_text(size = 30))

f2 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = temp_dm, group = location, fill = location, 
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  # scale_y_continuous(expand = c(0, 0), limits = c(8, 16)) +
  labs(y = "Temp.") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f3 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sal_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  # scale_y_continuous(expand = c(0, 0), limits = c(27, 33), 
                     # breaks = seq(27, 33, by = 2)) +
  labs(y = "Salinity") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f4 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = delta_rho_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  # scale_y_continuous(expand = c(0, 0), limits = c(0, 16)) +
  labs(y = expression(~ Delta * rho)) +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))


f5 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = no2_dm, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 20)) +
  facet_wrap(~ year) +
  labs(y = expression(NO[3]^{"-"} ~ "+" ~ NO[2]^{"-"})) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f6 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = secchi_depth, group = location, fill = location,
             color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  # scale_y_continuous(expand = c(0, 0), limits = c(0, 15)) +
  xlab("Year Day") +
  ylab("Secchi") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(
        # axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

fig <- f1/f2/f3/f4/f5/f6

ggsave(here("figures_rev2", "timeseries_drivers_short.png"), fig,
       width = 16, height = 14, dpi = 300)
```

```{r}
data_2 <- data %>% 
  filter(!site_id == "QU39")


#I want to look at annual averages of important variables

data_global <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, temp_dm:bulk_chl) %>% 
  mutate(n_p = no2_dm/po4_dm,
         si_n = sio2_dm/no2_dm) %>% 
  group_by(location) %>% 
  summarise(across(temp_dm:si_n, .f = list(mean = mean, median = median,
                                               min = min, max = max, sd = sd),
                   na.rm = TRUE)) %>% 
  ungroup()

annual_dfo2_sio2 <- data %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(site_id == "DFO2") %>% 
  select(year, sio2_dm) %>% 
  group_by(year) %>% 
  summarise(across(sio2_dm, .f = list(mean = mean, median = median,
                                               min = min, max = max, sd = sd),
                   na.rm = TRUE)) %>% 
  ungroup()

n_p <- data %>% 
  filter(!site_id == "QU39") %>%
  mutate(year = lubridate::year(date)) %>% 
  select(year, location, no2_dm, po4_dm) %>% 
  filter(po4_dm > 0.0001) %>% 
  mutate(n_p = no2_dm/po4_dm)
  
  
n_p_stat <- n_p %>% 
  group_by(location) %>% 
  summarise(across(n_p, .f = list(mean = mean, median = median,
                                               min = min, max = max, sd = sd),
                   na.rm = TRUE)) %>% 
  ungroup()


s_n <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date)) %>%
  select(year, location, sio2_dm, no2_dm) %>% 
  filter(no2_dm > 0.0001) %>% 
  mutate(s_n = sio2_dm/no2_dm) 


s_n_stat <- s_n %>% 
  group_by(location) %>% 
  summarise(across(s_n, .f = list(mean = mean, median = median,
                                               min = min, max = max, sd = sd),
                   na.rm = TRUE)) %>% 
  ungroup() 

chl_stat <- chl_merge %>% 
  filter(!site_id == "QU39") %>%
  group_by(location) %>% 
  summarise(across(chl, .f = list(mean = mean, median = median,
                                               min = min, max = max, sd = sd),
                   na.rm = TRUE)) %>% 
  ungroup()

annual_dfo2_chl <- chl_merge %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(site_id == "DFO2") %>% 
  select(year, chl) %>% 
  group_by(year) %>% 
  summarise(across(chl, .f = list(mean = mean, median = median,
                                               min = min, max = max, sd = sd),
                   na.rm = TRUE)) %>% 
  ungroup()
```

```{r}
#Trying Kruskal Wallis Test
kw_temp <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, temp_dm) 

kruskal.test(temp_dm ~ location, data = kw_temp)


#Pair-wise wilcox
pairwise.wilcox.test(kw_temp$temp_dm, g = kw_temp$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_temp$temp_dm ~ kw_temp$location,
         data = data,
         method = "bonferroni")

```
```{r}
#Trying Kruskal Wallis Test
kw_year <- data %>% 
  filter(site_id == "DFO2") %>%
  mutate(year = lubridate::year(date)) %>% 
  select(year, sio2_dm) 

kruskal.test(sio2_dm ~ year, data = kw_year)


#Pair-wise wilcox
pairwise.wilcox.test(kw_year$sio2_dm, g = kw_year$year,
                     p.adjust.method = "bonferroni")

kw_year_dfo <- kw_year %>% 
  mutate(year_factor = as.factor(year))

#Dunn
FSA::dunnTest(kw_year_dfo$sio2_dm ~ kw_year_dfo$year_factor,
         data = data,
         method = "bonferroni")

```





```{r}
#Trying Kruskal Wallis Test
kw_sal <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, sal_dm) 

kruskal.test(sal_dm ~ location, data = kw_sal)


#Pair-wise wilcox
pairwise.wilcox.test(kw_sal$sal_dm, g = kw_sal$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_sal$sal_dm ~ kw_sal$location,
         data = data,
         method = "bonferroni")

```
```{r}
#Trying Kruskal Wallis Test
kw_drho <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, delta_rho_dm) 

kruskal.test(delta_rho_dm ~ location, data = kw_drho)


#Pair-wise wilcox
pairwise.wilcox.test(kw_drho$delta_rho_dm, g = kw_drho$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_drho$delta_rho_dm ~ kw_drho$location,
         data = data,
         method = "bonferroni")

```
```{r}
#Trying Kruskal Wallis Test
kw_no2 <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, no2_dm) 

kruskal.test(no2_dm ~ location, data = kw_no2)


#Pair-wise wilcox
pairwise.wilcox.test(kw_no2$no2_dm, g = kw_no2$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_no2$no2_dm ~ kw_no2$location,
         data = data,
         method = "bonferroni")

```
```{r}
#Trying Kruskal Wallis Test
kw_po4 <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, po4_dm) 

kruskal.test(po4_dm ~ location, data = kw_po4)


#Pair-wise wilcox
pairwise.wilcox.test(kw_po4$po4_dm, g = kw_no2$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_po4$po4_dm ~ kw_po4$location,
         data = data,
         method = "bonferroni")

```
```{r}
#Trying Kruskal Wallis Test
kruskal.test(n_p ~ location, data = n_p)


#Pair-wise wilcox
pairwise.wilcox.test(n_p$n_p, g = n_p$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(n_p$n_p ~ n_p$location,
         data = data,
         method = "bonferroni")

```
```{r}
n_p_year <- n_p 

n_p_year <- n_p_year %>% 
  filter(location == "S")

#Trying Kruskal Wallis Test - year
kruskal.test(n_p ~ year, data = n_p_year)


#Pair-wise wilcox
pairwise.wilcox.test(n_p_year$n_p, g = n_p_year$year,
                     p.adjust.method = "bonferroni")

#Dunn
# FSA::dunnTest(n_p_year$n_p ~ n_p_year$year,
#          data = data,
#          method = "bonferroni")

```







```{r}
s_n_year <- s_n 

s_n_year <- s_n_year %>% 
  filter(location == "S")


#Trying Kruskal Wallis Test
kruskal.test(s_n ~ year, data = s_n_year)


#Pair-wise wilcox
pairwise.wilcox.test(s_n$s_n, g = s_n$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(s_n$s_n ~ s_n$location,
         data = data,
         method = "bonferroni")

```
```{r}
#Trying Kruskal Wallis Test
kw_secchi <- data %>% 
  filter(!site_id == "QU39") %>% 
  select(location, secchi_depth) 

kruskal.test(secchi_depth ~ location, data = kw_secchi)


#Pair-wise wilcox
pairwise.wilcox.test(kw_secchi$secchi_depth, g = kw_secchi$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_secchi$secchi_depth ~ kw_secchi$location,
         data = data,
         method = "bonferroni")

```






```{r}
#Trying Kruskal Wallis Test
kw_chl <- chl_merge %>% 
  filter(!site_id == "QU39") %>% 
  select(location, chl) 

kruskal.test(chl ~ location, data = kw_chl)


#Pair-wise wilcox
pairwise.wilcox.test(kw_secchi$secchi_depth, g = kw_secchi$location,
                     p.adjust.method = "bonferroni")

#Dunn
FSA::dunnTest(kw_secchi$secchi_depth ~ kw_secchi$location,
         data = data,
         method = "bonferroni")


```
```{r}
#Trying Kruskal Wallis Test
kw_chl_year <- chl_merge %>% 
  mutate(year = lubridate::year(date)) %>% 
  filter(site_id == "DFO2") %>% 
  select(year, chl) 

kruskal.test(chl ~ year, data = kw_chl_year)


#Pair-wise wilcox
pairwise.wilcox.test(kw_secchi$secchi_depth, g = kw_secchi$location,
                     p.adjust.method = "bonferroni")


kw_chl_year <- kw_chl_year %>% 
  mutate(year_fact = as.factor(year))

#Dunn
FSA::dunnTest(kw_chl_year$chl ~ kw_chl_year$year_fact,
         data = data,
         method = "bonferroni")


```

































```{r}
#Doing a similar plot, but with nutrient ratios. 
f1 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = no2_dm, group = site_id, fill = site_id,
             color = site_id)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 20)) +
  facet_wrap(~ year) +
  labs(y = expression(NO[3]^{"-"} ~ "+" ~ NO[2]^{"-"})) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f2 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = po4_dm, group = site_id, fill = site_id, 
             color = site_id)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1.6)) +
  ylab(bquote(PO[4])) +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f3 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sio2_dm, group = site_id, fill = site_id,
             color = site_id)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 30)) +
  ylab(bquote(SiO[4])) +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))


f4 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = no2_dm/po4_dm, group = site_id, fill = site_id,
             color = site_id)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  # scale_y_continuous(expand = c(0, 0), limits = c(0, 20)) +
  facet_wrap(~ year) +
  labs(y = "N:P") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

f5 <- data %>% 
  filter(!site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sio2_dm/no2_dm, group = site_id, fill = site_id, 
             color = site_id)) +
  geom_line(size = 2) +
  geom_point(pch = 21, size = 3, color = "black", stroke = 2) +
  # scale_y_continuous(expand = c(0, 0), limits = c(0, 1.6)) +
  ylab("Si:N") +
  facet_wrap(~ year) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x =  element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))



fig <- f1/f2/f3/f4/f5

ggsave(here("figures_rev2", "timeseries_nut_ratios.png"), fig,
       width = 16, height = 14, dpi = 300)
```


```{r}
#Microscopy May - October 2018-2020 time-series - Calvert

#Creating new labels for the facets
site_labs <- c("F", "C", "S")
names(site_labs) <- c("DFO2", "KC10", "QCS01")


micro_sum %>% 
  filter(date > "2018-04-01" & date < "2020-11-01" & !site_id == "QU39") %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(sum, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sum/100000, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  geom_point(aes(x = yday, y = sum_all/100000), size = 2) +
  scale_fill_manual(values = color_palette_micro,
                    labels = c("Diat", #Y
                               "Chry", #Y
                               "Dict", #Y
                               "Raph", #Y
                               "Dino", #Y
                               "Crypt",#Y
                               "Chlor", #Y 
                               "Eugl", #Y
                               "Hapto")) +
  facet_grid(site_id ~ year, 
             labeller = labeller(site_id = site_labs)) +
    labs(x = "Year Day",
         y = bquote("Abundance (cells" ~10^5 ~ L^-1*")")) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(color="black")) +
        # axis.title.x = element_blank()) +
  guides(fill = guide_legend(nrow = 1)) 


ggsave(here("figures_good", "timeseries_microscopy_calvert.png"),
       width = 12, height = 8, dpi = 300)

```
```{r}
#Adding total abundance column to microsum
micro_sum <- micro_sum %>% 
  group_by(date) %>% 
  mutate(sum_all = sum(sum),
         sum_all_100k = sum_all/100000) %>% 
  ungroup()

#Adding survey month
month_surv <- micro %>% 
  select(date, month_surv, site_id) %>% 
  distinct()

micro_sum <- micro_sum %>% 
  left_join(month_surv)  
  
micro_sum <- micro_sum %>%  
  mutate(year = lubridate::year(date))

```

```{r}
micro_sum <- micro_sum %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))

#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
micro_sum <- arrange(mutate(micro_sum,
                       location = factor(location, levels = order_loc)))
```

```{r}
coeff <- 40

micro_sum %>% 
  filter(!site_id == "QU39") %>% 
  ggplot() + 
  geom_bar(aes(x = as.factor(location), y = sum, fill = group),
           stat = "identity", position = "fill", color = "black") + 
  geom_point(aes(x = as.factor(location), y = sum_all_100k/coeff), pch = 21,
             color = "Black", fill = "white", stroke = 1.5, size = 3) +
  scale_y_continuous(sec.axis = sec_axis(~ . *coeff,
                                         name = bquote("Total Abund. (cells"~ 10^5 ~ L^-1*")"))) +
  facet_grid(year ~ month_surv) + 
  scale_fill_manual(values = color_palette_micro,
                    labels = c("Diat", #Y
                               "Chry", #Y
                               "Dict", #Y
                               "Raph", #Y
                               "Dino", #Y
                               "Crypt",#Y
                               "Chlor", #Y 
                               "Eugl", #Y
                               "Hapto")) +
  ylab("% Abundance") +
  theme_bw() +
  # labs(y = bquote("Abundance (cells"~ 10^5 ~ L^-1*")")) +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 25),
        axis.line = element_line(colour = "black"),
        axis.text = element_text(color="black"),
        axis.title.x = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

ggsave(here("figures_rev2", "phyto_group_test.png"), 
       width = 12, height = 8, dpi = 300)
```
```{r}
micro_sum <- micro_sum %>% 
  filter(!site_id == "QU39") %>% 
  mutate(perc_cont = sum/sum_all)

group_percent <- micro_sum %>% 
  group_by(site_id, group) %>% 
  summarize(med_cont = median(perc_cont),
            min_cont = min(perc_cont),
            max_cont = max(perc_cont)) %>% 
  ungroup()

group_percent_all <- micro_sum %>% 
  group_by(group) %>% 
  summarize(med_cont = median(perc_cont),
            min_cont = min(perc_cont),
            max_cont = max(perc_cont),
            med_sum = median(sum),
            min_sum = min(sum),
            max_sum = max(sum)) %>% 
  ungroup()

cryp <- micro_sum %>% 
  filter(group == "Cryptophyta")
```

```{r}
#Trying Kruskal Wallis Test
kw_diat <- micro_sum %>% 
  filter(!site_id == "QU39") %>% 
  filter(group == "Chlorophyta-Prasinophyta") %>% 
  mutate(perc_cont = sum/sum_all) %>%
  mutate(year = lubridate::year(date)) %>% 
  select(date, year, location, sum_all, perc_cont) 

kruskal.test(perc_cont ~ location, data = kw_diat)


#Pair-wise wilcox
pairwise.wilcox.test(kw_secchi$secchi_depth, g = kw_secchi$location,
                     p.adjust.method = "bonferroni")


kw_chl_year <- kw_chl_year %>% 
  mutate(year_fact = as.factor(year))

#Dunn
FSA::dunnTest(kw_chl_year$chl ~ kw_chl_year$year_fact,
         data = data,
         method = "bonferroni")


```







```{r}

#Microscopy full year comparison of KC10 to QU39
micro_sum_2 %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(sum, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  geom_point(aes(x = yday, y = sum_all), size = 2) +
  scale_fill_manual(values = color_palette_micro) +
  facet_grid(site_id ~ year) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 11)) +
        # strip.background = element_blank(),
        # strip.text = element_blank()) + 
  labs(x = "Year Day",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25)) 

ggsave(here("figures_rev2", "timeseries_kc10_qu39.png"),
       width = 17, height = 10, dpi = 300)

```
```{r}

#Microscopy full year comparison of KC10 to QU39 with QU39 timeseries downscaled to similar temporal resolution as KC10 (monthly)

micro_sum_3 %>% 
  group_by(date, site_id) %>% 
  mutate(sum_all = sum(sum, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = sum, group = group, fill = group)) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  geom_point(aes(x = yday, y = sum_all), size = 2) +
  scale_fill_manual(values = color_palette_micro) +
  facet_grid(site_id ~ year) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 11)) +
        # strip.background = element_blank(),
        # strip.text = element_blank()) + 
  labs(x = "Year Day",
           y = bquote("Abundance (cells" ~ L^-1*")")) +
  theme(text = element_text(size = 25)) 

ggsave(here("figures_rev2", "timeseries_kc10_qu39_downscaled.png"),
       width = 17, height = 10, dpi = 300)

```

Working with chemtax data

```{r}

#Order phytoplankton groups roughly from smallest to largest - create order list
order_chem <- c("cyan", "hapto", "green", "cryp",
                "dino", "raph", "dict", "diat")

#Chemtax - Specify order of phyto groups for figures
chem_tidy <- arrange(mutate(chem_tidy,
                                phyto_group = factor(phyto_group,
                                levels = order_chem)))

chem_tidy <- chem_tidy %>% 
  arrange(date, phyto_group)

```

```{r}

#Set Color palette for plotting. Currently based on QU39 manuscript. Brewer has some good ones for R style.
palette_chem <- c("#ff8000", #1 - Diatoms (orange)
                  "#ff99c7", #2 - Dictyochophytes (pink)
                  "#4d6600", #3 - Raphidophytes (dark green)
                  "#ff0000", #4 - Dinoflagellates (Red)
                  "#ffff00", #5 - Cryptophytes (yellow)
                  "#00ff00", #6 - Chlorophyta (light green)
                  "#7d4dcc", #7 - Haptophytes (purple)
                  "#000000") #8 - Cyanobacteria (black)

#Set month labels for plot
month_labels <- c('J','F','M','A','M','J','J','A','S','O','N','D')
```

```{r}
#Creating plot of Calvert timeseries (May-October) Chemtax trends.

chem_tidy %>% 
  filter(date > "2018-04-01" & date < "2020-11-01" & !site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = TChla_mean, fill = fct_rev(phyto_group))) +
  geom_area(position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  geom_point(aes(x = yday, y = TChla_sum), size = 2) +
  scale_fill_manual(values = palette_chem) +
  facet_grid(site_id ~ year) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 11)) +
  guides(fill = guide_legend(nrow = 1)) +
        # strip.background = element_blank(),
        # strip.text = element_blank()) + 
  labs(x = "Year Day",
           y = bquote("TChl (mg" ~ m^-3*")")) +
  theme(text = element_text(size = 25)) 

ggsave(here("figures_rev2", "timeseries_calvert_chem.png"),
       width = 16, height = 10, dpi = 300)

```

```{r}
#Plot Calvert chemtax data by station - relative

chem_tidy %>%
  ggplot() +
  geom_area(aes(date, TChla_mean, fill = fct_rev(phyto_group)),
    position = "fill", alpha = 0.8, size = 0.5, colour = "black") +
  geom_point(aes(date, 1)) +
  facet_wrap(~ site_id, nrow = 4) +
  scale_fill_manual(values = palette_chem) +
  theme_bw() +
  labs(y = bquote("Relative (%)"),
       fill = "Group") +
  scale_x_date(limits = startEnd,
               breaks = scales::date_breaks("1 month"),
               labels = scales::date_format("%m")) +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 30)) +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        text = element_text(size = 30)) +
        # plot.margin = margin(0, 50, 0, 0)) +
  guides(fill = guide_legend(nrow = 1))
  
ggsave(here("figures", "calvert_qu39_chem_relative_2019-ts.png"),
       width = 16, height = 14, dpi = 300)
```

```{r}
#Making timeseries plot of SF Chlorophyll in a similar way to the chemtax and microscopy data. Will likely plot as stacked bars and there are data gaps.

#Subsetting size-fractionated chlorophyll data and removing rows with na's - need all three filters for plotting.
sf <- data %>%
  select(date:site_id, micro_chl:pico_chl) %>% 
  filter(!(is.na(micro_chl) | is.na(nano_chl) | is.na(pico_chl)))

#Making size-fractionated data tidy  
sf_tidy <- sf %>% 
  pivot_longer(c(micro_chl, nano_chl, pico_chl),
                 names_to = "size", values_to = "chl") %>% 
  group_by(date, site_id) %>% 
  mutate(sf_sum = sum(chl)) %>% 
  ungroup()

#List for order of size fractions from smallest to largest
order_sf <- c("pico_chl", "nano_chl", "micro_chl")
# order_sf <- c("micro_chl", "nano_chl", "pico_chl")


#Applying order of size fractions to datasheet
sf_tidy <- arrange(mutate(sf_tidy,
                                size = factor(size,
                                levels = order_sf)))

#Arranging dataset by date and size.
sf_tidy <- sf_tidy %>% 
  arrange(date, size)

```

```{r}
#Plotting size fraction timeseries -  stacked area plot

sf_tidy %>% 
  filter(date > "2018-04-01" & date < "2020-11-01" & !site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = yday, y = chl, fill = fct_rev(size))) +
  geom_area(position = "stack", size = 0.5, colour = "black") +
  geom_point(aes(x = yday, y = sf_sum), size = 2) +
  scale_fill_brewer(palette = "RdYlBu") +
  facet_grid(site_id ~ year) +
  labs(x = "Year Day",
           y = bquote("TChl (mg" ~ m^-3*")")) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 25))
        # strip.background = element_blank(),
        # strip.text = element_blank()) + 
  

ggsave(here("figures_rev2", "timeseries_calvert_sf.png"),
       width = 17, height = 10, dpi = 300)

```
```{r}
#Plotting size fraction timeseries -  stacked area plot

sf_tidy %>% 
  filter(date > "2018-04-01" & date < "2020-11-01" & !site_id == "QU39") %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = as.factor(month_surv), y = chl, fill = fct_rev(size))) +
  geom_bar(stat = "identity", position = "stack", size = 0.5, colour = "black") +
  # geom_point(aes(x = yday, y = sf_sum), size = 2) +
  scale_fill_brewer(palette = "RdYlBu") +
  facet_grid(site_id ~ year) +
  labs(x = "Survey Month",
           y = bquote("Chl (mg" ~ m^-3*")")) +
  theme_bw() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        text = element_text(size = 25))
        # strip.background = element_blank(),
        # strip.text = element_blank()) + 
  

ggsave(here("figures_rev2", "timeseries_calvert_sf_bar.png"),
       width = 17, height = 10, dpi = 300)

```

