---
title: "pca_environemtal_data"
output: html_notebook
---

```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(cluster)
library(ggdendro)
library(RColorBrewer)
library(indicspecies)
library(factoextra)
library(zoo)
```

```{r}
env <- read_csv(here("outputs", "enviro_2023-05-26_up.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

co2 <- read_csv(here("files", "co2.csv"))

ctd <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

```

```{r}
ctd <- ctd %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```


```{r}
co2_avg <- co2 %>%
  select(measurementTime, year, sw_xCO2_QC, sw_xCO2) %>% 
  mutate(date_time = lubridate::mdy_hm(measurementTime)) %>%
  mutate(date = lubridate::date(date_time)) %>% 
  filter(is.na(sw_xCO2_QC)) %>%
  filter(!is.na(sw_xCO2)) %>% 
  filter(year > 2017 & year < 2022) %>% 
  group_by(date) %>% 
  summarise(mean_co2 = mean(sw_xCO2)) %>%
  ungroup()
```

```{r}
up_cm <- env %>% 
  select(date, up_dm) %>% 
  # drop_na() %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  group_by(year) %>% 
  mutate(up_cm = cumsum(replace_na(up_dm, 0))) %>% 
  ungroup()
```


```{r}
up_fig <-
  up_cm %>% 
  ggplot() +
  geom_col(aes(x = date, y = ifelse(up_dm < 0/10^3, up_dm/10^3, 0)), fill= "blue") +
  geom_col(aes(x = date, y = ifelse(up_dm > 0/10^3, up_dm/10^3, 0)), fill= "red") +
  geom_line(aes(x = date, y = up_cm/10^4, color = as.factor(year)), size = 2) +
  labs(y = "upwelling") +
  # scale_colour_steps2()
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        legend.position = "none")
```


```{r}
wind_fig <-
  env %>% 
  ggplot(aes(x = date, y = wind_dm^3, color = wind_dir_dm)) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  scale_color_stepsn(colors = brewer.pal(n = 8, name = "RdBu"),
                     breaks = seq(0, 360, by = 45),
                    limits = c(0, 360),
                    name = "Dir.(°)") +
  # scale_color_continuous(type = "viridis",
  #                        guide_colourbar(title = "Dir. (°)",
  #                                        barwidth = 0.5,
  #                                        barheight = 10)) +
  labs(y = bquote("Wind ("*m^3~s^-3*")")) +
  # scale_colour_steps2()
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(color = guide_colourbar(barwidth = 1, barheight = 12))
```

```{r}
riv <- env %>% 
  select(date, Q_GM = gm_dis, Q_SM = sm_dis, Q_RA = ra_dis) %>% 
  mutate(Q_tot = Q_GM + Q_SM + Q_RA) %>% 
  pivot_longer(!date, names_to = "Watershed_group", values_to = "Q")

# Order locations from fjord to shelf
riv_loc <- c("Q_GM",
             "Q_SM",
             "Q_RA",
             "Q_tot")

riv <- arrange(mutate(riv, 
                      Watershed_group = factor(Watershed_group,
                                               levels = riv_loc)))
riv_test <- riv %>% 
  group_by(date) %>% 
  summarise(sum = sum(Q)) %>% 
  ungroup()

riv_fig <- riv %>% 
  filter(!Watershed_group == "Q_tot") %>% 
  ggplot() +
  geom_area(aes(x = date, y = Q, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.5) +
  # geom_line(data = riv %>% filter(Watershed_group == "Wan"),
  #           aes(x = date, y = Q), color = "white", size = 1) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Blues",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote(Dis. ~ "("~m^-3*~s^-1*")")) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
chl <- chl %>% 
   add_row(date = as.Date("2020-01-01"), site_id = "QCS01",
           tchla = NA, location = "S") %>% 
   add_row(date = as.Date("2019-01-01"), site_id = "QCS01",
           tchla = NA, location = "S")

loc <- c("F",
         "C",
         "S")

chl <- arrange(mutate(chl, 
                      location = factor(location,
                                               levels = loc)))

chl_fig <- chl %>% 
  ggplot(aes(x = date, y = tchla, color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", size = 2, stroke = 2) +
  # geom_vline(xintercept = as.Date("2019-03-28"), color = "#EFC000FF") +
  # geom_vline(xintercept = as.Date("2020-04-16"), color = "#EFC000FF") +
  scale_color_jco() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  labs(y = bquote("TChla (mg" ~ m^-3*")"),
       color = NULL) +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        # axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```
```{r}
scales::show_col(pal_jco("default")(3))
```

```{r}
co2_fig <-
  co2_avg %>% 
  ggplot(aes(x = date, y = mean_co2)) +
  geom_point(size = 1) +
  geom_line(size = 1) +
  geom_area(alpha = 0.3) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  labs(y = "ρCO2 (ppm)") +
  ylim(0, 900) +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
fig <- up_fig / wind_fig / riv_fig / chl_fig / co2_fig

ggsave(here("figures_river", "riv_co2_chl_upwelling.png"), fig,
       width = 16, height = 18, dpi = 300)
```

```{r}
ctd_t <- ctd %>% 
  select(date, location, temp = temp_dm) %>% 
   add_row(date = as.Date("2020-01-01"), location = "S",
           temp = NA) %>% 
   add_row(date = as.Date("2019-01-01"), location = "S",
           temp = NA)

loc <- c("F",
         "C",
         "S")

ctd_t <- arrange(mutate(ctd_t, 
                      location = factor(location,
                                               levels = loc)))

tf <- ctd_t %>% 
  ggplot(aes(x = date, y = temp, color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", size = 2, stroke = 2) +
  scale_color_jco() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  labs(y = bquote("Temp (°C)"),
       color = NULL) +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```
```{r}
ctd_s <- ctd %>% 
  select(date, location, sal = sal_dm) %>% 
   add_row(date = as.Date("2020-01-01"), location = "S",
           sal = NA) %>% 
   add_row(date = as.Date("2019-01-01"), location = "S",
           sal = NA)

ctd_s <- arrange(mutate(ctd_s, 
                      location = factor(location,
                                               levels = loc)))

sf <- ctd_s %>% 
  ggplot(aes(x = date, y = sal, color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", size = 2, stroke = 2) +
  scale_color_jco() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  labs(y = bquote("Sal. (PSU)"),
       color = NULL) +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
ctd_n <- ctd %>% 
  select(date, location, din = no2_dm) %>% 
   add_row(date = as.Date("2020-01-01"), location = "S",
           din = NA) %>% 
   add_row(date = as.Date("2019-01-01"), location = "S",
           din = NA)

ctd_n <- arrange(mutate(ctd_n, 
                      location = factor(location,
                                               levels = loc)))

nf <- ctd_n %>% 
  ggplot(aes(x = date, y = din, color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", size = 2, stroke = 2) +
  scale_color_jco() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  labs(y = "DIN\u207B\u0020\u0028\u00B5mol\u0020L\u207B\u00B9\u0029",
       color = NULL) +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
fig <- wind_fig / riv_fig / tf / sf / nf / chl_fig 

ggsave(here("figures_river", "riv_temp_sal_nuts_Tchla.png"), fig,
       width = 16, height = 20, dpi = 300)
```

```{r}
fig <- up_fig / wind_fig / riv_fig / tf / sf / nf / chl_fig 

ggsave(here("figures_river", "riv_co2_chl_upwelling_test2.png"), fig,
       width = 16, height = 22, dpi = 300)
```

```{r}
ws.labs <- c("G.Mtn", "S.Mtn", "Rain", "Total")
names(ws.labs) <- c("Q_GM", "Q_SM", "Q_RA", "Q_tot")

riv %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  ggplot(aes(x = as.factor(month), y = Q, fill = as.factor(year))) +
  geom_boxplot() +
  labs(y = bquote(Dis. ~ "("~m^-3*~s^-1*")"),
       fill = NULL) +
  facet_grid(Watershed_group ~ ., scales = "free_y",
             labeller = labeller(Watershed_group = ws.labs)) +
  scale_fill_brewer(palette = "Dark2") +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        legend.position = c(0.1, 0.9))

ggsave(here("figures_river", "discharge_monthly.png"),
       width = 16, height = 12, dpi = 300)
```
```{r}
riv %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  filter(!Watershed_group == "Q_tot") %>% 
  ggplot() +
  geom_area(aes(x = yday, y = Q, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.5) +
  # geom_line(data = riv %>% filter(Watershed_group == "Wan"),
  #           aes(x = date, y = Q), color = "white", size = 1) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Set2",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote(Dis. ~ "("~m^-3*~s^-1*")")) +
  facet_grid(year ~.) +
  # scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures_river", "discharge_vert.png"),
       width = 16, height = 12, dpi = 300)
```
```{r}
cs_riv <- riv %>% 
  filter(Watershed_group == "Q_tot") %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  mutate(median = median(Q)) %>% 
  group_by(year) %>% 
  mutate(ms = Q - median,
         cs = cumsum(ms),
         cs_raw = cumsum(Q),
         ip = cs - lag(cs, 1)) %>% 
  ungroup()

cs_wan <- env %>%
  select(date, wan_dis) %>% 
  mutate(year = lubridate::year(date),
         yday = lubridate::yday(date)) %>% 
  mutate(median = median(wan_dis)) %>% 
  group_by(year) %>% 
  mutate(ms = wan_dis - median,
         cs = cumsum(ms),
         cs_raw = cumsum(wan_dis),
         ip = cs - lag(cs, 1)) %>% 
  ungroup()

cs_join <- cs_riv %>% 
  select(date, cs, cs_raw)

cs_wan_join <- cs_wan %>% 
  select(date, cs_wan = cs, cs_wan_raw = cs_raw)

riv <- riv %>% 
  left_join(cs_join) %>% 
  left_join(cs_wan_join)
```

```{r}
cs_wan %>% 
  ggplot(aes(x = date, y = cs_raw, color = as.factor(year))) +
  geom_line()
```

```{r}
riv_test <- riv %>% 
  mutate(Q_d = Q/10^3,
         cs_d = cs/10^4,
         cs_raw_d = cs_raw/10^4,
         cs_wan_d = cs_wan/10^4,
         cs_wan_raw_d = cs_wan_raw/10^4)
```



```{r}
scale <- 2

riv_test %>% 
  filter(!Watershed_group == "Q_tot") %>% 
  ggplot() +
  geom_area(aes(x = date, y = Q_d, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.1, alpha = 0.8) +
  geom_line(data = filter(riv_test, date >= "2018-01-01" &
                            date <= "2018-12-31"),
            aes(date, y = cs_d/scale),
            color = "black", size = 1.5) +
  geom_line(data = filter(riv_test, date >= "2019-01-01" &
                            date <= "2019-12-31"),
            aes(date, y = cs_d/scale),
            color = "black", size = 1.5) +
  geom_line(data = filter(riv_test, date >= "2020-01-01" &
                            date <= "2020-12-31"),
            aes(date, y = cs_d/scale),
            color = "black", size = 1.5) +
  geom_line(data = filter(riv_test, date >= "2018-01-01" &
                            date <= "2018-12-31"),
            aes(date, y = cs_wan_d/scale),
            color = "black", size = 1.0, linetype = "dotted") +
  geom_line(data = filter(riv_test, date >= "2019-01-01" &
                            date <= "2019-12-31"),
            aes(date, y = cs_wan_d/scale),
            color = "black", size = 1.0, linetype = "dotted") +
  geom_line(data = filter(riv_test, date >= "2020-01-01" &
                            date <= "2020-12-31"),
            aes(date, y = cs_wan_d/scale),
            color = "black", size = 1.0, linetype = "dotted") +
  geom_point(aes(x = as.Date("2018-05-02"), y = -5.786401/scale), pch = 21,
             fill = "white", stroke = 1.5, size = 2.5) +
  geom_point(aes(x = as.Date("2019-05-08"), y = -9.507108/scale), pch = 21,
             fill = "white", stroke = 1.5, size = 2.5) +
  geom_point(aes(x = as.Date("2020-04-19"), y = -4.7487954/scale), pch = 21,
             fill = "white", stroke = 1.5, size = 2.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale,
                                         name = bquote("Int. Dis."~"("*10^4~m^3*~s^-1*")"))) + 
  # geom_line(data = riv %>% filter(Watershed_group == "Wan"),
  #           aes(x = date, y = Q), color = "white", size = 1) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Dark2",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote("Dis."~"("*10^3~m^3*~s^-1*")")) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  theme_bw() +
  theme(legend.position = c(0.08, 0.86),
        text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures_river", "discharge_cs.png"),
       width = 16, height = 6, dpi = 300)
```
```{r}
max_cs <- riv_test %>%
  mutate(year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  filter(cs_d == max(cs_d))
```



```{r}
scale <- 10

riv_test %>% 
  filter(!Watershed_group == "Q_tot") %>% 
  ggplot() +
  geom_area(aes(x = date, y = Q_d, fill = Watershed_group),
            stat = "identity", position = "stack", color = "black", 
            size = 0.1, alpha = 0.8) +
  geom_line(data = filter(riv_test, date >= "2018-01-01" &
                            date <= "2018-12-31"),
            aes(date, y = cs_raw_d/scale),
            color = "black", size = 1.5) +
  geom_line(data = filter(riv_test, date >= "2019-01-01" &
                            date <= "2019-12-31"),
            aes(date, y = cs_raw_d/scale),
            color = "black", size = 1.5) +
  geom_line(data = filter(riv_test, date >= "2020-01-01" &
                            date <= "2020-12-31"),
            aes(date, y = cs_raw_d/scale),
            color = "black", size = 1.5) +
  geom_line(data = filter(riv_test, date >= "2018-01-01" &
                            date <= "2018-12-31"),
            aes(date, y = cs_wan_raw_d/scale),
            color = "black", size = 1.0, linetype = "dotted") +
  geom_line(data = filter(riv_test, date >= "2019-01-01" &
                            date <= "2019-12-31"),
            aes(date, y = cs_wan_raw_d/scale),
            color = "black", size = 1.0, linetype = "dotted") +
  geom_line(data = filter(riv_test, date >= "2020-01-01" &
                            date <= "2020-12-31"),
            aes(date, y = cs_wan_raw_d/scale),
            color = "black", size = 1.0, linetype = "dotted") +
  geom_point(aes(x = as.Date("2018-05-02"), y = 12.020980/scale), pch = 21,
             fill = "white", stroke = 1.5, size = 2.5) +
  geom_point(aes(x = as.Date("2019-05-08"), y = 9.169442/scale), pch = 21,
             fill = "white", stroke = 1.5, size = 2.5) +
  geom_point(aes(x = as.Date("2020-04-19"), y = 11.301365/scale), pch = 21,
             fill = "white", stroke = 1.5, size = 2.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale,
                                         name = bquote("Int. Dis."~"("*10^4~m^3*~s^-1*")"))) + 
  # geom_line(data = riv %>% filter(Watershed_group == "Wan"),
  #           aes(x = date, y = Q), color = "white", size = 1) +
  # scale_fill_d3(labels = c('glacier', 'snow', 'rain')) +
  scale_fill_brewer(palette = "Dark2",
                    labels = c('glacier', 'snow', 'rain')) +
  labs(fill = NULL,
       y = bquote("Dis."~"("*10^3~m^3*~s^-1*")")) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  theme_bw() +
  theme(legend.position = c(0.08, 0.86),
        text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())

ggsave(here("figures_river", "discharge_cs_raw.png"),
       width = 16, height = 6, dpi = 300)
```




```{r}
sal_fig <- sal_dis <- ctd_s %>% 
  ggplot(aes(x = date, y = sal, color = location)) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", size = 2, stroke = 2) +
  scale_color_jco() +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01")),
               expand = c(0, 0),
               date_breaks = "years", date_labels = "%b%y") +
  theme_bw() +
  labs(y = bquote("Sal. (PSU)"),
       color = NULL) +
  theme(legend.position = c(0.08, 0.1),
        text = element_text(size = 30),
        axis.text = element_text(color = 'black'),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank())
```

```{r}
fig <- cs_fig / sal_fig

ggsave(here("figures_river", "discharge_cs_salt.png"),
       width = 16, height = 10, dpi = 300)
```

