---
title: "R Notebook"
output: html_notebook
---


```{r}
#Load packages
library(tidyverse)
library(patchwork)
library(here)
library(readr)
library(readxl)
library(gsw)
```

```{r}
#Upload fully formatted microscopy data

micro <- read_csv(here("outputs", "micro_kc10_2021-12-01.csv"))

hplc <- read_csv(here("files", "hplc_2018_2020.csv"))

chl <- read_csv(here("files", "chl_2018_2020.csv"))

ctd <- read_csv(here("files", "kc10_ctd.csv"))

nuts <- read_csv(here("files", "kc10_nuts.csv"))
```

```{r}
#Removing QU39 
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
ctd <- ctd %>% 
  select(date_time = `Measurement time`,
         pres = `Pressure (dbar)`,
         sal = `Salinity (PSU)`,
         temp = `Temperature (deg C)`) %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  relocate(date, .after = date_time)

ctd <- ctd %>% 
  group_by(date, pres) %>% 
  summarise(temp = mean(temp),
            sal = mean(sal)) %>% 
  ungroup()

```
```{r}
#Performing GSW calculations

#Some CTD casts are missing coordinates that are required for GSW calculations. Fill the coordinates in using those from the Hakai Station Master - Latitude
ctd <- ctd %>% 
  mutate(latitude = 51.65064,
         longitude = -127.9513)
                              

#Calculating absolute salinity
SA <- gsw_SA_from_SP(ctd$sal, ctd$pres, ctd$longitude, ctd$latitude)

#Converting absolute salinity output to a dataframe
SA <- as.data.frame(SA)

#Calculating conservative temperature
CT <- gsw_CT_from_t(SA$SA, ctd$temp, ctd$pres)

#Converting conservative temperature output to a dataframe
CT <- as.data.frame(CT)

#Calculating Density
rho = gsw_rho(SA$SA, CT$CT, ctd$pres)

#Converting Density to a dataframe
rho <- as.data.frame(rho)

#Calculating Brunt-Vaisala frequency
bv <- gsw_Nsquared(SA$SA, CT$CT, ctd$pres)

#Converting Brunt-Vaisala frequency to a dataframe
bv <- bind_rows(bv)

#Adding a row at the bottom of the Brunt-Vaisala dataframe to make the vector length equal to the other calculations
bv <- bv %>% 
  add_row(N2 = NA, p_mid = NA)

#Binding calculations to ctd dataframe
ctd <- cbind(ctd, SA, CT, rho, bv)
```

```{r}
#Filter 2m data from the CTD datasheet
ctd_2 <- ctd %>% 
  filter(pres == 2) %>% 
  select(date, rho_2 = rho)

#filter 30m data
ctd_30 <- ctd %>% 
  filter(pres == 30) %>% 
  select(date, rho_30 = rho)

#joining 2m data to 3m data
ctd_dd <- ctd_2 %>% 
  left_join(ctd_30)

#Calculating difference in density
ctd_dd <- ctd_dd %>% 
  mutate(delta_rho = rho_30 - rho_2) %>% 
  select(date, delta_rho)

ctd <- ctd %>% 
  left_join(ctd_dd)

```

```{r}
#Summing species for the KC10-QU39 Timeseries
micro_sum <- micro %>%
  filter(trophicStatus == "auto") %>% 
  complete(date, group) %>% # make each day have all species, even if not observed (for joining)
  group_by(date, group) %>% 
  summarise(sum = sum(count)) %>% #sum counts for each grouping/class
  ungroup() %>% 
  arrange(date, group) %>% 
  mutate(sum = replace_na(sum, 0),
         site_id = "KC10")
```
```{r}
chl_join <- chl %>% 
  filter(line_out_depth == 5 & filter_type == "Bulk GF/F") %>% 
  select(date, site_id, chla, chla_flag) %>% 
  filter(chla_flag == "AV" | is.na(chla_flag)) %>% 
  filter(!is.na(chla))

hplc_join <- hplc %>% 
  filter(line_out_depth == 5 & !is.na(all_chl_a)) %>% 
  select(date, site_id, tchla = all_chl_a)

hplc_join <- hplc_join %>% 
  left_join(chl_join)

hplc_join %>% 
  ggplot(aes(x = tchla, y = chla)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline(slope = 1, intercept = 0) +
  ggpubr::stat_cor(label.y.npc = 1.0, vjust = 2, size = 8) +
  ggpubr::stat_regline_equation(label.y = 18, size = 6)

chl_lm = lm(chla ~ tchla, data = hplc_join) 
summary(chl_lm) 
```



```{r}
#Separating the 2018 chlorophyll data where there is no HPLC
chl_cali <- chl_join %>%
  filter(date < "2019-01-01")

#Applying the correction to the 2018 chl data based on the relationship between chl and HPLC TChla for 2019 and 2020. This relationship is plotted below.
chl_cali <- chl_cali %>% 
  mutate(tchla = (chla + 0.04)/1.24)

chl_merge <- chl_cali %>% 
  select(date, site_id, tchla)

hplc_merge <- hplc %>% 
  filter(line_out_depth == 5 & !is.na(all_chl_a)) %>% 
  select(date, site_id, tchla = all_chl_a)

tchla_merge <- rbind(hplc_merge, chl_merge)

tchla_export <- tchla_merge %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id)))
```

```{r}
#Write output to csv.
write_csv(tchla_export, here("outputs", "tchla_calibration_2022-08-04.csv"))
```

```{r}
#Merge Tchla with microscopy data

micro_sum <- micro_sum %>% 
  left_join(tchla_merge)
```




```{r}
#Set order or groups for plotting

micro_sum$group <- factor(micro_sum$group,
                         levels = c("Bacillariophyta", #Y
                                    "Chrysophyta", #Y
                                    "Dictyochophyta", #Y
                                    "Raphidiophyta", #Y
                                    "Dinoflagellata", #Y
                                    "Cryptophyta",#Y
                                    "Chlorophyta-Prasinophyta", #Y 
                                    "Euglenophyta", #Y
                                    "Prymnesiophyta-Haptophyta", #Y 
                                    "Unknown_Chlorophyta?", #Y
                                    "Unknown_Dinophyceae?", #Y
                                    "Unknown_flagellate" #Y
                                    ))

```

```{r}
#Setting colour pallete for microscopy data - roughly comparable to chemtax data
color_palette_micro <- c("#ff8000", #Diatoms 
                   "#2642D5", #Chrysophytes
                   "#ff99c7", #Dicto (same color as chryso as same pig. group)
                   "#4d6600", #Raph
                   "#ff0000", #Dino
                   "#ffff00", #Crypto
                   "#00ff00", #Chloro (chloro and eugleno same colour, same pig. group)
                   "#93FFCA", #Eugleno
                   "#7d4dcc" #Hapto
                   )


```

```{r}
coeff <- 0.30

temp <- ctd %>% 
  filter(pres == 5) %>% 
  ggplot(aes(x = date, y = temp)) +
  annotate("rect", xmin = as.Date("2018-05-01"), xmax = as.Date("2018-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2019-05-01"), xmax = as.Date("2019-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2020-05-01"), xmax = as.Date("2020-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  geom_point(color = "red", size = 3) +
  geom_line(color = "red", size = 2) +
  coord_cartesian(ylim = c(6, 15)) +
  labs(y = expression("Temp. ("*~degree*C*")")) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 35))

sal <- ctd %>% 
  filter(pres == 5) %>% 
  ggplot(aes(x = date, y = sal)) +
  annotate("rect", xmin = as.Date("2018-05-01"), xmax = as.Date("2018-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2019-05-01"), xmax = as.Date("2019-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2020-05-01"), xmax = as.Date("2020-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  geom_point(color = "blue", size = 3) +
  geom_line(color = "blue", size = 2) +
  coord_cartesian(ylim = c(26.5, 31.5)) +
  labs(y = "Salinity") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 35))

drho <- ctd %>% 
  filter(pres == 5) %>% 
  ggplot(aes(x = date, y =delta_rho)) +
  annotate("rect", xmin = as.Date("2018-05-01"), xmax = as.Date("2018-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2019-05-01"), xmax = as.Date("2019-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2020-05-01"), xmax = as.Date("2020-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  geom_point(color = "black", size = 3) +
  geom_line(color = "black", size = 2) +
  coord_cartesian(ylim = c(0, 9)) +
  labs(y = expression(Delta*rho)) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 35))

nut_fig <- nuts %>% 
  filter(line_out_depth == 5) %>% 
  ggplot(aes(x = date, y = sio2)) +
  annotate("rect", xmin = as.Date("2018-05-01"), xmax = as.Date("2018-11-01"),
           ymin = 0, ymax = 50, alpha = .1) +
  annotate("rect", xmin = as.Date("2019-05-01"), xmax = as.Date("2019-11-01"),
           ymin = 0, ymax = 50, alpha = .1) +
  annotate("rect", xmin = as.Date("2020-05-01"), xmax = as.Date("2020-11-01"),
           ymin = 0, ymax = 50, alpha = .1) +
  geom_point(color = "black", size = 3) +
  geom_line(color = "black", size = 2) +
  labs(y = expression("Sio2 (um)")) +
  theme_bw() +
  coord_cartesian(ylim = c(0, 40)) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 35))


micro <- micro_sum %>% 
  group_by(date) %>% 
  mutate(sum_all = sum(sum, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  ggplot(aes(x = date)) + 
  annotate("rect", xmin = as.Date("2018-05-01"), xmax = as.Date("2018-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2019-05-01"), xmax = as.Date("2019-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  annotate("rect", xmin = as.Date("2020-05-01"), xmax = as.Date("2020-11-01"),
           ymin = 0, ymax = 35, alpha = .1) +
  geom_area(aes(y = sum/100000, group = group, fill = group), 
            position = "stack", alpha = 0.8, size = 0.5, colour = "black") +
  geom_point(aes(y = sum_all/100000), size = 1.2) +
  geom_point(aes(y = tchla/coeff), pch = 8,
             color = "Black", stroke = 1.5, size = 2) +
  scale_y_continuous(limits = c(0, 35),
                     sec.axis = sec_axis(~ . *coeff, name = "TChla (ug/L)")) +
  geom_hline(yintercept = 5/coeff, linetype = "dotted") +
  scale_fill_manual(values = color_palette_micro,
                    labels = c("diat",
                               "chry",
                               "dict",
                               "raph,",
                               "raph",
                               "dino",
                               "chlo",
                               "eugl",
                               "hapt")) +
  labs(x = "Year Day",
       y = bquote("Abun. (cells" ~10^5 ~ L^-1*")")) +
  theme_bw() +
  theme(legend.position = c(0.30, 0.87),
        # legend.position = "top",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        text = element_text(size = 35)) +
  guides(fill = guide_legend(nrow = 2))

pan <- temp/sal/drho/nut_fig/micro


ggsave(here("figures_good", "timeseries_kc10_sil.png"), pan,
       width = 16, height = 20, dpi = 300)

```








