---
title: "pca_environemtal_data"
output: html_notebook
---

Running PCA and cluster analysis on environmental variables.
```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(BiodiversityR)
library(ggrepel)
library(patchwork)
library(RColorBrewer)
```


```{r}
#Uploading datasheet with physio-chemical data.
data <- read_csv(here("outputs", "ctd_all_2022-11-25.csv"))

```

```{r}
#selecting data I am going to use with the PCA - wanted to cut down variables from the full list.
data_pca <- data %>%
  mutate(month = lubridate::month(date)) %>% 
  select(date, month, site_id, temp = temp_dm, sal = sal_dm, 
         drho = delta_rho_dm, no2 = no2_dm, sio2 = sio2_dm, po4 = po4_dm,
         secchi = secchi_depth)

#Cutting out sio2 and po4 because strongly correlated with no3 anyways.
data_pca <- data_pca %>% 
  select(-sio2, -po4)

#Removing NA's for analysis 
data_pca <- data_pca %>%
  drop_na()
```


```{r}
#Pulling out explanatory variables - not inlcuding ratio
expl <- data_pca[, 4:8]
```



```{r}
#Scaling data being used for PCA 
expl <- scale(expl)

#Converting to a data frame for subsequent analysis.
expl <- as.data.frame(expl)

```


```{r}
#Running PCA using vegan - when RDA is run without response variables, then it is a PCA
pca <- rda(expl)

#Looking at results - for interpretation of following look at.
head(summary(pca))

#Looking at scores
loadings <- scores (pca, display = 'species', scaling = 0)
loadings
```


```{r}
#Looking at the variables with highest correlation with axis 1
sort (abs (loadings[,1]), decreasing = TRUE)
```
```{r}
#Looking at the variables with highest correlation with axis 2
sort (abs (loadings[,2]), decreasing = TRUE)
```

```{r}
#Rough plot.
biplot (pca, display = 'species', scaling = 'species')
```

```{r}
#Looks at PCA axis significance

sig <- PCAsignificance (pca, axes = 14)
sig

barplot(sig[c('percentage of variance', 'broken-stick percentage'), ], beside = T, 
  xlab = 'PCA axis', ylab = 'explained variation [%]', col = c('grey', 'black'), 
  legend = TRUE)
```
```{r}
#This chunk is needed to set up for the ggplot2 plotting.

p_pca <- biplot(pca, scaling = 1, type = "none", xlab = c("PCA1"),
               ylab = c("PCA2"), xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1))

points(scores(pca, display = 'sites', choices = c(1, 2), scaling = 1),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(data_pca$site_id)])

legend("topright", legend = c(levels(as.factor(data_pca$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

#dev.off()


```


```{r}
#Setting up parameters for plotting PCA in ggplot2

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc_pca <- sites.long(p_pca, env.data = expl)

#Pull out metadata columns that you want to use.
meta_pca <- data_pca[,1:3]

#Joins metadata with site scores.
sites_loc_pca <- cbind(meta_pca, sites_loc_pca)
head(sites_loc_pca)

#Species location in ordination
species_loc_pca <- species.long(p_pca)
species_loc_pca

axis.long_pca <- axis.long(pca, choices = c(1, 2))
axis.long_pca

#these are both throwing zeros - One I won't need because I'm not plotting species vectors.
#trying something from here. https://tem11010.github.io/Plotting-PCAs/
# env_loc_pca <- as.data.frame(pca$biplot[,1:2])
vscores <- as.data.frame(pca$CA$v)
```



```{r}
#Changing row names for nice plotting - careful as order matters.
row.names(vscores) <- c("T",
                        "S",
                        "\u394\u3C1", 
                        "NO\u2083\u207B+NO\u2082\u207B ",
                        "Secchi")
```

```{r}
#Creates summary so I can pull out axis contribution for auto plotting in ggplot - probably a better way to do this as the scores are listed in one of the above chunk outputs, but I couldn't figure it out and I adapted it from my RDA script
pca_axis <- summary(pca)
pca_axis
```

```{r}
#This plots point color as month and site ID as shape.

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, fill = as.factor(month),
                                   shape = site_id, stroke = 1.5), 
             size = 7, color = "black", alpha = 1) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'darkgray', size = 1) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                      label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 9,
                  fontface = "bold",
                  color = "black") +
  labs(x = paste("PCA 1 (", format(100 *pca_axis$cont[[1]][2,1],
                                   digits = 3), "%)", sep = ""),
       y = paste("PCA 2 (", format(100 *pca_axis$cont[[1]][2,2],
                                   digits = 2), "%)", sep = "")) +
 
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 26)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

# ggsave(here("figures_pca", "pca_2023-03-15.png"),
#        width = 10, height = 7, dpi = 300)
```


