---
title: "pca_environemtal_data"
output: html_notebook
---

Running PCA and cluster analysis on environmental variables.
```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(cluster)
library(ggdendro)
library(RColorBrewer)
library(indicspecies)
library(factoextra)
library(zoo)
```


```{r}
#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
data <- read_csv(here("outputs", "ctd_all_2023-03-30_fwi3.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-08-04.csv"))

data <- data %>% 
  left_join(chl)

riv <- read_csv(here("files", "river.csv")) 

lk_wind <- read_csv(here("files", "wind_lookout.csv"))

lk_par <- read_csv(here("files", "lookout_par.csv"))

up <- read_csv(here("files", "upwell.csv"))

div <- read_csv(here("outputs", "diversity.csv"))

clust_bio <- read_csv(here("outputs", "bio_clust.csv"))

```

```{r}
riv <- riv %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_w <- riv %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_w <- riv_w %>% 
  select(date, Wan_b1)
```

```{r}
lk_wind2 <- lk_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

lk_da <- lk_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, dm_w, dm_wd, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par <- lk_par %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par <- par %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA)) %>% 
  select(date, par_b1)
  
```

```{r}
up_dm <- up %>% 
  select(date = time, upwelling_index) %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_up = mean(upwelling_index)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(up_b1 = rollmeanr(lag(dm_up, 1), k = 3, fill = NA)) %>% 
  select(date, dm_up, up_b1)
```

```{r}
up_dm %>%
  filter(date < "2021-01-01") %>% 
  ggplot(aes(x = date, y = up_b1)) +
  geom_line()
```
```{r}
up_dm %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  group_by(year, month) %>% 
  summarise(mm = mean(dm_up, na.rm = T)) %>% 
  ungroup() %>% 
  filter(year < 2021) %>% 
  ggplot(aes(x = as.factor(month), y = mm, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge")
```


```{r}
lk_da %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  group_by(year, month) %>% 
  summarise(mm = mean(dm_w, na.rm = T)) %>% 
  ungroup() %>% 
  filter(year < 2021) %>% 
  ggplot(aes(x = as.factor(month), y = mm, fill = as.factor(year))) +
  geom_bar(stat = "identity") +
  facet_grid(. ~ year)

```

```{r}
data_long <- data %>% 
  select(date, site_id, temp = temp_dm, sal = sal_dm, dr = delta_rho_dm,
         no2 = no2_dm) %>% 
  pivot_longer(c(temp:no2), values_to = "val", names_to = "param")
```


```{r}
f1 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "DFO2" & param == "temp") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("Temp (5m)") +
  ylim(6, 18) +
  ggtitle("Fjord") +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f2 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "KC10" & param == "temp") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("Temp (5m)") +
  ylim(6, 18) +
  ggtitle("Channel") +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f3 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "QCS01" & param == "temp") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("Temp (5m)") +
  ylim(6, 18) +
  ggtitle("Shelf") +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f4 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "DFO2" & param == "sal") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("Sal 5m") +
  coord_cartesian(ylim = c(26.5, 32.5)) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f5 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "KC10" & param == "sal") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("Sal 5m") +
  coord_cartesian(ylim = c(26.5, 32.5)) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f6 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "QCS01" & param == "sal") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("Sal 5m") +
  coord_cartesian(ylim = c(26.5, 32.5)) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f7 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "DFO2" & param == "no2") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("NO\u2083\u207B+NO\u2082\u207B\u0020\u0028\u00B5mol\u0020L\u207B\u00B9\u0029") +
  ylim(0, 22) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f8 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "KC10" & param == "no2") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("NO\u2083\u207B+NO\u2082\u207B\u0020\u0028\u00B5mol\u0020L\u207B\u00B9\u0029") +
  ylim(0, 22) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

f9 <- data_long %>% 
  filter(date < "2021-01-01" & site_id == "QCS01" & param == "no2") %>%
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = date, y = val, color = as.factor(year))) +
  geom_line(size = 2) +
  geom_point(pch = 21, fill = "white", stroke = 1.5, size = 2) +
  scale_color_brewer(palette = "Dark2") +
  ylab("NO\u2083\u207B+NO\u2082\u207B\u0020\u0028\u00B5mol\u0020L\u207B\u00B9\u0029") +
  ylim(0, 22) +
  scale_x_date(limits = as.Date(c("2018-01-01", "2021-01-01"))) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 25),
        axis.text = element_text(color = 'black'))

fig <- (f1 + f2 + f3) / (f4 + f5 + f6) / (f7 + f8 + f9) 

ggsave(here("figures_pca", "timeseries.png"), fig,
       width = 16, height = 10, dpi = 300)
```


```{r}
data <- data %>% 
  left_join(lk_da) %>% 
  left_join(par) %>%
```


```{r}
left_join(riv_w) %>% 
  left_join(chl) %>% 
  left_join(up_dm)
```


```{r}
#This just ensures that there are no exact duplicates introduced through joining. There aren't here, but it must have occured in earlier versions and I am keeping it in-case I make changes in the future.
data <- data %>% 
  distinct(date, site_id, .keep_all = TRUE)

#Removing QU39 for this worksheet
# data <- data %>%
#   filter(site_id == "KC10")
```

```{r}
# data_bio <- data %>%
#   mutate(month = lubridate::month(date)) %>% 
#   select(date, month, site_id, temp = temp_dm, sal = sal_dm, 
#          drho = delta_rho_dm, no2 = no2_dm, sio2 = sio2_dm, po4 = po4_dm,
#          secchi = secchi_depth, fwc = fwc_dm, lk_wd, par_b1, tchla, Wan_b1)
#          
# data_bio <- data_bio %>% 
#   left_join(clust_bio) %>% 
#   relocate(cluster, .after = site_id) %>% 
#   select(-(sample_name:location))
# 
# data_bio_long <- data_bio %>% 
#   drop_na() %>% 
#   pivot_longer(c(temp:Wan_b1), names_to = "parameters", values_to = "values")
# 
# data_bio_long %>% 
#   ggplot(aes(x = as.factor(cluster), y = values)) +
#   geom_bar(stat = "summary") +
#   facet_wrap(~ parameters, scales = "free_y")
```  
  




```{r}
#selecting data I am going to use with the PCA - I think a case could be made to only include sio@ as this is what comes out as a driver in RDA and also, they all point in the same direction and have the same strength in PCA biplot.
data_pca <- data %>%
  mutate(month = lubridate::month(date)) %>% 
  select(date, month, site_id, temp = temp_dm, sal = sal_dm, 
         drho = delta_rho_dm, no2 = no2_dm, po4_dm, sio2_dm, Wan_b1)
         
         # , sio2 = sio2_dm, po4 = po4_dm
         # secchi = secchi_depth)
         
         # fwc = fwc_dm)

# lk_wd, par_b1, tchla, Wan_b1 

#Changing site_id to location 
data_pca <- data_pca %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) %>% 
  relocate(location, .after = site_id)
```


```{r}
#Working with nitrate ratios - Strom et al. (2006): 

# "In addition, samples with nitrate concentrations <0.5 μM (primarily from July) were excluded from all N:P slope calculations. Below 0.5 μM, phosphate use was not associated with measurable changes in nitrate, indicating that phytoplankton production was fueled entirely by regenerated N at these times."

#Removing NA's for analysis (currently only 1)
data_pca <- data_pca %>%
  drop_na()

# data_pca <- data_pca %>%
#   select(-sio2, -po4)
# 
# data_pca[data_pca == Inf] <- 0

#Pulling out explanatory variables - not inlcuding ratio
expl <- data_pca[, 5:11]
```


```{r}
#Scaling data being used for PCA (Should look into whether I should also center as I did with the mantel tests)
expl <- scale(expl)

#Converting to a data frame for subsequent analysis.
expl <- as.data.frame(expl)

```


```{r}
#Running PCA using vegan - when RDA is run without response variables, then it is a PCA
pca <- rda(expl)

#Looking at results - for interpretation of following look at.
head(summary(pca))

#Looking at scores
loadings <- scores (pca, display = 'species', scaling = 0)
loadings
```


```{r}
#Looking at the variables with highest correlation with axis 1
sort (abs (loadings[,1]), decreasing = TRUE)
```
```{r}
#Looking at the variables with highest correlation with axis 2
sort (abs (loadings[,2]), decreasing = TRUE)
```


```{r}
biplot (pca, display = 'species', scaling = 'species')
```

```{r}
#Looking at different scalings
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR2/cleanplot.pca.R')
par (mfrow = c(1,2))
cleanplot.pca (pca, scaling = 1)
cleanplot.pca (pca, scaling = 2)
```

```{r}
#Looking into importance of each axis

# define "evplot" function first:
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR1/evplot.R')

# Finally, in the PCA object select the component $eig with the vector of eigenvalues:
ev <- pca$CA$eig

evplot (ev)
```


```{r}
library (BiodiversityR)
sig <- PCAsignificance (pca, axes = 14)
sig

barplot(sig[c('percentage of variance', 'broken-stick percentage'), ], beside = T, 
  xlab = 'PCA axis', ylab = 'explained variation [%]', col = c('grey', 'black'), 
  legend = TRUE)
```


```{r}
#Trying the same thing, but bringing in arrows from previous plot - trying scaling 2
#pdf(file = "rda_s2.pdf", width = 6.5, height = 5, pointsize = 2)

p_pca <- biplot(pca, scaling = 1, type = "none", xlab = c("PCA1"),
               ylab = c("PCA2"), xlim = c(-0.01, 0.1), ylim = c(-1.1, 1.1))

# points(rda.signif, display = 'sites', pch = 21, cex = 2.2,
#        col = rgb(red = 1, green = 1, blue = 1, alpha = 0.5), scaling = 2,
#        bg = bg[eco])

points(scores(pca, display = 'sites', choices = c(1, 2), scaling = 1),
       pch = 21, cex = 2.0,
       bg = c("blue", "springgreen4", "black", "magenta")[as.factor(data_pca$site_id)])

#So since distance doesn't matter, I can make arrows longer with scaling 2? 
# arrows(0,0, scores(rda.signif, display = "species", choices = c(1),
#                    scaling = 1), scores(rda.signif, display = "species",
#                                             choices = c(2), scaling = 1),
#        col = "black", length = 0)

# text(pca, scaling = 1, display = "bp", col = "blue",cex = 0.8, font = 2)

# text(scores(rda.signif, display = "species", choices = c(1), scaling = 1),
#      scores(rda.signif, display = "species", choices = c(2), scaling = 1),
#      labels = rownames(scores(rda.signif, display = "species", scaling = 1)),
#      col = "black", cex = 0.8, font = 2)


# legend("topleft", legend = levels(eco), bty ="n", col="gray32", pch = 21,
#        cex = 1.5, pt.bg = bg)

legend("topright", legend = c(levels(as.factor(data_pca$site_id))),
       pch = 21,
       pt.bg = c("blue", "springgreen4", "black", "magenta"),
       bty = "n", cex = 1.5)

#dev.off()


```

```{r}

data_pca <- data_pca %>%
  mutate(season = case_when(month == 12 | month == 1 | month == 2 ~ "winter",
                            month >= 3 & month <= 5 ~ "spring",
                            month >= 6 & month <= 8 ~ "summer",
                            month >= 9 & month <= 12 ~ "autumn",)) %>%
  relocate(season, .after = month)    
  
#I want to push December from each year to winter of the next year
data_pca <- data_pca %>%
  mutate(year = lubridate::year(date)) %>%  
  mutate(year = case_when(season == "winter" & month == 12 ~ year+1,
                           TRUE ~ as.numeric(year)))
```

```{r}
#Setting up parameters for plotting PCA

# https://programmer.ink/think/r-redundancy-analysis-rda-ggplot2.html
# https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html

#Extracting site locations
sites_loc_pca <- sites.long(p_pca, env.data = expl)
meta_pca <- data_pca[,1:5]
sites_loc_pca <- cbind(meta_pca, sites_loc_pca)
head(sites_loc_pca)
sites_loc_pca <- sites_loc_pca %>% 
  mutate(year = lubridate::year(date))

#Species location in ordination
species_loc_pca <- species.long(p_pca)
species_loc_pca

axis.long_pca <- axis.long(pca, choices = c(1, 2))
axis.long_pca

#these are both throwing zeros - One I won't need because I'm not plotting species vectors.
#trying something from here. https://tem11010.github.io/Plotting-PCAs/
# env_loc_pca <- as.data.frame(pca$biplot[,1:2])
vscores <- as.data.frame(pca$CA$v)
```

```{r}
#Order locations from fjord to shelf
order_loc <- c("F", "C", "S")

#Chemtax - Specify order of phyto groups for figures
sites_loc_pca <- arrange(mutate(sites_loc_pca,
                         location = factor(location, levels = order_loc)))

#Order locations from fjord to shelf
order_loc_seas <- c("winter", "spring", "summer", "autumn")

#Chemtax - Specify order of phyto groups for figures
sites_loc_pca <- arrange(mutate(sites_loc_pca,
                         season = factor(season, levels = order_loc_seas)))
```

```{r}
#Plotting PCA.

# sp_loc_pca <-  as.data.frame(pca$species[,1:2])

# row.names(vscores) <- c("T",
#                         "S",
#                         "\u394\u3C1", 
#                         "NO\u2083\u207B+NO\u2082\u207B ",
#                         "Secchi")


ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, fill = as.factor(year),
                                   shape = location, stroke = 1.5), 
             size = 7, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "Spectral") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.2) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                      label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 9,
                  fontface = "bold",
                  color = "black") +
  labs(x = "PCA1 (48%)",
       y = "PCA2 (21%)") +
  # xlim(-0.75, 0.8) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 26)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

# ggsave(here("figures_pca", "pca_2023-03-27_all_data_2_fwc_KC10.png"),
#        width = 10, height = 7, dpi = 300)
```

```{r}
#Plotting PCA.

# sp_loc_pca <-  as.data.frame(pca$species[,1:2])

p1 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, fill = as.factor(month),
                                   shape = location, stroke = 1.5), 
             size = 6, color = "gray", alpha = 0.9) +
  scale_fill_brewer(palette = "RdYlBu") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'darkgray', size = 1) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (47%)",
       y = "PCA2 (33%)") +
  # xlim(-1.0, 1.3) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.7),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Month", shape = "Station")

p2 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, 
                                       fill = as.factor(year), 
                                       shape = location, stroke = 1.5), 
             size = 6, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "Dark2") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'darkgray', size = 1) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (47%)",
       y = "PCA2 (33%)") +
  # xlim(-1.0, 1.3) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.85),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  labs(fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")
  

fig <- p1/p2

# ggsave(here("figures_pca", "pca_year_2023-03-27_fwc.png"), fig,
#        width = 10, height = 14, dpi = 300)
```


```{r}
hc <- expl

# hc <- scale(hc)

metadata <- data_pca %>%
  select(location, site_id, date) %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE) %>% 
  relocate(sample_name, .before = date)

#Creating a list of rownames
# labs_list <- labs$sample_name
labs_list <- metadata$sample_name


#Making the rownames of the clustering matrix the ones specified in the above list.
rownames(hc) <- labs_list
```


```{r}

#Performing hierarchical clustering

#Calculating Bray-Curtis Distances
dis <- dist(hc, method = "euclidean")

#Applying average linkage hierarchical clustering
cluster.average <- hclust(dis, "ward.D2")

```

```{r}
#Looking at tests to derive cluster number - turning off for now because adds time.
fviz_nbclust(hc, FUN = hcut, method = "wss")
fviz_nbclust(hc, FUN = hcut, method = "silhouette")
gap_stat <- clusGap(hc, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)
```


```{r}
#This step sets clusters. Currently, set to three. Not fully supported by silhouette plot, but does make sense considering the data.

k <- 5
clust <- cutree(cluster.average, k = k)

clust.df <- data.frame(label = rownames(hc),
                                   cluster = factor(clust))

write_csv(clust.df, here("outputs", "pca_clusters_2023-04-18.csv"))
```

```{r}
#I want to export the clusters so that I can work with them in indicator analysis.

```



```{r}
# extract dendrogram segment data for plotting

dend <- as.dendrogram(cluster.average)
dendrogram_data <- dendro_data(dend)
dendrogram_segments <- dendrogram_data$segments 
```

```{r}
#Creating metadata sheet with 
# metadata <- micro_piv %>% 
#   select(site_id, date)

# metadata <- micro_piv %>% 
#    select(sample_name, site_id, date)

#Making unique labels by combining site and date into single string
# metadata <- metadata %>% 
#   unite(sample_name, c(site_id, date), sep = "_", remove = FALSE)

# get terminal dendrogram segments and join with names.
dendrogram_ends <- dendrogram_segments %>%
 filter(yend == 0) %>% 
 left_join(dendrogram_data$labels, by = "x") %>% 
 rename(sample_name = label) %>% 
 left_join(metadata, by = "sample_name") 

```

```{r}
#This is used to draw cluster boxes around the dendrogram clusters in the plot. Not currently using clusters so have turned off, but necessary if using clusters.

dendrogram_data[["labels"]] <- merge(dendrogram_data[["labels"]], clust.df, by = "label")
rect <- aggregate(x~cluster, label(dendrogram_data), range)
rect <- data.frame(rect$cluster, rect$x)
ymax <- mean(cluster.average$height[length(cluster.average$height) - ((k-2):(k-1))])
```


```{r}
#I'm not 100% sure how this all works, but it does - sets up colors for the sites for plotting with dendrogram.

# Generate custom color palette for dendrogram ends based on metadata variable - Site
unique_vars <- levels(factor(dendrogram_ends$site_id)) %>% 
  as.data.frame() %>% 
  rownames_to_column("row_id")

# count number of unique variables
color_count <- length(unique(unique_vars$.))

# get RColorBrewer palette
get_palette <- colorRampPalette(brewer.pal(n = 3, name = "Set1"))

# produce RColorBrewer palette based on number of unique variables in metadata:
palette <- get_palette(color_count) %>% 
 as.data.frame() %>%
 rename("color" = ".") %>%
 rownames_to_column(var = "row_id")

color_list <- left_join(unique_vars, palette, by = "row_id") %>%
 select(-row_id)

site_color <- as.character(color_list$color)
names(site_color) <- color_list$.
```

```{r}
#Plotting dendrogram - saving for incorporation later.
ggplot() +
 geom_segment(data = dendrogram_segments, 
              aes(x = x, y = y, xend = xend, yend = yend)) +
 geom_segment(data = dendrogram_ends, aes(x = x, y = y.x, xend = xend,
                                          yend = yend, color = site_id),
              size = 2) +
 geom_text(data = dendrogram_ends, aes(x = x, y = y.y, label = sample_name,
                                       color = site_id),
           hjust = 0, angle = 0, size = 6) +
 geom_rect(data = rect, aes(xmin = X1 - .3, xmax = X2 + .3, ymin = 0, ymax = ymax),
            color = "black", fill = NA, size = 0.8) +
 scale_color_manual(values = site_color) +
 scale_y_reverse(limits = c(20, -5)) +
 coord_flip() +
 theme_bw() +
 theme(legend.position = "none",
       axis.title.x = element_blank(),
       axis.title.y = element_blank(),
       axis.text.y = element_blank(),
       text = element_text(size = 30)) +
 ylab("Distance") # flipped x and y coordinates for aesthetic reasons

 
ggsave(here("figures_pca", "ward_eucl_2023-03-27_no_secchi.png"),
       width = 6, height = 12, dpi = 300)
```



```{r}
#Adding results of clustering to the pca scores for plotting

sites_loc_pca_clust <- sites_loc_pca %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

clust_df <- clust.df %>%
  rename(sample_name = label)

sites_loc_pca_clust <- sites_loc_pca_clust %>%
  left_join(clust_df) %>%
  relocate(cluster, .after = month)
```

```{r}
# #Export cluster data from inclusion in nMDS.
# write_csv(clust_df, here("outputs", "clusters_phys_2022-04-19.csv"))
# 
# #Creating separate file for merging with chemtax data.
# chem_join <- sites_loc_pca_clust %>% 
#   select(sample_name, date, site_id, location, phys_clust = cluster) %>% 
#   filter(date > "2019-01-01")
# 
# #Export cluster data from inclusion in nMDS.
# write_csv(chem_join, here("outputs", "clusters_phys_chem.csv"))

```



```{r}
#Set order for locations in plot
sites_loc_pca_clust <- arrange(mutate(sites_loc_pca_clust,
                         location = factor(location, levels = order_loc)))

#Order locations from fjord to shelf
order_loc_seas <- c("winter", "spring", "summer", "autumn")

#Chemtax - Specify order of phyto groups for figures
sites_loc_pca_clust <- arrange(mutate(sites_loc_pca_clust,
                         season = factor(season, levels = order_loc_seas)))
```


```{r}
#Plotting PCA with clusters

# sp_loc_pca <-  as.data.frame(pca$species[,1:2])

p1 <- ggplot(data = sites_loc_pca_clust, aes(x = axis1, y = axis2)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca_clust, aes(fill = as.factor(season),
                                   shape = location, stroke = 1.5), 
             size = 9, color = "darkgray", alpha = 0.9) +
  # geom_mark_hull(data = sites_loc_pca_clust, aes(color = cluster, label = cluster),
  #                concavity = 2.8, label.fontsize = 30) + 
  scale_fill_manual(values = c("dodgerblue3", "darkolivegreen", "red2", "goldenrod1")) + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (59%)",
       y = "PCA2 (27%)") +
  # xlim(-0.9, 1.1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.24),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Season", shape = "Station")

p2 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, 
                                       fill = as.factor(year), 
                                       shape = location, stroke = 1.5), 
             size = 9, color = "darkgray", alpha = 0.9) +
  scale_fill_brewer(palette = "Dark2") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (59%)",
       y = "PCA2 (27%)") +
  # xlim(-1.0, 1.3) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.85),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  labs(fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")

p3 <- ggplot(data = sites_loc_pca_clust, aes(x = axis1, y = axis2)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca_clust, aes(fill = as.factor(cluster),
                                   shape = location, stroke = 1.5), 
             size = 9, color = "darkgray", alpha = 0.9) +
  # geom_mark_hull(data = sites_loc_pca_clust, aes(color = cluster, label = cluster),
  #                concavity = 2.8, label.fontsize = 30) + 
  scale_fill_brewer(palette = "Set1") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (59%)",
       y = "PCA2 (27%)") +
  # xlim(-0.9, 1.1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        # axis.title.y = element_blank(),
        # axis.text.y = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.1),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  labs(fill = "Cluster", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)),
         shape = "none") 
  


# expand = unit(4.1, "mm"), radius = unit(4, "mm")) + 

fig <- p1 / p2 / p3
 
# ggsave(here("figures_pca", "PCA_panel_2023-03-27_no_secchi.png"), fig,
#        width = 8, height = 16, dpi = 300)
```

```{r}
#Looking at boxplot of each cluster
data_clust <- data_pca %>% 
  unite(sample_name, c(location, date), sep = "", remove = FALSE)

data_clust <- data_clust %>%
  left_join(clust_df) %>%
  relocate(cluster, .after = month)

# data_clust <- data_clust %>% 
#   mutate(n_p = no2/po4,
#          si_n = sio2/no2)
```
```{r}
data_clust_long <- data_clust %>% 
  pivot_longer(c(temp:Wan_b1), names_to = "parameters", values_to = "values")
```

```{r}
data_clust_long %>% 
  ggplot(aes(x = as.factor(cluster), y = values)) +
  geom_boxplot() +
  facet_wrap(~ parameters, scales = "free_y")
```


```{r}


hd <- 
  data_clust_long %>% 
  filter(parameters == "drho") %>% 
  ggplot(aes(x = as.factor(cluster), y = values)) +
  geom_boxplot(aes(fill = as.factor(cluster))) +
  scale_fill_brewer(palette = "Set1") +
  labs(y = bquote(Delta*rho[30-3] ~ "(kg"~ m^-3*")")) +
  theme_bw() +
  theme(
        axis.text = element_text(color = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 28))

hn <- 
  data_clust_long %>% 
  filter(parameters == "no2") %>% 
  ggplot(aes(x = as.factor(cluster), y = values)) +
  geom_boxplot(aes(fill = as.factor(cluster))) +
  scale_fill_brewer(palette = "Set1") +
  labs(y = "NO\u2083\u207B+NO\u2082\u207B\u0020\u0028\u00B5mol\u0020L\u207B\u00B9\u0029",
       x = "Cluster") +
  theme_bw() +
  theme(
        # axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(color = "black"),
        # axis.text.x = element_blank(),
        # axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 28))
  
ht <- 
  data_clust_long %>% 
  filter(parameters == "temp") %>% 
  ggplot(aes(x = as.factor(cluster), y = values)) +
  geom_boxplot(aes(fill = as.factor(cluster))) +
  scale_fill_brewer(palette = "Set1") +
  labs(y = "Temp (°C)") +
  theme_bw() +
  theme(
        # axis.title = element_text(face = "bold", colour = "black"),
        axis.text = element_text(color = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 28))

```

```{r}
check <- data_clust_long %>% 
  filter(cluster == 4)
```


```{r}
fig_panel <- (p1 + ht) / (p2 + hd) / (p3 + hn)

ggsave(here("figures_pca", "test_2023-04-19.png"), fig_panel,
       width = 15, height = 16, dpi = 300)
```



```{r}
#Stats
data_summ <- data_clust_long

data_summ[data_summ == Inf] <- 0

data_summ <- data_summ %>% 
  group_by(cluster, parameters) %>% 
  summarise(mean = mean(values),
            sdev = sd(values)) %>% 
  ungroup()
```
```{r}
data_corr <- data %>% 
  left_join(chl)

data_corr <- data_corr %>% 
  select(date, site_id, temp = temp_dm, sal = sal_dm, drho = delta_rho_dm,
         no2_dm, secchi = secchi_depth, lk_wd, par_b1, Wan_b1, tchla)

data_corr <- data_corr %>%
  drop_na()
```

```{r}
f <- data_corr %>% 
  filter(site_id == "DFO2")

f <- f %>% 
  select(temp:tchla)

c <- data_corr %>% 
  filter(site_id == "KC10")

c <- c %>% 
  select(temp:tchla)

s <- data_corr %>% 
  filter(site_id == "QCS01")

s <- s %>% 
  select(temp:tchla)
```

```{r}
#Making correlation matrix
cor_f <- round(cor(f, method = "spearman"), 2)

#Making significance' matrix
p.mat_f <- cor_pmat(f, method = "spearman")

#Making correlation matrix
cor_c <- round(cor(c, method = "spearman"), 2)

#Making significance' matrix
p.mat_c <- cor_pmat(c, method = "spearman")

#Making correlation matrix
cor_s <- round(cor(s, method = "spearman"), 2)

#Making significance' matrix
p.mat_s <- cor_pmat(s, method = "spearman")

```

```{r}
fig_f <- ggcorrplot(cor_f,
  p.mat = p.mat_f,
  method = "circle",
  type = "lower",
  sig.level = 0.05,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 3,
  outline.color = "black") +
  scale_x_discrete(labels = c("S",
                              "\u394\u3C1",
                              "NO\u2083\u207B+NO\u2082\u207B",
                                "Secchi",
                                "Wind. Dir.",
                                "PAR",
                                "Disch.",
                                "TChla")) +
  #                             "Riv_B10", 
  #                             "lk_w", 
  #                             "lk_wd",
  #                             "par_b1",
  #                             "lev",
  #                             "rain",
  #                             "lev_b1",
  #                             "rain_b1",
  #                             "TChla",
  #                             "Diat.")) +
  scale_y_discrete(labels = c("T",
                                "S",
                                "\u394\u3C1",
                                "NO\u2083\u207B+NO\u2082\u207B",
                                "Secchi",
                                "Wind. Dir.",
                                "PAR",
                                "Disch.",
                                "TChla")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Fjord") +
  theme_bw() +
  theme(text = element_text(size = 25, color = "black"),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2, color = "black"),
        # axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")

# ggsave(here("figures_good", "corr_kc10_full_year2_844_rain.png"),
#        width = 8, height = 8, dpi = 300)
```

```{r}
fig_c <- ggcorrplot(cor_c,
  p.mat = p.mat_c,
  method = "circle",
  type = "lower",
  sig.level = 0.05,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 3,
  outline.color = "black") +
  scale_x_discrete(labels = c("S",
                              "\u394\u3C1",
                              "NO\u2083\u207B+NO\u2082\u207B",
                                "Secchi",
                                "Wind. Dir.",
                                "PAR",
                                "Disch.",
                                "TChla")) +
  #                             "Riv_B10", 
  #                             "lk_w", 
  #                             "lk_wd",
  #                             "par_b1",
  #                             "lev",
  #                             "rain",
  #                             "lev_b1",
  #                             "rain_b1",
  #                             "TChla",
  #                             "Diat.")) +
  scale_y_discrete(labels = c("T",
                                "S",
                                "\u394\u3C1",
                                "NO\u2083\u207B+NO\u2082\u207B",
                                "Secchi",
                                "Wind. Dir.",
                                "PAR",
                                "Disch.",
                                "TChla")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Channel") +
  theme_bw() +
  theme(text = element_text(size = 25, color = "black"),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2, color = "black"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")

# ggsave(here("figures_good", "corr_kc10_full_year2_844_rain.png"),
#        width = 8, height = 8, dpi = 300)
```


```{r}
fig_s <- ggcorrplot(cor_s,
  p.mat = p.mat_c,
  method = "circle",
  type = "lower",
  sig.level = 0.05,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 3,
  outline.color = "black") +
  scale_x_discrete(labels = c("S",
                              "\u394\u3C1",
                              "NO\u2083\u207B+NO\u2082\u207B",
                                "Secchi",
                                "Wind. Dir.",
                                "PAR",
                                "Disch.",
                                "TChla")) +
  #                             "Riv_B10", 
  #                             "lk_w", 
  #                             "lk_wd",
  #                             "par_b1",
  #                             "lev",
  #                             "rain",
  #                             "lev_b1",
  #                             "rain_b1",
  #                             "TChla",
  #                             "Diat.")) +
  scale_y_discrete(labels = c("T",
                                "S",
                                "\u394\u3C1",
                                "NO\u2083\u207B+NO\u2082\u207B",
                                "Secchi",
                                "Wind. Dir.",
                                "PAR",
                                "Disch.",
                                "TChla")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Shelf") +
  theme_bw() +
  theme(text = element_text(size = 25, color = "black"),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2, color = "black"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")

# ggsave(here("figures_good", "corr_kc10_full_year2_844_rain.png"),
#        width = 8, height = 8, dpi = 300)
```

```{r}
fig <- fig_f + fig_c + fig_s

ggsave(here("figures_pca", "corr_spearman.png"), fig,
       width = 10, height = 5, dpi = 300)
```
```{r}
pca1 <- ggplot(data = sites_loc_pca_clust, aes(x = axis1, y = axis2)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca_clust, aes(fill = as.factor(season),
                                   shape = location, stroke = 1.5), 
             size = 7, color = "black", alpha = 0.9) +
  # geom_mark_hull(data = sites_loc_pca_clust, aes(color = cluster, label = cluster),
  #                concavity = 2.8, label.fontsize = 30) + 
  scale_fill_brewer(palette = "Spectral") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (52%)",
       y = "PCA2 (27%)") +
  # xlim(-0.9, 1.1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.24),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  guides(fill = guide_legend(override.aes = list(shape = 21))) +
  labs(fill = "Season", shape = "Station")

pca2 <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) + 
  geom_point(data = sites_loc_pca, aes(x = axis1, y = axis2, 
                                       fill = as.factor(year), 
                                       shape = location, stroke = 1.5), 
             size = 7, color = "black", alpha = 0.9) +
  scale_fill_brewer(palette = "Dark2") + 
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  # geom_text(data = vscores, aes(x = PC1, y = PC2, label = rownames(vscores)),
  #           col = 'red') +
  geom_segment(data = vscores, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(length = unit(0.2,"cm")),
               alpha = 1, color = 'black', size = 1.5) +
  geom_text_repel(data = vscores, aes(PC1, PC2,
                                           label = row.names(vscores)),
                  box.padding = unit(0.3, 'lines'),
                  # point.padding = NA,
                  point.padding = unit(2, 'lines'),
                  segment.color = 'blue',
                  # segment.size = 0.5,
                  # segment.alpha = 0.4,
                  # arrow = arrow(length = unit(0.01, 'npc')),
                  # nudge_y = -0.02,
                  # nudge_x = 0.1,
                  force = 0.1,
                  max.iter = 3e3,
                  size = 8,
                  color = "black") +
  labs(x = "PCA1 (52%)",
       y = "PCA2 (27%)") +
  # xlim(-1.0, 1.3) +
  # labs(x = paste("PCA 1 (", format(100 *pca$cont[[1]][2,1],
  #                                  digits = 3), "%)", sep = ""),
  #      y = paste("PCA 2 (", format(100 *pca$cont[[1]][2,2], 
  #                                  digits = 2), "%)", sep = "")) +
 
  # coord_fixed(ratio = 1) +
  theme_bw() +
  theme(axis.title = element_text(face = "bold", colour = "black"),
        # axis.text.x = element_blank(),
        # axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        legend.title = element_text(face = "bold", colour = "black"), 
        legend.text = element_text(colour = "black"),
        # legend.position = c(0.9, 0.85),
        legend.margin = margin(-0.3, 0, 0, 0, unit = "cm"),
        text = element_text(size = 24)) +
  labs(fill = "Year") +
  guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")
```



```{r}
fig2 <- pca1 / pca2

ggsave(here("figures_pca", "pca_long.png"), fig2,
       width = 9, height = 12, dpi = 300)
```

```{r}
data_corr %>% 
  mutate(year = lubridate::year(date)) %>% 
  ggplot(aes(x = secchi, y = Wan_b1, fill = as.factor(year), shape = site_id)) +
  geom_point(size = 2) +
  scale_shape_manual(values = c(21, 22, 23 ,24)) + 
  theme_bw() +
    guides(fill = guide_legend(override.aes = list(shape = 21)),
         color = "none",
         shape = "none")
```

```{r}
#Upload data

#Upload data from my master data standardization sheet
micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

#Uploading size separated S.marinoi counts.
# sm_size <- read_csv(here("outputs", "s_mar_size.csv"))
```

```{r}
#Removing Station QU39
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
#Adding location instead of site ID.
micro <- micro %>% 
    mutate(location = case_when(site_id == "DFO2" ~ "F",
                              site_id == "KC10" ~ "C",
                              site_id == "QCS01" ~ "S",
                              TRUE ~ as.character(site_id))) 
```


```{r}
#Creating a list of distinct species and groups
species_distinct <- micro %>% 
  distinct(group, scientificName)

#Removing groups that are not well quantified or that I am not looking at
micro <- micro %>% 
  filter(!scientificName_accepted == "Cyanobacteria")
         
         
         
         # &
         #   !group == "Metazoa" &
         #   !group == "Protozoa" &
         #   !group == "Choanoflagellata" &
         #   !group == "Ciliophora" &
         #   !group == "Kinetoplastidea")

```

```{r}
micro_n <- micro %>% 
  distinct(date, site_id)


#Determining species that are present in > 10% of samples.
species_10 <- micro %>% 
  group_by(scientificName) %>% 
  summarise(n_obs = n()) %>%
  ungroup() %>% 
  mutate(perc_obs = n_obs/78) %>% 
  filter(perc_obs >= 0.10)

#Creating a list of species in > 10% of samples.
species_10_list <- species_10$scientificName

#Removing species that are not present in > 10% of samples.
micro <- micro %>% 
  filter(scientificName %in% species_10_list)

```

```{r}
micro <- micro %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>% 
  relocate(year, .after = date) %>% 
  relocate(month, .after = year)
```

```{r}
#Creating separate sheets for just diatoms and dinoflagellates
# micro_diat <- micro %>% 
#   filter(class == "Bacillariophyceae")
# 
# micro_dino <- micro %>% 
#   filter(class == "Dinophyceae")
```

```{r}
#Preparing data for nMDS analysis - needs to be in wide matrix.

#Selecting columns - all species
micro_piv <- micro %>% 
  select(date, month, location, scientificName, species_sum)

# micro_piv_diat <- micro_diat %>% 
#   select(date, month, location, scientificName, species_sum)
# 
# micro_piv_dino <- micro_dino %>% 
#   select(date, month, location, scientificName, species_sum)

#pivoting wider so species are columns. 
micro_piv <- micro_piv %>% 
  pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
  mutate_if(is.numeric, ~ replace_na(., 0))

#Diatoms
# micro_piv_diat <- micro_piv_diat %>% 
#   pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0))
# 
# #Dinoflagellates
# micro_piv_dino <- micro_piv_dino %>% 
#   pivot_wider(names_from = scientificName, values_from = species_sum) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0))


#Adding year to wide format for plotting
micro_piv <- micro_piv %>% 
  mutate(year = lubridate::year(date)) %>% 
  relocate(year, .before = month)

#Diatoms
# micro_piv_diat <- micro_piv_diat %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   relocate(year, .before = month)
# 
# #Dinoflaggelates
# micro_piv_dino <- micro_piv_dino %>% 
#   mutate(year = lubridate::year(date)) %>% 
#   relocate(year, .before = month)
```

```{r}
data_clust_2 <- data_clust %>% 
  select(date, location, cluster)

micro_piv <- micro_piv %>% 
  left_join(data_clust_2) %>% 
  relocate(cluster, .after = location) 

#Quite a few samples don't have a cluster - 7 - why?
#Separating
no_clust <- micro_piv %>% 
  filter(is.na(cluster))

#Filtering ctd data to see if it is because of missing variables
#Creating date list to filter with
date_list <- no_clust$date

#Filter ctd data for dates
no_clust_ctd <- data %>% 
  filter(date %in% date_list) %>% 
  select(date, site_id, temp_dm, sal_dm, no2_dm, delta_rho_dm, secchi_depth)

#4 files out of 7 came out of CTD/nutrient search
#3 are due to secchi depth - secchi didn't seem to be collected. 
#Can I use PAR or Turbidity - ugh so tough! Shame to lose these three points.
#1 is due to delta-rho - profile didn't start until 4m depth. This can be rectified because there were two casts and only one started a 4m. Must have thrown an NA when averaging - FIX
#2 Are somewhat important summer samples

#Look into secchi depths

#3 dates not in ctd file
#2018-11-22-fjord. - winter, not a huge deal.
#2019-11-28-Shelf - winter, not a huge deal.
#2020-06-04-Channel - why no CTD here

# %>% 
#   filter(!is.na(cluster))

micro_piv_clust <- micro_piv %>% 
  left_join(data_clust_2) %>% 
  relocate(cluster, .after = location) %>% 
  filter(!is.na(cluster))

# micro_piv_dino <- micro_piv_dino %>% 
#   left_join(data_clust_2) %>% 
#   relocate(cluster, .after = location) %>% 
#   filter(!is.na(cluster))
```


```{r}
#Pulling out species counts for transform and input into clustering and NMDS
species <- micro_piv_clust[, 6:ncol(micro_piv_clust)]

#Diatoms
# species_diat <- micro_piv_diat[, 6:ncol(micro_piv_diat)]

#Dinoflagellates
# species_dino <- micro_piv_dino[, 6:ncol(micro_piv_dino)]

transform <- log1p(species)

# transform <- decostand(species, method = "total")

# transform <- sqrt(transform)
```


```{r}
#Creating relative abundance matrix 
# transform <- decostand(species, method = "total")
# 
# transform_diat <- decostand(species_diat, method = "total")
# 
# transform_dino <- decostand(species_dino, method = "total")
# 
# transform <- sqrt(transform)
# 
# #Diatoms
# transform_diat <- sqrt(transform_diat)
# 
# #Dinoflagellates
# transform_dino <- sqrt(transform_dino)

#Performing square root transformation
# transform <- log10(transform + 1)
# 
# #Diatoms
# transform_diat <- log10(transform_diat + 1)
# 
# #Dinoflagellates
# transform_dino <- log10(transform_dino + 1)
```

```{r}
clust <- micro_piv_clust$cluster
clust_site <- micro_piv_clust$location

# clust_diat <- micro_piv_diat$cluster
# clust_dino <- micro_piv_dino$cluster

```

```{r}
#ANOSIM test to see if groupings statistically significant 

# By Station
ano_clust = anosim(transform, clust, distance = "bray", permutations = 9999)
ano_clust
# 
# ano_clust_diat = anosim(transform_diat, clust, distance = "bray", permutations = 9999)
# ano_clust_diat
# 
# ano_clust_dino = anosim(transform_dino, clust, distance = "bray", permutations = 9999)
# ano_clust_dino

```


```{r}
#Not working...

inv_clust = multipatt(transform, clust, func = "r.g", duleg = F,
                       control = how(nperm = 9999))

summary(inv_clust, indvalcomp = TRUE)

```

```{r}
phy_clust_div <- data_clust %>% 
  select(date, site_id, cluster) %>% 
  left_join(div)

div_stat <- phy_clust_div %>% 
  filter(!is.na(div)) %>% 
  group_by(cluster) %>% 
  summarise(mean_div = mean(div))
```

