---
title: "pca_environemtal_data"
output: html_notebook
---

Running PCA and cluster analysis on environmental variables.
```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)
library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)
library(patchwork)
library(cluster)
library(ggdendro)
library(RColorBrewer)
library(indicspecies)
library(factoextra)
library(ggcorrplot)
library(zoo)
library(gsw)
```


```{r}
ctd <- read_csv(here("outputs", "ctd_all_2022-11-25.csv"))

micro <- read_csv(here("outputs", "micro_all_2022-11-25.csv")) 

dis_wan <- read_csv(here("files", "river.csv")) 

wind_lo <- read_csv(here("files", "wind_lookout.csv"))

par_lo <- read_csv(here("files", "lookout_par.csv"))

rain_bux <- read_csv(here("files", "buxton_rain.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))
```

```{r}
dis_wan <- dis_wan %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

dis_wan_calc <- dis_wan %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA))

dis_wan_join <- dis_wan_calc %>% 
  select(date, Wan_b1)
```



```{r}
wind_lo <- wind_lo %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

wind_lo_calc <- wind_lo %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA))
  
wind_lo_join <- wind_lo_calc %>%  
  select(date, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par_lo <- par_lo %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par_lo_calc <- par_lo %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA))  

par_lo_join <- par_lo_calc %>%  
  select(date, par_b1)
  
```

```{r}
rain_bux <- rain_bux %>%
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, rain = Rain) %>% 
  filter(year > 2017 & year < 2022)

rain_bux_calc <- rain_bux %>%
  mutate(rain_b1 = rollmeanr(lag(rain, 1), k = 10, fill = NA))


rain_bux_join <- rain_bux_calc %>% 
  select(date, rain)
```

```{r}
data <- ctd %>% 
  left_join(dis_wan_join) %>% 
  left_join(wind_lo_join) %>% 
  left_join(par_lo_join) %>% 
  left_join(rain_bux_join)
```

```{r}
data_corr <- data %>% 
  select(date,
         site_id,
         temp = temp_dm, 
         sal = sal_dm, 
         delta_rho = delta_rho_dm, 
         no2_no3_um = no2_dm, 
         sio2 = sio2_dm, 
         po4 = po4_dm,
         secchi = secchi_depth,
         Wan_b1,
         rain,
         # Bel_b1,
         # eth_w, eth_wd, 
         lk_w, 
         lk_wd,
         par_b1)
```

```{r}
diatom_sum <- micro %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(diat. = sum(species_sum)) %>% 
  ungroup()

chl_join <- chl %>% 
  select(date, site_id, TChla = tchla)

```

```{r}
phyto <- chl_join %>% 
  left_join(diatom_sum)
```
```{r}
data_corr <- data_corr %>% 
  left_join(phyto) 
```

```{r}
# data_corr_na <- data_corr %>%
#   drop_na()

data_corr_fjord <- data_corr %>% 
  filter(site_id == "DFO2") %>% 
  select(-site_id)

data_corr_channel <- data_corr %>% 
  filter(site_id == "KC10") %>% 
  select(-site_id)

data_corr_shelf <- data_corr %>% 
  filter(site_id == "QCS01") %>% 
  select(-site_id) 
```

```{r}
#Creating correlogram to show link between variables
corr_fjord <- data_corr_fjord %>% 
  select(temp:diat.)
#Making correlation matrix
corr_fjord <- round(cor(na.omit(corr_fjord), method = "spearman"), 2)

#Making significance' matrix
p.mat_fjord <- cor_pmat(corr_fjord, method = "spearman", exact = FALSE)

corr_channel <- data_corr_channel %>% 
  select(temp:diat.)
#Making correlation matrix
corr_channel <- round(cor(na.omit(corr_channel), method = "spearman"), 2)

#Making significance' matrix
p.mat_channel <- cor_pmat(corr_channel, method = "spearman", exact = FALSE)

corr_shelf <- data_corr_shelf %>% 
  select(temp:diat.)
#Making correlation matrix
corr_shelf <- round(cor(na.omit(corr_shelf), method = "spearman"), 2)

#Making significance' matrix
p.mat_shelf <- cor_pmat(corr_shelf, method = "spearman", exact = FALSE)

```

```{r}
fig_fjord <- ggcorrplot(corr_fjord,
  p.mat = p.mat_fjord,
  method = "square",
  type = "lower",
  sig.level = 0.01,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 3,
  outline.color = "black") +
  scale_x_discrete(labels = c("S", 
                              "\u394\u3C1", 
                              "NO\u2083\u207B+NO\u2082\u207B", 
                              "SiO\u2082\u207B", 
                              "PO\u2084\u207B",
                              "Secchi",
                              "Dis.",
                              "Rain",
                              "Wind", 
                              "WDir.",
                              "PAR",
                              "TChla",
                              "Diat.")) +
  scale_y_discrete(labels = c("T", 
                              "S", 
                              "\u394\u3C1", 
                              "NO\u2083\u207B+NO\u2082\u207B", 
                              "SiO\u2082\u207B", 
                              "PO\u2084\u207B", 
                              "Secchi",
                              "Dis.",
                              "Rain",
                              "Wind", 
                              "WDir.",
                              "PAR",
                              "TChla",
                              "Diat.")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Fjord") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2),
        # axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")
```

```{r}
fig_channel <- ggcorrplot(corr_channel,
  p.mat = p.mat_channel,
  method = "square",
  type = "lower",
  sig.level = 0.01,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 3,
  outline.color = "black") +
  scale_x_discrete(labels = c("S", 
                              "\u394\u3C1", 
                              "NO\u2083\u207B+NO\u2082\u207B", 
                              "SiO\u2082\u207B", 
                              "PO\u2084\u207B", 
                              "Secchi",
                              "Dis.",
                              "Rain",
                              "Wind", 
                              "WDir.",
                              "PAR",
                              "TChla",
                              "Diat.")) +
  scale_y_discrete(labels = c("T", 
                              "S", 
                              "\u394\u3C1", 
                              "NO\u2083\u207B+NO\u2082\u207B", 
                              "SiO\u2082\u207B", 
                              "PO\u2084\u207B",
                              "Secchi",
                              "Dis.",
                              "Rain",
                              "Wind", 
                              "WDir.",
                              "PAR",
                              "TChla",
                              "Diat.")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Channel") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")
```

```{r}
fig_shelf <- ggcorrplot(corr_shelf,
  p.mat = p.mat_shelf,
  method = "square",
  type = "lower",
  sig.level = 0.01,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 3,
  outline.color = "black") +
  scale_x_discrete(labels = c("S", 
                              "\u394\u3C1", 
                              "NO\u2083\u207B+NO\u2082\u207B", 
                              "SiO\u2082\u207B", 
                              "PO\u2084\u207B",
                              "Secchi",
                              "Dis.",
                              "Rain",
                              "Wind", 
                              "WDir.",
                              "PAR",
                              "TChla",
                              "Diat.")) +
  scale_y_discrete(labels = c("T", 
                              "S", 
                              "\u394\u3C1", 
                              "NO\u2083\u207B+NO\u2082\u207B", 
                              "SiO\u2082\u207B", 
                              "PO\u2084\u207B",
                              "Secchi",
                              "Dis.",
                              "Rain",
                              "Wind", 
                              "WDir.",
                              "PAR",
                              "TChla",
                              "Diat.")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Shelf") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")
```

```{r}
fig_corrs <- fig_fjord + fig_channel + fig_shelf

ggsave(here("figures_correlogram", "correlation_panel_spearman2.png"), fig_corrs,
       width = 16, height = 7, dpi = 300)
```












