---
title: "pca_environemtal_data"
output: html_notebook
---

Running PCA and cluster analysis on environmental variables.
```{r}
#Loading packages
library(tidyverse)
library(readxl)
library(here)
library(vegan)
library(adespatial)
library(ggord)
library(fuzzySim)

#From https://rstudio-pubs-static.s3.amazonaws.com/694016_e2d53d65858d4a1985616fa3855d237f.html#1_Packages_needed

#For plotting with ggplot2

library(BiodiversityR)
library(ggsci)
library(ggrepel)
library(ggforce)

library(patchwork)

library(cluster)
library(ggdendro)

library(RColorBrewer)

library(indicspecies)

library(factoextra)

library(ggcorrplot) #Correlation plots

library(zoo)

library(gsw)
```


```{r}
#Uploading datasheet with physical, nutrients, chlorophyll, microscopy and chemtax data.
micro <- read_csv(here("outputs", "micro_kc10_2021-12-01.csv"))

data_short <- read_csv(here("outputs", "ctd_merge_2021-11-04_chem.csv"))

micro_short <- read_csv(here("outputs", "micro_master_2021-10-18.csv")) 

ctd <- read_csv(here("files", "kc10_ctd.csv"))

chl <- read_csv(here("outputs", "tchla_calibration_2022-11-15.csv"))

nuts <- read_csv(here("files", "kc10_nuts.csv"))

riv <- read_csv(here("files", "river.csv")) 

riv_b <- read_csv(here("files", "riv_bella_4.csv"))

ethel_wind <- read_csv(here("files", "ethel_wind.csv"))

lk_wind <- read_csv(here("files", "wind_lookout.csv"))

lk_par <- read_csv(here("files", "lookout_par.csv"))
```

```{r}
#Removing QU39 
micro <- micro %>% 
  filter(!site_id == "QU39")
```

```{r}
ctd <- ctd %>% 
  select(date_time = `Measurement time`,
         pres = `Pressure (dbar)`,
         sal = `Salinity (PSU)`,
         temp = `Temperature (deg C)`) %>% 
  mutate(date = lubridate::date(date_time)) %>% 
  relocate(date, .after = date_time)

ctd <- ctd %>% 
  group_by(date, pres) %>% 
  summarise(temp = mean(temp),
            sal = mean(sal)) %>% 
  ungroup()

```

```{r}
#Performing GSW calculations

#Some CTD casts are missing coordinates that are required for GSW calculations. Fill the coordinates in using those from the Hakai Station Master - Latitude
ctd <- ctd %>% 
  mutate(latitude = 51.65064,
         longitude = -127.9513)
                              

#Calculating absolute salinity
SA <- gsw_SA_from_SP(ctd$sal, ctd$pres, ctd$longitude, ctd$latitude)

#Converting absolute salinity output to a dataframe
SA <- as.data.frame(SA)

#Calculating conservative temperature
CT <- gsw_CT_from_t(SA$SA, ctd$temp, ctd$pres)

#Converting conservative temperature output to a dataframe
CT <- as.data.frame(CT)

#Calculating Density
rho = gsw_rho(SA$SA, CT$CT, ctd$pres)

#Converting Density to a dataframe
rho <- as.data.frame(rho)

#Calculating Brunt-Vaisala frequency
bv <- gsw_Nsquared(SA$SA, CT$CT, ctd$pres)

#Converting Brunt-Vaisala frequency to a dataframe
bv <- bind_rows(bv)

#Adding a row at the bottom of the Brunt-Vaisala dataframe to make the vector length equal to the other calculations
bv <- bv %>% 
  add_row(N2 = NA, p_mid = NA)

#Binding calculations to ctd dataframe
ctd <- cbind(ctd, SA, CT, rho, bv)
```

```{r}
#Filter 2m data from the CTD datasheet
ctd_2 <- ctd %>% 
  filter(pres == 2) %>% 
  select(date, rho_2 = rho)

#filter 30m data
ctd_30 <- ctd %>% 
  filter(pres == 30) %>% 
  select(date, rho_30 = rho)

#joining 2m data to 3m data
ctd_dd <- ctd_2 %>% 
  left_join(ctd_30)

#Calculating difference in density
ctd_dd <- ctd_dd %>% 
  mutate(delta_rho = rho_30 - rho_2) %>% 
  select(date, delta_rho)

ctd <- ctd %>% 
  left_join(ctd_dd)
```

```{r}
ctd <- ctd %>% 
  filter(pres == 5)

nuts <- nuts %>% 
  filter(line_out_depth == 5) %>% 
  select(date, no2_no3_um, po4, sio2)

data <- ctd %>% 
  left_join(nuts)
```
```{r}
riv <- riv %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_w <- riv %>%
  mutate(Wan_b1 = rollmeanr(lag(dis, 1), k = 10, fill = NA),
         Wan_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Wan_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_w <- riv_w %>% 
  select(date, Wan_b1, Wan_b25, Wan_b40)
```

```{r}
riv_b <- riv_b %>% 
  mutate(Date = lubridate::mdy(Date))

riv_b <- riv_b %>%
  filter(PARAM == 1) %>% 
  mutate(year = lubridate::year(Date),
         month = lubridate::month(Date),
         yday = lubridate::yday(Date)) %>% 
  select(date = Date, year, month, yday, dis = Value) %>% 
  filter(year > 2017 & year < 2022)

riv_b <- riv_b %>%
  mutate(Bel_b1 = rollmeanr(lag(dis, 1), k = 5, fill = NA),
         Bel_b5 = rollmeanr(lag(dis, 5), k = 4, fill = NA),
         Bel_b10 = rollmeanr(lag(dis, 10), k = 4, fill = NA),
         Bel_b25 = rollmeanr(lag(dis, 25), k = 4, fill = NA),
         Bel_b40 = rollmeanr(lag(dis, 40), k = 4, fill = NA))

#So this is offsetting the the rolling average to one day before
riv_b <- riv_b %>% 
  select(date, Bel_b1, Bel_b5, Bel_b10, Bel_b25, Bel_b40)
```

```{r}
ethel_wind2 <- ethel_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

ew_da <- ethel_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, eth_w = w_b1, eth_wd = wd_b1)

lk_wind2 <- lk_wind %>%
  filter(WindSpd_UQL == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, WindSpd_Avg, WindDir_Avg) %>% 
  filter(year > 2017 & year < 2022)

lk_da <- lk_wind2 %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_w = mean(WindSpd_Avg),
            dm_wd = mean(WindDir_Avg)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(w_b1 = rollmeanr(lag(dm_w, 1), k = 3, fill = NA),
         wd_b1 = rollmeanr(lag(dm_wd, 1), k = 3, fill = NA)) %>% 
  select(date, lk_w = w_b1, lk_wd = wd_b1)
  
```

```{r}
par <- lk_par %>%
  filter(`1hourPAR_UQL` == 2) %>% 
  mutate(date = lubridate::mdy_hm(measurementTime),
         year = lubridate::year(date),
         month = lubridate::month(date),
         yday = lubridate::yday(date)) %>% 
  select(date, year, month, yday, par = `1hourPAR`) %>% 
  filter(year > 2017 & year < 2022)

par <- par %>% 
  mutate(date2 = lubridate::date(date)) %>% 
  group_by(date2) %>% 
  summarize(dm_par = mean(par)) %>% 
  ungroup() %>% 
  rename(date = date2) %>%
  mutate(par_b1 = rollmeanr(lag(dm_par, 1), k = 3, fill = NA)) %>% 
  select(date, par_b1)
  
```

```{r}
data <- data %>% 
  left_join(riv_w) %>% 
  left_join(riv_b) %>% 
  left_join(ew_da) %>% 
  left_join(lk_da) %>% 
  left_join(par)
```

```{r}
data_pca <- data %>% 
  select(date, temp, sal, 
         delta_rho, no2_no3_um, sio2, po4, 
         Wan_b1)

data_pca <- data_pca %>%
  drop_na()
```

```{r}


#First do the summarizing and filtering for each grouping I want correlated against.
# s_sum <- micro %>% 
#   filter(scientificName == "Skeletonema marinoi") %>% 
#   select(date, site_id, S.m. = species_sum)

d_sum <- micro %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(diat. = sum(species_sum)) %>% 
  ungroup()


chl_corr <- chl %>% 
  filter(site_id == "KC10") %>% 
  select(date, site_id, TChla = tchla)

```
```{r}
cor_exp <- chl_corr %>% 
  # left_join(s_sum) %>% 
  left_join(d_sum)
```
```{r}
data <- data_pca %>% 
  left_join(cor_exp) %>% 
  select(-site_id)
```


```{r}
#Working with nitrate ratios - Strom et al. (2006): 

# "In addition, samples with nitrate concentrations <0.5 μM (primarily from July) were excluded from all N:P slope calculations. Below 0.5 μM, phosphate use was not associated with measurable changes in nitrate, indicating that phytoplankton production was fueled entirely by regenerated N at these times."


#Trying to add n_p to see what it does to clustering
# data_corr <- data_pca %>%
#   mutate(n_p = no2/po4,
#          n_s = no2/sio2,
#          p_s = po4/sio2)

data_corr <- data %>%
  drop_na()

# data_corr <- data_corr %>%
#   rename(T = temp,
#          S = sal,
#          "\u394\u3C1" = delta_rho,
#          "NO\u2083\u207B+NO\u2082\u207B" = no2_no3_um,
#          "SiO\u2082\u207B" = sio2,
#          "PO\u2084\u207B" = po4,
#          Riv_b10 = Wan_b1)

```

```{r}
#Creating correlogram to show link between variables
data_all <- data_corr %>% 
  select(temp:diat.)
#Making correlation matrix
cor_all <- round(cor(data_all), 2)

#Making significance' matrix
p.mat_all <- cor_pmat(data_all)

```

```{r}
f_c <- ggcorrplot(cor_all,
  p.mat = p.mat_all,
  method = "square",
  type = "lower",
  sig.level = 0.05,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 4.5,
  outline.color = "black") +
  scale_x_discrete(labels = c("S", "\u394\u3C1", "NO\u2083\u207B+NO\u2082\u207B",
                        "SiO\u2082\u207B", "PO\u2084\u207B", "Riv_B10",
                        "TChla", "Diat.")) +
  scale_y_discrete(labels = c("T", "S", "\u394\u3C1", "NO\u2083\u207B+NO\u2082\u207B",
                        "SiO\u2082\u207B", "PO\u2084\u207B", "Riv_B10",
                        "TChla", "Diat.")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Channel") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2, color = "black"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")

# ggsave(here("figures_good", "corr_kc10_full_year2.png"),
#        width = 8, height = 8, dpi = 300)
```

```{r}

data_short <- data_short %>% 
  left_join(riv_w) %>% 
  left_join(riv_b) %>% 
  left_join(ew_da) %>% 
  left_join(lk_da) %>% 
  left_join(par)
```

```{r}
data_short <- data_short %>% 
  select(date, site_id, temp = temp_dm, sal = sal_dm, 
         delta_rho = delta_rho_dm, no2_dm, sio2 = sio2_dm, po4 = po4_dm, 
         Wan_b1)

data_short <- data_short %>%
  drop_na()
```

```{r}


#First do the summarizing and filtering for each grouping I want correlated against.
# s_sum_s <- micro_short %>% 
#   filter(scientificName == "Skeletonema marinoi") %>% 
#   select(date, site_id, S.m. = species_sum)

d_sum_s <- micro_short %>% 
  filter(group == "Bacillariophyta") %>% 
  group_by(date, site_id) %>% 
  summarise(diat. = sum(species_sum)) %>% 
  ungroup()

chl_corr_s <- chl %>% 
  select(date, site_id, TChla = tchla)

```

```{r}
cor_exp_s <- chl_corr_s %>% 
  # left_join(s_sum_s) %>% 
  left_join(d_sum_s)
```
```{r}
data_short <- data_short %>% 
  left_join(cor_exp_s)

```


```{r}
#Creating correlogram to show link between variables
data_f <- data_short %>% 
  filter(site_id == "DFO2") %>% 
  select(temp:diat.)

data_s <- data_short %>% 
  filter(site_id == "QCS01") %>% 
  select(temp:diat.)

#Making correlation matrix
cor_f <- round(cor(data_f), 2)
cor_s <- round(cor(data_s), 2)

#Making significance' matrix
p.mat_f <- cor_pmat(data_f)
p.mat_s <- cor_pmat(data_s)
```

```{r}
f_f <- ggcorrplot(cor_f,
  p.mat = p.mat_f,
  method = "square",
  type = "lower",
  sig.level = 0.05,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 4.5,
  outline.color = "black") +
  scale_x_discrete(labels = c("S", "\u394\u3C1", "NO\u2083\u207B+NO\u2082\u207B",
                        "SiO\u2082\u207B", "PO\u2084\u207B", "Riv_B10",
                        "TChla", "Diat.")) +
  scale_y_discrete(labels = c("T", "S", "\u394\u3C1", "NO\u2083\u207B+NO\u2082\u207B",
                        "SiO\u2082\u207B", "PO\u2084\u207B", "Riv_B10",
                        "TChla", "Diat.")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Fjord") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2, color = "black"),
        axis.text.y = element_text(angle = 0, color = "black"),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")

f_s <- ggcorrplot(cor_s,
  p.mat = p.mat_s,
  method = "square",
  type = "lower",
  sig.level = 0.05,
  lab = TRUE,
  # title = "Channel",
  insig = "blank",
  lab_size = 4.5,
  outline.color = "black") +
  scale_x_discrete(labels = c("S", "\u394\u3C1", "NO\u2083\u207B+NO\u2082\u207B",
                        "SiO\u2082\u207B", "PO\u2084\u207B", "Riv_B10",
                        "TChla", "Diat.")) +
  scale_y_discrete(labels = c("T", "S", "\u394\u3C1", "NO\u2083\u207B+NO\u2082\u207B",
                        "SiO\u2082\u207B", "PO\u2084\u207B", "Riv_B10",
                        "TChla", "Diat.")) +
  # annotate(geom = "text", x = 2.5, y = 19, label= "Channel", size = 10) +
  ggtitle("Shelf") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text.x = element_text(angle = 90,hjust = 0.95, vjust = 0.2, color = "black"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(margin = margin(t = 40,b = -30)),
        legend.position = "none")
```

```{r}
fig <- f_f + f_c + f_s

ggsave(here("figures_good", "corr_all_station_p05.png"), fig,
       width = 14, height = 6, dpi = 300)
```


